var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~17~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~17~4~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah,Ephraim~~~~2Ch~17~2~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~17~5~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~17~6~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~17~7~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~17~9~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~17~10~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~17~12~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~17~13~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~17~14~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~17~19~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~2Ch~17~17~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~17~1~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~17~4~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah,Ephraim~~~~2Ch~17~2~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~17~5~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~17~6~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~17~7~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~17~9~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~17~10~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~17~12~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~17~13~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~17~14~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~17~19~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~2Ch~17~17~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~17~13~images/maps/Otest/otest_template.html~3a';
LOI[27] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~17~13~images/maps/Otest/otest_template.html~3b';
LOI[28] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~17~1~images/maps/Otest/otest_template.html~3c';
LOI[29] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~17~4~images/maps/Otest/otest_template.html~3c';
LOI[30] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~17~1~images/maps/Otest/otest_template.html~4';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~17~4~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~17~13~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~17~1~images/maps/Christ/christ_template.html~1';
LOI[34] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~17~4~images/maps/Christ/christ_template.html~1';
LOI[35] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~17~13~images/places/Israel/israel_template.html~11';
LOI[36] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~17~13~images/places/Israel/israel_template.html~12';
LOI[37] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~17~13~images/places/Israel/israel_template.html~13';
LOI[38] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~17~13~images/places/Israel/israel_template.html~14';
LOI[39] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~17~13~images/places/Israel/israel_template.html~17';
LOI[40] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Ch~17~11~images/bible_images/Samson/samson_template.html~6';
LOI[41] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Ch~17~3~images/bible_images/Kings/kings_template.html~1';
LOI[42] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Ch~17~3~images/bible_images/Kings/kings_template.html~2';
