var LOI = [];
LOI[0] = 'hymn~12~O HAPPY DAY, THAT FIXED MY CHOICE~htm_o_h_ohappday.html';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~15~3~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~15~4~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~2Ch~15~9~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~15~13~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~15~17~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah,Benjamin~~~~2Ch~15~2~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~2Ch~15~8~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~15~15~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~15~3~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~15~4~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~2Ch~15~9~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~15~13~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~15~17~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah,Benjamin~~~~2Ch~15~2~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~2Ch~15~8~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~15~15~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~15~10~images/maps/Otest/otest_template.html~3a';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~15~10~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~15~3~images/maps/Otest/otest_template.html~3c';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~15~4~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~15~9~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~15~13~images/maps/Otest/otest_template.html~3c';
LOI[23] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~15~17~images/maps/Otest/otest_template.html~3c';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~15~3~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~15~4~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~15~9~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~15~13~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~15~17~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~15~10~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~15~3~images/maps/Christ/christ_template.html~1';
LOI[31] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~15~4~images/maps/Christ/christ_template.html~1';
LOI[32] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~15~9~images/maps/Christ/christ_template.html~1';
LOI[33] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~15~13~images/maps/Christ/christ_template.html~1';
LOI[34] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~15~17~images/maps/Christ/christ_template.html~1';
LOI[35] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~15~10~images/places/Israel/israel_template.html~11';
LOI[36] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~15~10~images/places/Israel/israel_template.html~12';
LOI[37] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~15~10~images/places/Israel/israel_template.html~13';
LOI[38] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~15~10~images/places/Israel/israel_template.html~14';
LOI[39] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~15~10~images/places/Israel/israel_template.html~17';
