var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~21~2~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~21~4~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~21~6~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Ch~21~13~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~21~3~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~21~8~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~21~10~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~21~11~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~21~12~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~21~17~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~21~2~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~21~4~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~21~6~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Ch~21~13~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~21~3~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~21~8~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~21~10~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~21~11~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~21~12~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~21~17~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~21~5~images/maps/Otest/otest_template.html~3a';
LOI[21] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~21~11~images/maps/Otest/otest_template.html~3a';
LOI[22] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~21~13~images/maps/Otest/otest_template.html~3a';
LOI[23] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~21~20~images/maps/Otest/otest_template.html~3a';
LOI[24] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~21~5~images/maps/Otest/otest_template.html~3b';
LOI[25] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~21~11~images/maps/Otest/otest_template.html~3b';
LOI[26] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~21~13~images/maps/Otest/otest_template.html~3b';
LOI[27] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~21~20~images/maps/Otest/otest_template.html~3b';
LOI[28] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~21~2~images/maps/Otest/otest_template.html~3c';
LOI[29] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~21~4~images/maps/Otest/otest_template.html~3c';
LOI[30] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~21~6~images/maps/Otest/otest_template.html~3c';
LOI[31] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~21~13~images/maps/Otest/otest_template.html~3c';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~21~2~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~21~4~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~21~6~images/maps/Otest/otest_template.html~4';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jerusalem~~~~2Ch~21~13~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~21~5~images/maps/Otest/otest_template.html~4';
LOI[37] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~21~11~images/maps/Otest/otest_template.html~4';
LOI[38] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~21~20~images/maps/Otest/otest_template.html~4';
LOI[39] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~21~2~images/maps/Christ/christ_template.html~1';
LOI[40] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~21~4~images/maps/Christ/christ_template.html~1';
LOI[41] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~21~6~images/maps/Christ/christ_template.html~1';
LOI[42] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~21~13~images/maps/Christ/christ_template.html~1';
LOI[43] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~21~5~images/places/Israel/israel_template.html~11';
LOI[44] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~21~11~images/places/Israel/israel_template.html~11';
LOI[45] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~21~13~images/places/Israel/israel_template.html~11';
LOI[46] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~21~20~images/places/Israel/israel_template.html~11';
LOI[47] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~21~5~images/places/Israel/israel_template.html~12';
LOI[48] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~21~11~images/places/Israel/israel_template.html~12';
LOI[49] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~21~13~images/places/Israel/israel_template.html~12';
LOI[50] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~21~20~images/places/Israel/israel_template.html~12';
LOI[51] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~21~5~images/places/Israel/israel_template.html~13';
LOI[52] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~21~11~images/places/Israel/israel_template.html~13';
LOI[53] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~21~13~images/places/Israel/israel_template.html~13';
LOI[54] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~21~20~images/places/Israel/israel_template.html~13';
LOI[55] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~21~5~images/places/Israel/israel_template.html~14';
LOI[56] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~21~11~images/places/Israel/israel_template.html~14';
LOI[57] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~21~13~images/places/Israel/israel_template.html~14';
LOI[58] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~21~20~images/places/Israel/israel_template.html~14';
LOI[59] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~21~5~images/places/Israel/israel_template.html~17';
LOI[60] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~21~11~images/places/Israel/israel_template.html~17';
LOI[61] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~21~13~images/places/Israel/israel_template.html~17';
LOI[62] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~21~20~images/places/Israel/israel_template.html~17';
LOI[63] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Ch~21~16~images/bible_images/Samson/samson_template.html~6';
LOI[64] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Ch~21~1~images/bible_images/Kings/kings_template.html~1';
LOI[65] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Ch~21~7~images/bible_images/Kings/kings_template.html~1';
LOI[66] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Ch~21~12~images/bible_images/Kings/kings_template.html~1';
LOI[67] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Ch~21~20~images/bible_images/Kings/kings_template.html~1';
LOI[68] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Ch~21~1~images/bible_images/Kings/kings_template.html~2';
LOI[69] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Ch~21~7~images/bible_images/Kings/kings_template.html~2';
LOI[70] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Ch~21~12~images/bible_images/Kings/kings_template.html~2';
LOI[71] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Ch~21~20~images/bible_images/Kings/kings_template.html~2';
LOI[72] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~2Ch~21~12~images/bible_images/Kings/kings_template.html~5';
