var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~32~17~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Ch~32~32~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~32~1~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~32~8~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~32~9~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~32~12~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~32~23~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~32~25~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah,Manasseh~~~~2Ch~32~33~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~32~17~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Ch~32~32~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~32~1~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~32~8~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~32~9~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~32~12~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~32~23~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~32~25~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah,Manasseh~~~~2Ch~32~33~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~32~2~images/maps/Otest/otest_template.html~3a';
LOI[19] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~32~9~images/maps/Otest/otest_template.html~3a';
LOI[20] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~32~10~images/maps/Otest/otest_template.html~3a';
LOI[21] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~32~12~images/maps/Otest/otest_template.html~3a';
LOI[22] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~32~18~images/maps/Otest/otest_template.html~3a';
LOI[23] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~32~19~images/maps/Otest/otest_template.html~3a';
LOI[24] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~32~22~images/maps/Otest/otest_template.html~3a';
LOI[25] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~32~23~images/maps/Otest/otest_template.html~3a';
LOI[26] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~32~25~images/maps/Otest/otest_template.html~3a';
LOI[27] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~32~26~images/maps/Otest/otest_template.html~3a';
LOI[28] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~32~33~images/maps/Otest/otest_template.html~3a';
LOI[29] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Gihon~~~~2Ch~32~30~images/maps/Otest/otest_template.html~3a';
LOI[30] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~32~2~images/maps/Otest/otest_template.html~3b';
LOI[31] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~32~9~images/maps/Otest/otest_template.html~3b';
LOI[32] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~32~10~images/maps/Otest/otest_template.html~3b';
LOI[33] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~32~12~images/maps/Otest/otest_template.html~3b';
LOI[34] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~32~18~images/maps/Otest/otest_template.html~3b';
LOI[35] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~32~19~images/maps/Otest/otest_template.html~3b';
LOI[36] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~32~22~images/maps/Otest/otest_template.html~3b';
LOI[37] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~32~23~images/maps/Otest/otest_template.html~3b';
LOI[38] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~32~25~images/maps/Otest/otest_template.html~3b';
LOI[39] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~32~26~images/maps/Otest/otest_template.html~3b';
LOI[40] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~32~33~images/maps/Otest/otest_template.html~3b';
LOI[41] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~32~17~images/maps/Otest/otest_template.html~3c';
LOI[42] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~32~32~images/maps/Otest/otest_template.html~3c';
LOI[43] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~32~17~images/maps/Otest/otest_template.html~4';
LOI[44] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~32~32~images/maps/Otest/otest_template.html~4';
LOI[45] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~32~2~images/maps/Otest/otest_template.html~4';
LOI[46] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~32~9~images/maps/Otest/otest_template.html~4';
LOI[47] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~32~10~images/maps/Otest/otest_template.html~4';
LOI[48] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~32~12~images/maps/Otest/otest_template.html~4';
LOI[49] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~32~18~images/maps/Otest/otest_template.html~4';
LOI[50] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~32~19~images/maps/Otest/otest_template.html~4';
LOI[51] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~32~22~images/maps/Otest/otest_template.html~4';
LOI[52] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~32~23~images/maps/Otest/otest_template.html~4';
LOI[53] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~32~25~images/maps/Otest/otest_template.html~4';
LOI[54] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~32~26~images/maps/Otest/otest_template.html~4';
LOI[55] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~32~33~images/maps/Otest/otest_template.html~4';
LOI[56] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~32~17~images/maps/Christ/christ_template.html~1';
LOI[57] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~32~32~images/maps/Christ/christ_template.html~1';
LOI[58] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~32~2~images/places/Israel/israel_template.html~11';
LOI[59] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~32~9~images/places/Israel/israel_template.html~11';
LOI[60] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~32~10~images/places/Israel/israel_template.html~11';
LOI[61] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~32~12~images/places/Israel/israel_template.html~11';
LOI[62] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~32~18~images/places/Israel/israel_template.html~11';
LOI[63] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~32~19~images/places/Israel/israel_template.html~11';
LOI[64] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~32~22~images/places/Israel/israel_template.html~11';
LOI[65] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~32~23~images/places/Israel/israel_template.html~11';
LOI[66] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~32~25~images/places/Israel/israel_template.html~11';
LOI[67] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~32~26~images/places/Israel/israel_template.html~11';
LOI[68] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~32~33~images/places/Israel/israel_template.html~11';
LOI[69] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~32~2~images/places/Israel/israel_template.html~12';
LOI[70] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~32~9~images/places/Israel/israel_template.html~12';
LOI[71] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~32~10~images/places/Israel/israel_template.html~12';
LOI[72] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~32~12~images/places/Israel/israel_template.html~12';
LOI[73] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~32~18~images/places/Israel/israel_template.html~12';
LOI[74] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~32~19~images/places/Israel/israel_template.html~12';
LOI[75] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~32~22~images/places/Israel/israel_template.html~12';
LOI[76] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~32~23~images/places/Israel/israel_template.html~12';
LOI[77] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~32~25~images/places/Israel/israel_template.html~12';
LOI[78] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~32~26~images/places/Israel/israel_template.html~12';
LOI[79] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~32~33~images/places/Israel/israel_template.html~12';
LOI[80] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~32~2~images/places/Israel/israel_template.html~13';
LOI[81] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~32~9~images/places/Israel/israel_template.html~13';
LOI[82] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~32~10~images/places/Israel/israel_template.html~13';
LOI[83] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~32~12~images/places/Israel/israel_template.html~13';
LOI[84] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~32~18~images/places/Israel/israel_template.html~13';
LOI[85] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~32~19~images/places/Israel/israel_template.html~13';
LOI[86] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~32~22~images/places/Israel/israel_template.html~13';
LOI[87] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~32~23~images/places/Israel/israel_template.html~13';
LOI[88] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~32~25~images/places/Israel/israel_template.html~13';
LOI[89] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~32~26~images/places/Israel/israel_template.html~13';
LOI[90] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~32~33~images/places/Israel/israel_template.html~13';
LOI[91] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~32~2~images/places/Israel/israel_template.html~14';
LOI[92] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~32~9~images/places/Israel/israel_template.html~14';
LOI[93] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~32~10~images/places/Israel/israel_template.html~14';
LOI[94] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~32~12~images/places/Israel/israel_template.html~14';
LOI[95] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~32~18~images/places/Israel/israel_template.html~14';
LOI[96] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~32~19~images/places/Israel/israel_template.html~14';
LOI[97] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~32~22~images/places/Israel/israel_template.html~14';
LOI[98] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~32~23~images/places/Israel/israel_template.html~14';
LOI[99] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~32~25~images/places/Israel/israel_template.html~14';
LOI[100] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~32~26~images/places/Israel/israel_template.html~14';
LOI[101] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~32~33~images/places/Israel/israel_template.html~14';
LOI[102] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~32~2~images/places/Israel/israel_template.html~17';
LOI[103] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~32~9~images/places/Israel/israel_template.html~17';
LOI[104] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~32~10~images/places/Israel/israel_template.html~17';
LOI[105] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~32~12~images/places/Israel/israel_template.html~17';
LOI[106] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~32~18~images/places/Israel/israel_template.html~17';
LOI[107] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~32~19~images/places/Israel/israel_template.html~17';
LOI[108] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~32~22~images/places/Israel/israel_template.html~17';
LOI[109] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~32~23~images/places/Israel/israel_template.html~17';
LOI[110] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~32~25~images/places/Israel/israel_template.html~17';
LOI[111] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~32~26~images/places/Israel/israel_template.html~17';
LOI[112] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~32~33~images/places/Israel/israel_template.html~17';
LOI[113] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Ch~32~5~images/bible_images/Kings/kings_template.html~1';
LOI[114] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Ch~32~30~images/bible_images/Kings/kings_template.html~1';
LOI[115] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Ch~32~33~images/bible_images/Kings/kings_template.html~1';
LOI[116] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Ch~32~5~images/bible_images/Kings/kings_template.html~2';
LOI[117] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Ch~32~30~images/bible_images/Kings/kings_template.html~2';
LOI[118] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Ch~32~33~images/bible_images/Kings/kings_template.html~2';
LOI[119] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~2Ch~32~31~images/bible_images/Kings/kings_template.html~7';
LOI[120] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~1~images/bible_images/History/history_template.html~1';
LOI[121] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~2~images/bible_images/History/history_template.html~1';
LOI[122] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~3~images/bible_images/History/history_template.html~1';
LOI[123] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~4~images/bible_images/History/history_template.html~1';
LOI[124] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~5~images/bible_images/History/history_template.html~1';
LOI[125] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~6~images/bible_images/History/history_template.html~1';
LOI[126] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~7~images/bible_images/History/history_template.html~1';
LOI[127] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~8~images/bible_images/History/history_template.html~1';
LOI[128] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~9~images/bible_images/History/history_template.html~1';
LOI[129] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~10~images/bible_images/History/history_template.html~1';
LOI[130] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~11~images/bible_images/History/history_template.html~1';
LOI[131] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~12~images/bible_images/History/history_template.html~1';
LOI[132] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~13~images/bible_images/History/history_template.html~1';
LOI[133] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~14~images/bible_images/History/history_template.html~1';
LOI[134] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~15~images/bible_images/History/history_template.html~1';
LOI[135] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~16~images/bible_images/History/history_template.html~1';
LOI[136] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~17~images/bible_images/History/history_template.html~1';
LOI[137] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~18~images/bible_images/History/history_template.html~1';
LOI[138] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~19~images/bible_images/History/history_template.html~1';
LOI[139] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~20~images/bible_images/History/history_template.html~1';
LOI[140] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~21~images/bible_images/History/history_template.html~1';
LOI[141] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~22~images/bible_images/History/history_template.html~1';
LOI[142] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~23~images/bible_images/History/history_template.html~1';
LOI[143] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~24~images/bible_images/History/history_template.html~1';
LOI[144] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~25~images/bible_images/History/history_template.html~1';
LOI[145] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~26~images/bible_images/History/history_template.html~1';
LOI[146] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~27~images/bible_images/History/history_template.html~1';
LOI[147] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~28~images/bible_images/History/history_template.html~1';
LOI[148] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~29~images/bible_images/History/history_template.html~1';
LOI[149] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~30~images/bible_images/History/history_template.html~1';
LOI[150] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~31~images/bible_images/History/history_template.html~1';
LOI[151] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~32~images/bible_images/History/history_template.html~1';
LOI[152] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet)~~~~2Ch~32~33~images/bible_images/History/history_template.html~1';
