var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~28~2~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~28~3~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~28~5~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~28~8~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~28~13~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Ch~28~19~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~28~23~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Ch~28~26~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~28~27~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~28~6~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~28~9~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~28~10~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~28~17~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~28~18~images/maps/Otest/otest_template.html~1b';
LOI[14] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~28~25~images/maps/Otest/otest_template.html~1b';
LOI[15] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~2Ch~28~7~images/maps/Otest/otest_template.html~1b';
LOI[16] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~2Ch~28~12~images/maps/Otest/otest_template.html~1b';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~28~2~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~28~3~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~28~5~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~28~8~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~28~13~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Ch~28~19~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~28~23~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Ch~28~26~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~28~27~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~28~6~images/maps/Otest/otest_template.html~1c';
LOI[27] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~28~9~images/maps/Otest/otest_template.html~1c';
LOI[28] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~28~10~images/maps/Otest/otest_template.html~1c';
LOI[29] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~28~17~images/maps/Otest/otest_template.html~1c';
LOI[30] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~28~18~images/maps/Otest/otest_template.html~1c';
LOI[31] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~28~25~images/maps/Otest/otest_template.html~1c';
LOI[32] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~2Ch~28~7~images/maps/Otest/otest_template.html~1c';
LOI[33] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~2Ch~28~12~images/maps/Otest/otest_template.html~1c';
LOI[34] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~28~1~images/maps/Otest/otest_template.html~3a';
LOI[35] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~28~10~images/maps/Otest/otest_template.html~3a';
LOI[36] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~28~24~images/maps/Otest/otest_template.html~3a';
LOI[37] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~28~27~images/maps/Otest/otest_template.html~3a';
LOI[38] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Hinnom~~~~2Ch~28~3~images/maps/Otest/otest_template.html~3a';
LOI[39] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~28~1~images/maps/Otest/otest_template.html~3b';
LOI[40] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~28~10~images/maps/Otest/otest_template.html~3b';
LOI[41] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~28~24~images/maps/Otest/otest_template.html~3b';
LOI[42] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~28~27~images/maps/Otest/otest_template.html~3b';
LOI[43] = 'image~Bible~Maps~Modern Jerusalem (map) key=Hinnom~~~~2Ch~28~3~images/maps/Otest/otest_template.html~3b';
LOI[44] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~28~2~images/maps/Otest/otest_template.html~3c';
LOI[45] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~28~3~images/maps/Otest/otest_template.html~3c';
LOI[46] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~28~5~images/maps/Otest/otest_template.html~3c';
LOI[47] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~28~8~images/maps/Otest/otest_template.html~3c';
LOI[48] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~28~13~images/maps/Otest/otest_template.html~3c';
LOI[49] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~28~19~images/maps/Otest/otest_template.html~3c';
LOI[50] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~28~23~images/maps/Otest/otest_template.html~3c';
LOI[51] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~28~26~images/maps/Otest/otest_template.html~3c';
LOI[52] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~28~27~images/maps/Otest/otest_template.html~3c';
LOI[53] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~28~2~images/maps/Otest/otest_template.html~4';
LOI[54] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~28~3~images/maps/Otest/otest_template.html~4';
LOI[55] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~28~5~images/maps/Otest/otest_template.html~4';
LOI[56] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~28~8~images/maps/Otest/otest_template.html~4';
LOI[57] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~28~13~images/maps/Otest/otest_template.html~4';
LOI[58] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~28~19~images/maps/Otest/otest_template.html~4';
LOI[59] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~28~23~images/maps/Otest/otest_template.html~4';
LOI[60] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~28~26~images/maps/Otest/otest_template.html~4';
LOI[61] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jerusalem~~~~2Ch~28~27~images/maps/Otest/otest_template.html~4';
LOI[62] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~28~1~images/maps/Otest/otest_template.html~4';
LOI[63] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~28~10~images/maps/Otest/otest_template.html~4';
LOI[64] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~28~24~images/maps/Otest/otest_template.html~4';
LOI[65] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~2Ch~28~15~images/maps/Otest/otest_template.html~4';
LOI[66] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~28~2~images/maps/Christ/christ_template.html~1';
LOI[67] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~28~3~images/maps/Christ/christ_template.html~1';
LOI[68] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~28~5~images/maps/Christ/christ_template.html~1';
LOI[69] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel,Samaria~~~~2Ch~28~8~images/maps/Christ/christ_template.html~1';
LOI[70] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~28~13~images/maps/Christ/christ_template.html~1';
LOI[71] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~28~19~images/maps/Christ/christ_template.html~1';
LOI[72] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~28~23~images/maps/Christ/christ_template.html~1';
LOI[73] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~28~26~images/maps/Christ/christ_template.html~1';
LOI[74] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~28~27~images/maps/Christ/christ_template.html~1';
LOI[75] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~2Ch~28~9~images/maps/Christ/christ_template.html~1';
LOI[76] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~2Ch~28~15~images/maps/Christ/christ_template.html~1';
LOI[77] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~2Ch~28~5~images/maps/Journeys/journeys_template.html~2';
LOI[78] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~2Ch~28~23~images/maps/Journeys/journeys_template.html~2';
LOI[79] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~2Ch~28~15~images/places/Israel/israel_template.html~9';
LOI[80] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~28~1~images/places/Israel/israel_template.html~11';
LOI[81] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~28~10~images/places/Israel/israel_template.html~11';
LOI[82] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~28~24~images/places/Israel/israel_template.html~11';
LOI[83] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~28~27~images/places/Israel/israel_template.html~11';
LOI[84] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~28~1~images/places/Israel/israel_template.html~12';
LOI[85] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~28~10~images/places/Israel/israel_template.html~12';
LOI[86] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~28~24~images/places/Israel/israel_template.html~12';
LOI[87] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~28~27~images/places/Israel/israel_template.html~12';
LOI[88] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~28~1~images/places/Israel/israel_template.html~13';
LOI[89] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~28~10~images/places/Israel/israel_template.html~13';
LOI[90] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~28~24~images/places/Israel/israel_template.html~13';
LOI[91] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~28~27~images/places/Israel/israel_template.html~13';
LOI[92] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~28~1~images/places/Israel/israel_template.html~14';
LOI[93] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~28~10~images/places/Israel/israel_template.html~14';
LOI[94] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~28~24~images/places/Israel/israel_template.html~14';
LOI[95] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~28~27~images/places/Israel/israel_template.html~14';
LOI[96] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~28~1~images/places/Israel/israel_template.html~17';
LOI[97] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~28~10~images/places/Israel/israel_template.html~17';
LOI[98] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~28~24~images/places/Israel/israel_template.html~17';
LOI[99] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~28~27~images/places/Israel/israel_template.html~17';
LOI[100] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Ch~28~18~images/bible_images/Samson/samson_template.html~6';
LOI[101] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Ch~28~1~images/bible_images/Kings/kings_template.html~1';
LOI[102] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Ch~28~1~images/bible_images/Kings/kings_template.html~2';
