var LOI = [];
LOI[0] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Moriah~~~~2Ch~3~1~images/maps/Otest/otest_template.html~3a';
LOI[1] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~2Ch~3~17~images/maps/Otest/otest_template.html~3a';
LOI[2] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Moriah~~~~2Ch~3~1~images/maps/Otest/otest_template.html~3b';
LOI[3] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~2Ch~3~17~images/maps/Otest/otest_template.html~3b';
LOI[4] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~3~1~images/maps/Otest/otest_template.html~4';
LOI[5] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~3~1~images/places/Israel/israel_template.html~11';
LOI[6] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~3~1~images/places/Israel/israel_template.html~12';
LOI[7] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~3~1~images/places/Israel/israel_template.html~13';
LOI[8] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~3~1~images/places/Israel/israel_template.html~14';
LOI[9] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~3~1~images/places/Israel/israel_template.html~17';
LOI[10] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Ch~3~1~images/bible_images/Kings/kings_template.html~1';
LOI[11] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Ch~3~1~images/bible_images/Kings/kings_template.html~2';
LOI[12] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~2Ch~3~1~images/bible_images/Kings/kings_template.html~3';
LOI[13] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~2Ch~3~3~images/bible_images/Kings/kings_template.html~3';
LOI[14] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~2Ch~3~1~images/bible_images/Kings/kings_template.html~4';
LOI[15] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~2Ch~3~3~images/bible_images/Kings/kings_template.html~4';
LOI[16] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~1';
LOI[17] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~1';
LOI[18] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~2';
LOI[19] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~2';
LOI[20] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~3';
LOI[21] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~3';
LOI[22] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~4';
LOI[23] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~4';
LOI[24] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~5';
LOI[25] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~5';
LOI[26] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~6';
LOI[27] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~6';
LOI[28] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~7';
LOI[29] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~7';
LOI[30] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~8';
LOI[31] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~8';
LOI[32] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~9';
LOI[33] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~9';
LOI[34] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~10';
LOI[35] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~10';
LOI[36] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~11';
LOI[37] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~11';
LOI[38] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~12';
LOI[39] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~12';
LOI[40] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~13';
LOI[41] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~13';
LOI[42] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~14';
LOI[43] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~14';
LOI[44] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~2Ch~3~1~images/bible_images/Song/song_template.html~15';
LOI[45] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~2Ch~3~3~images/bible_images/Song/song_template.html~15';
LOI[46] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~2Ch~3~17~images/bible_images/Temple/temple_template.html~1';
LOI[47] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~2Ch~3~17~images/bible_images/Temple/temple_template.html~2';
