var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~35~3~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~35~4~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~35~17~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Ch~35~18~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ch~35~25~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Ch~35~27~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~35~21~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ch~35~24~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~35~3~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~35~4~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~35~17~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~2Ch~35~18~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ch~35~25~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Ch~35~27~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~35~21~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ch~35~24~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~35~1~images/maps/Otest/otest_template.html~3a';
LOI[17] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~35~18~images/maps/Otest/otest_template.html~3a';
LOI[18] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ch~35~24~images/maps/Otest/otest_template.html~3a';
LOI[19] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~2Ch~35~20~images/maps/Otest/otest_template.html~3a';
LOI[20] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~35~1~images/maps/Otest/otest_template.html~3b';
LOI[21] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~35~18~images/maps/Otest/otest_template.html~3b';
LOI[22] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ch~35~24~images/maps/Otest/otest_template.html~3b';
LOI[23] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~2Ch~35~20~images/maps/Otest/otest_template.html~3b';
LOI[24] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~35~3~images/maps/Otest/otest_template.html~3c';
LOI[25] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~35~4~images/maps/Otest/otest_template.html~3c';
LOI[26] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~35~17~images/maps/Otest/otest_template.html~3c';
LOI[27] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~35~18~images/maps/Otest/otest_template.html~3c';
LOI[28] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~35~25~images/maps/Otest/otest_template.html~3c';
LOI[29] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ch~35~27~images/maps/Otest/otest_template.html~3c';
LOI[30] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~35~3~images/maps/Otest/otest_template.html~4';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~35~4~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~35~17~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jerusalem~~~~2Ch~35~18~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~35~25~images/maps/Otest/otest_template.html~4';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ch~35~27~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~35~1~images/maps/Otest/otest_template.html~4';
LOI[37] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ch~35~24~images/maps/Otest/otest_template.html~4';
LOI[38] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~2Ch~35~20~images/maps/Otest/otest_template.html~5';
LOI[39] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~35~3~images/maps/Christ/christ_template.html~1';
LOI[40] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~35~4~images/maps/Christ/christ_template.html~1';
LOI[41] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~35~17~images/maps/Christ/christ_template.html~1';
LOI[42] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~35~18~images/maps/Christ/christ_template.html~1';
LOI[43] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~35~25~images/maps/Christ/christ_template.html~1';
LOI[44] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ch~35~27~images/maps/Christ/christ_template.html~1';
LOI[45] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~35~1~images/places/Israel/israel_template.html~11';
LOI[46] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~35~18~images/places/Israel/israel_template.html~11';
LOI[47] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ch~35~24~images/places/Israel/israel_template.html~11';
LOI[48] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~35~1~images/places/Israel/israel_template.html~12';
LOI[49] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~35~18~images/places/Israel/israel_template.html~12';
LOI[50] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ch~35~24~images/places/Israel/israel_template.html~12';
LOI[51] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~35~1~images/places/Israel/israel_template.html~13';
LOI[52] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~35~18~images/places/Israel/israel_template.html~13';
LOI[53] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ch~35~24~images/places/Israel/israel_template.html~13';
LOI[54] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~35~1~images/places/Israel/israel_template.html~14';
LOI[55] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~35~18~images/places/Israel/israel_template.html~14';
LOI[56] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ch~35~24~images/places/Israel/israel_template.html~14';
LOI[57] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~35~1~images/places/Israel/israel_template.html~17';
LOI[58] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~35~18~images/places/Israel/israel_template.html~17';
LOI[59] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ch~35~24~images/places/Israel/israel_template.html~17';
LOI[60] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~2Ch~35~6~images/bible_images/Moses/moses_template.html~6';
LOI[61] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~2Ch~35~12~images/bible_images/Moses/moses_template.html~6';
LOI[62] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~2Ch~35~6~images/bible_images/Moses/moses_template.html~7';
LOI[63] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~2Ch~35~12~images/bible_images/Moses/moses_template.html~7';
LOI[64] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~2Ch~35~6~images/bible_images/Moses/moses_template.html~9';
LOI[65] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~2Ch~35~12~images/bible_images/Moses/moses_template.html~9';
LOI[66] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~2Ch~35~6~images/bible_images/Moses/moses_template.html~10';
LOI[67] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~2Ch~35~12~images/bible_images/Moses/moses_template.html~10';
LOI[68] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~2Ch~35~6~images/bible_images/Moses/moses_template.html~11';
LOI[69] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~2Ch~35~12~images/bible_images/Moses/moses_template.html~11';
LOI[70] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Ch~35~3~images/bible_images/Kings/kings_template.html~1';
LOI[71] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Ch~35~4~images/bible_images/Kings/kings_template.html~1';
LOI[72] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Ch~35~15~images/bible_images/Kings/kings_template.html~1';
LOI[73] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Ch~35~3~images/bible_images/Kings/kings_template.html~2';
LOI[74] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Ch~35~4~images/bible_images/Kings/kings_template.html~2';
LOI[75] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Ch~35~15~images/bible_images/Kings/kings_template.html~2';
LOI[76] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~2Ch~35~3~images/bible_images/Kings/kings_template.html~3';
LOI[77] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~2Ch~35~4~images/bible_images/Kings/kings_template.html~3';
LOI[78] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~2Ch~35~3~images/bible_images/Kings/kings_template.html~4';
LOI[79] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~2Ch~35~4~images/bible_images/Kings/kings_template.html~4';
LOI[80] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~1';
LOI[81] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~1';
LOI[82] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~2';
LOI[83] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~2';
LOI[84] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~3';
LOI[85] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~3';
LOI[86] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~4';
LOI[87] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~4';
LOI[88] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~5';
LOI[89] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~5';
LOI[90] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~6';
LOI[91] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~6';
LOI[92] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~7';
LOI[93] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~7';
LOI[94] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~8';
LOI[95] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~8';
LOI[96] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~9';
LOI[97] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~9';
LOI[98] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~10';
LOI[99] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~10';
LOI[100] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~11';
LOI[101] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~11';
LOI[102] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~12';
LOI[103] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~12';
LOI[104] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~13';
LOI[105] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~13';
LOI[106] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~14';
LOI[107] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~14';
LOI[108] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~2Ch~35~3~images/bible_images/Song/song_template.html~15';
LOI[109] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~2Ch~35~4~images/bible_images/Song/song_template.html~15';
LOI[110] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~2Ch~35~20~images/bible_images/Temple/temple_template.html~1';
LOI[111] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~2Ch~35~20~images/bible_images/Temple/temple_template.html~2';
LOI[112] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~2Ch~35~3~images/bible_images/Temple/temple_template.html~4';
