var LOI = [];
LOI[0] = 'hymn~1~DOWN IN THE VALLEY~htm_d_o_downvall.html';
LOI[1] = 'hymn~1~JESUS, ROSE OF SHARON~htm_j_r_jroseosh.html';
LOI[2] = 'hymn~1~LILY OF THE VALLEY, THE~htm_l_i_lilyvall.html';
LOI[3] = 'hymn~1~LO, HOW A ROSE E&#8217;ER BLOOMING~htm_l_h_lhowrose.html';
LOI[4] = 'hymn~4~ALL OVER THE WORLD~htm_a_l_alloverw.html';
LOI[5] = 'hymn~4~AT THY FEET, OUR GOD AND FATHER~htm_a_t_athyfeet.html';
LOI[6] = 'hymn~4~GO FORWARD, CHRISTIAN SOLDIER~htm_g_f_gforward.html';
LOI[7] = 'hymn~4~JESUS SPREADS HIS BANNER O&#8217;ER US~htm_j_s_jspreads.html';
LOI[8] = 'hymn~4~SURROUNDED BY UNNUMBERED FOES~htm_s_u_surrounu.html';
LOI[9] = 'hymn~8~HIS VOICE, AS THE SOUND OF THE DULCIMER SWEET~htm_h_i_hisvoice.html';
LOI[10] = 'hymn~8~THERE&#8217;S A LIGHT UPON THE MOUNTAINS~htm_t_h_e_theresal.html';
LOI[11] = 'hymn~10~COME AWAY TO THE SKIES~htm_c_o_comeaway.html';
LOI[12] = 'hymn~10~O VOICE OF THE BELOVED~htm_o_v_o_voice.html';
LOI[13] = 'hymn~16~I LIFT MY HEART TO THEE~htm_i_l_iliftmyh.html';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Sgs~2~7~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Sgs~2~7~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Sharon~~~~Sgs~2~1~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Sgs~2~7~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Sharon~~~~Sgs~2~1~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Sgs~2~7~images/places/Israel/israel_template.html~11';
LOI[20] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Sgs~2~7~images/places/Israel/israel_template.html~12';
LOI[21] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Sgs~2~7~images/places/Israel/israel_template.html~13';
LOI[22] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Sgs~2~7~images/places/Israel/israel_template.html~14';
LOI[23] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Sgs~2~7~images/places/Israel/israel_template.html~17';
LOI[24] = 'image~Bible~Images~I am a rose of Sharon...(color plate)~~~~Sgs~2~1~images/bible_images/Song/song_template.html~7';
LOI[25] = 'image~Bible~Images~I am a rose of Sharon...(color plate)~~~~Sgs~2~2~images/bible_images/Song/song_template.html~7';
LOI[26] = 'image~Bible~Images~As the apple tree among...(color plate)~~~~Sgs~2~3~images/bible_images/Song/song_template.html~8';
LOI[27] = 'image~Bible~Images~As the apple tree among...(color plate)~~~~Sgs~2~4~images/bible_images/Song/song_template.html~8';
LOI[28] = 'image~Bible~Images~As the apple tree among...(color plate)~~~~Sgs~2~5~images/bible_images/Song/song_template.html~8';
LOI[29] = 'image~Bible~Images~As the apple tree among...(color plate)~~~~Sgs~2~6~images/bible_images/Song/song_template.html~8';
LOI[30] = 'image~Bible~Images~As the apple tree among...(color plate)~~~~Sgs~2~7~images/bible_images/Song/song_template.html~8';
LOI[31] = 'image~Bible~Images~The voice of my beloved!...(color plate)~~~~Sgs~2~8~images/bible_images/Song/song_template.html~9';
LOI[32] = 'image~Bible~Images~The voice of my beloved!...(color plate)~~~~Sgs~2~9~images/bible_images/Song/song_template.html~9';
LOI[33] = 'image~Bible~Images~The voice of my beloved!...(color plate)~~~~Sgs~2~10~images/bible_images/Song/song_template.html~9';
LOI[34] = 'image~Bible~Images~The voice of my beloved!...(color plate)~~~~Sgs~2~11~images/bible_images/Song/song_template.html~9';
LOI[35] = 'image~Bible~Images~The voice of my beloved!...(color plate)~~~~Sgs~2~12~images/bible_images/Song/song_template.html~9';
LOI[36] = 'image~Bible~Images~The voice of my beloved!...(color plate)~~~~Sgs~2~13~images/bible_images/Song/song_template.html~9';
LOI[37] = 'image~Bible~Images~The voice of my beloved!...(color plate)~~~~Sgs~2~14~images/bible_images/Song/song_template.html~9';
LOI[38] = 'image~Bible~Images~The voice of my beloved!...(color plate)~~~~Sgs~2~15~images/bible_images/Song/song_template.html~9';
LOI[39] = 'image~Bible~Images~The voice of my beloved!...(color plate)~~~~Sgs~2~16~images/bible_images/Song/song_template.html~9';
LOI[40] = 'image~Bible~Images~The voice of my beloved!...(color plate)~~~~Sgs~2~17~images/bible_images/Song/song_template.html~9';
