var LOI = [];
LOI[0] = 'hymn~29~HIS EYE IS ON THE SPARROW~htm_h_i_hiseyeis.html';
LOI[1] = 'hymn~29~HE&#8217;LL NEVER FORGET TO KEEP ME~htm_h_e_helnever.html';
LOI[2] = 'hymn~29~ROCKED IN THE CRADLE OF THE DEEP~htm_r_o_rockcrad.html';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Mat~10~6~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Mat~10~23~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Mat~10~6~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Mat~10~23~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Mat~10~6~images/maps/Otest/otest_template.html~3c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Mat~10~23~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Mat~10~6~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Mat~10~23~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Mat~10~6~images/maps/Christ/christ_template.html~1';
LOI[12] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Mat~10~23~images/maps/Christ/christ_template.html~1';
