var LOI = [];
LOI[0] = 'hymn~1~LORD, WHO THROUGHOUT THESE FORTY DAYS~htm_l_w_lwtt40da.html';
LOI[1] = 'hymn~19~JESUS CALLS US~htm_j_e_jesuscus.html';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Mat~4~25~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Mat~4~5~images/maps/Otest/otest_template.html~3a';
LOI[4] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Mat~4~25~images/maps/Otest/otest_template.html~3b';
LOI[5] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Mat~4~5~images/maps/Otest/otest_template.html~3b';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Mat~4~12~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee,Jordan~~~~Mat~4~15~images/maps/Otest/otest_template.html~3c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Mat~4~18~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Mat~4~23~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee,Jordan~~~~Mat~4~25~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Mat~4~25~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Mat~4~12~images/maps/Christ/christ_template.html~1';
LOI[13] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Mat~4~15~images/maps/Christ/christ_template.html~1';
LOI[14] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Mat~4~18~images/maps/Christ/christ_template.html~1';
LOI[15] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Mat~4~23~images/maps/Christ/christ_template.html~1';
LOI[16] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Mat~4~25~images/maps/Christ/christ_template.html~1';
LOI[17] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~Mat~4~24~images/maps/Journeys/journeys_template.html~2';
LOI[18] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Mat~4~25~images/places/Israel/israel_template.html~11';
LOI[19] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Mat~4~25~images/places/Israel/israel_template.html~12';
LOI[20] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Mat~4~25~images/places/Israel/israel_template.html~13';
LOI[21] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Mat~4~25~images/places/Israel/israel_template.html~14';
LOI[22] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Mat~4~25~images/places/Israel/israel_template.html~17';
LOI[23] = 'image~Bible~Images~Angels Minister to Jesus (engraving)~~~~Mat~4~11~images/bible_images/Taylor/taylor_template.html~1';
LOI[24] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Mat~4~5~images/bible_images/Temple/temple_template.html~1';
LOI[25] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Mat~4~5~images/bible_images/Temple/temple_template.html~2';
