var LOI = [];
LOI[0] = 'hymn~20~JOSEPH DEAREST~htm_j_o_josephde.html';
LOI[1] = 'hymn~20~WHILE THE WORLD AWAITED~htm_w_h_i_whilethe.html';
LOI[2] = 'hymn~21~I KNOW OF A NAME~htm_i_k_iknownam.html';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Mat~1~16~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Mat~1~18~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Mat~1~19~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Mat~1~20~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Mat~1~24~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Mat~1~16~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Mat~1~18~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Mat~1~19~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Mat~1~20~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Mat~1~24~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Mat~1~1~images/places/Israel/israel_template.html~8';
LOI[14] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Mat~1~2~images/places/Israel/israel_template.html~8';
LOI[15] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Mat~1~17~images/places/Israel/israel_template.html~8';
LOI[16] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Mat~1~1~images/bible_images/Moses/moses_template.html~3';
LOI[17] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Mat~1~2~images/bible_images/Moses/moses_template.html~3';
LOI[18] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Mat~1~17~images/bible_images/Moses/moses_template.html~3';
LOI[19] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Mat~1~1~images/bible_images/Moses/moses_template.html~3i';
LOI[20] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Mat~1~2~images/bible_images/Moses/moses_template.html~3i';
LOI[21] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Mat~1~17~images/bible_images/Moses/moses_template.html~3i';
LOI[22] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~Mat~1~2~images/bible_images/Moses/moses_template.html~3a';
LOI[23] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Mat~1~1~images/bible_images/Moses/moses_template.html~3a';
LOI[24] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Mat~1~17~images/bible_images/Moses/moses_template.html~3a';
LOI[25] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Mat~1~2~images/bible_images/Moses/moses_template.html~4';
LOI[26] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Mat~1~16~images/bible_images/Moses/moses_template.html~5';
LOI[27] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Mat~1~18~images/bible_images/Moses/moses_template.html~5';
LOI[28] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Mat~1~19~images/bible_images/Moses/moses_template.html~5';
LOI[29] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Mat~1~20~images/bible_images/Moses/moses_template.html~5';
LOI[30] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Mat~1~24~images/bible_images/Moses/moses_template.html~5';
LOI[31] = 'image~Bible~Images~Ruth and Naomi (engraving) key=Ruth~~~~Mat~1~5~images/bible_images/Ruth/ruth_template.html~1';
LOI[32] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Mat~1~1~images/bible_images/Kings/kings_template.html~1';
LOI[33] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Mat~1~6~images/bible_images/Kings/kings_template.html~1';
LOI[34] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Mat~1~17~images/bible_images/Kings/kings_template.html~1';
LOI[35] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Mat~1~20~images/bible_images/Kings/kings_template.html~1';
LOI[36] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Mat~1~1~images/bible_images/Kings/kings_template.html~2';
LOI[37] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Mat~1~6~images/bible_images/Kings/kings_template.html~2';
LOI[38] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Mat~1~17~images/bible_images/Kings/kings_template.html~2';
LOI[39] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Mat~1~20~images/bible_images/Kings/kings_template.html~2';
LOI[40] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~Mat~1~6~images/bible_images/Kings/kings_template.html~3';
LOI[41] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~Mat~1~7~images/bible_images/Kings/kings_template.html~3';
LOI[42] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~Mat~1~6~images/bible_images/Kings/kings_template.html~4';
LOI[43] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~Mat~1~7~images/bible_images/Kings/kings_template.html~4';
LOI[44] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Mat~1~11~images/bible_images/Kings/kings_template.html~7';
LOI[45] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Mat~1~12~images/bible_images/Kings/kings_template.html~7';
LOI[46] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Mat~1~17~images/bible_images/Kings/kings_template.html~7';
LOI[47] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~1';
LOI[48] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~1';
LOI[49] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~2';
LOI[50] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~2';
LOI[51] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~3';
LOI[52] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~3';
LOI[53] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~4';
LOI[54] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~4';
LOI[55] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~5';
LOI[56] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~5';
LOI[57] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~6';
LOI[58] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~6';
LOI[59] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~7';
LOI[60] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~7';
LOI[61] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~8';
LOI[62] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~8';
LOI[63] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~9';
LOI[64] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~9';
LOI[65] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~10';
LOI[66] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~10';
LOI[67] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~11';
LOI[68] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~11';
LOI[69] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~12';
LOI[70] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~12';
LOI[71] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~13';
LOI[72] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~13';
LOI[73] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~14';
LOI[74] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~14';
LOI[75] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~Mat~1~6~images/bible_images/Song/song_template.html~15';
LOI[76] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~Mat~1~7~images/bible_images/Song/song_template.html~15';
