var LOI = [];
LOI[0] = 'hymn~6~O PERFECT LOVE~htm_o_p_operflov.html';
LOI[1] = 'hymn~14~COME CHILDREN, WITH SINGING~htm_c_o_comchild.html';
LOI[2] = 'hymn~14~JESUS LOVES THE LITTLE CHILDREN~htm_j_e_jesloves.html';
LOI[3] = 'hymn~14~LEAD THEM TO THEE~htm_l_e_a_leadthem.html';
LOI[4] = 'hymn~14~LET LITTLE CHILDREN COME TO ME~htm_l_e_lelittle.html';
LOI[5] = 'hymn~14~O JESUS CHRIST, OUR LORD MOST DEAR~htm_o_j_ojcolord.html';
LOI[6] = 'hymn~14~TELL ME THE STORIES OF JESUS~htm_t_m_tmtsoj.html';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Mat~19~28~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Mat~19~28~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Mat~19~28~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee,Jordan~~~~Mat~19~1~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Mat~19~28~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Mat~19~28~images/maps/Christ/christ_template.html~1';
LOI[13] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Mat~19~1~images/maps/Christ/christ_template.html~1';
LOI[14] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Mat~19~7~images/bible_images/Moses/moses_template.html~6';
LOI[15] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Mat~19~8~images/bible_images/Moses/moses_template.html~6';
LOI[16] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Mat~19~7~images/bible_images/Moses/moses_template.html~7';
LOI[17] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Mat~19~8~images/bible_images/Moses/moses_template.html~7';
LOI[18] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Mat~19~7~images/bible_images/Moses/moses_template.html~9';
LOI[19] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Mat~19~8~images/bible_images/Moses/moses_template.html~9';
LOI[20] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Mat~19~7~images/bible_images/Moses/moses_template.html~10';
LOI[21] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Mat~19~8~images/bible_images/Moses/moses_template.html~10';
LOI[22] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Mat~19~7~images/bible_images/Moses/moses_template.html~11';
LOI[23] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Mat~19~8~images/bible_images/Moses/moses_template.html~11';
