var LOI = [];
LOI[0] = 'hymn~1~BRIGHT AND GLORIOUS IS THE SKY~htm_b_r_brightag.html';
LOI[1] = 'hymn~1~BRIGHT WAS THE GUIDING STAR THAT LED~htm_b_r_brightwa.html';
LOI[2] = 'hymn~1~FROM THE EASTERN MOUNTAINS~htm_f_r_fromthee.html';
LOI[3] = 'hymn~1~I AM SO GLAD EACH CHRISTMAS EVE~htm_i_m_imsoglad.html';
LOI[4] = 'hymn~1~I SAW THREE SHIPS COME SAILING IN~htm_i_s_isaw3shp.html';
LOI[5] = 'hymn~1~SAW YOU NEVER, IN THE TWILIGHT?~htm_s_a_sawyoune.html';
LOI[6] = 'hymn~1~STAR IN THE EAST~htm_s_t_stareast.html';
LOI[7] = 'hymn~1~STAR OF BETHLEHEM, THE~htm_s_t_starbeth.html';
LOI[8] = 'hymn~1~THEY ALL WERE LOOKING FOR A KING~htm_t_a_tallwere.html';
LOI[9] = 'hymn~1~WE THREE KINGS~htm_w_e_wethree.html';
LOI[10] = 'hymn~9~THE KINGS OF THE EAST ARE RIDING~htm_k_i_kingeast.html';
LOI[11] = 'hymn~10~AS WITH GLADNESS, MEN OF OLD~htm_a_s_aswithgl.html';
LOI[12] = 'hymn~16~ALL HAIL, YE LITTLE MARTYR FLOWERS~htm_a_l_allhaily.html';
LOI[13] = 'hymn~16~COVENTRY CAROL~htm_c_o_coventry.html';
LOI[14] = 'hymn~16~WHEN CHRIST WAS BORN IN BETHLEHEM~htm_w_h_e_whenborn.html';
LOI[15] = 'hymn~23~HAVE YE BEEN TO NAZARETH?~htm_h_a_haveybtn.html';
LOI[16] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Mat~2~6~images/maps/Otest/otest_template.html~1b';
LOI[17] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Mat~2~20~images/maps/Otest/otest_template.html~1b';
LOI[18] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Mat~2~21~images/maps/Otest/otest_template.html~1b';
LOI[19] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Mat~2~13~images/maps/Otest/otest_template.html~1b';
LOI[20] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Mat~2~19~images/maps/Otest/otest_template.html~1b';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Mat~2~6~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Mat~2~20~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Mat~2~21~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Mat~2~13~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Mat~2~19~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Mat~2~1~images/maps/Otest/otest_template.html~3a';
LOI[27] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Mat~2~3~images/maps/Otest/otest_template.html~3a';
LOI[28] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Mat~2~1~images/maps/Otest/otest_template.html~3b';
LOI[29] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Mat~2~3~images/maps/Otest/otest_template.html~3b';
LOI[30] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Mat~2~6~images/maps/Otest/otest_template.html~3c';
LOI[31] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Mat~2~20~images/maps/Otest/otest_template.html~3c';
LOI[32] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Mat~2~21~images/maps/Otest/otest_template.html~3c';
LOI[33] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Mat~2~22~images/maps/Otest/otest_template.html~3c';
LOI[34] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Bethlehem~~~~Mat~2~6~images/maps/Otest/otest_template.html~4';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Mat~2~20~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Mat~2~21~images/maps/Otest/otest_template.html~4';
LOI[37] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem,Bethlehem~~~~Mat~2~1~images/maps/Otest/otest_template.html~4';
LOI[38] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Mat~2~3~images/maps/Otest/otest_template.html~4';
LOI[39] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~Mat~2~5~images/maps/Otest/otest_template.html~4';
LOI[40] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~Mat~2~8~images/maps/Otest/otest_template.html~4';
LOI[41] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~Mat~2~16~images/maps/Otest/otest_template.html~4';
LOI[42] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Mat~2~13~images/maps/Otest/otest_template.html~5';
LOI[43] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Mat~2~14~images/maps/Otest/otest_template.html~5';
LOI[44] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Mat~2~15~images/maps/Otest/otest_template.html~5';
LOI[45] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Mat~2~19~images/maps/Otest/otest_template.html~5';
LOI[46] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Mat~2~6~images/maps/Christ/christ_template.html~1';
LOI[47] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Mat~2~20~images/maps/Christ/christ_template.html~1';
LOI[48] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Mat~2~21~images/maps/Christ/christ_template.html~1';
LOI[49] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Mat~2~22~images/maps/Christ/christ_template.html~1';
LOI[50] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Mat~2~1~images/places/Israel/israel_template.html~11';
LOI[51] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Mat~2~3~images/places/Israel/israel_template.html~11';
LOI[52] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Mat~2~1~images/places/Israel/israel_template.html~12';
LOI[53] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Mat~2~3~images/places/Israel/israel_template.html~12';
LOI[54] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Mat~2~1~images/places/Israel/israel_template.html~13';
LOI[55] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Mat~2~3~images/places/Israel/israel_template.html~13';
LOI[56] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Mat~2~1~images/places/Israel/israel_template.html~14';
LOI[57] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Mat~2~3~images/places/Israel/israel_template.html~14';
LOI[58] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Mat~2~1~images/places/Israel/israel_template.html~17';
LOI[59] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Mat~2~3~images/places/Israel/israel_template.html~17';
LOI[60] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Mat~2~13~images/bible_images/Moses/moses_template.html~5';
LOI[61] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Mat~2~19~images/bible_images/Moses/moses_template.html~5';
