var LOI = [];
LOI[0] = 'hymn~37~AS BIRDS THEIR INFANT BROOD PROTECT~htm_a_s_asbirdst.html';
LOI[1] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Mat~23~37~images/maps/Otest/otest_template.html~3a';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Mat~23~16~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Mat~23~17~images/maps/Otest/otest_template.html~3a';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Mat~23~21~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Mat~23~35~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Mat~23~37~images/maps/Otest/otest_template.html~3b';
LOI[7] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Mat~23~16~images/maps/Otest/otest_template.html~3b';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Mat~23~17~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Mat~23~21~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Mat~23~35~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Mat~23~37~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Mat~23~37~images/places/Israel/israel_template.html~11';
LOI[13] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Mat~23~37~images/places/Israel/israel_template.html~12';
LOI[14] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Mat~23~37~images/places/Israel/israel_template.html~13';
LOI[15] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Mat~23~37~images/places/Israel/israel_template.html~14';
LOI[16] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Mat~23~37~images/places/Israel/israel_template.html~17';
LOI[17] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Mat~23~2~images/bible_images/Moses/moses_template.html~6';
LOI[18] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Mat~23~2~images/bible_images/Moses/moses_template.html~7';
LOI[19] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Mat~23~2~images/bible_images/Moses/moses_template.html~9';
LOI[20] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Mat~23~2~images/bible_images/Moses/moses_template.html~10';
LOI[21] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Mat~23~2~images/bible_images/Moses/moses_template.html~11';
LOI[22] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Mat~23~16~images/bible_images/Temple/temple_template.html~1';
LOI[23] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Mat~23~17~images/bible_images/Temple/temple_template.html~1';
LOI[24] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Mat~23~21~images/bible_images/Temple/temple_template.html~1';
LOI[25] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Mat~23~35~images/bible_images/Temple/temple_template.html~1';
LOI[26] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Mat~23~16~images/bible_images/Temple/temple_template.html~2';
LOI[27] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Mat~23~17~images/bible_images/Temple/temple_template.html~2';
LOI[28] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Mat~23~21~images/bible_images/Temple/temple_template.html~2';
LOI[29] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Mat~23~35~images/bible_images/Temple/temple_template.html~2';
