var LOI = [];
LOI[0] = 'hymn~3~JESUS, THY CHURCH WITH LONGING EYES~htm_j_t_jthychur.html';
LOI[1] = 'hymn~3~&#8217;TIS ALMOST TIME FOR THE LORD TO COME~htm_t_i_tisalmos.html';
LOI[2] = 'hymn~7~HOW HAPPY ARE THE LITTLE FLOCK~htm_h_o_howhappy.html';
LOI[3] = 'hymn~14~LET THE SONG GO ROUND THE EARTH~htm_l_e_letsongg.html';
LOI[4] = 'hymn~14~LORD, HER WATCH THY CHURCH IS KEEPING~htm_l_h_lhewatch.html';
LOI[5] = 'hymn~14~WATCHMAN, BLOW THE GOSPEL TRUMPET~htm_w_b_wbgtrump.html';
LOI[6] = 'hymn~27~LIGHT IN THE EASTERN SKY~htm_l_e_leastern.html';
LOI[7] = 'hymn~30~MY LORD, WHAT A MORNING!~htm_m_y_mylwhatm.html';
LOI[8] = 'hymn~30~ONCE MORE, O LORD, THY SIGN~htm_o_n_oncemor.html';
LOI[9] = 'hymn~32~THE KING IS COMING IN GLORY~htm_k_i_kingiscg.html';
LOI[10] = 'hymn~32~LIFT UP YOUR HEADS, REJOICE~htm_l_u_lupyhrej.html';
LOI[11] = 'hymn~32~THE MESSAGE OF HIS COMING~htm_m_s_msgcomin.html';
LOI[12] = 'hymn~35~HOLD UP THE GRAND OLD BIBLE~htm_h_o_holdupgb.html';
LOI[13] = 'hymn~35~IF TONIGHT SHOULD END THE WORLD~htm_i_f_iftonite.html';
LOI[14] = 'hymn~35~LORD, THY WORD ABIDETH~htm_l_t_lthyword.html';
LOI[15] = 'hymn~35~MY MOTHER&#8217;S BIBLE~htm_m_y_mymother.html';
LOI[16] = 'hymn~35~O CHANGELESS WORD~htm_o_c_ochglssw.html';
LOI[17] = 'hymn~35~OLD BOOK AND THE OLD FAITH, THE~htm_o_l_oldboldf.html';
LOI[18] = 'hymn~35~STANDING AT THE PORTAL~htm_s_t_standpor.html';
LOI[19] = 'hymn~35~STARRY FIRMAMENT ON HIGH, THE~htm_s_t_starryfi.html';
LOI[20] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Mat~24~1~images/maps/Otest/otest_template.html~3a';
LOI[21] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Mat~24~1~images/maps/Otest/otest_template.html~3b';
LOI[22] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart) key=tribulation~~~~Mat~24~21~images/charts/Bible/bible_template.html~1';
LOI[23] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart) key=tribulation~~~~Mat~24~29~images/charts/Bible/bible_template.html~1';
LOI[24] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Daniel~~~~Mat~24~15~images/bible_images/Daniel/daniel_template.html~1';
LOI[25] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Mat~24~15~images/bible_images/Daniel/daniel_template.html~2';
LOI[26] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Mat~24~15~images/bible_images/Daniel/daniel_template.html~3';
LOI[27] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Mat~24~15~images/bible_images/Daniel/daniel_template.html~4';
LOI[28] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Mat~24~15~images/bible_images/Daniel/daniel_template.html~5';
LOI[29] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Mat~24~15~images/bible_images/Daniel/daniel_template.html~6';
LOI[30] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Mat~24~1~images/bible_images/Temple/temple_template.html~1';
LOI[31] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Mat~24~1~images/bible_images/Temple/temple_template.html~2';
LOI[32] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Mat~24~38~images/bible_images/Temple/temple_template.html~4';
