var LOI = [];
LOI[0] = 'hymn~6~&#8217;MID ALL THE TRAFFIC OF THE WAYS~htm_m_i_midalltt.html';
LOI[1] = 'hymn~6~PRAY, PRAY~htm_p_r_praypray.html';
LOI[2] = 'hymn~8~MY FATHER KNOWS~htm_m_y_myfather.html';
LOI[3] = 'hymn~8~SOMEBODY KNOWS~htm_s_o_somebody.html';
LOI[4] = 'hymn~9~ETERNAL POWER, WHOSE HIGH ABODE~htm_e_p_epwhabod.html';
LOI[5] = 'hymn~9~FATHER OF ALL, TO THEE~htm_f_a_fatheroa.html';
LOI[6] = 'hymn~9~JESUS, KNEEL BESIDE ME~htm_j_k_jkneelbm.html';
LOI[7] = 'hymn~9~THE LORD&#8217;S PRAYER~htm_l_p_lprayer.html';
LOI[8] = 'hymn~10~ALL AS GOD WILLS~htm_a_l_allasgod.html';
LOI[9] = 'hymn~10~HIS WAY WITH THEE~htm_h_i_hiswaywt.html';
LOI[10] = 'hymn~10~LORD OF LIGHT, WHOSE NAME OUTSHINETH~htm_l_o_loflight.html';
LOI[11] = 'hymn~10~MY GOD, MY FATHER, WHILE I STRAY~htm_m_g_mgodmfat.html';
LOI[12] = 'hymn~10~MY JESUS, AS THOU WILT~htm_m_j_mjesuatw.html';
LOI[13] = 'hymn~10~SUN IS SINKING FAST, THE~htm_s_u_sunisink.html';
LOI[14] = 'hymn~10~THY WILL BE DONE~htm_t_w_twbedone.html';
LOI[15] = 'hymn~19~HOW HAPPY IS THE PILGRIM&#8217;S LOT~htm_h_i_hispilot.html';
LOI[16] = 'hymn~19~RISE UP, O MEN OF GOD~htm_r_i_riseupom.html';
LOI[17] = 'hymn~20~LORD, WHEN I ALL THINGS WOULD POSSESS~htm_l_w_lwiatwop.html';
LOI[18] = 'hymn~20~O HOW HAPPY ARE THEY~htm_o_h_ohowhapp.html';
LOI[19] = 'hymn~28~FLOWER CAROL~htm_f_l_flowcaro.html';
LOI[20] = 'hymn~34~JUST FOR TODAY~htm_j_u_justfort.html';
LOI[21] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~Mat~6~29~images/bible_images/Kings/kings_template.html~3';
LOI[22] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~Mat~6~29~images/bible_images/Kings/kings_template.html~4';
LOI[23] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~1';
LOI[24] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~2';
LOI[25] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~3';
LOI[26] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~4';
LOI[27] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~5';
LOI[28] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~6';
LOI[29] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~7';
LOI[30] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~8';
LOI[31] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~9';
LOI[32] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~10';
LOI[33] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~11';
LOI[34] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~12';
LOI[35] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~13';
LOI[36] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~14';
LOI[37] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~Mat~6~29~images/bible_images/Song/song_template.html~15';
