var LOI = [];
LOI[0] = 'hymn~2~WHEN FROM THE EAST THE WISE MEN CAME~htm_w_h_e_whefewmc.html';
LOI[1] = 'hymn~9~ALL GLORY, LAUD AND HONOR~htm_a_g_aglahonr.html';
LOI[2] = 'hymn~9~HOSANNA TO THE LIVING LORD~htm_h_t_htliving.html';
LOI[3] = 'hymn~9~THE SON OF DAVID BOWED TO DIE~htm_s_o_n_sonofdav.html';
LOI[4] = 'hymn~16~CAN A LITTLE CHILD LIKE ME~htm_c_l_clchlime.html';
LOI[5] = 'hymn~16~CHILDREN SING~htm_c_h_chilsing.html';
LOI[6] = 'hymn~16~COME, CHILDREN, RAISE YOUR VOICES~htm_c_o_cocraise.html';
LOI[7] = 'hymn~16~LITTLE CHILDREN, RISE AND SING~htm_l_c_lchildrs.html';
LOI[8] = 'hymn~16~PRAISE HIM, ALL YE LITTLE CHILDREN~htm_p_r_prahimal.html';
LOI[9] = 'hymn~16~SING TO THE LORD THE CHILDREN&#8217;S HYMN~htm_s_i_sing2lch.html';
LOI[10] = 'hymn~41~IN THE VINEYARD OF OUR FATHER~htm_i_v_ivineyar.html';
LOI[11] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Mat~21~1~images/maps/Otest/otest_template.html~3a';
LOI[12] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Mat~21~10~images/maps/Otest/otest_template.html~3a';
LOI[13] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Mat~21~12~images/maps/Otest/otest_template.html~3a';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Mat~21~14~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Mat~21~15~images/maps/Otest/otest_template.html~3a';
LOI[16] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Mat~21~23~images/maps/Otest/otest_template.html~3a';
LOI[17] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Mat~21~1~images/maps/Otest/otest_template.html~3b';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Mat~21~10~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Mat~21~12~images/maps/Otest/otest_template.html~3b';
LOI[20] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Mat~21~14~images/maps/Otest/otest_template.html~3b';
LOI[21] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Mat~21~15~images/maps/Otest/otest_template.html~3b';
LOI[22] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Mat~21~23~images/maps/Otest/otest_template.html~3b';
LOI[23] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Mat~21~11~images/maps/Otest/otest_template.html~3c';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Mat~21~1~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Mat~21~10~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Mat~21~11~images/maps/Christ/christ_template.html~1';
LOI[27] = 'image~Bible~Places~Bethany (engraving) key=Bethany~~~~Mat~21~17~images/places/Israel/israel_template.html~10';
LOI[28] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Mat~21~1~images/places/Israel/israel_template.html~11';
LOI[29] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Mat~21~10~images/places/Israel/israel_template.html~11';
LOI[30] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Mat~21~1~images/places/Israel/israel_template.html~12';
LOI[31] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Mat~21~10~images/places/Israel/israel_template.html~12';
LOI[32] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Mat~21~1~images/places/Israel/israel_template.html~13';
LOI[33] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Mat~21~10~images/places/Israel/israel_template.html~13';
LOI[34] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Mat~21~1~images/places/Israel/israel_template.html~14';
LOI[35] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Mat~21~10~images/places/Israel/israel_template.html~14';
LOI[36] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Mat~21~1~images/places/Israel/israel_template.html~17';
LOI[37] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Mat~21~10~images/places/Israel/israel_template.html~17';
LOI[38] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Mat~21~9~images/bible_images/Kings/kings_template.html~1';
LOI[39] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Mat~21~15~images/bible_images/Kings/kings_template.html~1';
LOI[40] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Mat~21~9~images/bible_images/Kings/kings_template.html~2';
LOI[41] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Mat~21~15~images/bible_images/Kings/kings_template.html~2';
LOI[42] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Mat~21~12~images/bible_images/Temple/temple_template.html~1';
LOI[43] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Mat~21~14~images/bible_images/Temple/temple_template.html~1';
LOI[44] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Mat~21~15~images/bible_images/Temple/temple_template.html~1';
LOI[45] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Mat~21~23~images/bible_images/Temple/temple_template.html~1';
LOI[46] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Mat~21~12~images/bible_images/Temple/temple_template.html~2';
LOI[47] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Mat~21~14~images/bible_images/Temple/temple_template.html~2';
LOI[48] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Mat~21~15~images/bible_images/Temple/temple_template.html~2';
LOI[49] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Mat~21~23~images/bible_images/Temple/temple_template.html~2';
