var LOI = [];
LOI[0] = 'hymn~1~THERE WERE TWELVE DISCIPLES~htm_t_w_twere_12.html';
LOI[1] = 'hymn~23~BELIEVE NOT THOSE WHO SAY~htm_b_e_believen.html';
LOI[2] = 'hymn~23~HOW SHALL I FOLLOW HIM I SERVE?~htm_h_s_hshallif.html';
LOI[3] = 'hymn~29~NOT ALWAYS ON THE MOUNT~htm_n_o_notalotm.html';
LOI[4] = 'hymn~29~O SPLENDOR OF GOD&#8217;S GLORY BRIGHT~htm_o_s_osplendr.html';
LOI[5] = 'hymn~29~O WONDROUS SIGHT!~htm_o_w_owondrus.html';
LOI[6] = 'hymn~58~NO LONGER OF HIM BE IT SAID~htm_n_o_nolonger.html';
LOI[7] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~9~31~images/maps/Otest/otest_template.html~3a';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~9~51~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~9~53~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~9~31~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~9~51~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~9~53~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~9~31~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~9~51~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~9~53~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~9~31~images/places/Israel/israel_template.html~11';
LOI[17] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~9~51~images/places/Israel/israel_template.html~11';
LOI[18] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~9~53~images/places/Israel/israel_template.html~11';
LOI[19] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~9~31~images/places/Israel/israel_template.html~12';
LOI[20] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~9~51~images/places/Israel/israel_template.html~12';
LOI[21] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~9~53~images/places/Israel/israel_template.html~12';
LOI[22] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~9~31~images/places/Israel/israel_template.html~13';
LOI[23] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~9~51~images/places/Israel/israel_template.html~13';
LOI[24] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~9~53~images/places/Israel/israel_template.html~13';
LOI[25] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~9~31~images/places/Israel/israel_template.html~14';
LOI[26] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~9~51~images/places/Israel/israel_template.html~14';
LOI[27] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~9~53~images/places/Israel/israel_template.html~14';
LOI[28] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~9~31~images/places/Israel/israel_template.html~17';
LOI[29] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~9~51~images/places/Israel/israel_template.html~17';
LOI[30] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~9~53~images/places/Israel/israel_template.html~17';
LOI[31] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Luk~9~30~images/bible_images/Moses/moses_template.html~6';
LOI[32] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Luk~9~33~images/bible_images/Moses/moses_template.html~6';
LOI[33] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Luk~9~30~images/bible_images/Moses/moses_template.html~7';
LOI[34] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Luk~9~33~images/bible_images/Moses/moses_template.html~7';
LOI[35] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Luk~9~30~images/bible_images/Moses/moses_template.html~9';
LOI[36] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Luk~9~33~images/bible_images/Moses/moses_template.html~9';
LOI[37] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Luk~9~30~images/bible_images/Moses/moses_template.html~10';
LOI[38] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Luk~9~33~images/bible_images/Moses/moses_template.html~10';
LOI[39] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Luk~9~30~images/bible_images/Moses/moses_template.html~11';
LOI[40] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Luk~9~33~images/bible_images/Moses/moses_template.html~11';
LOI[41] = 'image~Bible~Images~John the Baptist Asks (engraving) key=Baptist~~~~Luk~9~19~images/bible_images/Taylor/taylor_template.html~3';
LOI[42] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving)~~~~Luk~9~12~images/bible_images/Miracles/miracles_template.html~5';
LOI[43] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving)~~~~Luk~9~13~images/bible_images/Miracles/miracles_template.html~5';
LOI[44] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving)~~~~Luk~9~14~images/bible_images/Miracles/miracles_template.html~5';
LOI[45] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving)~~~~Luk~9~15~images/bible_images/Miracles/miracles_template.html~5';
LOI[46] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving)~~~~Luk~9~16~images/bible_images/Miracles/miracles_template.html~5';
LOI[47] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving)~~~~Luk~9~17~images/bible_images/Miracles/miracles_template.html~5';
