var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Luk~4~25~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Luk~4~27~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Luk~4~25~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Luk~4~27~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Temple~~~~Luk~4~9~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Temple~~~~Luk~4~9~images/maps/Otest/otest_template.html~3b';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Luk~4~25~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Luk~4~27~images/maps/Otest/otest_template.html~3c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Luk~4~14~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Luk~4~31~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Luk~4~44~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Luk~4~1~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Luk~4~25~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Luk~4~27~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~4~9~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Luk~4~25~images/maps/Christ/christ_template.html~1';
LOI[16] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Luk~4~27~images/maps/Christ/christ_template.html~1';
LOI[17] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Luk~4~14~images/maps/Christ/christ_template.html~1';
LOI[18] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Luk~4~31~images/maps/Christ/christ_template.html~1';
LOI[19] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Luk~4~44~images/maps/Christ/christ_template.html~1';
LOI[20] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~4~9~images/places/Israel/israel_template.html~11';
LOI[21] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~4~9~images/places/Israel/israel_template.html~12';
LOI[22] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~4~9~images/places/Israel/israel_template.html~13';
LOI[23] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~4~9~images/places/Israel/israel_template.html~14';
LOI[24] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~4~9~images/places/Israel/israel_template.html~17';
LOI[25] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Luk~4~9~images/bible_images/Temple/temple_template.html~1';
LOI[26] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Luk~4~9~images/bible_images/Temple/temple_template.html~2';
