var LOI = [];
LOI[0] = 'hymn~3~REPENT! &#8217;TIS THE VOICE OF JESUS~htm_r_e_repentvj.html';
LOI[1] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~13~4~images/maps/Otest/otest_template.html~3a';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~13~22~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~13~33~images/maps/Otest/otest_template.html~3a';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~13~34~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~13~4~images/maps/Otest/otest_template.html~3b';
LOI[6] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~13~22~images/maps/Otest/otest_template.html~3b';
LOI[7] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~13~33~images/maps/Otest/otest_template.html~3b';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~13~34~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~13~4~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~13~22~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~13~33~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~13~34~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Luk~13~16~images/places/Israel/israel_template.html~8';
LOI[14] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Luk~13~28~images/places/Israel/israel_template.html~8';
LOI[15] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~13~4~images/places/Israel/israel_template.html~11';
LOI[16] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~13~22~images/places/Israel/israel_template.html~11';
LOI[17] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~13~33~images/places/Israel/israel_template.html~11';
LOI[18] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~13~34~images/places/Israel/israel_template.html~11';
LOI[19] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~13~4~images/places/Israel/israel_template.html~12';
LOI[20] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~13~22~images/places/Israel/israel_template.html~12';
LOI[21] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~13~33~images/places/Israel/israel_template.html~12';
LOI[22] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~13~34~images/places/Israel/israel_template.html~12';
LOI[23] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~13~4~images/places/Israel/israel_template.html~13';
LOI[24] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~13~22~images/places/Israel/israel_template.html~13';
LOI[25] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~13~33~images/places/Israel/israel_template.html~13';
LOI[26] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~13~34~images/places/Israel/israel_template.html~13';
LOI[27] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~13~4~images/places/Israel/israel_template.html~14';
LOI[28] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~13~22~images/places/Israel/israel_template.html~14';
LOI[29] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~13~33~images/places/Israel/israel_template.html~14';
LOI[30] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~13~34~images/places/Israel/israel_template.html~14';
LOI[31] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~13~4~images/places/Israel/israel_template.html~17';
LOI[32] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~13~22~images/places/Israel/israel_template.html~17';
LOI[33] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~13~33~images/places/Israel/israel_template.html~17';
LOI[34] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~13~34~images/places/Israel/israel_template.html~17';
LOI[35] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Luk~13~16~images/bible_images/Moses/moses_template.html~3';
LOI[36] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Luk~13~28~images/bible_images/Moses/moses_template.html~3';
LOI[37] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Luk~13~16~images/bible_images/Moses/moses_template.html~3i';
LOI[38] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Luk~13~28~images/bible_images/Moses/moses_template.html~3i';
LOI[39] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~Luk~13~28~images/bible_images/Moses/moses_template.html~3a';
LOI[40] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Luk~13~16~images/bible_images/Moses/moses_template.html~3a';
LOI[41] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Luk~13~28~images/bible_images/Moses/moses_template.html~4';
