var LOI = [];
LOI[0] = 'hymn~1~PRAYER IS THE SOUL&#8217;S SINCERE DESIRE~htm_p_r_prayeris.html';
LOI[1] = 'hymn~2~THY KINGDOM COME~htm_t_h_thykingc.html';
LOI[2] = 'hymn~2~THY KINGDOM COME, O GOD~htm_t_h_y_thykicog.html';
LOI[3] = 'hymn~2~THY KINGDOM COME, O LORD~htm_t_h_y_thykicol.html';
LOI[4] = 'hymn~2~THY KINGDOM COME, ON BENDED KNEE~htm_t_h_thykcobk.html';
LOI[5] = 'hymn~3~DAY BY DAY THE MANNA FELL~htm_d_a_daymanna.html';
LOI[6] = 'hymn~4~GENTLY LORD, O GENTLY LEAD US~htm_g_e_gentlylo.html';
LOI[7] = 'hymn~9~TELL IT TO JESUS~htm_t_e_tellitto.html';
LOI[8] = 'hymn~28~O BLESSED BIBLE~htm_o_b_oblessbi.html';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Luk~11~51~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Luk~11~51~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~Luk~11~31~images/bible_images/Kings/kings_template.html~3';
LOI[12] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~Luk~11~31~images/bible_images/Kings/kings_template.html~4';
LOI[13] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~1';
LOI[14] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~2';
LOI[15] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~3';
LOI[16] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~4';
LOI[17] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~5';
LOI[18] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~6';
LOI[19] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~7';
LOI[20] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~8';
LOI[21] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~9';
LOI[22] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~10';
LOI[23] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~11';
LOI[24] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~12';
LOI[25] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~13';
LOI[26] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~14';
LOI[27] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~Luk~11~31~images/bible_images/Song/song_template.html~15';
LOI[28] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Luk~11~51~images/bible_images/Temple/temple_template.html~1';
LOI[29] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Luk~11~51~images/bible_images/Temple/temple_template.html~2';
