var LOI = [];
LOI[0] = 'hymn~5~HEAR US, O LORD~htm_h_e_hearusol.html';
LOI[1] = 'hymn~20~THE HALLOWED SPOT~htm_h_a_hallowed.html';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Levi~~~~Luk~5~27~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Levi~~~~Luk~5~29~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Levi~~~~Luk~5~27~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Levi~~~~Luk~5~29~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~5~17~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~5~17~images/maps/Otest/otest_template.html~3b';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Luk~5~17~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~5~17~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Luk~5~17~images/maps/Christ/christ_template.html~1';
LOI[11] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~5~17~images/places/Israel/israel_template.html~11';
LOI[12] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~5~17~images/places/Israel/israel_template.html~12';
LOI[13] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~5~17~images/places/Israel/israel_template.html~13';
LOI[14] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~5~17~images/places/Israel/israel_template.html~14';
LOI[15] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~5~17~images/places/Israel/israel_template.html~17';
LOI[16] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Luk~5~14~images/bible_images/Moses/moses_template.html~6';
LOI[17] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Luk~5~14~images/bible_images/Moses/moses_template.html~7';
LOI[18] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Luk~5~14~images/bible_images/Moses/moses_template.html~9';
LOI[19] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Luk~5~14~images/bible_images/Moses/moses_template.html~10';
LOI[20] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Luk~5~14~images/bible_images/Moses/moses_template.html~11';
LOI[21] = 'image~Bible~Images~The Leper Healed (engraving)~~~~Luk~5~12~images/bible_images/Miracles/miracles_template.html~1';
LOI[22] = 'image~Bible~Images~The Leper Healed (engraving)~~~~Luk~5~13~images/bible_images/Miracles/miracles_template.html~1';
LOI[23] = 'image~Bible~Images~The Leper Healed (engraving)~~~~Luk~5~14~images/bible_images/Miracles/miracles_template.html~1';
LOI[24] = 'image~Bible~Images~The Leper Healed (engraving)~~~~Luk~5~15~images/bible_images/Miracles/miracles_template.html~1';
LOI[25] = 'image~Bible~Images~The Leper Healed (engraving)~~~~Luk~5~16~images/bible_images/Miracles/miracles_template.html~1';
LOI[26] = 'image~Bible~Images~Man With Palsy Healed (engraving)~~~~Luk~5~17~images/bible_images/Miracles/miracles_template.html~2';
LOI[27] = 'image~Bible~Images~Man With Palsy Healed (engraving)~~~~Luk~5~18~images/bible_images/Miracles/miracles_template.html~2';
LOI[28] = 'image~Bible~Images~Man With Palsy Healed (engraving)~~~~Luk~5~19~images/bible_images/Miracles/miracles_template.html~2';
LOI[29] = 'image~Bible~Images~Man With Palsy Healed (engraving)~~~~Luk~5~20~images/bible_images/Miracles/miracles_template.html~2';
LOI[30] = 'image~Bible~Images~Man With Palsy Healed (engraving)~~~~Luk~5~21~images/bible_images/Miracles/miracles_template.html~2';
LOI[31] = 'image~Bible~Images~Man With Palsy Healed (engraving)~~~~Luk~5~22~images/bible_images/Miracles/miracles_template.html~2';
LOI[32] = 'image~Bible~Images~Man With Palsy Healed (engraving)~~~~Luk~5~23~images/bible_images/Miracles/miracles_template.html~2';
LOI[33] = 'image~Bible~Images~Man With Palsy Healed (engraving)~~~~Luk~5~24~images/bible_images/Miracles/miracles_template.html~2';
LOI[34] = 'image~Bible~Images~Man With Palsy Healed (engraving)~~~~Luk~5~25~images/bible_images/Miracles/miracles_template.html~2';
LOI[35] = 'image~Bible~Images~Man With Palsy Healed (engraving)~~~~Luk~5~26~images/bible_images/Miracles/miracles_template.html~2';
