var LOI = [];
LOI[0] = 'hymn~27~BLESSING AND HONOR AND GLORY AND POWER~htm_b_l_blessing.html';
LOI[1] = 'hymn~27~THE HOPE OF THE AGES~htm_h_o_hopeages.html';
LOI[2] = 'hymn~27~WHEN JESUS COMES IN GLORY~htm_w_j_wjcomesg.html';
LOI[3] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~21~20~images/maps/Otest/otest_template.html~3a';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~21~24~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Luk~21~5~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Luk~21~37~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Luk~21~38~images/maps/Otest/otest_template.html~3a';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~21~20~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~21~24~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Luk~21~5~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Luk~21~37~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Luk~21~38~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~21~20~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~21~24~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~21~20~images/places/Israel/israel_template.html~11';
LOI[16] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~21~24~images/places/Israel/israel_template.html~11';
LOI[17] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~21~20~images/places/Israel/israel_template.html~12';
LOI[18] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~21~24~images/places/Israel/israel_template.html~12';
LOI[19] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~21~20~images/places/Israel/israel_template.html~13';
LOI[20] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~21~24~images/places/Israel/israel_template.html~13';
LOI[21] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~21~20~images/places/Israel/israel_template.html~14';
LOI[22] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~21~24~images/places/Israel/israel_template.html~14';
LOI[23] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~21~20~images/places/Israel/israel_template.html~17';
LOI[24] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~21~24~images/places/Israel/israel_template.html~17';
LOI[25] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Luk~21~5~images/bible_images/Temple/temple_template.html~1';
LOI[26] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Luk~21~37~images/bible_images/Temple/temple_template.html~1';
LOI[27] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Luk~21~38~images/bible_images/Temple/temple_template.html~1';
LOI[28] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Luk~21~5~images/bible_images/Temple/temple_template.html~2';
LOI[29] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Luk~21~37~images/bible_images/Temple/temple_template.html~2';
LOI[30] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Luk~21~38~images/bible_images/Temple/temple_template.html~2';
