var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Simeon,Joseph~~~~Luk~3~30~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Levi,Joseph~~~~Luk~3~24~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Levi~~~~Luk~3~29~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Luk~3~23~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Luk~3~26~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Simeon,Joseph~~~~Luk~3~30~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Levi,Joseph~~~~Luk~3~24~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Levi~~~~Luk~3~29~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Luk~3~23~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Luk~3~26~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Luk~3~1~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Luk~3~3~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Luk~3~1~images/maps/Christ/christ_template.html~1';
LOI[13] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Luk~3~8~images/places/Israel/israel_template.html~8';
LOI[14] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Luk~3~34~images/places/Israel/israel_template.html~8';
LOI[15] = 'image~Bible~Images~The Judgement of Adam and Eve (engraving) key=Adam~~~~Luk~3~38~images/bible_images/Moses/moses_template.html~1b';
LOI[16] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Luk~3~8~images/bible_images/Moses/moses_template.html~3';
LOI[17] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Luk~3~34~images/bible_images/Moses/moses_template.html~3';
LOI[18] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Luk~3~8~images/bible_images/Moses/moses_template.html~3i';
LOI[19] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Luk~3~34~images/bible_images/Moses/moses_template.html~3i';
LOI[20] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~Luk~3~34~images/bible_images/Moses/moses_template.html~3a';
LOI[21] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Luk~3~8~images/bible_images/Moses/moses_template.html~3a';
LOI[22] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Luk~3~34~images/bible_images/Moses/moses_template.html~4';
LOI[23] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Luk~3~23~images/bible_images/Moses/moses_template.html~5';
LOI[24] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Luk~3~24~images/bible_images/Moses/moses_template.html~5';
LOI[25] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Luk~3~26~images/bible_images/Moses/moses_template.html~5';
LOI[26] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Luk~3~30~images/bible_images/Moses/moses_template.html~5';
LOI[27] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Luk~3~31~images/bible_images/Kings/kings_template.html~1';
LOI[28] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Luk~3~31~images/bible_images/Kings/kings_template.html~2';
