var LOI = [];
LOI[0] = 'hymn~6~THE FRIENDLY BEASTS~htm_f_r_friendbe.html';
LOI[1] = 'hymn~6~ONCE IN ROYAL DAVID&#8217;S CITY~htm_o_n_onceirdc.html';
LOI[2] = 'hymn~7~AH, DEAREST JESUS~htm_a_d_adearest.html';
LOI[3] = 'hymn~7~AWAY IN A MANGER~htm_a_w_awaymang.html';
LOI[4] = 'hymn~7~CHILD IN THE MANGER~htm_c_h_childman.html';
LOI[5] = 'hymn~7~CRADLED IN A MANGER, MEANLY~htm_c_r_cradledi.html';
LOI[6] = 'hymn~7~DEAR LITTLE STRANGER~htm_d_e_dearlitt.html';
LOI[7] = 'hymn~7~DOST THOU IN A MANGER LIE?~htm_d_o_dostthou.html';
LOI[8] = 'hymn~7~GENTLE MARY LAID HER CHILD~htm_g_e_gentleml.html';
LOI[9] = 'hymn~7~GIVE HEED, MY HEART~htm_g_i_giveheed.html';
LOI[10] = 'hymn~7~GLAD CHRISTMAS BELLS~htm_g_l_gladxmas.html';
LOI[11] = 'hymn~7~HUSH, MY DEAR~htm_h_u_hushmyba.html';
LOI[12] = 'hymn~7~IN THE BLEAK MIDWINTER~htm_i_n_intbleak.html';
LOI[13] = 'hymn~7~INFANT HOLY, INFANT LOWLY~htm_i_n_infantho.html';
LOI[14] = 'hymn~7~NO ROOM IN THE INN~htm_n_r_nroomitn.html';
LOI[15] = 'hymn~7~O JESUS CHRIST, THY MANGER IS~htm_o_j_ojctmang.html';
LOI[16] = 'hymn~7~RING OUT THE BELLS FOR CHRISTMAS~htm_r_o_rotbxmas.html';
LOI[17] = 'hymn~7~SNOW LAY ON GROUND, THE~htm_s_n_snowlayg.html';
LOI[18] = 'hymn~7~THERE CAME A LITTLE CHILD TO EARTH~htm_t_h_thercame.html';
LOI[19] = 'hymn~7~THERE&#8217;S A SONG IN THE AIR~htm_t_s_tsongair.html';
LOI[20] = 'hymn~7~THIS ENDRIS NIGHT~htm_t_h_thisendr.html';
LOI[21] = 'hymn~7~WHEN CHRISTMAS MORN IS DAWNING~htm_w_x_wxmasmid.html';
LOI[22] = 'hymn~8~THE CHILD AND THE SHEPHERD~htm_c_h_childshe.html';
LOI[23] = 'hymn~8~CHRISTIANS, AWAKE, SALUTE THE HAPPY MORN~htm_c_a_casthamo.html';
LOI[24] = 'hymn~8~DAWNING FAIR, MORNING WONDERFUL~htm_d_a_dawningf.html';
LOI[25] = 'hymn~8~THE FIRST NOEL~htm_f_r_frstnoel.html';
LOI[26] = 'hymn~8~GO, TELL IT ON THE MOUNTAIN~htm_g_o_gotitotm.html';
LOI[27] = 'hymn~8~IN THE FIELD WITH THEIR FLOCKS ABIDING~htm_i_n_intfield.html';
LOI[28] = 'hymn~8~IT CAME UPON THE MIDNIGHT CLEAR~htm_i_t_itcameup.html';
LOI[29] = 'hymn~8~LONG YEARS AGO O&#8217;ER BETHLEHEM&#8217;S HILLS~htm_l_o_longyear.html';
LOI[30] = 'hymn~8~O HOLY NIGHT~htm_o_h_oholynit.html';
LOI[31] = 'hymn~8~O SING A SONG OF BETHLEHEM~htm_o_s_osingson.html';
LOI[32] = 'hymn~8~RISE UP, SHEPHERD, AND FOLLOW~htm_r_i_riseupsh.html';
LOI[33] = 'hymn~8~SEE AMID THE WINTER&#8217;S SNOW~htm_s_e_seeamid.html';
LOI[34] = 'hymn~8~SILENT NIGHT~htm_s_i_silntnit.html';
LOI[35] = 'hymn~8~THE STORY THAT NEVER GROWS OLD~htm_s_t_storthat.html';
LOI[36] = 'hymn~8~WHILE SHEPHERDS WATCHED THEIR FLOCKS~htm_w_s_wshepwtf.html';
LOI[37] = 'hymn~9~ONCE O&#8217;ER JUDEA&#8217;S HILLS BY NIGHT~htm_o_n_onceoerj.html';
LOI[38] = 'hymn~10~FROM HEAVEN ABOVE TO EARTH I COME~htm_f_r_fromheav.html';
LOI[39] = 'hymn~10~GLAD TIDINGS~htm_g_l_gladtids.html';
LOI[40] = 'hymn~10~GOD REST YE MERRY, GENTLEMEN~htm_g_o_godrest.html';
LOI[41] = 'hymn~10~HARK! HARK! THE NOTES OF JOY~htm_h_h_hhnotesj.html';
LOI[42] = 'hymn~10~JOY FILLS OUR INMOST HEARTS TODAY!~htm_j_o_joyfills.html';
LOI[43] = 'hymn~10~JOY TO THE WORLD~htm_j_o_joyworld.html';
LOI[44] = 'hymn~10~LET SIGHING CEASE AND WOE~htm_l_s_lsighing.html';
LOI[45] = 'hymn~10~ON CHRISTMAS NIGHT ALL CHRISTIANS SING~htm_o_x_oxnallcs.html';
LOI[46] = 'hymn~10~ON JUDAH&#8217;S PLAINS AS SHEPHERDS SAT~htm_o_n_onjudahs.html';
LOI[47] = 'hymn~10~REJOICE, REJOICE, YE CHRISTIANS~htm_r_e_rejrejyc.html';
LOI[48] = 'hymn~10~SHEPHERDS, REJOICE! LIFT UP YOUR EYES~htm_s_r_srliftup.html';
LOI[49] = 'hymn~10~SHOUT THE GLAD TIDINGS~htm_s_h_shouttgt.html';
LOI[50] = 'hymn~10~WE CHRISTIANS MAY REJOICE TODAY~htm_w_e_wechrist.html';
LOI[51] = 'hymn~10~YE CHRISTIAN HERALDS, GO PROCLAIM~htm_y_e_yechrist.html';
LOI[52] = 'hymn~11~ALL MY HEART THIS NIGHT REJOICES~htm_a_l_allmyhea.html';
LOI[53] = 'hymn~11~BRING A TORCH, JEANETTE, ISABELLA~htm_b_r_bringtor.html';
LOI[54] = 'hymn~11~A CHILD THIS DAY IS BORN~htm_c_h_childthi.html';
LOI[55] = 'hymn~11~COME HITHER, YE FAITHFUL~htm_c_o_comehith.html';
LOI[56] = 'hymn~11~REJOICE, REJOICE, THIS HAPPY MORN~htm_r_e_rejrejth.html';
LOI[57] = 'hymn~13~ANGELS FROM THE REALM OF GLORY~htm_a_f_afrglory.html';
LOI[58] = 'hymn~13~ANGELS WE HAVE HEARD ON HIGH~htm_a_n_angelswe.html';
LOI[59] = 'hymn~13~CALM ON THE LISTENING EAR OF NIGHT~htm_c_a_calmonth.html';
LOI[60] = 'hymn~13~DO YOU KNOW THE SONG THAT THE ANGELS SANG~htm_d_y_dyknowts.html';
LOI[61] = 'hymn~13~FROM EVERY SPIRE ON CHRISTMAS EVE~htm_f_e_fevsponx.html';
LOI[62] = 'hymn~13~HARK! THE HERALD ANGELS SING~htm_h_h_hheralda.html';
LOI[63] = 'hymn~13~HARK! WHAT MEAN THOSE HOLY VOICES?~htm_h_w_hwhamean.html';
LOI[64] = 'hymn~13~HEARKEN, ALL! WHAT HOLY SINGING~htm_h_e_hearkena.html';
LOI[65] = 'hymn~13~I HEARD THE BELLS ON CHRISTMAS DAY~htm_i_h_iheardtb.html';
LOI[66] = 'hymn~13~IN THE LONELY MIDNIGHT~htm_i_n_inlonemi.html';
LOI[67] = 'hymn~13~LONG AGO A SHINING THRONG~htm_l_o_longagos.html';
LOI[68] = 'hymn~13~MORTALS AWAKE, WITH ANGELS JOIN~htm_m_o_mortawaj.html';
LOI[69] = 'hymn~13~MUSIC ON CHRISTMAS MORNING~htm_m_u_musiconx.html';
LOI[70] = 'hymn~13~PEACEFUL THE WONDROUS NIGHT~htm_p_e_peaceful.html';
LOI[71] = 'hymn~14~FAR, FAR AWAY ON JUDEA&#8217;S PLAINS~htm_f_a_farfaraw.html';
LOI[72] = 'hymn~14~GLORY TO GOD, HALLELUJAH~htm_g_l_glorytog.html';
LOI[73] = 'hymn~14~HAPPY CHRISTMAS COMES ONCE MORE, THE~htm_h_a_hapyxmas.html';
LOI[74] = 'hymn~14~ON A CHRISTMAS MORNING~htm_o_x_oxmasmor.html';
LOI[75] = 'hymn~15~COME, ALL YE SHEPHERDS~htm_c_o_comeayes.html';
LOI[76] = 'hymn~15~O COME, ALL YE FAITHFUL~htm_o_c_ocomeayf.html';
LOI[77] = 'hymn~16~WHO IS HE IN YONDER STALL?~htm_w_h_whoishe.html';
LOI[78] = 'hymn~20~OUR DAY OF JOY IS HERE AGAIN~htm_o_u_ourdayoj.html';
LOI[79] = 'hymn~20~SLEEP, MY LITTLE JESUS~htm_s_l_sleepmlj.html';
LOI[80] = 'hymn~22~HAIL TO THE LORD WHO COMES~htm_h_l_hlwcomes.html';
LOI[81] = 'hymn~22~O HAPPY DAY, WHEN FIRST WAS POURED~htm_o_h_ohappyda.html';
LOI[82] = 'hymn~32~IT IS GLORY JUST TO WALK WITH HIM~htm_i_t_itisglor.html';
LOI[83] = 'hymn~34~O ZION OPEN WIDE THY GATES~htm_o_z_ozionope.html';
LOI[84] = 'hymn~40~BY COOL SILOAM&#8217;S SHADY RILL~htm_b_y_bycoolsi.html';
LOI[85] = 'hymn~49~O MASTER WORKMAN OF THE RACE~htm_o_m_omasterw.html';
LOI[86] = 'hymn~52~IN STATURE GROWS THE HEAVENLY CHILD~htm_i_n_instatur.html';
LOI[87] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Simeon~~~~Luk~2~25~images/maps/Otest/otest_template.html~1b';
LOI[88] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Luk~2~32~images/maps/Otest/otest_template.html~1b';
LOI[89] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Simeon~~~~Luk~2~34~images/maps/Otest/otest_template.html~1b';
LOI[90] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Luk~2~4~images/maps/Otest/otest_template.html~1b';
LOI[91] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Luk~2~16~images/maps/Otest/otest_template.html~1b';
LOI[92] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Luk~2~33~images/maps/Otest/otest_template.html~1b';
LOI[93] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Luk~2~43~images/maps/Otest/otest_template.html~1b';
LOI[94] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Simeon~~~~Luk~2~25~images/maps/Otest/otest_template.html~1c';
LOI[95] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Luk~2~32~images/maps/Otest/otest_template.html~1c';
LOI[96] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Simeon~~~~Luk~2~34~images/maps/Otest/otest_template.html~1c';
LOI[97] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Luk~2~4~images/maps/Otest/otest_template.html~1c';
LOI[98] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Luk~2~16~images/maps/Otest/otest_template.html~1c';
LOI[99] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Luk~2~33~images/maps/Otest/otest_template.html~1c';
LOI[100] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Luk~2~43~images/maps/Otest/otest_template.html~1c';
LOI[101] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~2~22~images/maps/Otest/otest_template.html~3a';
LOI[102] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~2~25~images/maps/Otest/otest_template.html~3a';
LOI[103] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~2~38~images/maps/Otest/otest_template.html~3a';
LOI[104] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~2~41~images/maps/Otest/otest_template.html~3a';
LOI[105] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~2~42~images/maps/Otest/otest_template.html~3a';
LOI[106] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~2~43~images/maps/Otest/otest_template.html~3a';
LOI[107] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~2~45~images/maps/Otest/otest_template.html~3a';
LOI[108] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Luk~2~27~images/maps/Otest/otest_template.html~3a';
LOI[109] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Luk~2~37~images/maps/Otest/otest_template.html~3a';
LOI[110] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Luk~2~46~images/maps/Otest/otest_template.html~3a';
LOI[111] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~2~22~images/maps/Otest/otest_template.html~3b';
LOI[112] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~2~25~images/maps/Otest/otest_template.html~3b';
LOI[113] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~2~38~images/maps/Otest/otest_template.html~3b';
LOI[114] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~2~41~images/maps/Otest/otest_template.html~3b';
LOI[115] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~2~42~images/maps/Otest/otest_template.html~3b';
LOI[116] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~2~43~images/maps/Otest/otest_template.html~3b';
LOI[117] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~2~45~images/maps/Otest/otest_template.html~3b';
LOI[118] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Luk~2~27~images/maps/Otest/otest_template.html~3b';
LOI[119] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Luk~2~37~images/maps/Otest/otest_template.html~3b';
LOI[120] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Luk~2~46~images/maps/Otest/otest_template.html~3b';
LOI[121] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Luk~2~25~images/maps/Otest/otest_template.html~3c';
LOI[122] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Luk~2~32~images/maps/Otest/otest_template.html~3c';
LOI[123] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Luk~2~34~images/maps/Otest/otest_template.html~3c';
LOI[124] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Luk~2~4~images/maps/Otest/otest_template.html~3c';
LOI[125] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Luk~2~39~images/maps/Otest/otest_template.html~3c';
LOI[126] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jerusalem~~~~Luk~2~25~images/maps/Otest/otest_template.html~4';
LOI[127] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Luk~2~32~images/maps/Otest/otest_template.html~4';
LOI[128] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Luk~2~34~images/maps/Otest/otest_template.html~4';
LOI[129] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~2~22~images/maps/Otest/otest_template.html~4';
LOI[130] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~2~38~images/maps/Otest/otest_template.html~4';
LOI[131] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~2~41~images/maps/Otest/otest_template.html~4';
LOI[132] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~2~42~images/maps/Otest/otest_template.html~4';
LOI[133] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~2~43~images/maps/Otest/otest_template.html~4';
LOI[134] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~2~45~images/maps/Otest/otest_template.html~4';
LOI[135] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~Luk~2~4~images/maps/Otest/otest_template.html~4';
LOI[136] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~Luk~2~15~images/maps/Otest/otest_template.html~4';
LOI[137] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Luk~2~25~images/maps/Christ/christ_template.html~1';
LOI[138] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Luk~2~32~images/maps/Christ/christ_template.html~1';
LOI[139] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Luk~2~34~images/maps/Christ/christ_template.html~1';
LOI[140] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Luk~2~4~images/maps/Christ/christ_template.html~1';
LOI[141] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Luk~2~39~images/maps/Christ/christ_template.html~1';
LOI[142] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~Luk~2~2~images/maps/Journeys/journeys_template.html~2';
LOI[143] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~2~22~images/places/Israel/israel_template.html~11';
LOI[144] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~2~25~images/places/Israel/israel_template.html~11';
LOI[145] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~2~38~images/places/Israel/israel_template.html~11';
LOI[146] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~2~41~images/places/Israel/israel_template.html~11';
LOI[147] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~2~42~images/places/Israel/israel_template.html~11';
LOI[148] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~2~43~images/places/Israel/israel_template.html~11';
LOI[149] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~2~45~images/places/Israel/israel_template.html~11';
LOI[150] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~2~22~images/places/Israel/israel_template.html~12';
LOI[151] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~2~25~images/places/Israel/israel_template.html~12';
LOI[152] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~2~38~images/places/Israel/israel_template.html~12';
LOI[153] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~2~41~images/places/Israel/israel_template.html~12';
LOI[154] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~2~42~images/places/Israel/israel_template.html~12';
LOI[155] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~2~43~images/places/Israel/israel_template.html~12';
LOI[156] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~2~45~images/places/Israel/israel_template.html~12';
LOI[157] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~2~22~images/places/Israel/israel_template.html~13';
LOI[158] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~2~25~images/places/Israel/israel_template.html~13';
LOI[159] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~2~38~images/places/Israel/israel_template.html~13';
LOI[160] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~2~41~images/places/Israel/israel_template.html~13';
LOI[161] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~2~42~images/places/Israel/israel_template.html~13';
LOI[162] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~2~43~images/places/Israel/israel_template.html~13';
LOI[163] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~2~45~images/places/Israel/israel_template.html~13';
LOI[164] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~2~22~images/places/Israel/israel_template.html~14';
LOI[165] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~2~25~images/places/Israel/israel_template.html~14';
LOI[166] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~2~38~images/places/Israel/israel_template.html~14';
LOI[167] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~2~41~images/places/Israel/israel_template.html~14';
LOI[168] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~2~42~images/places/Israel/israel_template.html~14';
LOI[169] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~2~43~images/places/Israel/israel_template.html~14';
LOI[170] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~2~45~images/places/Israel/israel_template.html~14';
LOI[171] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~2~22~images/places/Israel/israel_template.html~17';
LOI[172] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~2~25~images/places/Israel/israel_template.html~17';
LOI[173] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~2~38~images/places/Israel/israel_template.html~17';
LOI[174] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~2~41~images/places/Israel/israel_template.html~17';
LOI[175] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~2~42~images/places/Israel/israel_template.html~17';
LOI[176] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~2~43~images/places/Israel/israel_template.html~17';
LOI[177] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~2~45~images/places/Israel/israel_template.html~17';
LOI[178] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Luk~2~4~images/bible_images/Moses/moses_template.html~5';
LOI[179] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Luk~2~16~images/bible_images/Moses/moses_template.html~5';
LOI[180] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Luk~2~33~images/bible_images/Moses/moses_template.html~5';
LOI[181] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Luk~2~43~images/bible_images/Moses/moses_template.html~5';
LOI[182] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Luk~2~22~images/bible_images/Moses/moses_template.html~6';
LOI[183] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Luk~2~22~images/bible_images/Moses/moses_template.html~7';
LOI[184] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Luk~2~22~images/bible_images/Moses/moses_template.html~9';
LOI[185] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Luk~2~22~images/bible_images/Moses/moses_template.html~10';
LOI[186] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Luk~2~22~images/bible_images/Moses/moses_template.html~11';
LOI[187] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Luk~2~4~images/bible_images/Kings/kings_template.html~1';
LOI[188] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Luk~2~11~images/bible_images/Kings/kings_template.html~1';
LOI[189] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Luk~2~4~images/bible_images/Kings/kings_template.html~2';
LOI[190] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Luk~2~11~images/bible_images/Kings/kings_template.html~2';
LOI[191] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Luk~2~27~images/bible_images/Temple/temple_template.html~1';
LOI[192] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Luk~2~37~images/bible_images/Temple/temple_template.html~1';
LOI[193] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Luk~2~46~images/bible_images/Temple/temple_template.html~1';
LOI[194] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Luk~2~27~images/bible_images/Temple/temple_template.html~2';
LOI[195] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Luk~2~37~images/bible_images/Temple/temple_template.html~2';
LOI[196] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Luk~2~46~images/bible_images/Temple/temple_template.html~2';
