var LOI = [];
LOI[0] = 'hymn~14~IN THEE IS GLADNESS~htm_i_n_intheeis.html';
LOI[1] = 'hymn~35~NOW YIELD WE THANKS AND PRAISE~htm_n_o_nowyield.html';
LOI[2] = 'hymn~38~FROM EAST WEST, FROM SHORE TO SHORE~htm_f_r_fromeast.html';
LOI[3] = 'hymn~47~O WHAT SHALL I DO, MY SAVIOR TO PRAISE~htm_o_w_owhatsid.html';
LOI[4] = 'hymn~47~REST OF THE WEARY~htm_r_e_restwear.html';
LOI[5] = 'hymn~50~THERE&#8217;S A WIDENESS IN GOD&#8217;S MERCY~htm_t_h_therwide.html';
LOI[6] = 'hymn~78~AWAKE, MY SOUL, AWAKE, MY TONGUE~htm_a_w_awakmsmt.html';
LOI[7] = 'hymn~78~DAYSPRING OF ETERNITY~htm_d_a_dayspring.html';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Luk~1~16~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Luk~1~54~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Luk~1~68~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Luk~1~80~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Luk~1~27~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Luk~1~16~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Luk~1~54~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Luk~1~68~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Luk~1~80~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Luk~1~27~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Luk~1~9~images/maps/Otest/otest_template.html~3a';
LOI[19] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Luk~1~21~images/maps/Otest/otest_template.html~3a';
LOI[20] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Luk~1~22~images/maps/Otest/otest_template.html~3a';
LOI[21] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Luk~1~9~images/maps/Otest/otest_template.html~3b';
LOI[22] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Luk~1~21~images/maps/Otest/otest_template.html~3b';
LOI[23] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Luk~1~22~images/maps/Otest/otest_template.html~3b';
LOI[24] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Luk~1~16~images/maps/Otest/otest_template.html~3c';
LOI[25] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Luk~1~54~images/maps/Otest/otest_template.html~3c';
LOI[26] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Luk~1~68~images/maps/Otest/otest_template.html~3c';
LOI[27] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Luk~1~80~images/maps/Otest/otest_template.html~3c';
LOI[28] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Luk~1~26~images/maps/Otest/otest_template.html~3c';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Luk~1~16~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Luk~1~54~images/maps/Otest/otest_template.html~4';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Luk~1~68~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Luk~1~80~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Luk~1~16~images/maps/Christ/christ_template.html~1';
LOI[34] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Luk~1~54~images/maps/Christ/christ_template.html~1';
LOI[35] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Luk~1~68~images/maps/Christ/christ_template.html~1';
LOI[36] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Luk~1~80~images/maps/Christ/christ_template.html~1';
LOI[37] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Luk~1~26~images/maps/Christ/christ_template.html~1';
LOI[38] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Luk~1~55~images/places/Israel/israel_template.html~8';
LOI[39] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Luk~1~73~images/places/Israel/israel_template.html~8';
LOI[40] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Luk~1~55~images/bible_images/Moses/moses_template.html~3';
LOI[41] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Luk~1~73~images/bible_images/Moses/moses_template.html~3';
LOI[42] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Luk~1~9~images/bible_images/Moses/moses_template.html~3i';
LOI[43] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Luk~1~55~images/bible_images/Moses/moses_template.html~3i';
LOI[44] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Luk~1~73~images/bible_images/Moses/moses_template.html~3i';
LOI[45] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Luk~1~55~images/bible_images/Moses/moses_template.html~3a';
LOI[46] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Luk~1~73~images/bible_images/Moses/moses_template.html~3a';
LOI[47] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Luk~1~27~images/bible_images/Moses/moses_template.html~5';
LOI[48] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Luk~1~27~images/bible_images/Kings/kings_template.html~1';
LOI[49] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Luk~1~32~images/bible_images/Kings/kings_template.html~1';
LOI[50] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Luk~1~69~images/bible_images/Kings/kings_template.html~1';
LOI[51] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Luk~1~27~images/bible_images/Kings/kings_template.html~2';
LOI[52] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Luk~1~32~images/bible_images/Kings/kings_template.html~2';
LOI[53] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Luk~1~69~images/bible_images/Kings/kings_template.html~2';
LOI[54] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Luk~1~9~images/bible_images/Temple/temple_template.html~1';
LOI[55] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Luk~1~21~images/bible_images/Temple/temple_template.html~1';
LOI[56] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Luk~1~22~images/bible_images/Temple/temple_template.html~1';
LOI[57] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Luk~1~9~images/bible_images/Temple/temple_template.html~2';
LOI[58] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Luk~1~21~images/bible_images/Temple/temple_template.html~2';
LOI[59] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Luk~1~22~images/bible_images/Temple/temple_template.html~2';
