var LOI = [];
LOI[0] = 'hymn~10~SEEKING THE LOST~htm_s_e_seeklost.html';
LOI[1] = 'hymn~10~SWEET STORY OF JESUS~htm_s_w_sweetstj.html';
LOI[2] = 'hymn~40~GLORY BE TO GOD ON HIGH~htm_g_l_gloryb2g.html';
LOI[3] = 'hymn~40~WHEN, HIS SALVATION BRINGING~htm_w_h_i_whisalva.html';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~19~11~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~19~28~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Luk~19~45~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Luk~19~47~images/maps/Otest/otest_template.html~3a';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~19~11~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~19~28~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Luk~19~45~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Luk~19~47~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~19~11~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~19~28~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~Luk~19~1~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Luk~19~9~images/places/Israel/israel_template.html~8';
LOI[16] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Luk~19~1~images/places/Israel/israel_template.html~9';
LOI[17] = 'image~Bible~Places~Bethany (engraving) key=Bethany~~~~Luk~19~29~images/places/Israel/israel_template.html~10';
LOI[18] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~19~11~images/places/Israel/israel_template.html~11';
LOI[19] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~19~28~images/places/Israel/israel_template.html~11';
LOI[20] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~19~11~images/places/Israel/israel_template.html~12';
LOI[21] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~19~28~images/places/Israel/israel_template.html~12';
LOI[22] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~19~11~images/places/Israel/israel_template.html~13';
LOI[23] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~19~28~images/places/Israel/israel_template.html~13';
LOI[24] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~19~11~images/places/Israel/israel_template.html~14';
LOI[25] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~19~28~images/places/Israel/israel_template.html~14';
LOI[26] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~19~11~images/places/Israel/israel_template.html~17';
LOI[27] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~19~28~images/places/Israel/israel_template.html~17';
LOI[28] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Luk~19~9~images/bible_images/Moses/moses_template.html~3';
LOI[29] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Luk~19~9~images/bible_images/Moses/moses_template.html~3i';
LOI[30] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Luk~19~9~images/bible_images/Moses/moses_template.html~3a';
LOI[31] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Luk~19~45~images/bible_images/Temple/temple_template.html~1';
LOI[32] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Luk~19~47~images/bible_images/Temple/temple_template.html~1';
LOI[33] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Luk~19~45~images/bible_images/Temple/temple_template.html~2';
LOI[34] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Luk~19~47~images/bible_images/Temple/temple_template.html~2';
