var LOI = [];
LOI[0] = 'hymn~5~HALLELUJAH! JESUS LIVES!~htm_h_j_hjelives.html';
LOI[1] = 'hymn~6~BEAUTIFUL MORNING~htm_b_e_a_beaumorn.html';
LOI[2] = 'hymn~29~ABIDE WITH ME~htm_a_b_abidewme.html';
LOI[3] = 'hymn~29~ABIDE WITH ME, &#8217;TIS EVENTIDE~htm_a_b_abidewmt.html';
LOI[4] = 'hymn~29~ABIDE WITH US, OUR SAVIOR~htm_a_w_awuosavr.html';
LOI[5] = 'hymn~29~ABIDE WITH US, THE DAY IS WANING~htm_a_b_abidewus.html';
LOI[6] = 'hymn~29~AS NOW THE SUN&#8217;S DECLINING RAYS~htm_a_n_anowtsun.html';
LOI[7] = 'hymn~29~DAY, O LORD, IS SPENT, THE~htm_d_o_dolispen.html';
LOI[8] = 'hymn~29~DAY IS GENTLY SINKING TO A CLOSE, THE~htm_d_a_dayisgen.html';
LOI[9] = 'hymn~29~SINCE WITHOUT YOU WE DO NO GOOD~htm_s_i_sincewit.html';
LOI[10] = 'hymn~29~TARRY WITH ME~htm_t_a_tarrywme.html';
LOI[11] = 'hymn~32~WALK THOU WITH ME~htm_w_a_walkthou.html';
LOI[12] = 'hymn~34~MORNING KINDLES ALL THE SKY, THE~htm_m_o_mornkind.html';
LOI[13] = 'hymn~34~O JOYOUS EASTER MORNING~htm_o_j_ojoyemor.html';
LOI[14] = 'hymn~39~THAT EASTERTIDE WITH JOY WAS BRIGHT~htm_t_e_teastert.html';
LOI[15] = 'hymn~50~FATHER ALMIGHTY, BLESS US WITH THY BLESSING~htm_f_a_fablessu.html';
LOI[16] = 'hymn~50~SWEET SAVIOR, BLESS US ERE WE GO~htm_s_w_sweetsbu.html';
LOI[17] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Luk~24~21~images/maps/Otest/otest_template.html~1b';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Luk~24~21~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~24~13~images/maps/Otest/otest_template.html~3a';
LOI[20] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~24~18~images/maps/Otest/otest_template.html~3a';
LOI[21] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~24~33~images/maps/Otest/otest_template.html~3a';
LOI[22] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~24~47~images/maps/Otest/otest_template.html~3a';
LOI[23] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~24~49~images/maps/Otest/otest_template.html~3a';
LOI[24] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Luk~24~52~images/maps/Otest/otest_template.html~3a';
LOI[25] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Luk~24~53~images/maps/Otest/otest_template.html~3a';
LOI[26] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~24~13~images/maps/Otest/otest_template.html~3b';
LOI[27] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~24~18~images/maps/Otest/otest_template.html~3b';
LOI[28] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~24~33~images/maps/Otest/otest_template.html~3b';
LOI[29] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~24~47~images/maps/Otest/otest_template.html~3b';
LOI[30] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~24~49~images/maps/Otest/otest_template.html~3b';
LOI[31] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Luk~24~52~images/maps/Otest/otest_template.html~3b';
LOI[32] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Luk~24~53~images/maps/Otest/otest_template.html~3b';
LOI[33] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Luk~24~21~images/maps/Otest/otest_template.html~3c';
LOI[34] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Luk~24~6~images/maps/Otest/otest_template.html~3c';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Luk~24~21~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~24~13~images/maps/Otest/otest_template.html~4';
LOI[37] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~24~18~images/maps/Otest/otest_template.html~4';
LOI[38] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~24~33~images/maps/Otest/otest_template.html~4';
LOI[39] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~24~47~images/maps/Otest/otest_template.html~4';
LOI[40] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~24~49~images/maps/Otest/otest_template.html~4';
LOI[41] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Luk~24~52~images/maps/Otest/otest_template.html~4';
LOI[42] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Luk~24~21~images/maps/Christ/christ_template.html~1';
LOI[43] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Luk~24~6~images/maps/Christ/christ_template.html~1';
LOI[44] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~1~images/places/Israel/israel_template.html~5';
LOI[45] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~2~images/places/Israel/israel_template.html~5';
LOI[46] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~3~images/places/Israel/israel_template.html~5';
LOI[47] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~4~images/places/Israel/israel_template.html~5';
LOI[48] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~5~images/places/Israel/israel_template.html~5';
LOI[49] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~6~images/places/Israel/israel_template.html~5';
LOI[50] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~7~images/places/Israel/israel_template.html~5';
LOI[51] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~8~images/places/Israel/israel_template.html~5';
LOI[52] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~9~images/places/Israel/israel_template.html~5';
LOI[53] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~10~images/places/Israel/israel_template.html~5';
LOI[54] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~11~images/places/Israel/israel_template.html~5';
LOI[55] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~12~images/places/Israel/israel_template.html~5';
LOI[56] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~13~images/places/Israel/israel_template.html~5';
LOI[57] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~14~images/places/Israel/israel_template.html~5';
LOI[58] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~15~images/places/Israel/israel_template.html~5';
LOI[59] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~16~images/places/Israel/israel_template.html~5';
LOI[60] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~17~images/places/Israel/israel_template.html~5';
LOI[61] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~18~images/places/Israel/israel_template.html~5';
LOI[62] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~19~images/places/Israel/israel_template.html~5';
LOI[63] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~20~images/places/Israel/israel_template.html~5';
LOI[64] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~21~images/places/Israel/israel_template.html~5';
LOI[65] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~22~images/places/Israel/israel_template.html~5';
LOI[66] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~23~images/places/Israel/israel_template.html~5';
LOI[67] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~24~images/places/Israel/israel_template.html~5';
LOI[68] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~25~images/places/Israel/israel_template.html~5';
LOI[69] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~26~images/places/Israel/israel_template.html~5';
LOI[70] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~27~images/places/Israel/israel_template.html~5';
LOI[71] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~28~images/places/Israel/israel_template.html~5';
LOI[72] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~29~images/places/Israel/israel_template.html~5';
LOI[73] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~30~images/places/Israel/israel_template.html~5';
LOI[74] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~31~images/places/Israel/israel_template.html~5';
LOI[75] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~32~images/places/Israel/israel_template.html~5';
LOI[76] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~33~images/places/Israel/israel_template.html~5';
LOI[77] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~34~images/places/Israel/israel_template.html~5';
LOI[78] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~35~images/places/Israel/israel_template.html~5';
LOI[79] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~36~images/places/Israel/israel_template.html~5';
LOI[80] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~37~images/places/Israel/israel_template.html~5';
LOI[81] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~38~images/places/Israel/israel_template.html~5';
LOI[82] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~39~images/places/Israel/israel_template.html~5';
LOI[83] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~40~images/places/Israel/israel_template.html~5';
LOI[84] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~41~images/places/Israel/israel_template.html~5';
LOI[85] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~42~images/places/Israel/israel_template.html~5';
LOI[86] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~43~images/places/Israel/israel_template.html~5';
LOI[87] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~44~images/places/Israel/israel_template.html~5';
LOI[88] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~45~images/places/Israel/israel_template.html~5';
LOI[89] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~46~images/places/Israel/israel_template.html~5';
LOI[90] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~47~images/places/Israel/israel_template.html~5';
LOI[91] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~48~images/places/Israel/israel_template.html~5';
LOI[92] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~49~images/places/Israel/israel_template.html~5';
LOI[93] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~50~images/places/Israel/israel_template.html~5';
LOI[94] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~51~images/places/Israel/israel_template.html~5';
LOI[95] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~52~images/places/Israel/israel_template.html~5';
LOI[96] = 'image~Bible~Places~The Empty Tomb  (photo)~~~~Luk~24~53~images/places/Israel/israel_template.html~5';
LOI[97] = 'image~Bible~Places~Bethany (engraving) key=Bethany~~~~Luk~24~50~images/places/Israel/israel_template.html~10';
LOI[98] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~24~13~images/places/Israel/israel_template.html~11';
LOI[99] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~24~18~images/places/Israel/israel_template.html~11';
LOI[100] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~24~33~images/places/Israel/israel_template.html~11';
LOI[101] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~24~47~images/places/Israel/israel_template.html~11';
LOI[102] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~24~49~images/places/Israel/israel_template.html~11';
LOI[103] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Luk~24~52~images/places/Israel/israel_template.html~11';
LOI[104] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~24~13~images/places/Israel/israel_template.html~12';
LOI[105] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~24~18~images/places/Israel/israel_template.html~12';
LOI[106] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~24~33~images/places/Israel/israel_template.html~12';
LOI[107] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~24~47~images/places/Israel/israel_template.html~12';
LOI[108] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~24~49~images/places/Israel/israel_template.html~12';
LOI[109] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Luk~24~52~images/places/Israel/israel_template.html~12';
LOI[110] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~24~13~images/places/Israel/israel_template.html~13';
LOI[111] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~24~18~images/places/Israel/israel_template.html~13';
LOI[112] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~24~33~images/places/Israel/israel_template.html~13';
LOI[113] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~24~47~images/places/Israel/israel_template.html~13';
LOI[114] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~24~49~images/places/Israel/israel_template.html~13';
LOI[115] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Luk~24~52~images/places/Israel/israel_template.html~13';
LOI[116] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~24~13~images/places/Israel/israel_template.html~14';
LOI[117] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~24~18~images/places/Israel/israel_template.html~14';
LOI[118] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~24~33~images/places/Israel/israel_template.html~14';
LOI[119] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~24~47~images/places/Israel/israel_template.html~14';
LOI[120] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~24~49~images/places/Israel/israel_template.html~14';
LOI[121] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Luk~24~52~images/places/Israel/israel_template.html~14';
LOI[122] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~24~13~images/places/Israel/israel_template.html~17';
LOI[123] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~24~18~images/places/Israel/israel_template.html~17';
LOI[124] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~24~33~images/places/Israel/israel_template.html~17';
LOI[125] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~24~47~images/places/Israel/israel_template.html~17';
LOI[126] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~24~49~images/places/Israel/israel_template.html~17';
LOI[127] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Luk~24~52~images/places/Israel/israel_template.html~17';
LOI[128] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Luk~24~27~images/bible_images/Moses/moses_template.html~6';
LOI[129] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Luk~24~44~images/bible_images/Moses/moses_template.html~6';
LOI[130] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Luk~24~27~images/bible_images/Moses/moses_template.html~7';
LOI[131] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Luk~24~44~images/bible_images/Moses/moses_template.html~7';
LOI[132] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Luk~24~27~images/bible_images/Moses/moses_template.html~9';
LOI[133] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Luk~24~44~images/bible_images/Moses/moses_template.html~9';
LOI[134] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Luk~24~27~images/bible_images/Moses/moses_template.html~10';
LOI[135] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Luk~24~44~images/bible_images/Moses/moses_template.html~10';
LOI[136] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Luk~24~27~images/bible_images/Moses/moses_template.html~11';
LOI[137] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Luk~24~44~images/bible_images/Moses/moses_template.html~11';
LOI[138] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Luk~24~53~images/bible_images/Temple/temple_template.html~1';
LOI[139] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Luk~24~53~images/bible_images/Temple/temple_template.html~2';
