var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~9~3~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~9~6~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~9~8~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~9~12~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~9~14~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Ki~9~21~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ki~9~16~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ki~9~27~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ki~9~29~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~9~3~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~9~6~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~9~8~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~9~12~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~9~14~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Ki~9~21~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ki~9~16~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ki~9~27~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ki~9~29~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ki~9~28~images/maps/Otest/otest_template.html~3a';
LOI[19] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ki~9~28~images/maps/Otest/otest_template.html~3b';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~9~3~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~9~6~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~9~8~images/maps/Otest/otest_template.html~3c';
LOI[23] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~9~12~images/maps/Otest/otest_template.html~3c';
LOI[24] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~9~14~images/maps/Otest/otest_template.html~3c';
LOI[25] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~9~21~images/maps/Otest/otest_template.html~3c';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~9~3~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~9~6~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~9~8~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~9~12~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~9~14~images/maps/Otest/otest_template.html~4';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~9~21~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ki~9~28~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~9~3~images/maps/Christ/christ_template.html~1';
LOI[34] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~9~6~images/maps/Christ/christ_template.html~1';
LOI[35] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~9~8~images/maps/Christ/christ_template.html~1';
LOI[36] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~9~12~images/maps/Christ/christ_template.html~1';
LOI[37] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~9~14~images/maps/Christ/christ_template.html~1';
LOI[38] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~9~21~images/maps/Christ/christ_template.html~1';
LOI[39] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~2Ki~9~14~images/maps/Journeys/journeys_template.html~2';
LOI[40] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~2Ki~9~15~images/maps/Journeys/journeys_template.html~2';
LOI[41] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ki~9~28~images/places/Israel/israel_template.html~11';
LOI[42] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ki~9~28~images/places/Israel/israel_template.html~12';
LOI[43] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ki~9~28~images/places/Israel/israel_template.html~13';
LOI[44] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ki~9~28~images/places/Israel/israel_template.html~14';
LOI[45] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ki~9~28~images/places/Israel/israel_template.html~17';
LOI[46] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Ki~9~28~images/bible_images/Kings/kings_template.html~1';
LOI[47] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Ki~9~28~images/bible_images/Kings/kings_template.html~2';
LOI[48] = 'image~Bible~Images~Rehoboam and Jeroboam (engraving) key=Jeroboam~~~~2Ki~9~9~images/bible_images/Kings/kings_template.html~5';
LOI[49] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~2Ki~9~36~images/bible_images/Kings/kings_template.html~5';
