var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~2Ki~25~23~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~2Ki~25~25~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ki~25~21~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ki~25~22~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ki~25~27~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ki~25~21~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ki~25~22~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ki~25~27~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ki~25~1~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ki~25~8~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ki~25~9~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Ki~25~10~images/maps/Otest/otest_template.html~3a';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ki~25~1~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ki~25~8~images/maps/Otest/otest_template.html~3b';
LOI[14] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ki~25~9~images/maps/Otest/otest_template.html~3b';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Ki~25~10~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ki~25~1~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ki~25~8~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ki~25~9~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Ki~25~10~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~2Ki~25~5~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~2Ki~25~26~images/maps/Otest/otest_template.html~5';
LOI[22] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~2Ki~25~5~images/places/Israel/israel_template.html~9';
LOI[23] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ki~25~1~images/places/Israel/israel_template.html~11';
LOI[24] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ki~25~8~images/places/Israel/israel_template.html~11';
LOI[25] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ki~25~9~images/places/Israel/israel_template.html~11';
LOI[26] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Ki~25~10~images/places/Israel/israel_template.html~11';
LOI[27] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ki~25~1~images/places/Israel/israel_template.html~12';
LOI[28] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ki~25~8~images/places/Israel/israel_template.html~12';
LOI[29] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ki~25~9~images/places/Israel/israel_template.html~12';
LOI[30] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Ki~25~10~images/places/Israel/israel_template.html~12';
LOI[31] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ki~25~1~images/places/Israel/israel_template.html~13';
LOI[32] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ki~25~8~images/places/Israel/israel_template.html~13';
LOI[33] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ki~25~9~images/places/Israel/israel_template.html~13';
LOI[34] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Ki~25~10~images/places/Israel/israel_template.html~13';
LOI[35] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ki~25~1~images/places/Israel/israel_template.html~14';
LOI[36] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ki~25~8~images/places/Israel/israel_template.html~14';
LOI[37] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ki~25~9~images/places/Israel/israel_template.html~14';
LOI[38] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Ki~25~10~images/places/Israel/israel_template.html~14';
LOI[39] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ki~25~1~images/places/Israel/israel_template.html~17';
LOI[40] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ki~25~8~images/places/Israel/israel_template.html~17';
LOI[41] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ki~25~9~images/places/Israel/israel_template.html~17';
LOI[42] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Ki~25~10~images/places/Israel/israel_template.html~17';
LOI[43] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~2Ki~25~16~images/bible_images/Kings/kings_template.html~3';
LOI[44] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~2Ki~25~16~images/bible_images/Kings/kings_template.html~4';
LOI[45] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~2Ki~25~1~images/bible_images/Kings/kings_template.html~7';
LOI[46] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~2Ki~25~6~images/bible_images/Kings/kings_template.html~7';
LOI[47] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~2Ki~25~7~images/bible_images/Kings/kings_template.html~7';
LOI[48] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~2Ki~25~8~images/bible_images/Kings/kings_template.html~7';
LOI[49] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~2Ki~25~11~images/bible_images/Kings/kings_template.html~7';
LOI[50] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~2Ki~25~13~images/bible_images/Kings/kings_template.html~7';
LOI[51] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~2Ki~25~20~images/bible_images/Kings/kings_template.html~7';
LOI[52] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~2Ki~25~21~images/bible_images/Kings/kings_template.html~7';
LOI[53] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~2Ki~25~22~images/bible_images/Kings/kings_template.html~7';
LOI[54] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~2Ki~25~23~images/bible_images/Kings/kings_template.html~7';
LOI[55] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~2Ki~25~24~images/bible_images/Kings/kings_template.html~7';
LOI[56] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~2Ki~25~27~images/bible_images/Kings/kings_template.html~7';
LOI[57] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~2Ki~25~28~images/bible_images/Kings/kings_template.html~7';
LOI[58] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~1';
LOI[59] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~2';
LOI[60] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~3';
LOI[61] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~4';
LOI[62] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~5';
LOI[63] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~6';
LOI[64] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~7';
LOI[65] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~8';
LOI[66] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~9';
LOI[67] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~10';
LOI[68] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~11';
LOI[69] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~12';
LOI[70] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~13';
LOI[71] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~14';
LOI[72] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~2Ki~25~16~images/bible_images/Song/song_template.html~15';
LOI[73] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~2Ki~25~1~images/bible_images/Daniel/daniel_template.html~1';
LOI[74] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~2Ki~25~8~images/bible_images/Daniel/daniel_template.html~1';
LOI[75] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~2Ki~25~22~images/bible_images/Daniel/daniel_template.html~1';
LOI[76] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Nebuchadnezzar~~~~2Ki~25~1~images/bible_images/Daniel/daniel_template.html~3';
LOI[77] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Nebuchadnezzar~~~~2Ki~25~8~images/bible_images/Daniel/daniel_template.html~3';
LOI[78] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Nebuchadnezzar~~~~2Ki~25~22~images/bible_images/Daniel/daniel_template.html~3';
