var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Ki~13~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~13~2~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~13~3~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~13~4~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~13~5~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~13~6~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~13~8~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Ki~13~10~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~13~11~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Ki~13~12~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~13~13~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~13~14~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~13~16~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~13~18~images/maps/Otest/otest_template.html~1b';
LOI[14] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~13~22~images/maps/Otest/otest_template.html~1b';
LOI[15] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~13~25~images/maps/Otest/otest_template.html~1b';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Ki~13~1~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~13~2~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~13~3~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~13~4~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~13~5~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~13~6~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~13~8~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Ki~13~10~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~13~11~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Ki~13~12~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~13~13~images/maps/Otest/otest_template.html~1c';
LOI[27] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~13~14~images/maps/Otest/otest_template.html~1c';
LOI[28] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~13~16~images/maps/Otest/otest_template.html~1c';
LOI[29] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~13~18~images/maps/Otest/otest_template.html~1c';
LOI[30] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~13~22~images/maps/Otest/otest_template.html~1c';
LOI[31] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~13~25~images/maps/Otest/otest_template.html~1c';
LOI[32] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~1~images/maps/Otest/otest_template.html~3c';
LOI[33] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~2~images/maps/Otest/otest_template.html~3c';
LOI[34] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~3~images/maps/Otest/otest_template.html~3c';
LOI[35] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~4~images/maps/Otest/otest_template.html~3c';
LOI[36] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~5~images/maps/Otest/otest_template.html~3c';
LOI[37] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~6~images/maps/Otest/otest_template.html~3c';
LOI[38] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~8~images/maps/Otest/otest_template.html~3c';
LOI[39] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~10~images/maps/Otest/otest_template.html~3c';
LOI[40] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~11~images/maps/Otest/otest_template.html~3c';
LOI[41] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~12~images/maps/Otest/otest_template.html~3c';
LOI[42] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~13~images/maps/Otest/otest_template.html~3c';
LOI[43] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~14~images/maps/Otest/otest_template.html~3c';
LOI[44] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~16~images/maps/Otest/otest_template.html~3c';
LOI[45] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~18~images/maps/Otest/otest_template.html~3c';
LOI[46] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~22~images/maps/Otest/otest_template.html~3c';
LOI[47] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~13~25~images/maps/Otest/otest_template.html~3c';
LOI[48] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~1~images/maps/Otest/otest_template.html~4';
LOI[49] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~2~images/maps/Otest/otest_template.html~4';
LOI[50] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~3~images/maps/Otest/otest_template.html~4';
LOI[51] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~4~images/maps/Otest/otest_template.html~4';
LOI[52] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~5~images/maps/Otest/otest_template.html~4';
LOI[53] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~6~images/maps/Otest/otest_template.html~4';
LOI[54] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~8~images/maps/Otest/otest_template.html~4';
LOI[55] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~10~images/maps/Otest/otest_template.html~4';
LOI[56] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~11~images/maps/Otest/otest_template.html~4';
LOI[57] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~12~images/maps/Otest/otest_template.html~4';
LOI[58] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~13~images/maps/Otest/otest_template.html~4';
LOI[59] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~14~images/maps/Otest/otest_template.html~4';
LOI[60] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~16~images/maps/Otest/otest_template.html~4';
LOI[61] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~18~images/maps/Otest/otest_template.html~4';
LOI[62] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~22~images/maps/Otest/otest_template.html~4';
LOI[63] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~13~25~images/maps/Otest/otest_template.html~4';
LOI[64] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel,Samaria~~~~2Ki~13~1~images/maps/Christ/christ_template.html~1';
LOI[65] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~13~2~images/maps/Christ/christ_template.html~1';
LOI[66] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~13~3~images/maps/Christ/christ_template.html~1';
LOI[67] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~13~4~images/maps/Christ/christ_template.html~1';
LOI[68] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~13~5~images/maps/Christ/christ_template.html~1';
LOI[69] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel,Samaria~~~~2Ki~13~6~images/maps/Christ/christ_template.html~1';
LOI[70] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~13~8~images/maps/Christ/christ_template.html~1';
LOI[71] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel,Samaria~~~~2Ki~13~10~images/maps/Christ/christ_template.html~1';
LOI[72] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~13~11~images/maps/Christ/christ_template.html~1';
LOI[73] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~13~12~images/maps/Christ/christ_template.html~1';
LOI[74] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel,Samaria~~~~2Ki~13~13~images/maps/Christ/christ_template.html~1';
LOI[75] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~13~14~images/maps/Christ/christ_template.html~1';
LOI[76] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~13~16~images/maps/Christ/christ_template.html~1';
LOI[77] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~13~18~images/maps/Christ/christ_template.html~1';
LOI[78] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~13~22~images/maps/Christ/christ_template.html~1';
LOI[79] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~13~25~images/maps/Christ/christ_template.html~1';
LOI[80] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~2Ki~13~9~images/maps/Christ/christ_template.html~1';
LOI[81] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~2Ki~13~3~images/maps/Journeys/journeys_template.html~2';
LOI[82] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~2Ki~13~4~images/maps/Journeys/journeys_template.html~2';
LOI[83] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~2Ki~13~7~images/maps/Journeys/journeys_template.html~2';
LOI[84] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~2Ki~13~17~images/maps/Journeys/journeys_template.html~2';
LOI[85] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~2Ki~13~19~images/maps/Journeys/journeys_template.html~2';
LOI[86] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~2Ki~13~22~images/maps/Journeys/journeys_template.html~2';
LOI[87] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~2Ki~13~24~images/maps/Journeys/journeys_template.html~2';
LOI[88] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~2Ki~13~23~images/places/Israel/israel_template.html~8';
LOI[89] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~2Ki~13~23~images/bible_images/Moses/moses_template.html~3';
LOI[90] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~2Ki~13~23~images/bible_images/Moses/moses_template.html~3i';
LOI[91] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~2Ki~13~23~images/bible_images/Moses/moses_template.html~3a';
LOI[92] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~2Ki~13~23~images/bible_images/Moses/moses_template.html~4';
LOI[93] = 'image~Bible~Images~Rehoboam and Jeroboam (engraving) key=Jeroboam~~~~2Ki~13~2~images/bible_images/Kings/kings_template.html~5';
LOI[94] = 'image~Bible~Images~Rehoboam and Jeroboam (engraving) key=Jeroboam~~~~2Ki~13~6~images/bible_images/Kings/kings_template.html~5';
LOI[95] = 'image~Bible~Images~Rehoboam and Jeroboam (engraving) key=Jeroboam~~~~2Ki~13~11~images/bible_images/Kings/kings_template.html~5';
LOI[96] = 'image~Bible~Images~Rehoboam and Jeroboam (engraving) key=Jeroboam~~~~2Ki~13~13~images/bible_images/Kings/kings_template.html~5';
