var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Ki~3~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~3~3~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~3~4~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~3~5~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~3~6~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Ki~3~9~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~3~10~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~3~12~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~3~13~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~3~24~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~3~27~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ki~3~7~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Ki~3~14~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Ki~3~1~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~3~3~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~3~4~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~3~5~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~3~6~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Ki~3~9~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~3~10~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~3~12~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~3~13~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~3~24~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~3~27~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ki~3~7~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Ki~3~14~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~3~1~images/maps/Otest/otest_template.html~3c';
LOI[27] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~3~3~images/maps/Otest/otest_template.html~3c';
LOI[28] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~3~4~images/maps/Otest/otest_template.html~3c';
LOI[29] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~3~5~images/maps/Otest/otest_template.html~3c';
LOI[30] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~3~6~images/maps/Otest/otest_template.html~3c';
LOI[31] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~3~9~images/maps/Otest/otest_template.html~3c';
LOI[32] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~3~10~images/maps/Otest/otest_template.html~3c';
LOI[33] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~3~12~images/maps/Otest/otest_template.html~3c';
LOI[34] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~3~13~images/maps/Otest/otest_template.html~3c';
LOI[35] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~3~24~images/maps/Otest/otest_template.html~3c';
LOI[36] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~3~27~images/maps/Otest/otest_template.html~3c';
LOI[37] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~3~1~images/maps/Otest/otest_template.html~4';
LOI[38] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~3~3~images/maps/Otest/otest_template.html~4';
LOI[39] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Moab~~~~2Ki~3~4~images/maps/Otest/otest_template.html~4';
LOI[40] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Moab~~~~2Ki~3~5~images/maps/Otest/otest_template.html~4';
LOI[41] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~3~6~images/maps/Otest/otest_template.html~4';
LOI[42] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~3~9~images/maps/Otest/otest_template.html~4';
LOI[43] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Moab~~~~2Ki~3~10~images/maps/Otest/otest_template.html~4';
LOI[44] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~3~12~images/maps/Otest/otest_template.html~4';
LOI[45] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Moab~~~~2Ki~3~13~images/maps/Otest/otest_template.html~4';
LOI[46] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~3~24~images/maps/Otest/otest_template.html~4';
LOI[47] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~3~27~images/maps/Otest/otest_template.html~4';
LOI[48] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~2Ki~3~7~images/maps/Otest/otest_template.html~4';
LOI[49] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~2Ki~3~23~images/maps/Otest/otest_template.html~4';
LOI[50] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~2Ki~3~26~images/maps/Otest/otest_template.html~4';
LOI[51] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel,Samaria~~~~2Ki~3~1~images/maps/Christ/christ_template.html~1';
LOI[52] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~3~3~images/maps/Christ/christ_template.html~1';
LOI[53] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~3~4~images/maps/Christ/christ_template.html~1';
LOI[54] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~3~5~images/maps/Christ/christ_template.html~1';
LOI[55] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel,Samaria~~~~2Ki~3~6~images/maps/Christ/christ_template.html~1';
LOI[56] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~3~9~images/maps/Christ/christ_template.html~1';
LOI[57] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~3~10~images/maps/Christ/christ_template.html~1';
LOI[58] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~3~12~images/maps/Christ/christ_template.html~1';
LOI[59] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~3~13~images/maps/Christ/christ_template.html~1';
LOI[60] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~3~24~images/maps/Christ/christ_template.html~1';
LOI[61] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~3~27~images/maps/Christ/christ_template.html~1';
LOI[62] = 'image~Bible~Images~Rehoboam and Jeroboam (engraving) key=Jeroboam~~~~2Ki~3~3~images/bible_images/Kings/kings_template.html~5';
LOI[63] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~2Ki~3~11~images/bible_images/Kings/kings_template.html~5';
