var LOI = [];
LOI[0] = 'hymn~9~GOD OF THE PROPHETS, BLESS THE PROPHETS&#8217; SONS~htm_g_o_godproph.html';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~2~12~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~2~12~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~2~12~images/maps/Otest/otest_template.html~3c';
LOI[4] = 'image~Bible~Maps~Middle Palestine (map) key=Carmel~~~~2Ki~2~25~images/maps/Otest/otest_template.html~3c';
LOI[5] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~2Ki~2~6~images/maps/Otest/otest_template.html~3c';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~2Ki~2~7~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~2Ki~2~13~images/maps/Otest/otest_template.html~3c';
LOI[8] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~2~12~images/maps/Otest/otest_template.html~4';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~2Ki~2~4~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~2Ki~2~5~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~2Ki~2~15~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~2Ki~2~18~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~2~12~images/maps/Christ/christ_template.html~1';
LOI[14] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~2Ki~2~25~images/maps/Christ/christ_template.html~1';
LOI[15] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~2Ki~2~4~images/places/Israel/israel_template.html~9';
LOI[16] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~2Ki~2~5~images/places/Israel/israel_template.html~9';
LOI[17] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~2Ki~2~15~images/places/Israel/israel_template.html~9';
LOI[18] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~2Ki~2~18~images/places/Israel/israel_template.html~9';
LOI[19] = 'image~Bible~Places~Elisha\'s Fountain (engraving)~~~~2Ki~2~19~images/places/Israel/israel_template.html~18';
LOI[20] = 'image~Bible~Places~Elisha\'s Fountain (engraving)~~~~2Ki~2~20~images/places/Israel/israel_template.html~18';
LOI[21] = 'image~Bible~Places~Elisha\'s Fountain (engraving)~~~~2Ki~2~21~images/places/Israel/israel_template.html~18';
LOI[22] = 'image~Bible~Places~Elisha\'s Fountain (engraving)~~~~2Ki~2~22~images/places/Israel/israel_template.html~18';
LOI[23] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~2Ki~2~1~images/bible_images/Kings/kings_template.html~5';
LOI[24] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~2Ki~2~2~images/bible_images/Kings/kings_template.html~5';
LOI[25] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~2Ki~2~4~images/bible_images/Kings/kings_template.html~5';
LOI[26] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~2Ki~2~6~images/bible_images/Kings/kings_template.html~5';
LOI[27] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~2Ki~2~8~images/bible_images/Kings/kings_template.html~5';
LOI[28] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~2Ki~2~9~images/bible_images/Kings/kings_template.html~5';
LOI[29] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~2Ki~2~11~images/bible_images/Kings/kings_template.html~5';
LOI[30] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~2Ki~2~13~images/bible_images/Kings/kings_template.html~5';
LOI[31] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~2Ki~2~14~images/bible_images/Kings/kings_template.html~5';
LOI[32] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~2Ki~2~15~images/bible_images/Kings/kings_template.html~5';
