var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~5~2~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~5~4~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~5~5~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~5~6~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~5~7~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~5~8~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~5~12~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Ki~5~15~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~2Ki~5~22~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~5~2~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~5~4~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~5~5~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~5~6~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~5~7~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~5~8~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~5~12~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Ki~5~15~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~2Ki~5~22~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~5~2~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~5~4~images/maps/Otest/otest_template.html~3c';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~5~5~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~5~6~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~5~7~images/maps/Otest/otest_template.html~3c';
LOI[23] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~5~8~images/maps/Otest/otest_template.html~3c';
LOI[24] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~5~12~images/maps/Otest/otest_template.html~3c';
LOI[25] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Ki~5~15~images/maps/Otest/otest_template.html~3c';
LOI[26] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~2Ki~5~10~images/maps/Otest/otest_template.html~3c';
LOI[27] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~2Ki~5~14~images/maps/Otest/otest_template.html~3c';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~5~2~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~5~4~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~5~5~images/maps/Otest/otest_template.html~4';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~5~6~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~5~7~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~5~8~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~5~12~images/maps/Otest/otest_template.html~4';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Ki~5~15~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~5~2~images/maps/Christ/christ_template.html~1';
LOI[37] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~5~4~images/maps/Christ/christ_template.html~1';
LOI[38] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~5~5~images/maps/Christ/christ_template.html~1';
LOI[39] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~5~6~images/maps/Christ/christ_template.html~1';
LOI[40] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~5~7~images/maps/Christ/christ_template.html~1';
LOI[41] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~5~8~images/maps/Christ/christ_template.html~1';
LOI[42] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~5~12~images/maps/Christ/christ_template.html~1';
LOI[43] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Ki~5~15~images/maps/Christ/christ_template.html~1';
LOI[44] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~2Ki~5~3~images/maps/Christ/christ_template.html~1';
LOI[45] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~2Ki~5~1~images/maps/Journeys/journeys_template.html~2';
LOI[46] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~2Ki~5~5~images/maps/Journeys/journeys_template.html~2';
