var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~26~46~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~26~46~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~26~46~images/maps/Otest/otest_template.html~3c';
LOI[3] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~26~46~images/maps/Otest/otest_template.html~4';
LOI[4] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Lev~26~13~images/maps/Otest/otest_template.html~5';
LOI[5] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Lev~26~45~images/maps/Otest/otest_template.html~5';
LOI[6] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Sinai~~~~Lev~26~46~images/maps/Otest/otest_template.html~5';
LOI[7] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~26~46~images/maps/Christ/christ_template.html~1';
LOI[8] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Lev~26~42~images/places/Israel/israel_template.html~8';
LOI[9] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Lev~26~42~images/bible_images/Moses/moses_template.html~3';
LOI[10] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Lev~26~42~images/bible_images/Moses/moses_template.html~3i';
LOI[11] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~Lev~26~42~images/bible_images/Moses/moses_template.html~3a';
LOI[12] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Lev~26~42~images/bible_images/Moses/moses_template.html~4';
LOI[13] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~26~46~images/bible_images/Moses/moses_template.html~6';
LOI[14] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~26~46~images/bible_images/Moses/moses_template.html~7';
LOI[15] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~26~46~images/bible_images/Moses/moses_template.html~9';
LOI[16] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~26~46~images/bible_images/Moses/moses_template.html~10';
LOI[17] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~26~46~images/bible_images/Moses/moses_template.html~11';
LOI[18] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Lev~26~11~images/bible_images/Temple/temple_template.html~2';
LOI[19] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Lev~26~11~images/bible_images/Temple/temple_template.html~3';
