var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~12~2~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~12~2~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~12~2~images/maps/Otest/otest_template.html~3c';
LOI[3] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~12~2~images/maps/Otest/otest_template.html~4';
LOI[4] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~12~2~images/maps/Christ/christ_template.html~1';
LOI[5] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~12~1~images/bible_images/Moses/moses_template.html~6';
LOI[6] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~12~1~images/bible_images/Moses/moses_template.html~7';
LOI[7] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~12~1~images/bible_images/Moses/moses_template.html~9';
LOI[8] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~12~1~images/bible_images/Moses/moses_template.html~10';
LOI[9] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~12~1~images/bible_images/Moses/moses_template.html~11';
LOI[10] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Lev~12~6~images/bible_images/Temple/temple_template.html~2';
LOI[11] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Lev~12~6~images/bible_images/Temple/temple_template.html~3';
