var LOI = [];
LOI[0] = 'hymn~2~TAKE TIME TO BE HOLY~htm_t_a_taketime.html';
LOI[1] = 'hymn~18~A BEAUTIFUL LIFE~htm_b_e_beautlif.html';
LOI[2] = 'hymn~18~IS THERE A HEART BENT O&#8217;ER WITH SORROW?~htm_i_s_istherah.html';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~19~2~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~19~2~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~19~2~images/maps/Otest/otest_template.html~3c';
LOI[6] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~19~2~images/maps/Otest/otest_template.html~4';
LOI[7] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Lev~19~34~images/maps/Otest/otest_template.html~5';
LOI[8] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Lev~19~36~images/maps/Otest/otest_template.html~5';
LOI[9] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~19~2~images/maps/Christ/christ_template.html~1';
LOI[10] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~19~1~images/bible_images/Moses/moses_template.html~6';
LOI[11] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~19~1~images/bible_images/Moses/moses_template.html~7';
LOI[12] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~19~1~images/bible_images/Moses/moses_template.html~9';
LOI[13] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~19~1~images/bible_images/Moses/moses_template.html~10';
LOI[14] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~19~1~images/bible_images/Moses/moses_template.html~11';
LOI[15] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Lev~19~21~images/bible_images/Temple/temple_template.html~2';
LOI[16] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Lev~19~21~images/bible_images/Temple/temple_template.html~3';
