var LOI = [];
LOI[0] = 'hymn~9~BLOW YE THE TRUMPET, BLOW~htm_b_l_blowblow.html';
LOI[1] = 'hymn~10~AWAKE! AWAKE!~htm_a_w_awakawak.html';
LOI[2] = 'hymn~10~OUR LAND FOR CHRIST~htm_o_u_ourland4c.html';
LOI[3] = 'hymn~10~SOMEONE MUST TELL THE GLAD STORY~htm_s_o_someonem.html';
LOI[4] = 'hymn~10~WAKE THE SONG OF JUBILEE~htm_w_a_wakesonj.html';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~25~2~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~25~33~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~25~46~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~25~55~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~25~2~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~25~33~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~25~46~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~25~55~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~25~2~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~25~33~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~25~46~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~25~55~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~25~2~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~25~33~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~25~46~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~25~55~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Lev~25~38~images/maps/Otest/otest_template.html~5';
LOI[22] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Lev~25~42~images/maps/Otest/otest_template.html~5';
LOI[23] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Lev~25~55~images/maps/Otest/otest_template.html~5';
LOI[24] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Sinai~~~~Lev~25~1~images/maps/Otest/otest_template.html~5';
LOI[25] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~25~2~images/maps/Christ/christ_template.html~1';
LOI[26] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~25~33~images/maps/Christ/christ_template.html~1';
LOI[27] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~25~46~images/maps/Christ/christ_template.html~1';
LOI[28] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~25~55~images/maps/Christ/christ_template.html~1';
LOI[29] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~25~1~images/bible_images/Moses/moses_template.html~6';
LOI[30] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~25~1~images/bible_images/Moses/moses_template.html~7';
LOI[31] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~25~1~images/bible_images/Moses/moses_template.html~9';
LOI[32] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~25~1~images/bible_images/Moses/moses_template.html~10';
LOI[33] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~25~1~images/bible_images/Moses/moses_template.html~11';
