var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~24~2~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~24~8~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~24~10~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~24~15~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~24~23~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Dan~~~~Lev~24~11~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~24~2~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~24~8~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~24~10~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~24~15~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~24~23~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Dan~~~~Lev~24~11~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~24~2~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~24~8~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~24~10~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~24~15~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~24~23~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~24~2~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~24~8~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~24~10~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~24~15~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~24~23~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~24~2~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~24~8~images/maps/Christ/christ_template.html~1';
LOI[24] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~24~10~images/maps/Christ/christ_template.html~1';
LOI[25] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~24~15~images/maps/Christ/christ_template.html~1';
LOI[26] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~24~23~images/maps/Christ/christ_template.html~1';
LOI[27] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~24~1~images/bible_images/Moses/moses_template.html~6';
LOI[28] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~24~11~images/bible_images/Moses/moses_template.html~6';
LOI[29] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~24~13~images/bible_images/Moses/moses_template.html~6';
LOI[30] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~24~23~images/bible_images/Moses/moses_template.html~6';
LOI[31] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~24~1~images/bible_images/Moses/moses_template.html~7';
LOI[32] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~24~11~images/bible_images/Moses/moses_template.html~7';
LOI[33] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~24~13~images/bible_images/Moses/moses_template.html~7';
LOI[34] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~24~23~images/bible_images/Moses/moses_template.html~7';
LOI[35] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~24~1~images/bible_images/Moses/moses_template.html~9';
LOI[36] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~24~11~images/bible_images/Moses/moses_template.html~9';
LOI[37] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~24~13~images/bible_images/Moses/moses_template.html~9';
LOI[38] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~24~23~images/bible_images/Moses/moses_template.html~9';
LOI[39] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~24~1~images/bible_images/Moses/moses_template.html~10';
LOI[40] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~24~11~images/bible_images/Moses/moses_template.html~10';
LOI[41] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~24~13~images/bible_images/Moses/moses_template.html~10';
LOI[42] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~24~23~images/bible_images/Moses/moses_template.html~10';
LOI[43] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~24~1~images/bible_images/Moses/moses_template.html~11';
LOI[44] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~24~11~images/bible_images/Moses/moses_template.html~11';
LOI[45] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~24~13~images/bible_images/Moses/moses_template.html~11';
LOI[46] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~24~23~images/bible_images/Moses/moses_template.html~11';
LOI[47] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Lev~24~3~images/bible_images/Temple/temple_template.html~2';
LOI[48] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Lev~24~3~images/bible_images/Temple/temple_template.html~3';
