var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~22~2~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~22~3~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~22~15~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~22~18~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Lev~22~32~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~22~2~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~22~3~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~22~15~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~22~18~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Lev~22~32~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~22~2~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~22~3~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~22~15~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~22~18~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Lev~22~32~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~22~2~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~22~3~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~22~15~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~22~18~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Lev~22~32~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Lev~22~33~images/maps/Otest/otest_template.html~5';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~22~2~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~22~3~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~22~15~images/maps/Christ/christ_template.html~1';
LOI[24] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~22~18~images/maps/Christ/christ_template.html~1';
LOI[25] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Lev~22~32~images/maps/Christ/christ_template.html~1';
LOI[26] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~22~1~images/bible_images/Moses/moses_template.html~6';
LOI[27] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~22~17~images/bible_images/Moses/moses_template.html~6';
LOI[28] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~22~26~images/bible_images/Moses/moses_template.html~6';
LOI[29] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~22~1~images/bible_images/Moses/moses_template.html~7';
LOI[30] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~22~17~images/bible_images/Moses/moses_template.html~7';
LOI[31] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~22~26~images/bible_images/Moses/moses_template.html~7';
LOI[32] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~22~1~images/bible_images/Moses/moses_template.html~9';
LOI[33] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~22~17~images/bible_images/Moses/moses_template.html~9';
LOI[34] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~22~26~images/bible_images/Moses/moses_template.html~9';
LOI[35] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~22~1~images/bible_images/Moses/moses_template.html~10';
LOI[36] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~22~17~images/bible_images/Moses/moses_template.html~10';
LOI[37] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~22~26~images/bible_images/Moses/moses_template.html~10';
LOI[38] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~22~1~images/bible_images/Moses/moses_template.html~11';
LOI[39] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~22~17~images/bible_images/Moses/moses_template.html~11';
LOI[40] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~22~26~images/bible_images/Moses/moses_template.html~11';
