var LOI = [];
LOI[0] = 'hymn~13~O THOU WHO CAMEST FROM ABOVE~htm_t_w_twhocame.html';
LOI[1] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~6~1~images/bible_images/Moses/moses_template.html~6';
LOI[2] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~6~8~images/bible_images/Moses/moses_template.html~6';
LOI[3] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~6~19~images/bible_images/Moses/moses_template.html~6';
LOI[4] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Lev~6~24~images/bible_images/Moses/moses_template.html~6';
LOI[5] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~6~1~images/bible_images/Moses/moses_template.html~7';
LOI[6] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~6~8~images/bible_images/Moses/moses_template.html~7';
LOI[7] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~6~19~images/bible_images/Moses/moses_template.html~7';
LOI[8] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Lev~6~24~images/bible_images/Moses/moses_template.html~7';
LOI[9] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~6~1~images/bible_images/Moses/moses_template.html~9';
LOI[10] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~6~8~images/bible_images/Moses/moses_template.html~9';
LOI[11] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~6~19~images/bible_images/Moses/moses_template.html~9';
LOI[12] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Lev~6~24~images/bible_images/Moses/moses_template.html~9';
LOI[13] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~6~1~images/bible_images/Moses/moses_template.html~10';
LOI[14] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~6~8~images/bible_images/Moses/moses_template.html~10';
LOI[15] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~6~19~images/bible_images/Moses/moses_template.html~10';
LOI[16] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Lev~6~24~images/bible_images/Moses/moses_template.html~10';
LOI[17] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~6~1~images/bible_images/Moses/moses_template.html~11';
LOI[18] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~6~8~images/bible_images/Moses/moses_template.html~11';
LOI[19] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~6~19~images/bible_images/Moses/moses_template.html~11';
LOI[20] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Lev~6~24~images/bible_images/Moses/moses_template.html~11';
LOI[21] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Lev~6~16~images/bible_images/Temple/temple_template.html~2';
LOI[22] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Lev~6~26~images/bible_images/Temple/temple_template.html~2';
LOI[23] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Lev~6~30~images/bible_images/Temple/temple_template.html~2';
LOI[24] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Lev~6~16~images/bible_images/Temple/temple_template.html~3';
LOI[25] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Lev~6~26~images/bible_images/Temple/temple_template.html~3';
LOI[26] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Lev~6~30~images/bible_images/Temple/temple_template.html~3';
