var LOI = [];
LOI[0] = 'hymn~11~DEAR LORD AND FATHER OF MANKIND~htm_d_e_dearlord.html';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ki~19~10~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ki~19~14~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ki~19~16~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ki~19~18~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~1Ki~19~3~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ki~19~10~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ki~19~14~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ki~19~16~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ki~19~18~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~1Ki~19~3~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ki~19~10~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ki~19~14~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ki~19~16~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ki~19~18~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ki~19~10~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ki~19~14~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ki~19~16~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ki~19~18~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Horeb~~~~1Ki~19~8~images/maps/Otest/otest_template.html~5';
LOI[20] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ki~19~10~images/maps/Christ/christ_template.html~1';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ki~19~14~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ki~19~16~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ki~19~18~images/maps/Christ/christ_template.html~1';
LOI[24] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~1Ki~19~15~images/maps/Journeys/journeys_template.html~2';
LOI[25] = 'image~Bible~Places~Beer-Sheeba (engraving) key=Beersheba~~~~1Ki~19~3~images/places/Israel/israel_template.html~7';
LOI[26] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~1Ki~19~1~images/bible_images/Kings/kings_template.html~5';
LOI[27] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~1Ki~19~2~images/bible_images/Kings/kings_template.html~5';
LOI[28] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~1Ki~19~9~images/bible_images/Kings/kings_template.html~5';
LOI[29] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~1Ki~19~13~images/bible_images/Kings/kings_template.html~5';
LOI[30] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~1Ki~19~19~images/bible_images/Kings/kings_template.html~5';
LOI[31] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~1Ki~19~20~images/bible_images/Kings/kings_template.html~5';
LOI[32] = 'image~Bible~Images~Elijah Raiseth the Widow\'s Son (engraving) key=Elijah~~~~1Ki~19~21~images/bible_images/Kings/kings_template.html~5';
