var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ophir~~~~1Ki~10~11~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Sheba~~~~1Ki~10~1~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Sheba~~~~1Ki~10~4~images/maps/Otest/otest_template.html~1a';
LOI[3] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Sheba~~~~1Ki~10~10~images/maps/Otest/otest_template.html~1a';
LOI[4] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Sheba~~~~1Ki~10~13~images/maps/Otest/otest_template.html~1a';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ki~10~9~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ki~10~9~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~1Ki~10~2~images/maps/Otest/otest_template.html~3a';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~1Ki~10~26~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~1Ki~10~27~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~1Ki~10~2~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~1Ki~10~26~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~1Ki~10~27~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ki~10~9~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Hiram~~~~1Ki~10~11~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Hiram~~~~1Ki~10~22~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ki~10~9~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~1Ki~10~2~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~1Ki~10~26~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~1Ki~10~27~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~1Ki~10~28~images/maps/Otest/otest_template.html~5';
LOI[21] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~1Ki~10~29~images/maps/Otest/otest_template.html~5';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ki~10~9~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~1Ki~10~29~images/maps/Journeys/journeys_template.html~2';
LOI[24] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~1Ki~10~2~images/places/Israel/israel_template.html~11';
LOI[25] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~1Ki~10~26~images/places/Israel/israel_template.html~11';
LOI[26] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~1Ki~10~27~images/places/Israel/israel_template.html~11';
LOI[27] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~1Ki~10~2~images/places/Israel/israel_template.html~12';
LOI[28] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~1Ki~10~26~images/places/Israel/israel_template.html~12';
LOI[29] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~1Ki~10~27~images/places/Israel/israel_template.html~12';
LOI[30] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~1Ki~10~2~images/places/Israel/israel_template.html~13';
LOI[31] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~1Ki~10~26~images/places/Israel/israel_template.html~13';
LOI[32] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~1Ki~10~27~images/places/Israel/israel_template.html~13';
LOI[33] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~1Ki~10~2~images/places/Israel/israel_template.html~14';
LOI[34] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~1Ki~10~26~images/places/Israel/israel_template.html~14';
LOI[35] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~1Ki~10~27~images/places/Israel/israel_template.html~14';
LOI[36] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~1Ki~10~2~images/places/Israel/israel_template.html~17';
LOI[37] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~1Ki~10~26~images/places/Israel/israel_template.html~17';
LOI[38] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~1Ki~10~27~images/places/Israel/israel_template.html~17';
LOI[39] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~1Ki~10~1~images/bible_images/Kings/kings_template.html~3';
LOI[40] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~1Ki~10~2~images/bible_images/Kings/kings_template.html~3';
LOI[41] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~1Ki~10~3~images/bible_images/Kings/kings_template.html~3';
LOI[42] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~1Ki~10~10~images/bible_images/Kings/kings_template.html~3';
LOI[43] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~1Ki~10~13~images/bible_images/Kings/kings_template.html~3';
LOI[44] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~1Ki~10~14~images/bible_images/Kings/kings_template.html~3';
LOI[45] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~1Ki~10~16~images/bible_images/Kings/kings_template.html~3';
LOI[46] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~1Ki~10~21~images/bible_images/Kings/kings_template.html~3';
LOI[47] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~1Ki~10~23~images/bible_images/Kings/kings_template.html~3';
LOI[48] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~1Ki~10~24~images/bible_images/Kings/kings_template.html~3';
LOI[49] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~1Ki~10~26~images/bible_images/Kings/kings_template.html~3';
LOI[50] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~1Ki~10~28~images/bible_images/Kings/kings_template.html~3';
LOI[51] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving)~~~~1Ki~10~1~images/bible_images/Kings/kings_template.html~4';
LOI[52] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving)~~~~1Ki~10~2~images/bible_images/Kings/kings_template.html~4';
LOI[53] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving)~~~~1Ki~10~3~images/bible_images/Kings/kings_template.html~4';
LOI[54] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving)~~~~1Ki~10~4~images/bible_images/Kings/kings_template.html~4';
LOI[55] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving)~~~~1Ki~10~5~images/bible_images/Kings/kings_template.html~4';
LOI[56] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving)~~~~1Ki~10~6~images/bible_images/Kings/kings_template.html~4';
LOI[57] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving)~~~~1Ki~10~7~images/bible_images/Kings/kings_template.html~4';
LOI[58] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving)~~~~1Ki~10~8~images/bible_images/Kings/kings_template.html~4';
LOI[59] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving)~~~~1Ki~10~9~images/bible_images/Kings/kings_template.html~4';
LOI[60] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving)~~~~1Ki~10~10~images/bible_images/Kings/kings_template.html~4';
LOI[61] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving)~~~~1Ki~10~11~images/bible_images/Kings/kings_template.html~4';
LOI[62] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving)~~~~1Ki~10~12~images/bible_images/Kings/kings_template.html~4';
LOI[63] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving)~~~~1Ki~10~13~images/bible_images/Kings/kings_template.html~4';
LOI[64] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving)~~~~1Ki~10~14~images/bible_images/Kings/kings_template.html~4';
LOI[65] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~1Ki~10~16~images/bible_images/Kings/kings_template.html~4';
LOI[66] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~1Ki~10~21~images/bible_images/Kings/kings_template.html~4';
LOI[67] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~1Ki~10~23~images/bible_images/Kings/kings_template.html~4';
LOI[68] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~1Ki~10~24~images/bible_images/Kings/kings_template.html~4';
LOI[69] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~1Ki~10~26~images/bible_images/Kings/kings_template.html~4';
LOI[70] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~1Ki~10~28~images/bible_images/Kings/kings_template.html~4';
LOI[71] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~1';
LOI[72] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~1';
LOI[73] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~1';
LOI[74] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~1';
LOI[75] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~1';
LOI[76] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~1';
LOI[77] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~1';
LOI[78] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~1';
LOI[79] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~1';
LOI[80] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~1';
LOI[81] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~1';
LOI[82] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~1';
LOI[83] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~2';
LOI[84] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~2';
LOI[85] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~2';
LOI[86] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~2';
LOI[87] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~2';
LOI[88] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~2';
LOI[89] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~2';
LOI[90] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~2';
LOI[91] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~2';
LOI[92] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~2';
LOI[93] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~2';
LOI[94] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~2';
LOI[95] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~3';
LOI[96] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~3';
LOI[97] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~3';
LOI[98] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~3';
LOI[99] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~3';
LOI[100] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~3';
LOI[101] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~3';
LOI[102] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~3';
LOI[103] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~3';
LOI[104] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~3';
LOI[105] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~3';
LOI[106] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~3';
LOI[107] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~4';
LOI[108] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~4';
LOI[109] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~4';
LOI[110] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~4';
LOI[111] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~4';
LOI[112] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~4';
LOI[113] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~4';
LOI[114] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~4';
LOI[115] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~4';
LOI[116] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~4';
LOI[117] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~4';
LOI[118] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~4';
LOI[119] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~5';
LOI[120] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~5';
LOI[121] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~5';
LOI[122] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~5';
LOI[123] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~5';
LOI[124] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~5';
LOI[125] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~5';
LOI[126] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~5';
LOI[127] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~5';
LOI[128] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~5';
LOI[129] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~5';
LOI[130] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~5';
LOI[131] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~6';
LOI[132] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~6';
LOI[133] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~6';
LOI[134] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~6';
LOI[135] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~6';
LOI[136] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~6';
LOI[137] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~6';
LOI[138] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~6';
LOI[139] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~6';
LOI[140] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~6';
LOI[141] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~6';
LOI[142] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~6';
LOI[143] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~7';
LOI[144] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~7';
LOI[145] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~7';
LOI[146] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~7';
LOI[147] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~7';
LOI[148] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~7';
LOI[149] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~7';
LOI[150] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~7';
LOI[151] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~7';
LOI[152] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~7';
LOI[153] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~7';
LOI[154] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~7';
LOI[155] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~8';
LOI[156] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~8';
LOI[157] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~8';
LOI[158] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~8';
LOI[159] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~8';
LOI[160] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~8';
LOI[161] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~8';
LOI[162] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~8';
LOI[163] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~8';
LOI[164] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~8';
LOI[165] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~8';
LOI[166] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~8';
LOI[167] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~9';
LOI[168] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~9';
LOI[169] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~9';
LOI[170] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~9';
LOI[171] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~9';
LOI[172] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~9';
LOI[173] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~9';
LOI[174] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~9';
LOI[175] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~9';
LOI[176] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~9';
LOI[177] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~9';
LOI[178] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~9';
LOI[179] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~10';
LOI[180] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~10';
LOI[181] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~10';
LOI[182] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~10';
LOI[183] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~10';
LOI[184] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~10';
LOI[185] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~10';
LOI[186] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~10';
LOI[187] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~10';
LOI[188] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~10';
LOI[189] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~10';
LOI[190] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~10';
LOI[191] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~11';
LOI[192] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~11';
LOI[193] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~11';
LOI[194] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~11';
LOI[195] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~11';
LOI[196] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~11';
LOI[197] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~11';
LOI[198] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~11';
LOI[199] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~11';
LOI[200] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~11';
LOI[201] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~11';
LOI[202] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~11';
LOI[203] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~12';
LOI[204] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~12';
LOI[205] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~12';
LOI[206] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~12';
LOI[207] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~12';
LOI[208] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~12';
LOI[209] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~12';
LOI[210] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~12';
LOI[211] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~12';
LOI[212] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~12';
LOI[213] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~12';
LOI[214] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~12';
LOI[215] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~13';
LOI[216] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~13';
LOI[217] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~13';
LOI[218] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~13';
LOI[219] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~13';
LOI[220] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~13';
LOI[221] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~13';
LOI[222] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~13';
LOI[223] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~13';
LOI[224] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~13';
LOI[225] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~13';
LOI[226] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~13';
LOI[227] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~14';
LOI[228] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~14';
LOI[229] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~14';
LOI[230] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~14';
LOI[231] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~14';
LOI[232] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~14';
LOI[233] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~14';
LOI[234] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~14';
LOI[235] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~14';
LOI[236] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~14';
LOI[237] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~14';
LOI[238] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~14';
LOI[239] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~1Ki~10~1~images/bible_images/Song/song_template.html~15';
LOI[240] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~1Ki~10~2~images/bible_images/Song/song_template.html~15';
LOI[241] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~1Ki~10~3~images/bible_images/Song/song_template.html~15';
LOI[242] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~1Ki~10~10~images/bible_images/Song/song_template.html~15';
LOI[243] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~1Ki~10~13~images/bible_images/Song/song_template.html~15';
LOI[244] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~1Ki~10~14~images/bible_images/Song/song_template.html~15';
LOI[245] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~1Ki~10~16~images/bible_images/Song/song_template.html~15';
LOI[246] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~1Ki~10~21~images/bible_images/Song/song_template.html~15';
LOI[247] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~1Ki~10~23~images/bible_images/Song/song_template.html~15';
LOI[248] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~1Ki~10~24~images/bible_images/Song/song_template.html~15';
LOI[249] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~1Ki~10~26~images/bible_images/Song/song_template.html~15';
LOI[250] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~1Ki~10~28~images/bible_images/Song/song_template.html~15';
