var LOI = [];
LOI[0] = 'hymn~11~WOULD JESUS HAVE THE SINNER DIE?~htm_w_o_wojehave.html';
LOI[1] = 'hymn~11~YEA, AS I LIVE, JEHOVAH SAITH~htm_y_e_yeasiliv.html';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~33~7~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~33~10~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~33~11~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~33~20~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~33~24~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~33~28~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~33~7~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~33~10~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~33~11~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~33~20~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~33~24~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~33~28~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Eze~33~21~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Eze~33~21~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~33~7~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~33~10~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~33~11~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~33~20~images/maps/Otest/otest_template.html~3c';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~33~24~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~33~28~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~33~7~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~33~10~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~33~11~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~33~20~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~33~24~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~33~28~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Eze~33~21~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~33~7~images/maps/Christ/christ_template.html~1';
LOI[30] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~33~10~images/maps/Christ/christ_template.html~1';
LOI[31] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~33~11~images/maps/Christ/christ_template.html~1';
LOI[32] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~33~20~images/maps/Christ/christ_template.html~1';
LOI[33] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~33~24~images/maps/Christ/christ_template.html~1';
LOI[34] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~33~28~images/maps/Christ/christ_template.html~1';
LOI[35] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Eze~33~24~images/places/Israel/israel_template.html~8';
LOI[36] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Eze~33~21~images/places/Israel/israel_template.html~11';
LOI[37] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Eze~33~21~images/places/Israel/israel_template.html~12';
LOI[38] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Eze~33~21~images/places/Israel/israel_template.html~13';
LOI[39] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Eze~33~21~images/places/Israel/israel_template.html~14';
LOI[40] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Eze~33~21~images/places/Israel/israel_template.html~17';
LOI[41] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Eze~33~24~images/bible_images/Moses/moses_template.html~3';
LOI[42] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Eze~33~24~images/bible_images/Moses/moses_template.html~3i';
LOI[43] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Eze~33~24~images/bible_images/Moses/moses_template.html~3a';
