var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~45~6~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~45~8~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~45~9~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~45~15~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~45~16~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~45~17~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~45~6~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~45~8~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~45~9~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~45~15~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~45~16~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~45~17~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~45~6~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~45~8~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~45~9~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~45~15~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~45~16~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~45~17~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~45~6~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~45~8~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~45~9~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~45~15~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~45~16~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~45~17~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~45~6~images/maps/Christ/christ_template.html~1';
LOI[25] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~45~8~images/maps/Christ/christ_template.html~1';
LOI[26] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~45~9~images/maps/Christ/christ_template.html~1';
LOI[27] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~45~15~images/maps/Christ/christ_template.html~1';
LOI[28] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~45~16~images/maps/Christ/christ_template.html~1';
LOI[29] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~45~17~images/maps/Christ/christ_template.html~1';
LOI[30] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Eze~45~1~images/bible_images/Moses/moses_template.html~3i';
