var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ethiopia~~~~Eze~30~4~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ethiopia~~~~Eze~30~5~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~30~4~images/maps/Otest/otest_template.html~5';
LOI[3] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~30~6~images/maps/Otest/otest_template.html~5';
LOI[4] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~30~8~images/maps/Otest/otest_template.html~5';
LOI[5] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~30~9~images/maps/Otest/otest_template.html~5';
LOI[6] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~30~10~images/maps/Otest/otest_template.html~5';
LOI[7] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~30~11~images/maps/Otest/otest_template.html~5';
LOI[8] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~30~13~images/maps/Otest/otest_template.html~5';
LOI[9] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~30~15~images/maps/Otest/otest_template.html~5';
LOI[10] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~30~16~images/maps/Otest/otest_template.html~5';
LOI[11] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~30~18~images/maps/Otest/otest_template.html~5';
LOI[12] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~30~19~images/maps/Otest/otest_template.html~5';
LOI[13] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~30~21~images/maps/Otest/otest_template.html~5';
LOI[14] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~30~22~images/maps/Otest/otest_template.html~5';
LOI[15] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~30~25~images/maps/Otest/otest_template.html~5';
LOI[16] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Eze~30~21~images/bible_images/Moses/moses_template.html~5';
LOI[17] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Eze~30~22~images/bible_images/Moses/moses_template.html~5';
LOI[18] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Eze~30~25~images/bible_images/Moses/moses_template.html~5';
LOI[19] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Eze~30~10~images/bible_images/Kings/kings_template.html~7';
LOI[20] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Eze~30~24~images/bible_images/Kings/kings_template.html~7';
LOI[21] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Eze~30~25~images/bible_images/Kings/kings_template.html~7';
