var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~48~11~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~48~19~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eze~48~29~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Eze~48~31~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Reuben,Ephraim~~~~Eze~48~6~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Reuben,Judah~~~~Eze~48~7~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Simeon,Benjamin~~~~Eze~48~24~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Simeon,Issachar~~~~Eze~48~25~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Eze~48~33~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Eze~48~8~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah,Benjamin~~~~Eze~48~22~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Zebulun,Issachar~~~~Eze~48~26~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Zebulun,Gad~~~~Eze~48~27~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Dan~~~~Eze~48~1~images/maps/Otest/otest_template.html~1b';
LOI[14] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Dan,Asher~~~~Eze~48~2~images/maps/Otest/otest_template.html~1b';
LOI[15] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Eze~48~32~images/maps/Otest/otest_template.html~1b';
LOI[16] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Gad~~~~Eze~48~28~images/maps/Otest/otest_template.html~1b';
LOI[17] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Eze~48~34~images/maps/Otest/otest_template.html~1b';
LOI[18] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Asher,Naphtali~~~~Eze~48~3~images/maps/Otest/otest_template.html~1b';
LOI[19] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Naphtali,Manasseh~~~~Eze~48~4~images/maps/Otest/otest_template.html~1b';
LOI[20] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim,Manasseh~~~~Eze~48~5~images/maps/Otest/otest_template.html~1b';
LOI[21] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~Eze~48~23~images/maps/Otest/otest_template.html~1b';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~48~11~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~48~19~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eze~48~29~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Eze~48~31~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Reuben,Ephraim~~~~Eze~48~6~images/maps/Otest/otest_template.html~1c';
LOI[27] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Reuben,Judah~~~~Eze~48~7~images/maps/Otest/otest_template.html~1c';
LOI[28] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Simeon,Benjamin~~~~Eze~48~24~images/maps/Otest/otest_template.html~1c';
LOI[29] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Simeon,Issachar~~~~Eze~48~25~images/maps/Otest/otest_template.html~1c';
LOI[30] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Eze~48~33~images/maps/Otest/otest_template.html~1c';
LOI[31] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Eze~48~8~images/maps/Otest/otest_template.html~1c';
LOI[32] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah,Benjamin~~~~Eze~48~22~images/maps/Otest/otest_template.html~1c';
LOI[33] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Zebulun,Issachar~~~~Eze~48~26~images/maps/Otest/otest_template.html~1c';
LOI[34] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Zebulun,Gad~~~~Eze~48~27~images/maps/Otest/otest_template.html~1c';
LOI[35] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Dan~~~~Eze~48~1~images/maps/Otest/otest_template.html~1c';
LOI[36] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Dan,Asher~~~~Eze~48~2~images/maps/Otest/otest_template.html~1c';
LOI[37] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Eze~48~32~images/maps/Otest/otest_template.html~1c';
LOI[38] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Gad~~~~Eze~48~28~images/maps/Otest/otest_template.html~1c';
LOI[39] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Eze~48~34~images/maps/Otest/otest_template.html~1c';
LOI[40] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Asher,Naphtali~~~~Eze~48~3~images/maps/Otest/otest_template.html~1c';
LOI[41] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Naphtali,Manasseh~~~~Eze~48~4~images/maps/Otest/otest_template.html~1c';
LOI[42] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim,Manasseh~~~~Eze~48~5~images/maps/Otest/otest_template.html~1c';
LOI[43] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~Eze~48~23~images/maps/Otest/otest_template.html~1c';
LOI[44] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~48~11~images/maps/Otest/otest_template.html~3c';
LOI[45] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~48~19~images/maps/Otest/otest_template.html~3c';
LOI[46] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~48~29~images/maps/Otest/otest_template.html~3c';
LOI[47] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eze~48~31~images/maps/Otest/otest_template.html~3c';
LOI[48] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~48~11~images/maps/Otest/otest_template.html~4';
LOI[49] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~48~19~images/maps/Otest/otest_template.html~4';
LOI[50] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~48~29~images/maps/Otest/otest_template.html~4';
LOI[51] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eze~48~31~images/maps/Otest/otest_template.html~4';
LOI[52] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~48~11~images/maps/Christ/christ_template.html~1';
LOI[53] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~48~19~images/maps/Christ/christ_template.html~1';
LOI[54] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~48~29~images/maps/Christ/christ_template.html~1';
LOI[55] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eze~48~31~images/maps/Christ/christ_template.html~1';
LOI[56] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Eze~48~29~images/bible_images/Moses/moses_template.html~3i';
LOI[57] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Eze~48~32~images/bible_images/Moses/moses_template.html~5';
