var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Elam~~~~Eze~32~24~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~32~2~images/maps/Otest/otest_template.html~5';
LOI[2] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~32~12~images/maps/Otest/otest_template.html~5';
LOI[3] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~32~15~images/maps/Otest/otest_template.html~5';
LOI[4] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~32~16~images/maps/Otest/otest_template.html~5';
LOI[5] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Eze~32~18~images/maps/Otest/otest_template.html~5';
LOI[6] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Eze~32~2~images/bible_images/Moses/moses_template.html~5';
LOI[7] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Eze~32~31~images/bible_images/Moses/moses_template.html~5';
LOI[8] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Eze~32~32~images/bible_images/Moses/moses_template.html~5';
LOI[9] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Eze~32~11~images/bible_images/Kings/kings_template.html~7';
