var LOI = [];
LOI[0] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Eze~41~1~images/maps/Otest/otest_template.html~3a';
LOI[1] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Eze~41~4~images/maps/Otest/otest_template.html~3a';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Eze~41~15~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Eze~41~20~images/maps/Otest/otest_template.html~3a';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Eze~41~21~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Eze~41~23~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Eze~41~25~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Eze~41~1~images/maps/Otest/otest_template.html~3b';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Eze~41~4~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Eze~41~15~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Eze~41~20~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Eze~41~21~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Eze~41~23~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Eze~41~25~images/maps/Otest/otest_template.html~3b';
LOI[14] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Eze~41~1~images/bible_images/Temple/temple_template.html~1';
LOI[15] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Eze~41~4~images/bible_images/Temple/temple_template.html~1';
LOI[16] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Eze~41~15~images/bible_images/Temple/temple_template.html~1';
LOI[17] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Eze~41~20~images/bible_images/Temple/temple_template.html~1';
LOI[18] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Eze~41~21~images/bible_images/Temple/temple_template.html~1';
LOI[19] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Eze~41~23~images/bible_images/Temple/temple_template.html~1';
LOI[20] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Eze~41~25~images/bible_images/Temple/temple_template.html~1';
LOI[21] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle,temple~~~~Eze~41~1~images/bible_images/Temple/temple_template.html~2';
LOI[22] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Eze~41~4~images/bible_images/Temple/temple_template.html~2';
LOI[23] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Eze~41~15~images/bible_images/Temple/temple_template.html~2';
LOI[24] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Eze~41~20~images/bible_images/Temple/temple_template.html~2';
LOI[25] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Eze~41~21~images/bible_images/Temple/temple_template.html~2';
LOI[26] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Eze~41~23~images/bible_images/Temple/temple_template.html~2';
LOI[27] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Eze~41~25~images/bible_images/Temple/temple_template.html~2';
LOI[28] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Eze~41~1~images/bible_images/Temple/temple_template.html~3';
