var LOI = [];
LOI[0] = 'hymn~13~ONCE MORE THE SOLEMN SEASON CALLS~htm_o_m_omsscall.html';
LOI[1] = 'hymn~28~HOLY GHOST, WITH LIGHT DIVINE~htm_h_g_hgwlight.html';
LOI[2] = 'hymn~28~JOY! BECAUSE THE CIRCLING YEAR~htm_j_o_joybeccy.html';
LOI[3] = 'hymn~28~WINTER REIGNS O&#8217;ER MANY A REGION~htm_w_i_winreign.html';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Joe~2~27~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Joe~2~27~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Zion~~~~Joe~2~32~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Joe~2~1~images/maps/Otest/otest_template.html~3a';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Joe~2~15~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Joe~2~23~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Zion~~~~Joe~2~32~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Joe~2~1~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Joe~2~15~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Joe~2~23~images/maps/Otest/otest_template.html~3b';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Joe~2~27~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Joe~2~27~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Joe~2~32~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Joe~2~27~images/maps/Christ/christ_template.html~1';
LOI[18] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Joe~2~32~images/places/Israel/israel_template.html~11';
LOI[19] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Joe~2~32~images/places/Israel/israel_template.html~12';
LOI[20] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Joe~2~32~images/places/Israel/israel_template.html~13';
LOI[21] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Joe~2~32~images/places/Israel/israel_template.html~14';
LOI[22] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Joe~2~32~images/places/Israel/israel_template.html~17';
