var LOI = [];
LOI[0] = 'hymn~4~TO GOD BE THE GLORY~htm_t_o_togodbe.html';
LOI[1] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Gal~1~17~images/maps/Otest/otest_template.html~3a';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Gal~1~18~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Gal~1~17~images/maps/Otest/otest_template.html~3b';
LOI[4] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Gal~1~18~images/maps/Otest/otest_template.html~3b';
LOI[5] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Gal~1~17~images/maps/Otest/otest_template.html~4';
LOI[6] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Gal~1~18~images/maps/Otest/otest_template.html~4';
LOI[7] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Gal~1~1~images/maps/Journeys/journeys_template.html~1';
LOI[8] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Gal~1~1~images/maps/Journeys/journeys_template.html~2';
LOI[9] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria,Cilicia~~~~Gal~1~21~images/maps/Journeys/journeys_template.html~2';
LOI[10] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Galatia~~~~Gal~1~2~images/maps/Journeys/journeys_template.html~2';
LOI[11] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Gal~1~1~images/maps/Journeys/journeys_template.html~3';
LOI[12] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Galatia~~~~Gal~1~2~images/maps/Journeys/journeys_template.html~3';
LOI[13] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Gal~1~17~images/places/Israel/israel_template.html~11';
LOI[14] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Gal~1~18~images/places/Israel/israel_template.html~11';
LOI[15] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Gal~1~17~images/places/Israel/israel_template.html~12';
LOI[16] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Gal~1~18~images/places/Israel/israel_template.html~12';
LOI[17] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Gal~1~17~images/places/Israel/israel_template.html~13';
LOI[18] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Gal~1~18~images/places/Israel/israel_template.html~13';
LOI[19] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Gal~1~17~images/places/Israel/israel_template.html~14';
LOI[20] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Gal~1~18~images/places/Israel/israel_template.html~14';
LOI[21] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Gal~1~17~images/places/Israel/israel_template.html~17';
LOI[22] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Gal~1~18~images/places/Israel/israel_template.html~17';
LOI[23] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Gal~1~1~images/bible_images/Acts/acts_template.html~2';
