var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Est~2~6~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Est~2~6~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Est~2~6~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Est~2~6~images/maps/Otest/otest_template.html~3b';
LOI[4] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Est~2~6~images/maps/Otest/otest_template.html~4';
LOI[5] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Est~2~6~images/places/Israel/israel_template.html~11';
LOI[6] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Est~2~6~images/places/Israel/israel_template.html~12';
LOI[7] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Est~2~6~images/places/Israel/israel_template.html~13';
LOI[8] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Est~2~6~images/places/Israel/israel_template.html~14';
LOI[9] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Est~2~6~images/places/Israel/israel_template.html~17';
LOI[10] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Est~2~6~images/bible_images/Kings/kings_template.html~7';
LOI[11] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~Est~2~6~images/bible_images/Daniel/daniel_template.html~1';
LOI[12] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Nebuchadnezzar~~~~Est~2~6~images/bible_images/Daniel/daniel_template.html~3';
