var LOI = [];
LOI[0] = 'hymn~3~MASTER, NO OFFERING COSTLY AND SWEET~htm_m_n_mnofcasw.html';
LOI[1] = 'hymn~12~HOSANNA, LOUD HOSANNA~htm_h_l_hlhosann.html';
LOI[2] = 'hymn~21~A PRAYER FOR GOD&#8217;S BLESSING~htm_p_r_prayerfg.html';
LOI[3] = 'hymn~21~WE WOULD SEE JESUS (1)~htm_w_o_wouldsee.html';
LOI[4] = 'hymn~21~WE WOULD SEE JESUS (2)~htm_w_e_w_wewouldc.html';
LOI[5] = 'hymn~26~CHRIST WILL GATHER IN HIS OWN~htm_c_w_cwgather.html';
LOI[6] = 'hymn~26~HE WHO WOULD VALIANT BE~htm_h_w_hwhowvbe.html';
LOI[7] = 'hymn~26~HOW BLESSED, FROM THE BONDS OF SIN~htm_h_b_hblessed.html';
LOI[8] = 'hymn~26~IT PAYS TO SERVE JESUS~htm_i_t_itpays2s.html';
LOI[9] = 'hymn~26~THERE WILL I FOLLOW THEE~htm_t_h_therewil.html';
LOI[10] = 'hymn~32~DRAW THOU MY SOUL, O CHRIST~htm_d_r_drawthou.html';
LOI[11] = 'hymn~47~JESUS SAVES~htm_j_e_jesussav.html';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jhn~12~13~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jhn~12~13~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jhn~12~12~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jhn~12~12~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jhn~12~13~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Jhn~12~21~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jhn~12~13~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jhn~12~12~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jhn~12~13~images/maps/Christ/christ_template.html~1';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Jhn~12~21~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Places~Bethany (engraving) key=Bethany~~~~Jhn~12~1~images/places/Israel/israel_template.html~10';
LOI[23] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jhn~12~12~images/places/Israel/israel_template.html~11';
LOI[24] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jhn~12~12~images/places/Israel/israel_template.html~12';
LOI[25] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jhn~12~12~images/places/Israel/israel_template.html~13';
LOI[26] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jhn~12~12~images/places/Israel/israel_template.html~14';
LOI[27] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jhn~12~12~images/places/Israel/israel_template.html~17';
LOI[28] = 'image~Bible~Images~The Leper Healed (engraving) key=miracles~~~~Jhn~12~37~images/bible_images/Miracles/miracles_template.html~1';
LOI[29] = 'image~Bible~Images~Man With Palsy Healed (engraving) key=miracles~~~~Jhn~12~37~images/bible_images/Miracles/miracles_template.html~2';
LOI[30] = 'image~Bible~Images~The Raising of Jairus\' Daughter (engraving) key=miracles~~~~Jhn~12~37~images/bible_images/Miracles/miracles_template.html~3';
LOI[31] = 'image~Bible~Images~The Paralytic Healed (engraving) key=miracles~~~~Jhn~12~37~images/bible_images/Miracles/miracles_template.html~4';
LOI[32] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving) key=miracles~~~~Jhn~12~37~images/bible_images/Miracles/miracles_template.html~5';
LOI[33] = 'image~Bible~Images~Jesus Walking on the Sea (engraving) key=miracles~~~~Jhn~12~37~images/bible_images/Miracles/miracles_template.html~6';
LOI[34] = 'image~Bible~Images~Healing Demoniac Daughter (engraving) key=miracles~~~~Jhn~12~37~images/bible_images/Miracles/miracles_template.html~7';
LOI[35] = 'image~Bible~Images~Deaf Man Hears (engraving) key=miracles~~~~Jhn~12~37~images/bible_images/Miracles/miracles_template.html~8';
LOI[36] = 'image~Bible~Images~Man Born Blind Healed (engraving) key=miracles~~~~Jhn~12~37~images/bible_images/Miracles/miracles_template.html~9';
LOI[37] = 'image~Bible~Images~Jesus Healing Ten Lepers (engraving) key=miracles~~~~Jhn~12~37~images/bible_images/Miracles/miracles_template.html~10';
LOI[38] = 'image~Bible~Images~Jesus Heals Bartimaeus (engraving) key=miracles~~~~Jhn~12~37~images/bible_images/Miracles/miracles_template.html~11';
