var LOI = [];
LOI[0] = 'hymn~4~ABIDE NOT IN THE REALM OF DREAMS~htm_a_b_abidenot.html';
LOI[1] = 'hymn~4~ALL FADED IS THE GLOWING LIGHT~htm_a_l_allfaded.html';
LOI[2] = 'hymn~4~GO, LABOR ON~ SPEND, AND BE SPENT~htm_g_o_golaboro.html';
LOI[3] = 'hymn~4~HANDFUL OF LEAVES, A~htm_h_a_handfull.html';
LOI[4] = 'hymn~4~MUST I GO, AND EMPTY HANDED?~htm_m_u_mustigoa.html';
LOI[5] = 'hymn~4~ONE MORE DAY&#8217;S WORK FOR JESUS~htm_o_n_onemored.html';
LOI[6] = 'hymn~4~WE&#8217;LL WORK TILL JESUS COMES~htm_w_e_l_wellwork.html';
LOI[7] = 'hymn~4~WORK, FOR THE NIGHT IS COMING~htm_w_o_workfort.html';
LOI[8] = 'hymn~25~AMAZING GRACE~htm_a_m_amazgrac.html';
LOI[9] = 'hymn~25~PRAISE GOD FOR WHAT HE'S DONE FOR ME~htm_p_g_pg4whhdm.html';
LOI[10] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jhn~9~28~images/bible_images/Moses/moses_template.html~6';
LOI[11] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jhn~9~29~images/bible_images/Moses/moses_template.html~6';
LOI[12] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jhn~9~28~images/bible_images/Moses/moses_template.html~7';
LOI[13] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jhn~9~29~images/bible_images/Moses/moses_template.html~7';
LOI[14] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jhn~9~28~images/bible_images/Moses/moses_template.html~9';
LOI[15] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jhn~9~29~images/bible_images/Moses/moses_template.html~9';
LOI[16] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jhn~9~28~images/bible_images/Moses/moses_template.html~10';
LOI[17] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jhn~9~29~images/bible_images/Moses/moses_template.html~10';
LOI[18] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jhn~9~28~images/bible_images/Moses/moses_template.html~11';
LOI[19] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jhn~9~29~images/bible_images/Moses/moses_template.html~11';
LOI[20] = 'image~Bible~Images~The Leper Healed (engraving) key=miracles~~~~Jhn~9~16~images/bible_images/Miracles/miracles_template.html~1';
LOI[21] = 'image~Bible~Images~Man With Palsy Healed (engraving) key=miracles~~~~Jhn~9~16~images/bible_images/Miracles/miracles_template.html~2';
LOI[22] = 'image~Bible~Images~The Raising of Jairus\' Daughter (engraving) key=miracles~~~~Jhn~9~16~images/bible_images/Miracles/miracles_template.html~3';
LOI[23] = 'image~Bible~Images~The Paralytic Healed (engraving) key=miracles~~~~Jhn~9~16~images/bible_images/Miracles/miracles_template.html~4';
LOI[24] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving) key=miracles~~~~Jhn~9~16~images/bible_images/Miracles/miracles_template.html~5';
LOI[25] = 'image~Bible~Images~Jesus Walking on the Sea (engraving) key=miracles~~~~Jhn~9~16~images/bible_images/Miracles/miracles_template.html~6';
LOI[26] = 'image~Bible~Images~Healing Demoniac Daughter (engraving) key=miracles~~~~Jhn~9~16~images/bible_images/Miracles/miracles_template.html~7';
LOI[27] = 'image~Bible~Images~Deaf Man Hears (engraving) key=miracles~~~~Jhn~9~16~images/bible_images/Miracles/miracles_template.html~8';
LOI[28] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~1~images/bible_images/Miracles/miracles_template.html~9';
LOI[29] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~2~images/bible_images/Miracles/miracles_template.html~9';
LOI[30] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~3~images/bible_images/Miracles/miracles_template.html~9';
LOI[31] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~4~images/bible_images/Miracles/miracles_template.html~9';
LOI[32] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~5~images/bible_images/Miracles/miracles_template.html~9';
LOI[33] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~6~images/bible_images/Miracles/miracles_template.html~9';
LOI[34] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~7~images/bible_images/Miracles/miracles_template.html~9';
LOI[35] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~8~images/bible_images/Miracles/miracles_template.html~9';
LOI[36] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~9~images/bible_images/Miracles/miracles_template.html~9';
LOI[37] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~10~images/bible_images/Miracles/miracles_template.html~9';
LOI[38] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~11~images/bible_images/Miracles/miracles_template.html~9';
LOI[39] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~12~images/bible_images/Miracles/miracles_template.html~9';
LOI[40] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~13~images/bible_images/Miracles/miracles_template.html~9';
LOI[41] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~14~images/bible_images/Miracles/miracles_template.html~9';
LOI[42] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~15~images/bible_images/Miracles/miracles_template.html~9';
LOI[43] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~16~images/bible_images/Miracles/miracles_template.html~9';
LOI[44] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~17~images/bible_images/Miracles/miracles_template.html~9';
LOI[45] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~18~images/bible_images/Miracles/miracles_template.html~9';
LOI[46] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~19~images/bible_images/Miracles/miracles_template.html~9';
LOI[47] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~20~images/bible_images/Miracles/miracles_template.html~9';
LOI[48] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~21~images/bible_images/Miracles/miracles_template.html~9';
LOI[49] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~22~images/bible_images/Miracles/miracles_template.html~9';
LOI[50] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~23~images/bible_images/Miracles/miracles_template.html~9';
LOI[51] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~24~images/bible_images/Miracles/miracles_template.html~9';
LOI[52] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~25~images/bible_images/Miracles/miracles_template.html~9';
LOI[53] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~26~images/bible_images/Miracles/miracles_template.html~9';
LOI[54] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~27~images/bible_images/Miracles/miracles_template.html~9';
LOI[55] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~28~images/bible_images/Miracles/miracles_template.html~9';
LOI[56] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~29~images/bible_images/Miracles/miracles_template.html~9';
LOI[57] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~30~images/bible_images/Miracles/miracles_template.html~9';
LOI[58] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~31~images/bible_images/Miracles/miracles_template.html~9';
LOI[59] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~32~images/bible_images/Miracles/miracles_template.html~9';
LOI[60] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~33~images/bible_images/Miracles/miracles_template.html~9';
LOI[61] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~34~images/bible_images/Miracles/miracles_template.html~9';
LOI[62] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~35~images/bible_images/Miracles/miracles_template.html~9';
LOI[63] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~36~images/bible_images/Miracles/miracles_template.html~9';
LOI[64] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~37~images/bible_images/Miracles/miracles_template.html~9';
LOI[65] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~38~images/bible_images/Miracles/miracles_template.html~9';
LOI[66] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~39~images/bible_images/Miracles/miracles_template.html~9';
LOI[67] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~40~images/bible_images/Miracles/miracles_template.html~9';
LOI[68] = 'image~Bible~Images~Man Born Blind Healed (engraving)~~~~Jhn~9~41~images/bible_images/Miracles/miracles_template.html~9';
LOI[69] = 'image~Bible~Images~Jesus Healing Ten Lepers (engraving) key=miracles~~~~Jhn~9~16~images/bible_images/Miracles/miracles_template.html~10';
LOI[70] = 'image~Bible~Images~Jesus Heals Bartimaeus (engraving) key=miracles~~~~Jhn~9~16~images/bible_images/Miracles/miracles_template.html~11';
