var LOI = [];
LOI[0] = 'hymn~37~YE THIRSTY FOR GOD~htm_y_t_ythirsty.html';
LOI[1] = 'hymn~38~LIKE A MIGHTY SEA~htm_l_i_likemsea.html';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jhn~7~25~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Jhn~7~14~images/maps/Otest/otest_template.html~3a';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Jhn~7~28~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jhn~7~25~images/maps/Otest/otest_template.html~3b';
LOI[6] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Jhn~7~14~images/maps/Otest/otest_template.html~3b';
LOI[7] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Jhn~7~28~images/maps/Otest/otest_template.html~3b';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Jhn~7~1~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Jhn~7~9~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Jhn~7~41~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Jhn~7~52~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jhn~7~25~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~Jhn~7~42~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Jhn~7~1~images/maps/Christ/christ_template.html~1';
LOI[15] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Jhn~7~9~images/maps/Christ/christ_template.html~1';
LOI[16] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Jhn~7~41~images/maps/Christ/christ_template.html~1';
LOI[17] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Jhn~7~52~images/maps/Christ/christ_template.html~1';
LOI[18] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jhn~7~25~images/places/Israel/israel_template.html~11';
LOI[19] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jhn~7~25~images/places/Israel/israel_template.html~12';
LOI[20] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jhn~7~25~images/places/Israel/israel_template.html~13';
LOI[21] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jhn~7~25~images/places/Israel/israel_template.html~14';
LOI[22] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jhn~7~25~images/places/Israel/israel_template.html~17';
LOI[23] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jhn~7~19~images/bible_images/Moses/moses_template.html~6';
LOI[24] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jhn~7~22~images/bible_images/Moses/moses_template.html~6';
LOI[25] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jhn~7~23~images/bible_images/Moses/moses_template.html~6';
LOI[26] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jhn~7~19~images/bible_images/Moses/moses_template.html~7';
LOI[27] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jhn~7~22~images/bible_images/Moses/moses_template.html~7';
LOI[28] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jhn~7~23~images/bible_images/Moses/moses_template.html~7';
LOI[29] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jhn~7~19~images/bible_images/Moses/moses_template.html~9';
LOI[30] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jhn~7~22~images/bible_images/Moses/moses_template.html~9';
LOI[31] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jhn~7~23~images/bible_images/Moses/moses_template.html~9';
LOI[32] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jhn~7~19~images/bible_images/Moses/moses_template.html~10';
LOI[33] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jhn~7~22~images/bible_images/Moses/moses_template.html~10';
LOI[34] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jhn~7~23~images/bible_images/Moses/moses_template.html~10';
LOI[35] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jhn~7~19~images/bible_images/Moses/moses_template.html~11';
LOI[36] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jhn~7~22~images/bible_images/Moses/moses_template.html~11';
LOI[37] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jhn~7~23~images/bible_images/Moses/moses_template.html~11';
LOI[38] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Jhn~7~42~images/bible_images/Kings/kings_template.html~1';
LOI[39] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Jhn~7~42~images/bible_images/Kings/kings_template.html~2';
LOI[40] = 'image~Bible~Images~The Leper Healed (engraving) key=miracles~~~~Jhn~7~31~images/bible_images/Miracles/miracles_template.html~1';
LOI[41] = 'image~Bible~Images~Man With Palsy Healed (engraving) key=miracles~~~~Jhn~7~31~images/bible_images/Miracles/miracles_template.html~2';
LOI[42] = 'image~Bible~Images~The Raising of Jairus\' Daughter (engraving) key=miracles~~~~Jhn~7~31~images/bible_images/Miracles/miracles_template.html~3';
LOI[43] = 'image~Bible~Images~The Paralytic Healed (engraving) key=miracles~~~~Jhn~7~31~images/bible_images/Miracles/miracles_template.html~4';
LOI[44] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving) key=miracles~~~~Jhn~7~31~images/bible_images/Miracles/miracles_template.html~5';
LOI[45] = 'image~Bible~Images~Jesus Walking on the Sea (engraving) key=miracles~~~~Jhn~7~31~images/bible_images/Miracles/miracles_template.html~6';
LOI[46] = 'image~Bible~Images~Healing Demoniac Daughter (engraving) key=miracles~~~~Jhn~7~31~images/bible_images/Miracles/miracles_template.html~7';
LOI[47] = 'image~Bible~Images~Deaf Man Hears (engraving) key=miracles~~~~Jhn~7~31~images/bible_images/Miracles/miracles_template.html~8';
LOI[48] = 'image~Bible~Images~Man Born Blind Healed (engraving) key=miracles~~~~Jhn~7~31~images/bible_images/Miracles/miracles_template.html~9';
LOI[49] = 'image~Bible~Images~Jesus Healing Ten Lepers (engraving) key=miracles~~~~Jhn~7~31~images/bible_images/Miracles/miracles_template.html~10';
LOI[50] = 'image~Bible~Images~Jesus Heals Bartimaeus (engraving) key=miracles~~~~Jhn~7~31~images/bible_images/Miracles/miracles_template.html~11';
LOI[51] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Jhn~7~14~images/bible_images/Temple/temple_template.html~1';
LOI[52] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Jhn~7~28~images/bible_images/Temple/temple_template.html~1';
LOI[53] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Jhn~7~14~images/bible_images/Temple/temple_template.html~2';
LOI[54] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Jhn~7~28~images/bible_images/Temple/temple_template.html~2';
