var LOI = [];
LOI[0] = 'hymn~1~HEAVENLY WORD PROCEEDING FORTH, THE~htm_h_w_hwprfort.html';
LOI[1] = 'hymn~1~HIGH WORD OF GOD~htm_h_i_highword.html';
LOI[2] = 'hymn~1~O SAVIOR, WHOM THIS HOLY MORN~htm_o_s_oswtholy.html';
LOI[3] = 'hymn~1~WORD SUPREME, BEFORE CREATION~htm_w_o_wordsupb.html';
LOI[4] = 'hymn~2~BLESSED JESUS, AT THY WORD~htm_b_l_blessedj.html';
LOI[5] = 'hymn~3~JESUS IS GOD!~htm_j_e_jesusgod.html';
LOI[6] = 'hymn~3~SEE THE GOLD UPON THE HILLS~htm_s_e_seetgold.html';
LOI[7] = 'hymn~4~JESUS, THOU JOY OF LOVING HEARTS~htm_j_t_jthoujoy.html';
LOI[8] = 'hymn~12~HE GIVES THE POWER~htm_h_e_hegivesp.html';
LOI[9] = 'hymn~12~O GOD, THOU ART THE FATHER~htm_o_g_ogtatfat.html';
LOI[10] = 'hymn~14~COME, THOU REDEEMER OF THE EARTH~htm_c_o_cothoure.html';
LOI[11] = 'hymn~14~O COME, REDEEMER OF MANKIND~htm_o_c_ocomered.html';
LOI[12] = 'hymn~14~O WORD OF GOD INCARNATE~htm_o_w_owordgod.html';
LOI[13] = 'hymn~14~SAVIOR OF THE HEATHEN, KNOWN~htm_s_a_savheath.html';
LOI[14] = 'hymn~14~WHEN CAME IN FLESH THE INCARNATE WORD~htm_w_h_whencame.html';
LOI[15] = 'hymn~23~ON JORDAN&#8217;S BANK THE BAPTIST&#8217;S CRY~htm_o_n_onjordan.html';
LOI[16] = 'hymn~29~BEHOLD THE GLORIES OF THE LAMB~htm_b_e_beholdgl.html';
LOI[17] = 'hymn~29~BEHOLD THE LAMB OF GOD~htm_b_e_beholdtl.html';
LOI[18] = 'hymn~29~JUST AS I AM, WITHOUT ONE PLEA~htm_j_u_justasam.html';
LOI[19] = 'hymn~29~LAMB OF GOD! OUR SOULS ADORE THEE~htm_l_g_lgodursa.html';
LOI[20] = 'hymn~29~O LAMB OF GOD MOST HOLY~htm_o_l_olambgod.html';
LOI[21] = 'hymn~29~O LORD JESUS, LAMB OF GOD~htm_o_l_oljlambg.html';
LOI[22] = 'hymn~29~LOOK TO THE LAMB OF GOD~htm_l_o_looklamb.html';
LOI[23] = 'hymn~36~GENTLE JESUS, MEEK AND MILD~htm_g_e_gentleje.html';
LOI[24] = 'hymn~43~BEHOLD, THE MASTER PASSETH BY~htm_b_e_beholdtm.html';
LOI[25] = 'hymn~43~I LOVE TO WALK WITH JESUS~htm_i_l_iltwwjes.html';
LOI[26] = 'hymn~43~LIGHT OF GOD IS FALLING, THE~htm_l_g_lgodfall.html';
LOI[27] = 'hymn~49~O JESUS, KING MOST WONDERFUL~htm_o_j_ojkmwond.html';
LOI[28] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jhn~1~31~images/maps/Otest/otest_template.html~1b';
LOI[29] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jhn~1~49~images/maps/Otest/otest_template.html~1b';
LOI[30] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Jhn~1~45~images/maps/Otest/otest_template.html~1b';
LOI[31] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jhn~1~31~images/maps/Otest/otest_template.html~1c';
LOI[32] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jhn~1~49~images/maps/Otest/otest_template.html~1c';
LOI[33] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Jhn~1~45~images/maps/Otest/otest_template.html~1c';
LOI[34] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jhn~1~19~images/maps/Otest/otest_template.html~3a';
LOI[35] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jhn~1~19~images/maps/Otest/otest_template.html~3b';
LOI[36] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jhn~1~31~images/maps/Otest/otest_template.html~3c';
LOI[37] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jhn~1~49~images/maps/Otest/otest_template.html~3c';
LOI[38] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Jhn~1~43~images/maps/Otest/otest_template.html~3c';
LOI[39] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Jhn~1~28~images/maps/Otest/otest_template.html~3c';
LOI[40] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jhn~1~31~images/maps/Otest/otest_template.html~4';
LOI[41] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jhn~1~49~images/maps/Otest/otest_template.html~4';
LOI[42] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jhn~1~19~images/maps/Otest/otest_template.html~4';
LOI[43] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jhn~1~31~images/maps/Christ/christ_template.html~1';
LOI[44] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jhn~1~49~images/maps/Christ/christ_template.html~1';
LOI[45] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Jhn~1~43~images/maps/Christ/christ_template.html~1';
LOI[46] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jhn~1~19~images/places/Israel/israel_template.html~11';
LOI[47] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jhn~1~19~images/places/Israel/israel_template.html~12';
LOI[48] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jhn~1~19~images/places/Israel/israel_template.html~13';
LOI[49] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jhn~1~19~images/places/Israel/israel_template.html~14';
LOI[50] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jhn~1~19~images/places/Israel/israel_template.html~17';
LOI[51] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Jhn~1~45~images/bible_images/Moses/moses_template.html~5';
LOI[52] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jhn~1~17~images/bible_images/Moses/moses_template.html~6';
LOI[53] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jhn~1~45~images/bible_images/Moses/moses_template.html~6';
LOI[54] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jhn~1~17~images/bible_images/Moses/moses_template.html~7';
LOI[55] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jhn~1~45~images/bible_images/Moses/moses_template.html~7';
LOI[56] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jhn~1~17~images/bible_images/Moses/moses_template.html~9';
LOI[57] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jhn~1~45~images/bible_images/Moses/moses_template.html~9';
LOI[58] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jhn~1~17~images/bible_images/Moses/moses_template.html~10';
LOI[59] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jhn~1~45~images/bible_images/Moses/moses_template.html~10';
LOI[60] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jhn~1~17~images/bible_images/Moses/moses_template.html~11';
LOI[61] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jhn~1~45~images/bible_images/Moses/moses_template.html~11';
