var LOI = [];
LOI[0] = 'hymn~8~JESUS LOVES EVEN ME~htm_j_l_jlovesem.html';
LOI[1] = 'hymn~8~LOVE IS THE THEME~htm_l_t_lthethem.html';
LOI[2] = 'hymn~23~O THOU TO WHOM, IN ANCIENT TIME~htm_o_t_oth2whom.html';
LOI[3] = 'hymn~24~BEHOLD US, LORD, A LITTLE SPACE~htm_b_e_beholdus.html';
LOI[4] = 'hymn~24~HOLY SPIRIT, TRUTH DIVINE~htm_h_o_holstdiv.html';
LOI[5] = 'hymn~35~REAPERS ARE NEEDED~htm_r_e_reapersn.html';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Jhn~4~5~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Jhn~4~5~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jhn~4~20~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jhn~4~21~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jhn~4~45~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jhn~4~20~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jhn~4~21~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jhn~4~45~images/maps/Otest/otest_template.html~3b';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Jhn~4~3~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Jhn~4~43~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Jhn~4~45~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Jhn~4~46~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Jhn~4~47~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Jhn~4~54~images/maps/Otest/otest_template.html~3c';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jhn~4~20~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jhn~4~21~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jhn~4~45~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Jhn~4~4~images/maps/Christ/christ_template.html~1';
LOI[24] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Jhn~4~5~images/maps/Christ/christ_template.html~1';
LOI[25] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Jhn~4~7~images/maps/Christ/christ_template.html~1';
LOI[26] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Jhn~4~9~images/maps/Christ/christ_template.html~1';
LOI[27] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Jhn~4~3~images/maps/Christ/christ_template.html~1';
LOI[28] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Jhn~4~43~images/maps/Christ/christ_template.html~1';
LOI[29] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Jhn~4~45~images/maps/Christ/christ_template.html~1';
LOI[30] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Jhn~4~46~images/maps/Christ/christ_template.html~1';
LOI[31] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Jhn~4~47~images/maps/Christ/christ_template.html~1';
LOI[32] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Jhn~4~54~images/maps/Christ/christ_template.html~1';
LOI[33] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jhn~4~20~images/places/Israel/israel_template.html~11';
LOI[34] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jhn~4~21~images/places/Israel/israel_template.html~11';
LOI[35] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jhn~4~45~images/places/Israel/israel_template.html~11';
LOI[36] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jhn~4~20~images/places/Israel/israel_template.html~12';
LOI[37] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jhn~4~21~images/places/Israel/israel_template.html~12';
LOI[38] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jhn~4~45~images/places/Israel/israel_template.html~12';
LOI[39] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jhn~4~20~images/places/Israel/israel_template.html~13';
LOI[40] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jhn~4~21~images/places/Israel/israel_template.html~13';
LOI[41] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jhn~4~45~images/places/Israel/israel_template.html~13';
LOI[42] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jhn~4~20~images/places/Israel/israel_template.html~14';
LOI[43] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jhn~4~21~images/places/Israel/israel_template.html~14';
LOI[44] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jhn~4~45~images/places/Israel/israel_template.html~14';
LOI[45] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jhn~4~20~images/places/Israel/israel_template.html~17';
LOI[46] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jhn~4~21~images/places/Israel/israel_template.html~17';
LOI[47] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jhn~4~45~images/places/Israel/israel_template.html~17';
LOI[48] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Jhn~4~5~images/bible_images/Moses/moses_template.html~5';
