var LOI = [];
LOI[0] = 'hymn~3~FATHER OF JESUS CHRIST, MY LORD~htm_f_a_fatjesus.html';
LOI[1] = 'hymn~10~ALL HAIL TO THEE, O BLESSED MORN!~htm_a_l_allhailt.html';
LOI[2] = 'hymn~10~HASTEN THE TIME APPOINTED~htm_h_t_htimeapp.html';
LOI[3] = 'hymn~18~COVERED BY THE BLOOD~htm_c_o_v_covblood.html';
LOI[4] = 'hymn~18~NOR SILVER NOR GOLD~htm_n_s_nsilverg.html';
LOI[5] = 'hymn~18~GLORY BE TO JESUS~htm_g_b_gb2jesus.html';
LOI[6] = 'hymn~21~AS SHADOWS CAST BY CLOUD AND SUN~htm_a_s_ashadows.html';
LOI[7] = 'hymn~25~OH, WONDERFUL WORD!~htm_o_w_owondwrd.html';
LOI[8] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Galatia,Bithynia~~~~1Pe~1~1~images/maps/Journeys/journeys_template.html~2';
LOI[9] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Galatia,Asia~~~~1Pe~1~1~images/maps/Journeys/journeys_template.html~3';
