var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Ezr~3~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Ezr~3~2~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Ezr~3~10~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Ezr~3~11~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Ezr~3~9~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Ezr~3~1~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Ezr~3~2~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Ezr~3~10~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Ezr~3~11~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Ezr~3~9~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~3~1~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~3~8~images/maps/Otest/otest_template.html~3a';
LOI[12] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Ezr~3~6~images/maps/Otest/otest_template.html~3a';
LOI[13] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Ezr~3~10~images/maps/Otest/otest_template.html~3a';
LOI[14] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~3~1~images/maps/Otest/otest_template.html~3b';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~3~8~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Ezr~3~6~images/maps/Otest/otest_template.html~3b';
LOI[17] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Ezr~3~10~images/maps/Otest/otest_template.html~3b';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~3~1~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~3~2~images/maps/Otest/otest_template.html~3c';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~3~10~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~3~11~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Middle Palestine (map) key=Tyre~~~~Ezr~3~7~images/maps/Otest/otest_template.html~3c';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jerusalem~~~~Ezr~3~1~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Ezr~3~2~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Ezr~3~10~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Ezr~3~11~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~3~8~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~3~1~images/maps/Christ/christ_template.html~1';
LOI[29] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~3~2~images/maps/Christ/christ_template.html~1';
LOI[30] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~3~10~images/maps/Christ/christ_template.html~1';
LOI[31] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~3~11~images/maps/Christ/christ_template.html~1';
LOI[32] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Tyre~~~~Ezr~3~7~images/maps/Journeys/journeys_template.html~3';
LOI[33] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~3~1~images/places/Israel/israel_template.html~11';
LOI[34] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~3~8~images/places/Israel/israel_template.html~11';
LOI[35] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~3~1~images/places/Israel/israel_template.html~12';
LOI[36] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~3~8~images/places/Israel/israel_template.html~12';
LOI[37] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~3~1~images/places/Israel/israel_template.html~13';
LOI[38] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~3~8~images/places/Israel/israel_template.html~13';
LOI[39] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~3~1~images/places/Israel/israel_template.html~14';
LOI[40] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~3~8~images/places/Israel/israel_template.html~14';
LOI[41] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~3~1~images/places/Israel/israel_template.html~17';
LOI[42] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~3~8~images/places/Israel/israel_template.html~17';
LOI[43] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Ezr~3~2~images/bible_images/Moses/moses_template.html~6';
LOI[44] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Ezr~3~2~images/bible_images/Moses/moses_template.html~7';
LOI[45] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Ezr~3~2~images/bible_images/Moses/moses_template.html~9';
LOI[46] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Ezr~3~2~images/bible_images/Moses/moses_template.html~10';
LOI[47] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Ezr~3~2~images/bible_images/Moses/moses_template.html~11';
LOI[48] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Ezr~3~10~images/bible_images/Kings/kings_template.html~1';
LOI[49] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Ezr~3~10~images/bible_images/Kings/kings_template.html~2';
LOI[50] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Ezr~3~6~images/bible_images/Temple/temple_template.html~1';
LOI[51] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Ezr~3~10~images/bible_images/Temple/temple_template.html~1';
LOI[52] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Ezr~3~6~images/bible_images/Temple/temple_template.html~2';
LOI[53] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Ezr~3~10~images/bible_images/Temple/temple_template.html~2';
