var LOI = [];
LOI[0] = 'hymn~22~STRENGTHEN FOR SERVICE, LORD~htm_s_t_stren4sv.html';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Ezr~6~14~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Ezr~6~16~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Ezr~6~17~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Ezr~6~21~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Ezr~6~22~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Ezr~6~14~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Ezr~6~16~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Ezr~6~17~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Ezr~6~21~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Ezr~6~22~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~6~3~images/maps/Otest/otest_template.html~3a';
LOI[12] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Temple~~~~Ezr~6~5~images/maps/Otest/otest_template.html~3a';
LOI[13] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~6~9~images/maps/Otest/otest_template.html~3a';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~6~12~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~6~18~images/maps/Otest/otest_template.html~3a';
LOI[16] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~6~3~images/maps/Otest/otest_template.html~3b';
LOI[17] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Temple~~~~Ezr~6~5~images/maps/Otest/otest_template.html~3b';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~6~9~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~6~12~images/maps/Otest/otest_template.html~3b';
LOI[20] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~6~18~images/maps/Otest/otest_template.html~3b';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~6~14~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~6~16~images/maps/Otest/otest_template.html~3c';
LOI[23] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~6~17~images/maps/Otest/otest_template.html~3c';
LOI[24] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~6~21~images/maps/Otest/otest_template.html~3c';
LOI[25] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~6~22~images/maps/Otest/otest_template.html~3c';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Ezr~6~14~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Ezr~6~16~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Ezr~6~17~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Ezr~6~21~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Ezr~6~22~images/maps/Otest/otest_template.html~4';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~6~3~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~6~5~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~6~9~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~6~12~images/maps/Otest/otest_template.html~4';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~6~18~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~6~14~images/maps/Christ/christ_template.html~1';
LOI[37] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~6~16~images/maps/Christ/christ_template.html~1';
LOI[38] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~6~17~images/maps/Christ/christ_template.html~1';
LOI[39] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~6~21~images/maps/Christ/christ_template.html~1';
LOI[40] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~6~22~images/maps/Christ/christ_template.html~1';
LOI[41] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~6~3~images/places/Israel/israel_template.html~11';
LOI[42] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~6~5~images/places/Israel/israel_template.html~11';
LOI[43] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~6~9~images/places/Israel/israel_template.html~11';
LOI[44] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~6~12~images/places/Israel/israel_template.html~11';
LOI[45] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~6~18~images/places/Israel/israel_template.html~11';
LOI[46] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~6~3~images/places/Israel/israel_template.html~12';
LOI[47] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~6~5~images/places/Israel/israel_template.html~12';
LOI[48] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~6~9~images/places/Israel/israel_template.html~12';
LOI[49] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~6~12~images/places/Israel/israel_template.html~12';
LOI[50] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~6~18~images/places/Israel/israel_template.html~12';
LOI[51] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~6~3~images/places/Israel/israel_template.html~13';
LOI[52] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~6~5~images/places/Israel/israel_template.html~13';
LOI[53] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~6~9~images/places/Israel/israel_template.html~13';
LOI[54] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~6~12~images/places/Israel/israel_template.html~13';
LOI[55] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~6~18~images/places/Israel/israel_template.html~13';
LOI[56] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~6~3~images/places/Israel/israel_template.html~14';
LOI[57] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~6~5~images/places/Israel/israel_template.html~14';
LOI[58] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~6~9~images/places/Israel/israel_template.html~14';
LOI[59] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~6~12~images/places/Israel/israel_template.html~14';
LOI[60] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~6~18~images/places/Israel/israel_template.html~14';
LOI[61] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~6~3~images/places/Israel/israel_template.html~17';
LOI[62] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~6~5~images/places/Israel/israel_template.html~17';
LOI[63] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~6~9~images/places/Israel/israel_template.html~17';
LOI[64] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~6~12~images/places/Israel/israel_template.html~17';
LOI[65] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~6~18~images/places/Israel/israel_template.html~17';
LOI[66] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Ezr~6~18~images/bible_images/Moses/moses_template.html~6';
LOI[67] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Ezr~6~18~images/bible_images/Moses/moses_template.html~7';
LOI[68] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Ezr~6~18~images/bible_images/Moses/moses_template.html~9';
LOI[69] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Ezr~6~18~images/bible_images/Moses/moses_template.html~10';
LOI[70] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Ezr~6~18~images/bible_images/Moses/moses_template.html~11';
LOI[71] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Ezr~6~1~images/bible_images/Kings/kings_template.html~7';
LOI[72] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Ezr~6~5~images/bible_images/Kings/kings_template.html~7';
LOI[73] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~Ezr~6~5~images/bible_images/Daniel/daniel_template.html~1';
LOI[74] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Nebuchadnezzar~~~~Ezr~6~5~images/bible_images/Daniel/daniel_template.html~3';
LOI[75] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Ezr~6~5~images/bible_images/Temple/temple_template.html~1';
LOI[76] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Ezr~6~5~images/bible_images/Temple/temple_template.html~2';
