var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Ezr~4~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Ezr~4~3~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Ezr~4~4~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Ezr~4~6~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Ezr~4~1~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Ezr~4~3~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Ezr~4~4~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Ezr~4~6~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~4~6~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~4~8~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~4~12~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~4~20~images/maps/Otest/otest_template.html~3a';
LOI[12] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~4~23~images/maps/Otest/otest_template.html~3a';
LOI[13] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~4~24~images/maps/Otest/otest_template.html~3a';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Ezr~4~1~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~4~6~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~4~8~images/maps/Otest/otest_template.html~3b';
LOI[17] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~4~12~images/maps/Otest/otest_template.html~3b';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~4~20~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~4~23~images/maps/Otest/otest_template.html~3b';
LOI[20] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~4~24~images/maps/Otest/otest_template.html~3b';
LOI[21] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Ezr~4~1~images/maps/Otest/otest_template.html~3b';
LOI[22] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~4~1~images/maps/Otest/otest_template.html~3c';
LOI[23] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~4~3~images/maps/Otest/otest_template.html~3c';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Ezr~4~1~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Ezr~4~3~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~4~6~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~4~8~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~4~12~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~4~20~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~4~23~images/maps/Otest/otest_template.html~4';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~4~24~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~4~1~images/maps/Christ/christ_template.html~1';
LOI[33] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~4~3~images/maps/Christ/christ_template.html~1';
LOI[34] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Ezr~4~10~images/maps/Christ/christ_template.html~1';
LOI[35] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Ezr~4~17~images/maps/Christ/christ_template.html~1';
LOI[36] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~4~6~images/places/Israel/israel_template.html~11';
LOI[37] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~4~8~images/places/Israel/israel_template.html~11';
LOI[38] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~4~12~images/places/Israel/israel_template.html~11';
LOI[39] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~4~20~images/places/Israel/israel_template.html~11';
LOI[40] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~4~23~images/places/Israel/israel_template.html~11';
LOI[41] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~4~24~images/places/Israel/israel_template.html~11';
LOI[42] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~4~6~images/places/Israel/israel_template.html~12';
LOI[43] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~4~8~images/places/Israel/israel_template.html~12';
LOI[44] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~4~12~images/places/Israel/israel_template.html~12';
LOI[45] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~4~20~images/places/Israel/israel_template.html~12';
LOI[46] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~4~23~images/places/Israel/israel_template.html~12';
LOI[47] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~4~24~images/places/Israel/israel_template.html~12';
LOI[48] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~4~6~images/places/Israel/israel_template.html~13';
LOI[49] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~4~8~images/places/Israel/israel_template.html~13';
LOI[50] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~4~12~images/places/Israel/israel_template.html~13';
LOI[51] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~4~20~images/places/Israel/israel_template.html~13';
LOI[52] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~4~23~images/places/Israel/israel_template.html~13';
LOI[53] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~4~24~images/places/Israel/israel_template.html~13';
LOI[54] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~4~6~images/places/Israel/israel_template.html~14';
LOI[55] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~4~8~images/places/Israel/israel_template.html~14';
LOI[56] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~4~12~images/places/Israel/israel_template.html~14';
LOI[57] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~4~20~images/places/Israel/israel_template.html~14';
LOI[58] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~4~23~images/places/Israel/israel_template.html~14';
LOI[59] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~4~24~images/places/Israel/israel_template.html~14';
LOI[60] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~4~6~images/places/Israel/israel_template.html~17';
LOI[61] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~4~8~images/places/Israel/israel_template.html~17';
LOI[62] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~4~12~images/places/Israel/israel_template.html~17';
LOI[63] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~4~20~images/places/Israel/israel_template.html~17';
LOI[64] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~4~23~images/places/Israel/israel_template.html~17';
LOI[65] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~4~24~images/places/Israel/israel_template.html~17';
LOI[66] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Ezr~4~1~images/bible_images/Temple/temple_template.html~1';
LOI[67] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Ezr~4~1~images/bible_images/Temple/temple_template.html~2';
