var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Elam~~~~Ezr~8~7~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Levi~~~~Ezr~8~18~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Ezr~8~25~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Ezr~8~29~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Ezr~8~35~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Levi~~~~Ezr~8~15~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Levi~~~~Ezr~8~18~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Ezr~8~25~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Ezr~8~29~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Ezr~8~35~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Levi~~~~Ezr~8~15~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~8~29~images/maps/Otest/otest_template.html~3a';
LOI[12] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~8~30~images/maps/Otest/otest_template.html~3a';
LOI[13] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~8~31~images/maps/Otest/otest_template.html~3a';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Ezr~8~32~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~8~29~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~8~30~images/maps/Otest/otest_template.html~3b';
LOI[17] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~8~31~images/maps/Otest/otest_template.html~3b';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Ezr~8~32~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~8~18~images/maps/Otest/otest_template.html~3c';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~8~25~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~8~29~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Ezr~8~35~images/maps/Otest/otest_template.html~3c';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Ezr~8~18~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Ezr~8~25~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jerusalem~~~~Ezr~8~29~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Ezr~8~35~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~8~30~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~8~31~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Ezr~8~32~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~8~18~images/maps/Christ/christ_template.html~1';
LOI[31] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~8~25~images/maps/Christ/christ_template.html~1';
LOI[32] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~8~29~images/maps/Christ/christ_template.html~1';
LOI[33] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Ezr~8~35~images/maps/Christ/christ_template.html~1';
LOI[34] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~8~29~images/places/Israel/israel_template.html~11';
LOI[35] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~8~30~images/places/Israel/israel_template.html~11';
LOI[36] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~8~31~images/places/Israel/israel_template.html~11';
LOI[37] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Ezr~8~32~images/places/Israel/israel_template.html~11';
LOI[38] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~8~29~images/places/Israel/israel_template.html~12';
LOI[39] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~8~30~images/places/Israel/israel_template.html~12';
LOI[40] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~8~31~images/places/Israel/israel_template.html~12';
LOI[41] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Ezr~8~32~images/places/Israel/israel_template.html~12';
LOI[42] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~8~29~images/places/Israel/israel_template.html~13';
LOI[43] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~8~30~images/places/Israel/israel_template.html~13';
LOI[44] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~8~31~images/places/Israel/israel_template.html~13';
LOI[45] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Ezr~8~32~images/places/Israel/israel_template.html~13';
LOI[46] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~8~29~images/places/Israel/israel_template.html~14';
LOI[47] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~8~30~images/places/Israel/israel_template.html~14';
LOI[48] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~8~31~images/places/Israel/israel_template.html~14';
LOI[49] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Ezr~8~32~images/places/Israel/israel_template.html~14';
LOI[50] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~8~29~images/places/Israel/israel_template.html~17';
LOI[51] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~8~30~images/places/Israel/israel_template.html~17';
LOI[52] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~8~31~images/places/Israel/israel_template.html~17';
LOI[53] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Ezr~8~32~images/places/Israel/israel_template.html~17';
LOI[54] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Ezr~8~2~images/bible_images/Kings/kings_template.html~1';
LOI[55] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Ezr~8~20~images/bible_images/Kings/kings_template.html~1';
LOI[56] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Ezr~8~2~images/bible_images/Kings/kings_template.html~2';
LOI[57] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Ezr~8~20~images/bible_images/Kings/kings_template.html~2';
LOI[58] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Ezr~8~1~images/bible_images/Kings/kings_template.html~7';
LOI[59] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Daniel~~~~Ezr~8~2~images/bible_images/Daniel/daniel_template.html~1';
LOI[60] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Ezr~8~2~images/bible_images/Daniel/daniel_template.html~2';
LOI[61] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Ezr~8~2~images/bible_images/Daniel/daniel_template.html~3';
LOI[62] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Ezr~8~2~images/bible_images/Daniel/daniel_template.html~4';
LOI[63] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Ezr~8~2~images/bible_images/Daniel/daniel_template.html~5';
LOI[64] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Ezr~8~2~images/bible_images/Daniel/daniel_template.html~6';
