var LOI = [];
LOI[0] = 'hymn~21~CLOSE TO THEE~htm_c_l_closthee.html';
LOI[1] = 'hymn~21~O GOD, OF GOOD THE UNFATHOMED SEA~htm_o_g_ogofgood.html';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~30~2~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Jer~30~3~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Jer~30~4~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~30~10~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~30~2~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Jer~30~3~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Jer~30~4~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~30~10~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Jer~30~17~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Jer~30~17~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~30~2~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~30~3~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~30~4~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~30~10~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~30~2~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~30~3~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~30~4~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~30~10~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~30~2~images/maps/Christ/christ_template.html~1';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~30~3~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~30~4~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~30~10~images/maps/Christ/christ_template.html~1';
LOI[24] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Jer~30~9~images/bible_images/Kings/kings_template.html~1';
LOI[25] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Jer~30~9~images/bible_images/Kings/kings_template.html~2';
