var LOI = [];
LOI[0] = 'hymn~30~BATTLE HYMN OF THE REPUBLIC~htm_b_h_bhymnotr.html';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Dedan~~~~Jer~25~23~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Elam~~~~Jer~25~25~images/maps/Otest/otest_template.html~1a';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~25~15~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~25~27~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~25~1~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~25~2~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~25~3~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~25~18~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~25~15~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~25~27~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~25~1~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~25~2~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~25~3~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~25~18~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~25~2~images/maps/Otest/otest_template.html~3a';
LOI[16] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~25~18~images/maps/Otest/otest_template.html~3a';
LOI[17] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~25~2~images/maps/Otest/otest_template.html~3b';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~25~18~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~25~15~images/maps/Otest/otest_template.html~3c';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~25~27~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~25~15~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~25~27~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~25~2~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~25~18~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~25~21~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~25~19~images/maps/Otest/otest_template.html~5';
LOI[27] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~25~15~images/maps/Christ/christ_template.html~1';
LOI[28] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~25~27~images/maps/Christ/christ_template.html~1';
LOI[29] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~25~2~images/places/Israel/israel_template.html~11';
LOI[30] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~25~18~images/places/Israel/israel_template.html~11';
LOI[31] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~25~2~images/places/Israel/israel_template.html~12';
LOI[32] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~25~18~images/places/Israel/israel_template.html~12';
LOI[33] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~25~2~images/places/Israel/israel_template.html~13';
LOI[34] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~25~18~images/places/Israel/israel_template.html~13';
LOI[35] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~25~2~images/places/Israel/israel_template.html~14';
LOI[36] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~25~18~images/places/Israel/israel_template.html~14';
LOI[37] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~25~2~images/places/Israel/israel_template.html~17';
LOI[38] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~25~18~images/places/Israel/israel_template.html~17';
LOI[39] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Jer~25~19~images/bible_images/Moses/moses_template.html~5';
LOI[40] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~Jer~25~20~images/bible_images/Samson/samson_template.html~6';
LOI[41] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~25~1~images/bible_images/Kings/kings_template.html~6';
LOI[42] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~25~2~images/bible_images/Kings/kings_template.html~6';
LOI[43] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~25~3~images/bible_images/Kings/kings_template.html~6';
LOI[44] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~25~4~images/bible_images/Kings/kings_template.html~6';
LOI[45] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~25~5~images/bible_images/Kings/kings_template.html~6';
LOI[46] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~25~6~images/bible_images/Kings/kings_template.html~6';
LOI[47] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~25~7~images/bible_images/Kings/kings_template.html~6';
LOI[48] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~25~8~images/bible_images/Kings/kings_template.html~6';
LOI[49] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~25~9~images/bible_images/Kings/kings_template.html~6';
LOI[50] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~25~10~images/bible_images/Kings/kings_template.html~6';
LOI[51] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~25~11~images/bible_images/Kings/kings_template.html~6';
LOI[52] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~25~12~images/bible_images/Kings/kings_template.html~6';
LOI[53] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~25~1~images/bible_images/Kings/kings_template.html~7';
LOI[54] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~25~2~images/bible_images/Kings/kings_template.html~7';
LOI[55] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~25~3~images/bible_images/Kings/kings_template.html~7';
LOI[56] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~25~4~images/bible_images/Kings/kings_template.html~7';
LOI[57] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~25~5~images/bible_images/Kings/kings_template.html~7';
LOI[58] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~25~6~images/bible_images/Kings/kings_template.html~7';
LOI[59] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~25~7~images/bible_images/Kings/kings_template.html~7';
LOI[60] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~25~8~images/bible_images/Kings/kings_template.html~7';
LOI[61] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~25~9~images/bible_images/Kings/kings_template.html~7';
LOI[62] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~25~10~images/bible_images/Kings/kings_template.html~7';
LOI[63] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~25~11~images/bible_images/Kings/kings_template.html~7';
LOI[64] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~25~12~images/bible_images/Kings/kings_template.html~7';
LOI[65] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~25~1~images/bible_images/Kings/kings_template.html~8';
LOI[66] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~25~2~images/bible_images/Kings/kings_template.html~8';
LOI[67] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~25~3~images/bible_images/Kings/kings_template.html~8';
LOI[68] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~25~4~images/bible_images/Kings/kings_template.html~8';
LOI[69] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~25~5~images/bible_images/Kings/kings_template.html~8';
LOI[70] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~25~6~images/bible_images/Kings/kings_template.html~8';
LOI[71] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~25~7~images/bible_images/Kings/kings_template.html~8';
LOI[72] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~25~8~images/bible_images/Kings/kings_template.html~8';
LOI[73] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~25~9~images/bible_images/Kings/kings_template.html~8';
LOI[74] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~25~10~images/bible_images/Kings/kings_template.html~8';
LOI[75] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~25~11~images/bible_images/Kings/kings_template.html~8';
LOI[76] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~25~12~images/bible_images/Kings/kings_template.html~8';
