var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Jer~37~7~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~37~1~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~Jer~37~12~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~Jer~37~13~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Jer~37~7~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~37~1~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~Jer~37~12~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~Jer~37~13~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~37~5~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~37~11~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~37~12~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~37~5~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~37~11~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~37~12~images/maps/Otest/otest_template.html~3b';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~37~7~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~37~7~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~37~5~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~37~11~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~37~12~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~37~5~images/maps/Otest/otest_template.html~5';
LOI[20] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~37~7~images/maps/Otest/otest_template.html~5';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~37~7~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~37~5~images/places/Israel/israel_template.html~11';
LOI[23] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~37~11~images/places/Israel/israel_template.html~11';
LOI[24] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~37~12~images/places/Israel/israel_template.html~11';
LOI[25] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~37~5~images/places/Israel/israel_template.html~12';
LOI[26] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~37~11~images/places/Israel/israel_template.html~12';
LOI[27] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~37~12~images/places/Israel/israel_template.html~12';
LOI[28] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~37~5~images/places/Israel/israel_template.html~13';
LOI[29] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~37~11~images/places/Israel/israel_template.html~13';
LOI[30] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~37~12~images/places/Israel/israel_template.html~13';
LOI[31] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~37~5~images/places/Israel/israel_template.html~14';
LOI[32] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~37~11~images/places/Israel/israel_template.html~14';
LOI[33] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~37~12~images/places/Israel/israel_template.html~14';
LOI[34] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~37~5~images/places/Israel/israel_template.html~17';
LOI[35] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~37~11~images/places/Israel/israel_template.html~17';
LOI[36] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~37~12~images/places/Israel/israel_template.html~17';
LOI[37] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving) key=Jehoiakim~~~~Jer~37~1~images/bible_images/Kings/kings_template.html~6';
LOI[38] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~37~1~images/bible_images/Kings/kings_template.html~7';
LOI[39] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~37~17~images/bible_images/Kings/kings_template.html~7';
LOI[40] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~37~19~images/bible_images/Kings/kings_template.html~7';
