var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Jer~51~5~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~51~19~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~51~33~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~51~49~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~51~59~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Jer~51~5~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~51~19~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~51~33~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~51~49~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~51~59~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Zion~~~~Jer~51~35~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~51~50~images/maps/Otest/otest_template.html~3a';
LOI[12] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Jer~51~11~images/maps/Otest/otest_template.html~3a';
LOI[13] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Jer~51~10~images/maps/Otest/otest_template.html~3a';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Jer~51~24~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Zion~~~~Jer~51~35~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~51~50~images/maps/Otest/otest_template.html~3b';
LOI[17] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Jer~51~11~images/maps/Otest/otest_template.html~3b';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Jer~51~10~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Jer~51~24~images/maps/Otest/otest_template.html~3b';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~51~5~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~51~19~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~51~33~images/maps/Otest/otest_template.html~3c';
LOI[23] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~51~49~images/maps/Otest/otest_template.html~3c';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~51~5~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~51~19~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~51~33~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~51~49~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~51~35~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~51~50~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~51~5~images/maps/Christ/christ_template.html~1';
LOI[31] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~51~19~images/maps/Christ/christ_template.html~1';
LOI[32] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~51~33~images/maps/Christ/christ_template.html~1';
LOI[33] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~51~49~images/maps/Christ/christ_template.html~1';
LOI[34] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~51~35~images/places/Israel/israel_template.html~11';
LOI[35] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~51~50~images/places/Israel/israel_template.html~11';
LOI[36] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~51~35~images/places/Israel/israel_template.html~12';
LOI[37] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~51~50~images/places/Israel/israel_template.html~12';
LOI[38] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~51~35~images/places/Israel/israel_template.html~13';
LOI[39] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~51~50~images/places/Israel/israel_template.html~13';
LOI[40] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~51~35~images/places/Israel/israel_template.html~14';
LOI[41] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~51~50~images/places/Israel/israel_template.html~14';
LOI[42] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~51~35~images/places/Israel/israel_template.html~17';
LOI[43] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~51~50~images/places/Israel/israel_template.html~17';
LOI[44] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~1~images/bible_images/Kings/kings_template.html~7';
LOI[45] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~2~images/bible_images/Kings/kings_template.html~7';
LOI[46] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~6~images/bible_images/Kings/kings_template.html~7';
LOI[47] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~7~images/bible_images/Kings/kings_template.html~7';
LOI[48] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~8~images/bible_images/Kings/kings_template.html~7';
LOI[49] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~9~images/bible_images/Kings/kings_template.html~7';
LOI[50] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~11~images/bible_images/Kings/kings_template.html~7';
LOI[51] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~12~images/bible_images/Kings/kings_template.html~7';
LOI[52] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~24~images/bible_images/Kings/kings_template.html~7';
LOI[53] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~29~images/bible_images/Kings/kings_template.html~7';
LOI[54] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~30~images/bible_images/Kings/kings_template.html~7';
LOI[55] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~31~images/bible_images/Kings/kings_template.html~7';
LOI[56] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~33~images/bible_images/Kings/kings_template.html~7';
LOI[57] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~34~images/bible_images/Kings/kings_template.html~7';
LOI[58] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~35~images/bible_images/Kings/kings_template.html~7';
LOI[59] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~37~images/bible_images/Kings/kings_template.html~7';
LOI[60] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~41~images/bible_images/Kings/kings_template.html~7';
LOI[61] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~42~images/bible_images/Kings/kings_template.html~7';
LOI[62] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~44~images/bible_images/Kings/kings_template.html~7';
LOI[63] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~47~images/bible_images/Kings/kings_template.html~7';
LOI[64] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~48~images/bible_images/Kings/kings_template.html~7';
LOI[65] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~49~images/bible_images/Kings/kings_template.html~7';
LOI[66] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~53~images/bible_images/Kings/kings_template.html~7';
LOI[67] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~54~images/bible_images/Kings/kings_template.html~7';
LOI[68] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~55~images/bible_images/Kings/kings_template.html~7';
LOI[69] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~56~images/bible_images/Kings/kings_template.html~7';
LOI[70] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~58~images/bible_images/Kings/kings_template.html~7';
LOI[71] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~59~images/bible_images/Kings/kings_template.html~7';
LOI[72] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~60~images/bible_images/Kings/kings_template.html~7';
LOI[73] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~61~images/bible_images/Kings/kings_template.html~7';
LOI[74] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~51~64~images/bible_images/Kings/kings_template.html~7';
LOI[75] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Jer~51~11~images/bible_images/Temple/temple_template.html~1';
LOI[76] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Jer~51~11~images/bible_images/Temple/temple_template.html~2';
