var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~1~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~2~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~3~images/maps/Otest/otest_template.html~1a';
LOI[3] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~6~images/maps/Otest/otest_template.html~1a';
LOI[4] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~7~images/maps/Otest/otest_template.html~1a';
LOI[5] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~8~images/maps/Otest/otest_template.html~1a';
LOI[6] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~9~images/maps/Otest/otest_template.html~1a';
LOI[7] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~10~images/maps/Otest/otest_template.html~1a';
LOI[8] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~11~images/maps/Otest/otest_template.html~1a';
LOI[9] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~12~images/maps/Otest/otest_template.html~1a';
LOI[10] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~13~images/maps/Otest/otest_template.html~1a';
LOI[11] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~14~images/maps/Otest/otest_template.html~1a';
LOI[12] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~15~images/maps/Otest/otest_template.html~1a';
LOI[13] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~16~images/maps/Otest/otest_template.html~1a';
LOI[14] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~Jer~41~18~images/maps/Otest/otest_template.html~1a';
LOI[15] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~41~9~images/maps/Otest/otest_template.html~1b';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~41~9~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jer~41~5~images/maps/Otest/otest_template.html~2';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~41~9~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~41~9~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~Jer~41~17~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~41~17~images/maps/Otest/otest_template.html~5';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~41~9~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Jer~41~5~images/maps/Christ/christ_template.html~1';
LOI[24] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~41~2~images/bible_images/Kings/kings_template.html~7';
LOI[25] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~41~18~images/bible_images/Kings/kings_template.html~7';
