var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~27~4~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Jer~27~21~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~27~1~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~27~3~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~27~12~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~27~18~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~27~20~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~27~4~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Jer~27~21~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~27~1~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~27~3~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~27~12~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~27~18~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~27~20~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~27~3~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~27~18~images/maps/Otest/otest_template.html~3a';
LOI[16] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~27~20~images/maps/Otest/otest_template.html~3a';
LOI[17] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~27~21~images/maps/Otest/otest_template.html~3a';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~27~3~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~27~18~images/maps/Otest/otest_template.html~3b';
LOI[20] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~27~20~images/maps/Otest/otest_template.html~3b';
LOI[21] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~27~21~images/maps/Otest/otest_template.html~3b';
LOI[22] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~27~4~images/maps/Otest/otest_template.html~3c';
LOI[23] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~27~21~images/maps/Otest/otest_template.html~3c';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~27~4~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jerusalem~~~~Jer~27~21~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem,Moab~~~~Jer~27~3~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~27~18~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~27~20~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~27~4~images/maps/Christ/christ_template.html~1';
LOI[30] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~27~21~images/maps/Christ/christ_template.html~1';
LOI[31] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~27~3~images/places/Israel/israel_template.html~11';
LOI[32] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~27~18~images/places/Israel/israel_template.html~11';
LOI[33] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~27~20~images/places/Israel/israel_template.html~11';
LOI[34] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~27~21~images/places/Israel/israel_template.html~11';
LOI[35] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~27~3~images/places/Israel/israel_template.html~12';
LOI[36] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~27~18~images/places/Israel/israel_template.html~12';
LOI[37] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~27~20~images/places/Israel/israel_template.html~12';
LOI[38] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~27~21~images/places/Israel/israel_template.html~12';
LOI[39] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~27~3~images/places/Israel/israel_template.html~13';
LOI[40] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~27~18~images/places/Israel/israel_template.html~13';
LOI[41] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~27~20~images/places/Israel/israel_template.html~13';
LOI[42] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~27~21~images/places/Israel/israel_template.html~13';
LOI[43] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~27~3~images/places/Israel/israel_template.html~14';
LOI[44] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~27~18~images/places/Israel/israel_template.html~14';
LOI[45] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~27~20~images/places/Israel/israel_template.html~14';
LOI[46] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~27~21~images/places/Israel/israel_template.html~14';
LOI[47] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~27~3~images/places/Israel/israel_template.html~17';
LOI[48] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~27~18~images/places/Israel/israel_template.html~17';
LOI[49] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~27~20~images/places/Israel/israel_template.html~17';
LOI[50] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~27~21~images/places/Israel/israel_template.html~17';
LOI[51] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving) key=Jehoiakim~~~~Jer~27~1~images/bible_images/Kings/kings_template.html~6';
LOI[52] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving) key=Jehoiakim~~~~Jer~27~20~images/bible_images/Kings/kings_template.html~6';
LOI[53] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~1~images/bible_images/Kings/kings_template.html~7';
LOI[54] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~2~images/bible_images/Kings/kings_template.html~7';
LOI[55] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~3~images/bible_images/Kings/kings_template.html~7';
LOI[56] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~4~images/bible_images/Kings/kings_template.html~7';
LOI[57] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~5~images/bible_images/Kings/kings_template.html~7';
LOI[58] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~6~images/bible_images/Kings/kings_template.html~7';
LOI[59] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~7~images/bible_images/Kings/kings_template.html~7';
LOI[60] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~8~images/bible_images/Kings/kings_template.html~7';
LOI[61] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~9~images/bible_images/Kings/kings_template.html~7';
LOI[62] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~10~images/bible_images/Kings/kings_template.html~7';
LOI[63] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~11~images/bible_images/Kings/kings_template.html~7';
LOI[64] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~12~images/bible_images/Kings/kings_template.html~7';
LOI[65] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~13~images/bible_images/Kings/kings_template.html~7';
LOI[66] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~14~images/bible_images/Kings/kings_template.html~7';
LOI[67] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~15~images/bible_images/Kings/kings_template.html~7';
LOI[68] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~16~images/bible_images/Kings/kings_template.html~7';
LOI[69] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~17~images/bible_images/Kings/kings_template.html~7';
LOI[70] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~18~images/bible_images/Kings/kings_template.html~7';
LOI[71] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~19~images/bible_images/Kings/kings_template.html~7';
LOI[72] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~20~images/bible_images/Kings/kings_template.html~7';
LOI[73] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~21~images/bible_images/Kings/kings_template.html~7';
LOI[74] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~27~22~images/bible_images/Kings/kings_template.html~7';
LOI[75] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~1~images/bible_images/Kings/kings_template.html~8';
LOI[76] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~2~images/bible_images/Kings/kings_template.html~8';
LOI[77] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~3~images/bible_images/Kings/kings_template.html~8';
LOI[78] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~4~images/bible_images/Kings/kings_template.html~8';
LOI[79] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~5~images/bible_images/Kings/kings_template.html~8';
LOI[80] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~6~images/bible_images/Kings/kings_template.html~8';
LOI[81] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~7~images/bible_images/Kings/kings_template.html~8';
LOI[82] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~8~images/bible_images/Kings/kings_template.html~8';
LOI[83] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~9~images/bible_images/Kings/kings_template.html~8';
LOI[84] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~10~images/bible_images/Kings/kings_template.html~8';
LOI[85] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~11~images/bible_images/Kings/kings_template.html~8';
LOI[86] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~12~images/bible_images/Kings/kings_template.html~8';
LOI[87] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~13~images/bible_images/Kings/kings_template.html~8';
LOI[88] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~14~images/bible_images/Kings/kings_template.html~8';
LOI[89] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~15~images/bible_images/Kings/kings_template.html~8';
LOI[90] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~16~images/bible_images/Kings/kings_template.html~8';
LOI[91] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~17~images/bible_images/Kings/kings_template.html~8';
LOI[92] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~18~images/bible_images/Kings/kings_template.html~8';
LOI[93] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~19~images/bible_images/Kings/kings_template.html~8';
LOI[94] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~20~images/bible_images/Kings/kings_template.html~8';
LOI[95] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~21~images/bible_images/Kings/kings_template.html~8';
LOI[96] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~27~22~images/bible_images/Kings/kings_template.html~8';
LOI[97] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~Jer~27~6~images/bible_images/Daniel/daniel_template.html~1';
LOI[98] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~Jer~27~8~images/bible_images/Daniel/daniel_template.html~1';
LOI[99] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~Jer~27~20~images/bible_images/Daniel/daniel_template.html~1';
LOI[100] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Nebuchadnezzar~~~~Jer~27~6~images/bible_images/Daniel/daniel_template.html~3';
LOI[101] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Nebuchadnezzar~~~~Jer~27~8~images/bible_images/Daniel/daniel_template.html~3';
LOI[102] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Nebuchadnezzar~~~~Jer~27~20~images/bible_images/Daniel/daniel_template.html~3';
