var LOI = [];
LOI[0] = 'hymn~13~HO! YE THAT THIRST, APPROACH THE SPRING~htm_h_y_hyettats.html';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~17~13~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~17~1~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~17~19~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~17~20~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~17~25~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah,Benjamin~~~~Jer~17~26~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~17~13~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~17~1~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~17~19~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~17~20~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~17~25~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah,Benjamin~~~~Jer~17~26~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~17~19~images/maps/Otest/otest_template.html~3a';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~17~20~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~17~21~images/maps/Otest/otest_template.html~3a';
LOI[16] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~17~25~images/maps/Otest/otest_template.html~3a';
LOI[17] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~17~26~images/maps/Otest/otest_template.html~3a';
LOI[18] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~17~27~images/maps/Otest/otest_template.html~3a';
LOI[19] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~17~19~images/maps/Otest/otest_template.html~3b';
LOI[20] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~17~20~images/maps/Otest/otest_template.html~3b';
LOI[21] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~17~21~images/maps/Otest/otest_template.html~3b';
LOI[22] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~17~25~images/maps/Otest/otest_template.html~3b';
LOI[23] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~17~26~images/maps/Otest/otest_template.html~3b';
LOI[24] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~17~27~images/maps/Otest/otest_template.html~3b';
LOI[25] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~17~13~images/maps/Otest/otest_template.html~3c';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~17~13~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~17~19~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~17~20~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~17~21~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~17~25~images/maps/Otest/otest_template.html~4';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~17~26~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~17~27~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~17~13~images/maps/Christ/christ_template.html~1';
LOI[34] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~17~19~images/places/Israel/israel_template.html~11';
LOI[35] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~17~20~images/places/Israel/israel_template.html~11';
LOI[36] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~17~21~images/places/Israel/israel_template.html~11';
LOI[37] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~17~25~images/places/Israel/israel_template.html~11';
LOI[38] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~17~26~images/places/Israel/israel_template.html~11';
LOI[39] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~17~27~images/places/Israel/israel_template.html~11';
LOI[40] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~17~19~images/places/Israel/israel_template.html~12';
LOI[41] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~17~20~images/places/Israel/israel_template.html~12';
LOI[42] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~17~21~images/places/Israel/israel_template.html~12';
LOI[43] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~17~25~images/places/Israel/israel_template.html~12';
LOI[44] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~17~26~images/places/Israel/israel_template.html~12';
LOI[45] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~17~27~images/places/Israel/israel_template.html~12';
LOI[46] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~17~19~images/places/Israel/israel_template.html~13';
LOI[47] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~17~20~images/places/Israel/israel_template.html~13';
LOI[48] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~17~21~images/places/Israel/israel_template.html~13';
LOI[49] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~17~25~images/places/Israel/israel_template.html~13';
LOI[50] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~17~26~images/places/Israel/israel_template.html~13';
LOI[51] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~17~27~images/places/Israel/israel_template.html~13';
LOI[52] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~17~19~images/places/Israel/israel_template.html~14';
LOI[53] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~17~20~images/places/Israel/israel_template.html~14';
LOI[54] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~17~21~images/places/Israel/israel_template.html~14';
LOI[55] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~17~25~images/places/Israel/israel_template.html~14';
LOI[56] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~17~26~images/places/Israel/israel_template.html~14';
LOI[57] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~17~27~images/places/Israel/israel_template.html~14';
LOI[58] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~17~19~images/places/Israel/israel_template.html~17';
LOI[59] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~17~20~images/places/Israel/israel_template.html~17';
LOI[60] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~17~21~images/places/Israel/israel_template.html~17';
LOI[61] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~17~25~images/places/Israel/israel_template.html~17';
LOI[62] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~17~26~images/places/Israel/israel_template.html~17';
LOI[63] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~17~27~images/places/Israel/israel_template.html~17';
LOI[64] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Jer~17~25~images/bible_images/Kings/kings_template.html~1';
LOI[65] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Jer~17~25~images/bible_images/Kings/kings_template.html~2';
