var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~1~2~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~1~3~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~1~15~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~1~18~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~Jer~1~1~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~1~2~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~1~3~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~1~15~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~1~18~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~Jer~1~1~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~1~3~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~1~15~images/maps/Otest/otest_template.html~3a';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~1~3~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~1~15~images/maps/Otest/otest_template.html~3b';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~1~3~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~1~15~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~1~3~images/places/Israel/israel_template.html~11';
LOI[17] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~1~15~images/places/Israel/israel_template.html~11';
LOI[18] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~1~3~images/places/Israel/israel_template.html~12';
LOI[19] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~1~15~images/places/Israel/israel_template.html~12';
LOI[20] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~1~3~images/places/Israel/israel_template.html~13';
LOI[21] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~1~15~images/places/Israel/israel_template.html~13';
LOI[22] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~1~3~images/places/Israel/israel_template.html~14';
LOI[23] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~1~15~images/places/Israel/israel_template.html~14';
LOI[24] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~1~3~images/places/Israel/israel_template.html~17';
LOI[25] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~1~15~images/places/Israel/israel_template.html~17';
LOI[26] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~1~1~images/bible_images/Kings/kings_template.html~6';
LOI[27] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~1~2~images/bible_images/Kings/kings_template.html~6';
LOI[28] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~1~3~images/bible_images/Kings/kings_template.html~6';
