var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~38~17~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~Jer~38~7~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~38~17~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~Jer~38~7~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~38~28~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~38~28~images/maps/Otest/otest_template.html~3b';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~38~17~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~38~17~images/maps/Otest/otest_template.html~4';
LOI[8] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~38~28~images/maps/Otest/otest_template.html~4';
LOI[9] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~38~17~images/maps/Christ/christ_template.html~1';
LOI[10] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~38~28~images/places/Israel/israel_template.html~11';
LOI[11] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~38~28~images/places/Israel/israel_template.html~12';
LOI[12] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~38~28~images/places/Israel/israel_template.html~13';
LOI[13] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~38~28~images/places/Israel/israel_template.html~14';
LOI[14] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~38~28~images/places/Israel/israel_template.html~17';
LOI[15] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~38~23~images/bible_images/Kings/kings_template.html~7';
