var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~48~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~48~13~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~48~27~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~48~1~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~48~13~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~48~27~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~48~1~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~48~13~images/maps/Otest/otest_template.html~3c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~48~27~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map)~~~~Jer~48~1~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Moab~~~~Jer~48~13~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~48~27~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~2~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~4~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~9~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~11~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~15~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~16~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~18~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~20~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~24~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~25~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~26~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~28~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~29~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~31~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~33~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~35~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~36~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~38~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~39~images/maps/Otest/otest_template.html~4';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~40~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~41~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~42~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~43~images/maps/Otest/otest_template.html~4';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~44~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~45~images/maps/Otest/otest_template.html~4';
LOI[37] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~46~images/maps/Otest/otest_template.html~4';
LOI[38] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Jer~48~47~images/maps/Otest/otest_template.html~4';
LOI[39] = 'image~Bible~Maps~Southern Palestine (map) key=Nebo~~~~Jer~48~22~images/maps/Otest/otest_template.html~4';
LOI[40] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~48~1~images/maps/Christ/christ_template.html~1';
LOI[41] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~48~13~images/maps/Christ/christ_template.html~1';
LOI[42] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~48~27~images/maps/Christ/christ_template.html~1';
LOI[43] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Nebo~~~~Jer~48~1~images/bible_images/Moses/moses_template.html~10';
LOI[44] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Nebo~~~~Jer~48~22~images/bible_images/Moses/moses_template.html~10';
LOI[45] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Nebo~~~~Jer~48~1~images/bible_images/Moses/moses_template.html~11';
LOI[46] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Nebo~~~~Jer~48~22~images/bible_images/Moses/moses_template.html~11';
