var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~21~4~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~21~7~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~21~11~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~21~4~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~21~7~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~21~11~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~21~4~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~21~4~images/maps/Otest/otest_template.html~4';
LOI[8] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~21~4~images/maps/Christ/christ_template.html~1';
LOI[9] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Jer~21~12~images/bible_images/Kings/kings_template.html~1';
LOI[10] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Jer~21~12~images/bible_images/Kings/kings_template.html~2';
LOI[11] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~21~1~images/bible_images/Kings/kings_template.html~7';
LOI[12] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~21~2~images/bible_images/Kings/kings_template.html~7';
LOI[13] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~21~3~images/bible_images/Kings/kings_template.html~7';
LOI[14] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~21~4~images/bible_images/Kings/kings_template.html~7';
LOI[15] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~21~5~images/bible_images/Kings/kings_template.html~7';
LOI[16] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~21~6~images/bible_images/Kings/kings_template.html~7';
LOI[17] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~21~7~images/bible_images/Kings/kings_template.html~7';
LOI[18] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~21~8~images/bible_images/Kings/kings_template.html~7';
LOI[19] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~21~9~images/bible_images/Kings/kings_template.html~7';
LOI[20] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~21~10~images/bible_images/Kings/kings_template.html~7';
LOI[21] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~21~11~images/bible_images/Kings/kings_template.html~7';
LOI[22] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~21~12~images/bible_images/Kings/kings_template.html~7';
LOI[23] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~21~13~images/bible_images/Kings/kings_template.html~7';
LOI[24] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~21~14~images/bible_images/Kings/kings_template.html~7';
