var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~43~10~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~43~4~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~43~5~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~43~9~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~43~10~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~43~4~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~43~5~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~43~9~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~43~10~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~43~10~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~43~2~images/maps/Otest/otest_template.html~5';
LOI[11] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~43~7~images/maps/Otest/otest_template.html~5';
LOI[12] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~43~11~images/maps/Otest/otest_template.html~5';
LOI[13] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~43~12~images/maps/Otest/otest_template.html~5';
LOI[14] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~43~13~images/maps/Otest/otest_template.html~5';
LOI[15] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~43~10~images/maps/Christ/christ_template.html~1';
LOI[16] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~43~3~images/bible_images/Kings/kings_template.html~7';
LOI[17] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~43~10~images/bible_images/Kings/kings_template.html~7';
