var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~3~6~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Jer~3~8~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Jer~3~11~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~3~12~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Jer~3~18~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~3~20~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~3~21~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~3~23~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~3~7~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~3~10~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~3~6~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Jer~3~8~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Jer~3~11~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~3~12~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Jer~3~18~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~3~20~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~3~21~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~3~23~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~3~7~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~3~10~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~3~17~images/maps/Otest/otest_template.html~3a';
LOI[21] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Jer~3~14~images/maps/Otest/otest_template.html~3a';
LOI[22] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~3~17~images/maps/Otest/otest_template.html~3b';
LOI[23] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Jer~3~14~images/maps/Otest/otest_template.html~3b';
LOI[24] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~3~6~images/maps/Otest/otest_template.html~3c';
LOI[25] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~3~8~images/maps/Otest/otest_template.html~3c';
LOI[26] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~3~11~images/maps/Otest/otest_template.html~3c';
LOI[27] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~3~12~images/maps/Otest/otest_template.html~3c';
LOI[28] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~3~18~images/maps/Otest/otest_template.html~3c';
LOI[29] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~3~20~images/maps/Otest/otest_template.html~3c';
LOI[30] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~3~21~images/maps/Otest/otest_template.html~3c';
LOI[31] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~3~23~images/maps/Otest/otest_template.html~3c';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~3~6~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~3~8~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~3~11~images/maps/Otest/otest_template.html~4';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~3~12~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~3~18~images/maps/Otest/otest_template.html~4';
LOI[37] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~3~20~images/maps/Otest/otest_template.html~4';
LOI[38] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~3~21~images/maps/Otest/otest_template.html~4';
LOI[39] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~3~23~images/maps/Otest/otest_template.html~4';
LOI[40] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~3~17~images/maps/Otest/otest_template.html~4';
LOI[41] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~3~6~images/maps/Christ/christ_template.html~1';
LOI[42] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~3~8~images/maps/Christ/christ_template.html~1';
LOI[43] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~3~11~images/maps/Christ/christ_template.html~1';
LOI[44] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~3~12~images/maps/Christ/christ_template.html~1';
LOI[45] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~3~18~images/maps/Christ/christ_template.html~1';
LOI[46] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~3~20~images/maps/Christ/christ_template.html~1';
LOI[47] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~3~21~images/maps/Christ/christ_template.html~1';
LOI[48] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~3~23~images/maps/Christ/christ_template.html~1';
LOI[49] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~3~17~images/places/Israel/israel_template.html~11';
LOI[50] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~3~17~images/places/Israel/israel_template.html~12';
LOI[51] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~3~17~images/places/Israel/israel_template.html~13';
LOI[52] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~3~17~images/places/Israel/israel_template.html~14';
LOI[53] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~3~17~images/places/Israel/israel_template.html~17';
LOI[54] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Jer~3~16~images/bible_images/Temple/temple_template.html~4';
