var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~22~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~22~2~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~22~6~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~22~11~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~22~18~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~22~24~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~22~30~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~22~1~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~22~2~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~22~6~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~22~11~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~22~18~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~22~24~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~22~30~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~22~19~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~22~19~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~Jer~22~6~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~22~19~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~Jer~22~6~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Divisions of Palestine (map) key=Bashan~~~~Jer~22~20~images/maps/Christ/christ_template.html~1';
LOI[20] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~22~19~images/places/Israel/israel_template.html~11';
LOI[21] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~22~19~images/places/Israel/israel_template.html~12';
LOI[22] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~22~19~images/places/Israel/israel_template.html~13';
LOI[23] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~22~19~images/places/Israel/israel_template.html~14';
LOI[24] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~22~19~images/places/Israel/israel_template.html~17';
LOI[25] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Jer~22~2~images/bible_images/Kings/kings_template.html~1';
LOI[26] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Jer~22~4~images/bible_images/Kings/kings_template.html~1';
LOI[27] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Jer~22~30~images/bible_images/Kings/kings_template.html~1';
LOI[28] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Jer~22~2~images/bible_images/Kings/kings_template.html~2';
LOI[29] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Jer~22~4~images/bible_images/Kings/kings_template.html~2';
LOI[30] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Jer~22~30~images/bible_images/Kings/kings_template.html~2';
LOI[31] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~22~18~images/bible_images/Kings/kings_template.html~6';
LOI[32] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~22~19~images/bible_images/Kings/kings_template.html~6';
LOI[33] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~22~20~images/bible_images/Kings/kings_template.html~6';
LOI[34] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~22~21~images/bible_images/Kings/kings_template.html~6';
LOI[35] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~22~22~images/bible_images/Kings/kings_template.html~6';
LOI[36] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~22~23~images/bible_images/Kings/kings_template.html~6';
LOI[37] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~22~24~images/bible_images/Kings/kings_template.html~6';
LOI[38] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~22~25~images/bible_images/Kings/kings_template.html~6';
LOI[39] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~22~26~images/bible_images/Kings/kings_template.html~6';
LOI[40] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~22~27~images/bible_images/Kings/kings_template.html~6';
LOI[41] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~22~28~images/bible_images/Kings/kings_template.html~6';
LOI[42] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~22~29~images/bible_images/Kings/kings_template.html~6';
LOI[43] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~22~30~images/bible_images/Kings/kings_template.html~6';
LOI[44] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~22~25~images/bible_images/Kings/kings_template.html~7';
