var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~32~14~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~32~15~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~32~20~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~32~21~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Jer~32~30~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Jer~32~32~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~32~36~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~32~1~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~32~3~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~32~4~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~32~35~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah,Benjamin~~~~Jer~32~44~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~Jer~32~8~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~32~14~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~32~15~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~32~20~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~32~21~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Jer~32~30~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Jer~32~32~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~32~36~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~32~1~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~32~3~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~32~4~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~32~35~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah,Benjamin~~~~Jer~32~44~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~Jer~32~8~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~32~2~images/maps/Otest/otest_template.html~3a';
LOI[27] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~32~32~images/maps/Otest/otest_template.html~3a';
LOI[28] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~32~44~images/maps/Otest/otest_template.html~3a';
LOI[29] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Hinnom~~~~Jer~32~35~images/maps/Otest/otest_template.html~3a';
LOI[30] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~32~2~images/maps/Otest/otest_template.html~3b';
LOI[31] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~32~32~images/maps/Otest/otest_template.html~3b';
LOI[32] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~32~44~images/maps/Otest/otest_template.html~3b';
LOI[33] = 'image~Bible~Maps~Modern Jerusalem (map) key=Hinnom~~~~Jer~32~35~images/maps/Otest/otest_template.html~3b';
LOI[34] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~32~14~images/maps/Otest/otest_template.html~3c';
LOI[35] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~32~15~images/maps/Otest/otest_template.html~3c';
LOI[36] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~32~20~images/maps/Otest/otest_template.html~3c';
LOI[37] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~32~21~images/maps/Otest/otest_template.html~3c';
LOI[38] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~32~30~images/maps/Otest/otest_template.html~3c';
LOI[39] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~32~32~images/maps/Otest/otest_template.html~3c';
LOI[40] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~32~36~images/maps/Otest/otest_template.html~3c';
LOI[41] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~32~14~images/maps/Otest/otest_template.html~4';
LOI[42] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~32~15~images/maps/Otest/otest_template.html~4';
LOI[43] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~32~20~images/maps/Otest/otest_template.html~4';
LOI[44] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~32~21~images/maps/Otest/otest_template.html~4';
LOI[45] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~32~30~images/maps/Otest/otest_template.html~4';
LOI[46] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jerusalem~~~~Jer~32~32~images/maps/Otest/otest_template.html~4';
LOI[47] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~32~36~images/maps/Otest/otest_template.html~4';
LOI[48] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~32~2~images/maps/Otest/otest_template.html~4';
LOI[49] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~32~44~images/maps/Otest/otest_template.html~4';
LOI[50] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~32~20~images/maps/Otest/otest_template.html~5';
LOI[51] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~32~21~images/maps/Otest/otest_template.html~5';
LOI[52] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~32~14~images/maps/Christ/christ_template.html~1';
LOI[53] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~32~15~images/maps/Christ/christ_template.html~1';
LOI[54] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~32~20~images/maps/Christ/christ_template.html~1';
LOI[55] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~32~21~images/maps/Christ/christ_template.html~1';
LOI[56] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~32~30~images/maps/Christ/christ_template.html~1';
LOI[57] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~32~32~images/maps/Christ/christ_template.html~1';
LOI[58] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~32~36~images/maps/Christ/christ_template.html~1';
LOI[59] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~32~2~images/places/Israel/israel_template.html~11';
LOI[60] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~32~32~images/places/Israel/israel_template.html~11';
LOI[61] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~32~44~images/places/Israel/israel_template.html~11';
LOI[62] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~32~2~images/places/Israel/israel_template.html~12';
LOI[63] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~32~32~images/places/Israel/israel_template.html~12';
LOI[64] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~32~44~images/places/Israel/israel_template.html~12';
LOI[65] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~32~2~images/places/Israel/israel_template.html~13';
LOI[66] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~32~32~images/places/Israel/israel_template.html~13';
LOI[67] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~32~44~images/places/Israel/israel_template.html~13';
LOI[68] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~32~2~images/places/Israel/israel_template.html~14';
LOI[69] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~32~32~images/places/Israel/israel_template.html~14';
LOI[70] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~32~44~images/places/Israel/israel_template.html~14';
LOI[71] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~32~2~images/places/Israel/israel_template.html~17';
LOI[72] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~32~32~images/places/Israel/israel_template.html~17';
LOI[73] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~32~44~images/places/Israel/israel_template.html~17';
LOI[74] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~32~24~images/bible_images/Kings/kings_template.html~7';
LOI[75] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~32~25~images/bible_images/Kings/kings_template.html~7';
LOI[76] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~32~26~images/bible_images/Kings/kings_template.html~7';
LOI[77] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~32~27~images/bible_images/Kings/kings_template.html~7';
LOI[78] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~32~28~images/bible_images/Kings/kings_template.html~7';
LOI[79] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~32~29~images/bible_images/Kings/kings_template.html~7';
LOI[80] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~32~30~images/bible_images/Kings/kings_template.html~7';
LOI[81] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~32~31~images/bible_images/Kings/kings_template.html~7';
LOI[82] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~32~32~images/bible_images/Kings/kings_template.html~7';
LOI[83] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~32~33~images/bible_images/Kings/kings_template.html~7';
LOI[84] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~32~34~images/bible_images/Kings/kings_template.html~7';
LOI[85] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~32~35~images/bible_images/Kings/kings_template.html~7';
LOI[86] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Jer~32~36~images/bible_images/Kings/kings_template.html~7';
LOI[87] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~32~3~images/bible_images/Kings/kings_template.html~7';
LOI[88] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~32~4~images/bible_images/Kings/kings_template.html~7';
LOI[89] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~32~5~images/bible_images/Kings/kings_template.html~7';
LOI[90] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~32~24~images/bible_images/Kings/kings_template.html~8';
LOI[91] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~32~25~images/bible_images/Kings/kings_template.html~8';
LOI[92] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~32~26~images/bible_images/Kings/kings_template.html~8';
LOI[93] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~32~27~images/bible_images/Kings/kings_template.html~8';
LOI[94] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~32~28~images/bible_images/Kings/kings_template.html~8';
LOI[95] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~32~29~images/bible_images/Kings/kings_template.html~8';
LOI[96] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~32~30~images/bible_images/Kings/kings_template.html~8';
LOI[97] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~32~31~images/bible_images/Kings/kings_template.html~8';
LOI[98] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~32~32~images/bible_images/Kings/kings_template.html~8';
LOI[99] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~32~33~images/bible_images/Kings/kings_template.html~8';
LOI[100] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~32~34~images/bible_images/Kings/kings_template.html~8';
LOI[101] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~32~35~images/bible_images/Kings/kings_template.html~8';
LOI[102] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Jer~32~36~images/bible_images/Kings/kings_template.html~8';
