var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~26~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~26~2~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~26~10~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~26~18~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~26~19~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~26~1~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~26~2~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~26~10~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~26~18~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~26~19~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Zion~~~~Jer~26~18~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Zion~~~~Jer~26~18~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~26~18~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~26~21~images/maps/Otest/otest_template.html~5';
LOI[14] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~26~22~images/maps/Otest/otest_template.html~5';
LOI[15] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~26~23~images/maps/Otest/otest_template.html~5';
LOI[16] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~26~18~images/places/Israel/israel_template.html~11';
LOI[17] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~26~18~images/places/Israel/israel_template.html~12';
LOI[18] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~26~18~images/places/Israel/israel_template.html~13';
LOI[19] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~26~18~images/places/Israel/israel_template.html~14';
LOI[20] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~26~18~images/places/Israel/israel_template.html~17';
LOI[21] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~1~images/bible_images/Kings/kings_template.html~6';
LOI[22] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~2~images/bible_images/Kings/kings_template.html~6';
LOI[23] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~3~images/bible_images/Kings/kings_template.html~6';
LOI[24] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~4~images/bible_images/Kings/kings_template.html~6';
LOI[25] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~5~images/bible_images/Kings/kings_template.html~6';
LOI[26] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~6~images/bible_images/Kings/kings_template.html~6';
LOI[27] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~7~images/bible_images/Kings/kings_template.html~6';
LOI[28] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~8~images/bible_images/Kings/kings_template.html~6';
LOI[29] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~9~images/bible_images/Kings/kings_template.html~6';
LOI[30] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~10~images/bible_images/Kings/kings_template.html~6';
LOI[31] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~11~images/bible_images/Kings/kings_template.html~6';
LOI[32] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~12~images/bible_images/Kings/kings_template.html~6';
LOI[33] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~13~images/bible_images/Kings/kings_template.html~6';
LOI[34] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~14~images/bible_images/Kings/kings_template.html~6';
LOI[35] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~15~images/bible_images/Kings/kings_template.html~6';
LOI[36] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~16~images/bible_images/Kings/kings_template.html~6';
LOI[37] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~17~images/bible_images/Kings/kings_template.html~6';
LOI[38] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~18~images/bible_images/Kings/kings_template.html~6';
LOI[39] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~19~images/bible_images/Kings/kings_template.html~6';
LOI[40] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~20~images/bible_images/Kings/kings_template.html~6';
LOI[41] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~21~images/bible_images/Kings/kings_template.html~6';
LOI[42] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~22~images/bible_images/Kings/kings_template.html~6';
LOI[43] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~23~images/bible_images/Kings/kings_template.html~6';
LOI[44] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving)~~~~Jer~26~24~images/bible_images/Kings/kings_template.html~6';
