var LOI = [];
LOI[0] = 'hymn~5~COME, LET US JOIN WITH FAITHFUL SOULS~htm_c_o_comeleus.html';
LOI[1] = 'hymn~5~COME, LET US USE THE GRACE DIVINE~htm_c_o_comletus.html';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Jer~50~4~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~50~17~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~50~18~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Ephraim~~~~Jer~50~19~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Jer~50~20~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~50~29~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Jer~50~33~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Jer~50~4~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~50~17~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~50~18~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Ephraim~~~~Jer~50~19~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Jer~50~20~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~50~29~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Jer~50~33~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple,Zion~~~~Jer~50~28~images/maps/Otest/otest_template.html~3a';
LOI[17] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Jer~50~5~images/maps/Otest/otest_template.html~3a';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple,Zion~~~~Jer~50~28~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Jer~50~5~images/maps/Otest/otest_template.html~3b';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~50~4~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~50~17~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~50~18~images/maps/Otest/otest_template.html~3c';
LOI[23] = 'image~Bible~Maps~Middle Palestine (map)~~~~Jer~50~19~images/maps/Otest/otest_template.html~3c';
LOI[24] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~50~20~images/maps/Otest/otest_template.html~3c';
LOI[25] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~50~29~images/maps/Otest/otest_template.html~3c';
LOI[26] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~50~33~images/maps/Otest/otest_template.html~3c';
LOI[27] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Jer~50~44~images/maps/Otest/otest_template.html~3c';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~50~4~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~50~17~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~50~18~images/maps/Otest/otest_template.html~4';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Gilead~~~~Jer~50~19~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~50~20~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~50~29~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~50~33~images/maps/Otest/otest_template.html~4';
LOI[35] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~50~4~images/maps/Christ/christ_template.html~1';
LOI[36] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~50~17~images/maps/Christ/christ_template.html~1';
LOI[37] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~50~18~images/maps/Christ/christ_template.html~1';
LOI[38] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel,Bashan~~~~Jer~50~19~images/maps/Christ/christ_template.html~1';
LOI[39] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~50~20~images/maps/Christ/christ_template.html~1';
LOI[40] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~50~29~images/maps/Christ/christ_template.html~1';
LOI[41] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~50~33~images/maps/Christ/christ_template.html~1';
LOI[42] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~1~images/bible_images/Kings/kings_template.html~7';
LOI[43] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~2~images/bible_images/Kings/kings_template.html~7';
LOI[44] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~8~images/bible_images/Kings/kings_template.html~7';
LOI[45] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~9~images/bible_images/Kings/kings_template.html~7';
LOI[46] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~13~images/bible_images/Kings/kings_template.html~7';
LOI[47] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~14~images/bible_images/Kings/kings_template.html~7';
LOI[48] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~16~images/bible_images/Kings/kings_template.html~7';
LOI[49] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~17~images/bible_images/Kings/kings_template.html~7';
LOI[50] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~18~images/bible_images/Kings/kings_template.html~7';
LOI[51] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~23~images/bible_images/Kings/kings_template.html~7';
LOI[52] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~24~images/bible_images/Kings/kings_template.html~7';
LOI[53] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~28~images/bible_images/Kings/kings_template.html~7';
LOI[54] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~29~images/bible_images/Kings/kings_template.html~7';
LOI[55] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~34~images/bible_images/Kings/kings_template.html~7';
LOI[56] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~35~images/bible_images/Kings/kings_template.html~7';
LOI[57] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~42~images/bible_images/Kings/kings_template.html~7';
LOI[58] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~43~images/bible_images/Kings/kings_template.html~7';
LOI[59] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~45~images/bible_images/Kings/kings_template.html~7';
LOI[60] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~50~46~images/bible_images/Kings/kings_template.html~7';
LOI[61] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Jer~50~28~images/bible_images/Temple/temple_template.html~1';
LOI[62] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Jer~50~28~images/bible_images/Temple/temple_template.html~2';
