var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Jer~19~3~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~19~15~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~19~4~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~19~7~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~19~13~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Jer~19~3~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~19~15~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~19~4~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~19~7~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~19~13~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~19~3~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~19~7~images/maps/Otest/otest_template.html~3a';
LOI[12] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~19~13~images/maps/Otest/otest_template.html~3a';
LOI[13] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Hinnom~~~~Jer~19~2~images/maps/Otest/otest_template.html~3a';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Hinnom~~~~Jer~19~6~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~19~3~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~19~7~images/maps/Otest/otest_template.html~3b';
LOI[17] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~19~13~images/maps/Otest/otest_template.html~3b';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Hinnom~~~~Jer~19~2~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Modern Jerusalem (map) key=Hinnom~~~~Jer~19~6~images/maps/Otest/otest_template.html~3b';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~19~3~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~19~15~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jerusalem~~~~Jer~19~3~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~19~15~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~19~7~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~19~13~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~19~3~images/maps/Christ/christ_template.html~1';
LOI[27] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~19~15~images/maps/Christ/christ_template.html~1';
LOI[28] = 'image~Bible~Places~Potter\'s Field (engraving) key=potter\'s~~~~Jer~19~1~images/places/Israel/israel_template.html~3';
LOI[29] = 'image~Bible~Places~Potter\'s Field (engraving) key=potter\'s~~~~Jer~19~11~images/places/Israel/israel_template.html~3';
LOI[30] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~19~3~images/places/Israel/israel_template.html~11';
LOI[31] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~19~7~images/places/Israel/israel_template.html~11';
LOI[32] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~19~13~images/places/Israel/israel_template.html~11';
LOI[33] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~19~3~images/places/Israel/israel_template.html~12';
LOI[34] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~19~7~images/places/Israel/israel_template.html~12';
LOI[35] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~19~13~images/places/Israel/israel_template.html~12';
LOI[36] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~19~3~images/places/Israel/israel_template.html~13';
LOI[37] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~19~7~images/places/Israel/israel_template.html~13';
LOI[38] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~19~13~images/places/Israel/israel_template.html~13';
LOI[39] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~19~3~images/places/Israel/israel_template.html~14';
LOI[40] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~19~7~images/places/Israel/israel_template.html~14';
LOI[41] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~19~13~images/places/Israel/israel_template.html~14';
LOI[42] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~19~3~images/places/Israel/israel_template.html~17';
LOI[43] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~19~7~images/places/Israel/israel_template.html~17';
LOI[44] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~19~13~images/places/Israel/israel_template.html~17';
