var LOI = [];
LOI[0] = 'hymn~11~THERE IS A BALM IN GILEAD~htm_t_i_tisabalm.html';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~46~25~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jer~46~27~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~46~2~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~46~25~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jer~46~27~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~46~2~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~46~25~images/maps/Otest/otest_template.html~3c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jer~46~27~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~Jer~46~11~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Carmel~~~~Jer~46~18~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~46~25~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jer~46~27~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~Jer~46~11~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~46~2~images/maps/Otest/otest_template.html~5';
LOI[15] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~46~8~images/maps/Otest/otest_template.html~5';
LOI[16] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~46~11~images/maps/Otest/otest_template.html~5';
LOI[17] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~46~13~images/maps/Otest/otest_template.html~5';
LOI[18] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~46~14~images/maps/Otest/otest_template.html~5';
LOI[19] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~46~17~images/maps/Otest/otest_template.html~5';
LOI[20] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~46~19~images/maps/Otest/otest_template.html~5';
LOI[21] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~46~20~images/maps/Otest/otest_template.html~5';
LOI[22] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~46~24~images/maps/Otest/otest_template.html~5';
LOI[23] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jer~46~25~images/maps/Otest/otest_template.html~5';
LOI[24] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~46~25~images/maps/Christ/christ_template.html~1';
LOI[25] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jer~46~27~images/maps/Christ/christ_template.html~1';
LOI[26] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Jer~46~17~images/bible_images/Moses/moses_template.html~5';
LOI[27] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Jer~46~25~images/bible_images/Moses/moses_template.html~5';
LOI[28] = 'image~Bible~Images~Jeremiah Before King Jehoiakim (engraving) key=Jehoiakim~~~~Jer~46~2~images/bible_images/Kings/kings_template.html~6';
LOI[29] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~46~2~images/bible_images/Kings/kings_template.html~7';
LOI[30] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~46~13~images/bible_images/Kings/kings_template.html~7';
LOI[31] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Jer~46~26~images/bible_images/Kings/kings_template.html~7';
