var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jer~8~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Dan~~~~Jer~8~16~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jer~8~1~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Dan~~~~Jer~8~16~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~8~1~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jer~8~5~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Jer~8~19~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~8~1~images/maps/Otest/otest_template.html~3b';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jer~8~5~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Jer~8~19~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~Jer~8~22~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~8~1~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jer~8~5~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~Jer~8~22~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~8~1~images/places/Israel/israel_template.html~11';
LOI[15] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jer~8~5~images/places/Israel/israel_template.html~11';
LOI[16] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~8~1~images/places/Israel/israel_template.html~12';
LOI[17] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jer~8~5~images/places/Israel/israel_template.html~12';
LOI[18] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~8~1~images/places/Israel/israel_template.html~13';
LOI[19] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jer~8~5~images/places/Israel/israel_template.html~13';
LOI[20] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~8~1~images/places/Israel/israel_template.html~14';
LOI[21] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jer~8~5~images/places/Israel/israel_template.html~14';
LOI[22] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~8~1~images/places/Israel/israel_template.html~17';
LOI[23] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jer~8~5~images/places/Israel/israel_template.html~17';
