var LOI = [];
LOI[0] = 'hymn~2~NOW THAT THE SUN IS GLEAMING BRIGHT~htm_n_t_ntthesun.html';
LOI[1] = 'hymn~11~I HEAR TEN THOUSAND VOICES SINGING~htm_i_h_ihtentvs.html';
LOI[2] = 'hymn~12~MY GOD, AND IS THY TABLE SPREAD~htm_m_g_mgttanis.html';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Mal~1~1~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Mal~1~5~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Mal~1~1~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Mal~1~5~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Mal~1~1~images/maps/Otest/otest_template.html~3c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Mal~1~5~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Mal~1~1~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Mal~1~5~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Mal~1~1~images/maps/Christ/christ_template.html~1';
LOI[12] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Mal~1~5~images/maps/Christ/christ_template.html~1';
