var LOI = [];
LOI[0] = 'hymn~6~ROLL OUT, O SONG, TO GOD!~htm_r_o_rollouto.html';
LOI[1] = 'hymn~6~&#8217;TWIXT GLEAMS OF JOY AND CLOUDS OF DOUBT~htm_t_w_twixtgoj.html';
LOI[2] = 'hymn~6~THE YEAR IS SWIFTLY WANING~htm_y_e_yearswif.html';
LOI[3] = 'hymn~17~WHEN HE COMETH~htm_w_h_whenheco.html';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Levi~~~~Mal~3~3~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Mal~3~4~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Levi~~~~Mal~3~3~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Mal~3~4~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Mal~3~4~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Mal~3~1~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Mal~3~4~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Mal~3~1~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Mal~3~4~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Mal~3~4~images/places/Israel/israel_template.html~11';
LOI[14] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Mal~3~4~images/places/Israel/israel_template.html~12';
LOI[15] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Mal~3~4~images/places/Israel/israel_template.html~13';
LOI[16] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Mal~3~4~images/places/Israel/israel_template.html~14';
LOI[17] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Mal~3~4~images/places/Israel/israel_template.html~17';
LOI[18] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Mal~3~1~images/bible_images/Temple/temple_template.html~1';
LOI[19] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Mal~3~1~images/bible_images/Temple/temple_template.html~2';
