var LOI = [];
LOI[0] = 'hymn~20~CHRISTIAN, RISE AND ACT THY CREED~htm_c_a_cariseat.html';
LOI[1] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Jam~2~21~images/places/Israel/israel_template.html~8';
LOI[2] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Jam~2~23~images/places/Israel/israel_template.html~8';
LOI[3] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Jam~2~21~images/bible_images/Moses/moses_template.html~3';
LOI[4] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Jam~2~23~images/bible_images/Moses/moses_template.html~3';
LOI[5] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Jam~2~21~images/bible_images/Moses/moses_template.html~3i';
LOI[6] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Jam~2~23~images/bible_images/Moses/moses_template.html~3i';
LOI[7] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~Jam~2~21~images/bible_images/Moses/moses_template.html~3a';
LOI[8] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Jam~2~23~images/bible_images/Moses/moses_template.html~3a';
LOI[9] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Jam~2~21~images/bible_images/Moses/moses_template.html~4';
