var LOI = [];
LOI[0] = 'hymn~1~CLEANSING FOUNTAIN, THE~htm_c_l_cleansnf.html';
LOI[1] = 'hymn~1~CLEANSING WAVE~htm_c_l_cleansin.html';
LOI[2] = 'hymn~1~FOREVER HERE MY REST SHALL BE~htm_f_o_forehere.html';
LOI[3] = 'hymn~1~FOUNTAIN OF GRACE~htm_f_o_fountgra.html';
LOI[4] = 'hymn~1~HEALING AT THE FOUNTAIN~htm_h_e_a_healfoun.html';
LOI[5] = 'hymn~1~SACRED FOUNTAIN~htm_s_a_sacredfo.html';
LOI[6] = 'hymn~1~THERE IS A FOUNTAIN FILLED WITH BLOOD~htm_t_f_tfountfb.html';
LOI[7] = 'hymn~1~THERE&#8217;S A FOUNTAIN FREE~htm_t_a_tafountf.html';
LOI[8] = 'hymn~7~SOULS OF MEN, WHY WILL YE SCATTER~htm_s_o_soulsmen.html';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Zec~13~1~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Zec~13~1~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Zec~13~1~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Zec~13~1~images/places/Israel/israel_template.html~11';
LOI[13] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Zec~13~1~images/places/Israel/israel_template.html~12';
LOI[14] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Zec~13~1~images/places/Israel/israel_template.html~13';
LOI[15] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Zec~13~1~images/places/Israel/israel_template.html~14';
LOI[16] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Zec~13~1~images/places/Israel/israel_template.html~17';
LOI[17] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Zec~13~1~images/bible_images/Kings/kings_template.html~1';
LOI[18] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Zec~13~1~images/bible_images/Kings/kings_template.html~2';
