var LOI = [];
LOI[0] = 'hymn~1~JESUS, THE CALM THAT FILLS MY BREAST~htm_j_e_jethecal.html';
LOI[1] = 'hymn~1~FATHER IN HEAVEN, IN THY LOVE ABOUNDING~htm_f_i_fihitlab.html';
LOI[2] = 'hymn~2~O GLORIOUS HOPE OF PERFECT LOVE~htm_o_g_oglorhop.html';
LOI[3] = 'hymn~5~COME, HOLY SPIRIT, HEAVENLY DOVE~htm_c_o_comehshd.html';
LOI[4] = 'hymn~5~O LOVE OF GOD MOST FULL~htm_o_l_olgmfull.html';
LOI[5] = 'hymn~8~I HAVE A SAVIOR~htm_i_h_ihavesav.html';
LOI[6] = 'hymn~8~O LOVE DIVINE, WHAT HAST THOU DONE~htm_o_l_olovediv.html';
LOI[7] = 'hymn~8~SAVIOR, THY DYING LOVE~htm_s_t_sthydynl.html';
LOI[8] = 'hymn~20~GRACE GREATER THAN OUR SIN~htm_g_g_ggreater.html';
LOI[9] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart) key=tribulation~~~~Rom~5~3~images/charts/Bible/bible_template.html~1';
LOI[10] = 'image~Bible~Images~The Judgement of Adam and Eve (engraving) key=Adam~~~~Rom~5~14~images/bible_images/Moses/moses_template.html~1b';
LOI[11] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Rom~5~14~images/bible_images/Moses/moses_template.html~6';
LOI[12] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Rom~5~14~images/bible_images/Moses/moses_template.html~7';
LOI[13] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Rom~5~14~images/bible_images/Moses/moses_template.html~9';
LOI[14] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Rom~5~14~images/bible_images/Moses/moses_template.html~10';
LOI[15] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Rom~5~14~images/bible_images/Moses/moses_template.html~11';
