var LOI = [];
LOI[0] = 'hymn~1~ONE DAY I TRAVELED A TOILSOME ROAD~htm_o_n_onedayit.html';
LOI[1] = 'hymn~2~O SPIRIT OF LIFE~htm_o_s_ospilife.html';
LOI[2] = 'hymn~12~WHEN THIS PASSING WORLD IS DONE~htm_w_t_wtpwidon.html';
LOI[3] = 'hymn~15~GOD OUR FATHER, WE ADORE THEE~htm_g_o_gofwat.html';
LOI[4] = 'hymn~17~A CHILD OF THE KING~htm_c_h_childkin.html';
LOI[5] = 'hymn~17~CHILDREN OF THE HEAVENLY KING~htm_c_o_cofthehk.html';
LOI[6] = 'hymn~17~O THAT WILL BE GLORY~htm_o_t_othatwbg.html';
LOI[7] = 'hymn~22~ALMIGHTY FATHER, WHO DOST GIVE~htm_a_f_afwdostg.html';
LOI[8] = 'hymn~22~CHRIST IS COMING!~htm_c_h_christic.html';
LOI[9] = 'hymn~22~COME, LORD, AND TARRY NOT~htm_c_l_cltarryn.html';
LOI[10] = 'hymn~22~FATHER, WHEN SHALL ALL THE WEARY EARTH~htm_f_a_fathwhen.html';
LOI[11] = 'hymn~29~LORD, I AM FONDLY, EARNESTLY LONGING~htm_l_o_lordiafe.html';
LOI[12] = 'hymn~29~PRINT THINE IMAGE, PURE AND HOLY~htm_p_r_printhin.html';
LOI[13] = 'hymn~34~ARISE, MY SOUL, ARISE~htm_a_r_arisemys.html';
LOI[14] = 'hymn~34~I AM NOT SKILLED TO UNDERSTAND~htm_i_a_imnots2u.html';
LOI[15] = 'hymn~34~JOHN IN VISION SAW THE DAY~htm_j_o_johnivis.html';
LOI[16] = 'hymn~35~THE LOVE OF GOD~htm_l_o_loveofgo.html';
LOI[17] = 'hymn~35~MY LORD, HOW FULL OF SWEET CONTENT~htm_m_y_mylordhf.html';
LOI[18] = 'hymn~37~CROSS OF CHRIST! LEAD ONWARD~htm_c_c_cclonwar.html';
LOI[19] = 'hymn~37~MORE THAN CONQUERORS~htm_m_o_morethan.html';
LOI[20] = 'hymn~38~NOTHING BETWEEN~htm_n_b_nbetween.html';
LOI[21] = 'hymn~38~O LOVE OF GOD, HOW STRONG AND TRUE~htm_o_l_olovegod.html';
LOI[22] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart) key=tribulation~~~~Rom~8~35~images/charts/Bible/bible_template.html~1';
LOI[23] = 'image~Bible~Images~The Creation (engraving) key=creation~~~~Rom~8~22~images/bible_images/Moses/moses_template.html~1a';
