var LOI = [];
LOI[0] = 'hymn~4~THE ANCIENT LAW DEPARTS~htm_a_n_ancientl.html';
LOI[1] = 'hymn~4~FREE FROM THE LAW~htm_f_r_freefrom.html';
LOI[2] = 'hymn~9~O BE SAVED~htm_o_b_obesaved.html';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Rom~10~1~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Rom~10~19~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Rom~10~21~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Rom~10~1~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Rom~10~19~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Rom~10~21~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Rom~10~1~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Rom~10~19~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Rom~10~21~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Rom~10~1~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Rom~10~19~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Rom~10~21~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Rom~10~1~images/maps/Christ/christ_template.html~1';
LOI[16] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Rom~10~19~images/maps/Christ/christ_template.html~1';
LOI[17] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Rom~10~21~images/maps/Christ/christ_template.html~1';
LOI[18] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Rom~10~5~images/bible_images/Moses/moses_template.html~6';
LOI[19] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Rom~10~19~images/bible_images/Moses/moses_template.html~6';
LOI[20] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Rom~10~5~images/bible_images/Moses/moses_template.html~7';
LOI[21] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Rom~10~19~images/bible_images/Moses/moses_template.html~7';
LOI[22] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Rom~10~5~images/bible_images/Moses/moses_template.html~9';
LOI[23] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Rom~10~19~images/bible_images/Moses/moses_template.html~9';
LOI[24] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Rom~10~5~images/bible_images/Moses/moses_template.html~10';
LOI[25] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Rom~10~19~images/bible_images/Moses/moses_template.html~10';
LOI[26] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Rom~10~5~images/bible_images/Moses/moses_template.html~11';
LOI[27] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Rom~10~19~images/bible_images/Moses/moses_template.html~11';
