var LOI = [];
LOI[0] = 'hymn~4~WONDERFUL BOOK~htm_w_o_wondbook.html';
LOI[1] = 'hymn~8~WE LIMIT NOT THE TRUTH OF GOD~htm_w_e_welimitn.html';
LOI[2] = 'hymn~17~IN THE SERVICE OF THE KING~htm_i_n_intservc.html';
LOI[3] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Rom~15~19~images/maps/Otest/otest_template.html~3a';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Rom~15~25~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Rom~15~26~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Rom~15~31~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Rom~15~19~images/maps/Otest/otest_template.html~3b';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Rom~15~25~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Rom~15~26~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Rom~15~31~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Rom~15~19~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Rom~15~25~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Rom~15~26~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Rom~15~31~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Achaia~~~~Rom~15~26~images/maps/Journeys/journeys_template.html~2';
LOI[16] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Macedonia,Achaia~~~~Rom~15~26~images/maps/Journeys/journeys_template.html~3';
LOI[17] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Rom~15~19~images/places/Israel/israel_template.html~11';
LOI[18] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Rom~15~25~images/places/Israel/israel_template.html~11';
LOI[19] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Rom~15~26~images/places/Israel/israel_template.html~11';
LOI[20] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Rom~15~31~images/places/Israel/israel_template.html~11';
LOI[21] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Rom~15~19~images/places/Israel/israel_template.html~12';
LOI[22] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Rom~15~25~images/places/Israel/israel_template.html~12';
LOI[23] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Rom~15~26~images/places/Israel/israel_template.html~12';
LOI[24] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Rom~15~31~images/places/Israel/israel_template.html~12';
LOI[25] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Rom~15~19~images/places/Israel/israel_template.html~13';
LOI[26] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Rom~15~25~images/places/Israel/israel_template.html~13';
LOI[27] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Rom~15~26~images/places/Israel/israel_template.html~13';
LOI[28] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Rom~15~31~images/places/Israel/israel_template.html~13';
LOI[29] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Rom~15~19~images/places/Israel/israel_template.html~14';
LOI[30] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Rom~15~25~images/places/Israel/israel_template.html~14';
LOI[31] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Rom~15~26~images/places/Israel/israel_template.html~14';
LOI[32] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Rom~15~31~images/places/Israel/israel_template.html~14';
LOI[33] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Rom~15~19~images/places/Israel/israel_template.html~17';
LOI[34] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Rom~15~25~images/places/Israel/israel_template.html~17';
LOI[35] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Rom~15~26~images/places/Israel/israel_template.html~17';
LOI[36] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Rom~15~31~images/places/Israel/israel_template.html~17';
