var LOI = [];
LOI[0] = 'hymn~1~OUR GUILT DO WE CONFESS TODAY~htm_o_u_ourguilt.html';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Hsa~4~1~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Hsa~4~15~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Hsa~4~16~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Hsa~4~17~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Hsa~4~1~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Hsa~4~15~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Hsa~4~16~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~Hsa~4~17~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Hsa~4~1~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Hsa~4~15~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Hsa~4~16~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Hsa~4~1~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Hsa~4~15~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Hsa~4~16~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Hsa~4~1~images/maps/Christ/christ_template.html~1';
LOI[16] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Hsa~4~15~images/maps/Christ/christ_template.html~1';
LOI[17] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Hsa~4~16~images/maps/Christ/christ_template.html~1';
