var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Hsa~12~12~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Hsa~12~13~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Hsa~12~2~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Hsa~12~1~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Hsa~12~8~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Hsa~12~14~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Hsa~12~12~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Hsa~12~13~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Hsa~12~2~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~Hsa~12~1~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~Hsa~12~8~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~Hsa~12~14~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Hsa~12~12~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Hsa~12~13~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~Hsa~12~11~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Hsa~12~12~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Hsa~12~13~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~Hsa~12~11~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Hsa~12~1~images/maps/Otest/otest_template.html~5';
LOI[19] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Hsa~12~9~images/maps/Otest/otest_template.html~5';
LOI[20] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Hsa~12~13~images/maps/Otest/otest_template.html~5';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Hsa~12~12~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Hsa~12~13~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~Hsa~12~12~images/maps/Journeys/journeys_template.html~2';
