var LOI = [];
LOI[0] = 'hymn~6~COUNT YOUR BLESSINGS~htm_c_o_countyou.html';
LOI[1] = 'hymn~22~SWEET THE MOMENTS, RICH IN BLESSING~htm_s_w_sweettmo.html';
LOI[2] = 'hymn~27~THUS FAR THE LORD HATH LED ME ON~htm_t_h_thusfarl.html';
LOI[3] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~Pro~10~1~images/bible_images/Kings/kings_template.html~3';
LOI[4] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~Pro~10~1~images/bible_images/Kings/kings_template.html~4';
LOI[5] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~1';
LOI[6] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~2';
LOI[7] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~3';
LOI[8] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~4';
LOI[9] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~5';
LOI[10] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~6';
LOI[11] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~7';
LOI[12] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~8';
LOI[13] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~9';
LOI[14] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~10';
LOI[15] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~11';
LOI[16] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~12';
LOI[17] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~13';
LOI[18] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~14';
LOI[19] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~Pro~10~1~images/bible_images/Song/song_template.html~15';
