var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Pro~1~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Pro~1~1~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Pro~1~1~images/maps/Otest/otest_template.html~3c';
LOI[3] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Pro~1~1~images/maps/Otest/otest_template.html~4';
LOI[4] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Pro~1~1~images/maps/Christ/christ_template.html~1';
LOI[5] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Pro~1~14~images/bible_images/Moses/moses_template.html~3i';
LOI[6] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Pro~1~1~images/bible_images/Kings/kings_template.html~1';
LOI[7] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Pro~1~1~images/bible_images/Kings/kings_template.html~2';
LOI[8] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~Pro~1~1~images/bible_images/Kings/kings_template.html~3';
LOI[9] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~Pro~1~1~images/bible_images/Kings/kings_template.html~4';
LOI[10] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~1';
LOI[11] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~2';
LOI[12] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~3';
LOI[13] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~4';
LOI[14] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~5';
LOI[15] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~6';
LOI[16] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~7';
LOI[17] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~8';
LOI[18] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~9';
LOI[19] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~10';
LOI[20] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~11';
LOI[21] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~12';
LOI[22] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~13';
LOI[23] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~14';
LOI[24] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~Pro~1~1~images/bible_images/Song/song_template.html~15';
