var LOI = [];
LOI[0] = 'hymn~8~GO!~htm_g_o_go.html';
LOI[1] = 'hymn~8~YE SHALL BE MY WITNESSES~htm_y_s_yshalbmw.html';
LOI[2] = 'hymn~9~HE IS GONE, A CLOUD OF LIGHT~htm_h_e_heisgone.html';
LOI[3] = 'hymn~11~HE IS COMING AGAIN~htm_h_e_heiscoma.html';
LOI[4] = 'hymn~11~A HYMN OF GLORY LET US SING~htm_h_h_hymglory.html';
LOI[5] = 'hymn~11~JESUS, MY ALL, TO HEAVEN IS GONE~htm_j_m_jmyall2h.html';
LOI[6] = 'hymn~11~THE SAVIOR WHO LOVES ME~htm_s_a_saviorwl.html';
LOI[7] = 'hymn~11~THOU ART GONE UP ON HIGH~htm_t_h_o_thoaguoh.html';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Act~1~6~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Act~1~23~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Act~1~6~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Act~1~23~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~1~4~images/maps/Otest/otest_template.html~3a';
LOI[13] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~1~8~images/maps/Otest/otest_template.html~3a';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~1~12~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~1~19~images/maps/Otest/otest_template.html~3a';
LOI[16] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~1~4~images/maps/Otest/otest_template.html~3b';
LOI[17] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~1~8~images/maps/Otest/otest_template.html~3b';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~1~12~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~1~19~images/maps/Otest/otest_template.html~3b';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Act~1~6~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Act~1~11~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Act~1~6~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~1~4~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~1~8~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~1~12~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~1~19~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Act~1~6~images/maps/Christ/christ_template.html~1';
LOI[28] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Act~1~8~images/maps/Christ/christ_template.html~1';
LOI[29] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Act~1~11~images/maps/Christ/christ_template.html~1';
LOI[30] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Barsabas~~~~Act~1~23~images/maps/Journeys/journeys_template.html~2';
LOI[31] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~1~4~images/places/Israel/israel_template.html~11';
LOI[32] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~1~8~images/places/Israel/israel_template.html~11';
LOI[33] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~1~12~images/places/Israel/israel_template.html~11';
LOI[34] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~1~19~images/places/Israel/israel_template.html~11';
LOI[35] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~1~4~images/places/Israel/israel_template.html~12';
LOI[36] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~1~8~images/places/Israel/israel_template.html~12';
LOI[37] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~1~12~images/places/Israel/israel_template.html~12';
LOI[38] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~1~19~images/places/Israel/israel_template.html~12';
LOI[39] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~1~4~images/places/Israel/israel_template.html~13';
LOI[40] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~1~8~images/places/Israel/israel_template.html~13';
LOI[41] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~1~12~images/places/Israel/israel_template.html~13';
LOI[42] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~1~19~images/places/Israel/israel_template.html~13';
LOI[43] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~1~4~images/places/Israel/israel_template.html~14';
LOI[44] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~1~8~images/places/Israel/israel_template.html~14';
LOI[45] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~1~12~images/places/Israel/israel_template.html~14';
LOI[46] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~1~19~images/places/Israel/israel_template.html~14';
LOI[47] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~1~4~images/places/Israel/israel_template.html~17';
LOI[48] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~1~8~images/places/Israel/israel_template.html~17';
LOI[49] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~1~12~images/places/Israel/israel_template.html~17';
LOI[50] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~1~19~images/places/Israel/israel_template.html~17';
LOI[51] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Act~1~26~images/bible_images/Moses/moses_template.html~3i';
LOI[52] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Act~1~23~images/bible_images/Moses/moses_template.html~5';
LOI[53] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Act~1~16~images/bible_images/Kings/kings_template.html~1';
LOI[54] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Act~1~16~images/bible_images/Kings/kings_template.html~2';
