var LOI = [];
LOI[0] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~6~7~images/maps/Otest/otest_template.html~3a';
LOI[1] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~6~7~images/maps/Otest/otest_template.html~3b';
LOI[2] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~6~7~images/maps/Otest/otest_template.html~4';
LOI[3] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Antioch~~~~Act~6~5~images/maps/Journeys/journeys_template.html~1';
LOI[4] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Antioch~~~~Act~6~5~images/maps/Journeys/journeys_template.html~2';
LOI[5] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Cilicia~~~~Act~6~9~images/maps/Journeys/journeys_template.html~2';
LOI[6] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Antioch~~~~Act~6~5~images/maps/Journeys/journeys_template.html~3';
LOI[7] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Asia~~~~Act~6~9~images/maps/Journeys/journeys_template.html~3';
LOI[8] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~6~7~images/places/Israel/israel_template.html~11';
LOI[9] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~6~7~images/places/Israel/israel_template.html~12';
LOI[10] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~6~7~images/places/Israel/israel_template.html~13';
LOI[11] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~6~7~images/places/Israel/israel_template.html~14';
LOI[12] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~6~7~images/places/Israel/israel_template.html~17';
LOI[13] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Act~6~11~images/bible_images/Moses/moses_template.html~6';
LOI[14] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Act~6~14~images/bible_images/Moses/moses_template.html~6';
LOI[15] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Act~6~11~images/bible_images/Moses/moses_template.html~7';
LOI[16] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Act~6~14~images/bible_images/Moses/moses_template.html~7';
LOI[17] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Act~6~11~images/bible_images/Moses/moses_template.html~9';
LOI[18] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Act~6~14~images/bible_images/Moses/moses_template.html~9';
LOI[19] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Act~6~11~images/bible_images/Moses/moses_template.html~10';
LOI[20] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Act~6~14~images/bible_images/Moses/moses_template.html~10';
LOI[21] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Act~6~11~images/bible_images/Moses/moses_template.html~11';
LOI[22] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Act~6~14~images/bible_images/Moses/moses_template.html~11';
LOI[23] = 'image~Bible~Images~The Leper Healed (engraving) key=miracles~~~~Act~6~8~images/bible_images/Miracles/miracles_template.html~1';
LOI[24] = 'image~Bible~Images~Man With Palsy Healed (engraving) key=miracles~~~~Act~6~8~images/bible_images/Miracles/miracles_template.html~2';
LOI[25] = 'image~Bible~Images~The Raising of Jairus\' Daughter (engraving) key=miracles~~~~Act~6~8~images/bible_images/Miracles/miracles_template.html~3';
LOI[26] = 'image~Bible~Images~The Paralytic Healed (engraving) key=miracles~~~~Act~6~8~images/bible_images/Miracles/miracles_template.html~4';
LOI[27] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving) key=miracles~~~~Act~6~8~images/bible_images/Miracles/miracles_template.html~5';
LOI[28] = 'image~Bible~Images~Jesus Walking on the Sea (engraving) key=miracles~~~~Act~6~8~images/bible_images/Miracles/miracles_template.html~6';
LOI[29] = 'image~Bible~Images~Healing Demoniac Daughter (engraving) key=miracles~~~~Act~6~8~images/bible_images/Miracles/miracles_template.html~7';
LOI[30] = 'image~Bible~Images~Deaf Man Hears (engraving) key=miracles~~~~Act~6~8~images/bible_images/Miracles/miracles_template.html~8';
LOI[31] = 'image~Bible~Images~Man Born Blind Healed (engraving) key=miracles~~~~Act~6~8~images/bible_images/Miracles/miracles_template.html~9';
LOI[32] = 'image~Bible~Images~Jesus Healing Ten Lepers (engraving) key=miracles~~~~Act~6~8~images/bible_images/Miracles/miracles_template.html~10';
LOI[33] = 'image~Bible~Images~Jesus Heals Bartimaeus (engraving) key=miracles~~~~Act~6~8~images/bible_images/Miracles/miracles_template.html~11';
LOI[34] = 'image~Bible~Images~The Death of Stephen key=Stephen~~~~Act~6~5~images/bible_images/Acts/acts_template.html~1';
LOI[35] = 'image~Bible~Images~The Death of Stephen key=Stephen~~~~Act~6~8~images/bible_images/Acts/acts_template.html~1';
LOI[36] = 'image~Bible~Images~The Death of Stephen key=Stephen~~~~Act~6~9~images/bible_images/Acts/acts_template.html~1';
