var LOI = [];
LOI[0] = 'hymn~12~CONQUERING KINGS THEIR TITLES TAKE~htm_c_o_conqking.html';
LOI[1] = 'hymn~12~TO THE NAME OF OUR SALVATION~htm_t_o_tothenam.html';
LOI[2] = 'hymn~12~TO THE NAME THAT IS SALVATION~htm_t_n_tntisalv.html';
LOI[3] = 'hymn~24~O FATHER, YOU ARE SOVEREIGN~htm_o_f_ofayarso.html';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Act~4~8~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Act~4~10~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Act~4~27~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Act~4~8~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Act~4~10~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Act~4~27~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~4~6~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~4~16~images/maps/Otest/otest_template.html~3a';
LOI[12] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Act~4~1~images/maps/Otest/otest_template.html~3a';
LOI[13] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~4~6~images/maps/Otest/otest_template.html~3b';
LOI[14] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~4~16~images/maps/Otest/otest_template.html~3b';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Act~4~1~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Act~4~8~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Act~4~10~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Act~4~27~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Act~4~8~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Act~4~10~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Act~4~27~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~4~6~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~4~16~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Act~4~8~images/maps/Christ/christ_template.html~1';
LOI[25] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Act~4~10~images/maps/Christ/christ_template.html~1';
LOI[26] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Act~4~27~images/maps/Christ/christ_template.html~1';
LOI[27] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Barnabas,Cyprus~~~~Act~4~36~images/maps/Journeys/journeys_template.html~1';
LOI[28] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Barnabas~~~~Act~4~36~images/maps/Journeys/journeys_template.html~2';
LOI[29] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Cyprus~~~~Act~4~36~images/maps/Journeys/journeys_template.html~3';
LOI[30] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~4~6~images/places/Israel/israel_template.html~11';
LOI[31] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~4~16~images/places/Israel/israel_template.html~11';
LOI[32] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~4~6~images/places/Israel/israel_template.html~12';
LOI[33] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~4~16~images/places/Israel/israel_template.html~12';
LOI[34] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~4~6~images/places/Israel/israel_template.html~13';
LOI[35] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~4~16~images/places/Israel/israel_template.html~13';
LOI[36] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~4~6~images/places/Israel/israel_template.html~14';
LOI[37] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~4~16~images/places/Israel/israel_template.html~14';
LOI[38] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~4~6~images/places/Israel/israel_template.html~17';
LOI[39] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~4~16~images/places/Israel/israel_template.html~17';
LOI[40] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Act~4~25~images/bible_images/Kings/kings_template.html~1';
LOI[41] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Act~4~25~images/bible_images/Kings/kings_template.html~2';
LOI[42] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Act~4~1~images/bible_images/Temple/temple_template.html~1';
LOI[43] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Act~4~1~images/bible_images/Temple/temple_template.html~2';
