var LOI = [];
LOI[0] = 'hymn~28~LIVING FOR JESUS~htm_l_i_livingfj.html';
LOI[1] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~17~2~images/maps/Journeys/journeys_template.html~1';
LOI[2] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~17~4~images/maps/Journeys/journeys_template.html~1';
LOI[3] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~17~10~images/maps/Journeys/journeys_template.html~1';
LOI[4] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~17~13~images/maps/Journeys/journeys_template.html~1';
LOI[5] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~17~14~images/maps/Journeys/journeys_template.html~1';
LOI[6] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~17~15~images/maps/Journeys/journeys_template.html~1';
LOI[7] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~17~16~images/maps/Journeys/journeys_template.html~1';
LOI[8] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~17~22~images/maps/Journeys/journeys_template.html~1';
LOI[9] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~17~33~images/maps/Journeys/journeys_template.html~1';
LOI[10] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~1~images/maps/Journeys/journeys_template.html~2';
LOI[11] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~2~images/maps/Journeys/journeys_template.html~2';
LOI[12] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~3~images/maps/Journeys/journeys_template.html~2';
LOI[13] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~4~images/maps/Journeys/journeys_template.html~2';
LOI[14] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~5~images/maps/Journeys/journeys_template.html~2';
LOI[15] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~6~images/maps/Journeys/journeys_template.html~2';
LOI[16] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~7~images/maps/Journeys/journeys_template.html~2';
LOI[17] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~8~images/maps/Journeys/journeys_template.html~2';
LOI[18] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~9~images/maps/Journeys/journeys_template.html~2';
LOI[19] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~10~images/maps/Journeys/journeys_template.html~2';
LOI[20] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~11~images/maps/Journeys/journeys_template.html~2';
LOI[21] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~12~images/maps/Journeys/journeys_template.html~2';
LOI[22] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~13~images/maps/Journeys/journeys_template.html~2';
LOI[23] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~14~images/maps/Journeys/journeys_template.html~2';
LOI[24] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~15~images/maps/Journeys/journeys_template.html~2';
LOI[25] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~16~images/maps/Journeys/journeys_template.html~2';
LOI[26] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~17~images/maps/Journeys/journeys_template.html~2';
LOI[27] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~18~images/maps/Journeys/journeys_template.html~2';
LOI[28] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~19~images/maps/Journeys/journeys_template.html~2';
LOI[29] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~20~images/maps/Journeys/journeys_template.html~2';
LOI[30] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~21~images/maps/Journeys/journeys_template.html~2';
LOI[31] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~22~images/maps/Journeys/journeys_template.html~2';
LOI[32] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~23~images/maps/Journeys/journeys_template.html~2';
LOI[33] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~24~images/maps/Journeys/journeys_template.html~2';
LOI[34] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~25~images/maps/Journeys/journeys_template.html~2';
LOI[35] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~26~images/maps/Journeys/journeys_template.html~2';
LOI[36] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~27~images/maps/Journeys/journeys_template.html~2';
LOI[37] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~28~images/maps/Journeys/journeys_template.html~2';
LOI[38] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~29~images/maps/Journeys/journeys_template.html~2';
LOI[39] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~30~images/maps/Journeys/journeys_template.html~2';
LOI[40] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~31~images/maps/Journeys/journeys_template.html~2';
LOI[41] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~32~images/maps/Journeys/journeys_template.html~2';
LOI[42] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~33~images/maps/Journeys/journeys_template.html~2';
LOI[43] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~17~34~images/maps/Journeys/journeys_template.html~2';
LOI[44] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~17~2~images/maps/Journeys/journeys_template.html~3';
LOI[45] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~17~4~images/maps/Journeys/journeys_template.html~3';
LOI[46] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~17~10~images/maps/Journeys/journeys_template.html~3';
LOI[47] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul,Thessalonica~~~~Act~17~13~images/maps/Journeys/journeys_template.html~3';
LOI[48] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~17~14~images/maps/Journeys/journeys_template.html~3';
LOI[49] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~17~15~images/maps/Journeys/journeys_template.html~3';
LOI[50] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~17~16~images/maps/Journeys/journeys_template.html~3';
LOI[51] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~17~22~images/maps/Journeys/journeys_template.html~3';
LOI[52] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~17~33~images/maps/Journeys/journeys_template.html~3';
LOI[53] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Thessalonica~~~~Act~17~1~images/maps/Journeys/journeys_template.html~3';
LOI[54] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Thessalonica~~~~Act~17~11~images/maps/Journeys/journeys_template.html~3';
LOI[55] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~17~2~images/bible_images/Acts/acts_template.html~2';
LOI[56] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~17~4~images/bible_images/Acts/acts_template.html~2';
LOI[57] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~17~10~images/bible_images/Acts/acts_template.html~2';
LOI[58] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~17~13~images/bible_images/Acts/acts_template.html~2';
LOI[59] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~17~14~images/bible_images/Acts/acts_template.html~2';
LOI[60] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~17~15~images/bible_images/Acts/acts_template.html~2';
LOI[61] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~17~16~images/bible_images/Acts/acts_template.html~2';
LOI[62] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~17~22~images/bible_images/Acts/acts_template.html~2';
LOI[63] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~17~33~images/bible_images/Acts/acts_template.html~2';
