var LOI = [];
LOI[0] = 'hymn~25~COME, HOLY GHOST, OUR HEARTS INSPIRE~htm_c_o_comehgoh.html';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Act~28~20~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Act~28~20~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~28~17~images/maps/Otest/otest_template.html~3a';
LOI[4] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~28~17~images/maps/Otest/otest_template.html~3b';
LOI[5] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Act~28~20~images/maps/Otest/otest_template.html~3c';
LOI[6] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Act~28~20~images/maps/Otest/otest_template.html~4';
LOI[7] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~28~17~images/maps/Otest/otest_template.html~4';
LOI[8] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Act~28~20~images/maps/Christ/christ_template.html~1';
LOI[9] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~28~3~images/maps/Journeys/journeys_template.html~1';
LOI[10] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~28~8~images/maps/Journeys/journeys_template.html~1';
LOI[11] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~28~15~images/maps/Journeys/journeys_template.html~1';
LOI[12] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~28~16~images/maps/Journeys/journeys_template.html~1';
LOI[13] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~28~17~images/maps/Journeys/journeys_template.html~1';
LOI[14] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~28~25~images/maps/Journeys/journeys_template.html~1';
LOI[15] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~28~30~images/maps/Journeys/journeys_template.html~1';
LOI[16] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~28~3~images/maps/Journeys/journeys_template.html~2';
LOI[17] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~28~8~images/maps/Journeys/journeys_template.html~2';
LOI[18] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~28~15~images/maps/Journeys/journeys_template.html~2';
LOI[19] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~28~16~images/maps/Journeys/journeys_template.html~2';
LOI[20] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~28~17~images/maps/Journeys/journeys_template.html~2';
LOI[21] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~28~25~images/maps/Journeys/journeys_template.html~2';
LOI[22] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~28~30~images/maps/Journeys/journeys_template.html~2';
LOI[23] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~28~3~images/maps/Journeys/journeys_template.html~3';
LOI[24] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~28~8~images/maps/Journeys/journeys_template.html~3';
LOI[25] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~28~15~images/maps/Journeys/journeys_template.html~3';
LOI[26] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~28~16~images/maps/Journeys/journeys_template.html~3';
LOI[27] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~28~17~images/maps/Journeys/journeys_template.html~3';
LOI[28] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~28~25~images/maps/Journeys/journeys_template.html~3';
LOI[29] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~28~30~images/maps/Journeys/journeys_template.html~3';
LOI[30] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~28~17~images/places/Israel/israel_template.html~11';
LOI[31] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~28~17~images/places/Israel/israel_template.html~12';
LOI[32] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~28~17~images/places/Israel/israel_template.html~13';
LOI[33] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~28~17~images/places/Israel/israel_template.html~14';
LOI[34] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~28~17~images/places/Israel/israel_template.html~17';
LOI[35] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Act~28~23~images/bible_images/Moses/moses_template.html~6';
LOI[36] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Act~28~23~images/bible_images/Moses/moses_template.html~7';
LOI[37] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Act~28~23~images/bible_images/Moses/moses_template.html~9';
LOI[38] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Act~28~23~images/bible_images/Moses/moses_template.html~10';
LOI[39] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Act~28~23~images/bible_images/Moses/moses_template.html~11';
LOI[40] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~28~3~images/bible_images/Acts/acts_template.html~2';
LOI[41] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~28~8~images/bible_images/Acts/acts_template.html~2';
LOI[42] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~28~15~images/bible_images/Acts/acts_template.html~2';
LOI[43] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~28~16~images/bible_images/Acts/acts_template.html~2';
LOI[44] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~28~17~images/bible_images/Acts/acts_template.html~2';
LOI[45] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~28~25~images/bible_images/Acts/acts_template.html~2';
LOI[46] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~28~30~images/bible_images/Acts/acts_template.html~2';
