var LOI = [];
LOI[0] = 'hymn~21~IS THY HEART RIGHT WITH GOD?~htm_i_s_isthyhrt.html';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ethiopia~~~~Act~8~27~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~Act~8~1~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~Act~8~3~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~8~1~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~8~14~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~8~25~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~8~26~images/maps/Otest/otest_template.html~3a';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~8~27~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~8~1~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~8~14~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~8~25~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~8~26~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~8~27~images/maps/Otest/otest_template.html~3b';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~8~1~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~8~14~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~8~25~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem,Gaza~~~~Act~8~26~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~8~27~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Act~8~1~images/maps/Christ/christ_template.html~1';
LOI[20] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Act~8~5~images/maps/Christ/christ_template.html~1';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Act~8~9~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Act~8~14~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Caesarea~~~~Act~8~40~images/maps/Journeys/journeys_template.html~2';
LOI[24] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~8~1~images/places/Israel/israel_template.html~11';
LOI[25] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~8~14~images/places/Israel/israel_template.html~11';
LOI[26] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~8~25~images/places/Israel/israel_template.html~11';
LOI[27] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~8~26~images/places/Israel/israel_template.html~11';
LOI[28] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~8~27~images/places/Israel/israel_template.html~11';
LOI[29] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~8~1~images/places/Israel/israel_template.html~12';
LOI[30] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~8~14~images/places/Israel/israel_template.html~12';
LOI[31] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~8~25~images/places/Israel/israel_template.html~12';
LOI[32] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~8~26~images/places/Israel/israel_template.html~12';
LOI[33] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~8~27~images/places/Israel/israel_template.html~12';
LOI[34] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~8~1~images/places/Israel/israel_template.html~13';
LOI[35] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~8~14~images/places/Israel/israel_template.html~13';
LOI[36] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~8~25~images/places/Israel/israel_template.html~13';
LOI[37] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~8~26~images/places/Israel/israel_template.html~13';
LOI[38] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~8~27~images/places/Israel/israel_template.html~13';
LOI[39] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~8~1~images/places/Israel/israel_template.html~14';
LOI[40] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~8~14~images/places/Israel/israel_template.html~14';
LOI[41] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~8~25~images/places/Israel/israel_template.html~14';
LOI[42] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~8~26~images/places/Israel/israel_template.html~14';
LOI[43] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~8~27~images/places/Israel/israel_template.html~14';
LOI[44] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~8~1~images/places/Israel/israel_template.html~17';
LOI[45] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~8~14~images/places/Israel/israel_template.html~17';
LOI[46] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~8~25~images/places/Israel/israel_template.html~17';
LOI[47] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~8~26~images/places/Israel/israel_template.html~17';
LOI[48] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~8~27~images/places/Israel/israel_template.html~17';
LOI[49] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Act~8~21~images/bible_images/Moses/moses_template.html~3i';
LOI[50] = 'image~Bible~Images~Saul and David (engraving) key=Saul~~~~Act~8~1~images/bible_images/Kings/kings_template.html~1';
LOI[51] = 'image~Bible~Images~Saul and David (engraving) key=Saul~~~~Act~8~3~images/bible_images/Kings/kings_template.html~1';
LOI[52] = 'image~Bible~Images~The Leper Healed (engraving) key=miracles~~~~Act~8~6~images/bible_images/Miracles/miracles_template.html~1';
LOI[53] = 'image~Bible~Images~The Leper Healed (engraving) key=miracles~~~~Act~8~13~images/bible_images/Miracles/miracles_template.html~1';
LOI[54] = 'image~Bible~Images~Man With Palsy Healed (engraving) key=miracles~~~~Act~8~6~images/bible_images/Miracles/miracles_template.html~2';
LOI[55] = 'image~Bible~Images~Man With Palsy Healed (engraving) key=miracles~~~~Act~8~13~images/bible_images/Miracles/miracles_template.html~2';
LOI[56] = 'image~Bible~Images~The Raising of Jairus\' Daughter (engraving) key=miracles~~~~Act~8~6~images/bible_images/Miracles/miracles_template.html~3';
LOI[57] = 'image~Bible~Images~The Raising of Jairus\' Daughter (engraving) key=miracles~~~~Act~8~13~images/bible_images/Miracles/miracles_template.html~3';
LOI[58] = 'image~Bible~Images~The Paralytic Healed (engraving) key=miracles~~~~Act~8~6~images/bible_images/Miracles/miracles_template.html~4';
LOI[59] = 'image~Bible~Images~The Paralytic Healed (engraving) key=miracles~~~~Act~8~13~images/bible_images/Miracles/miracles_template.html~4';
LOI[60] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving) key=miracles~~~~Act~8~6~images/bible_images/Miracles/miracles_template.html~5';
LOI[61] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving) key=miracles~~~~Act~8~13~images/bible_images/Miracles/miracles_template.html~5';
LOI[62] = 'image~Bible~Images~Jesus Walking on the Sea (engraving) key=miracles~~~~Act~8~6~images/bible_images/Miracles/miracles_template.html~6';
LOI[63] = 'image~Bible~Images~Jesus Walking on the Sea (engraving) key=miracles~~~~Act~8~13~images/bible_images/Miracles/miracles_template.html~6';
LOI[64] = 'image~Bible~Images~Healing Demoniac Daughter (engraving) key=miracles~~~~Act~8~6~images/bible_images/Miracles/miracles_template.html~7';
LOI[65] = 'image~Bible~Images~Healing Demoniac Daughter (engraving) key=miracles~~~~Act~8~13~images/bible_images/Miracles/miracles_template.html~7';
LOI[66] = 'image~Bible~Images~Deaf Man Hears (engraving) key=miracles~~~~Act~8~6~images/bible_images/Miracles/miracles_template.html~8';
LOI[67] = 'image~Bible~Images~Deaf Man Hears (engraving) key=miracles~~~~Act~8~13~images/bible_images/Miracles/miracles_template.html~8';
LOI[68] = 'image~Bible~Images~Man Born Blind Healed (engraving) key=miracles~~~~Act~8~6~images/bible_images/Miracles/miracles_template.html~9';
LOI[69] = 'image~Bible~Images~Man Born Blind Healed (engraving) key=miracles~~~~Act~8~13~images/bible_images/Miracles/miracles_template.html~9';
LOI[70] = 'image~Bible~Images~Jesus Healing Ten Lepers (engraving) key=miracles~~~~Act~8~6~images/bible_images/Miracles/miracles_template.html~10';
LOI[71] = 'image~Bible~Images~Jesus Healing Ten Lepers (engraving) key=miracles~~~~Act~8~13~images/bible_images/Miracles/miracles_template.html~10';
LOI[72] = 'image~Bible~Images~Jesus Heals Bartimaeus (engraving) key=miracles~~~~Act~8~6~images/bible_images/Miracles/miracles_template.html~11';
LOI[73] = 'image~Bible~Images~Jesus Heals Bartimaeus (engraving) key=miracles~~~~Act~8~13~images/bible_images/Miracles/miracles_template.html~11';
LOI[74] = 'image~Bible~Images~The Death of Stephen key=Stephen~~~~Act~8~2~images/bible_images/Acts/acts_template.html~1';
LOI[75] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~Act~8~1~images/bible_images/Acts/acts_template.html~1';
LOI[76] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~Act~8~3~images/bible_images/Acts/acts_template.html~1';
LOI[77] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~Act~8~1~images/bible_images/Acts/acts_template.html~2';
LOI[78] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~Act~8~3~images/bible_images/Acts/acts_template.html~2';
