var LOI = [];
LOI[0] = 'hymn~56~O SAVING VICTIM, OPEN WIDE~htm_o_s_osavingv.html';
LOI[1] = 'hymn~56~YESTERDAY, WITH EXULTATION~htm_y_e_yestexul.html';
LOI[2] = 'hymn~60~SAINT OF GOD, ELECT AND PRECIOUS~htm_s_a_saintgod.html';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Act~7~23~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Act~7~37~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Act~7~42~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Act~7~9~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Act~7~13~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Act~7~14~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Act~7~18~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Act~7~23~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Act~7~37~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Act~7~42~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Act~7~9~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Act~7~13~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Act~7~14~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Act~7~18~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~Act~7~58~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Act~7~23~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Act~7~37~images/maps/Otest/otest_template.html~3c';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Act~7~42~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Act~7~23~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Act~7~37~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Act~7~42~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Act~7~9~images/maps/Otest/otest_template.html~5';
LOI[25] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Act~7~10~images/maps/Otest/otest_template.html~5';
LOI[26] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Act~7~11~images/maps/Otest/otest_template.html~5';
LOI[27] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Act~7~12~images/maps/Otest/otest_template.html~5';
LOI[28] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Act~7~15~images/maps/Otest/otest_template.html~5';
LOI[29] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Act~7~17~images/maps/Otest/otest_template.html~5';
LOI[30] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Act~7~34~images/maps/Otest/otest_template.html~5';
LOI[31] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Act~7~36~images/maps/Otest/otest_template.html~5';
LOI[32] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Act~7~39~images/maps/Otest/otest_template.html~5';
LOI[33] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Act~7~40~images/maps/Otest/otest_template.html~5';
LOI[34] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Act~7~23~images/maps/Christ/christ_template.html~1';
LOI[35] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Act~7~37~images/maps/Christ/christ_template.html~1';
LOI[36] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Act~7~42~images/maps/Christ/christ_template.html~1';
LOI[37] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Act~7~2~images/places/Israel/israel_template.html~8';
LOI[38] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Act~7~8~images/places/Israel/israel_template.html~8';
LOI[39] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Act~7~16~images/places/Israel/israel_template.html~8';
LOI[40] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Act~7~17~images/places/Israel/israel_template.html~8';
LOI[41] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Act~7~32~images/places/Israel/israel_template.html~8';
LOI[42] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Act~7~2~images/bible_images/Moses/moses_template.html~3';
LOI[43] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Act~7~8~images/bible_images/Moses/moses_template.html~3';
LOI[44] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Act~7~16~images/bible_images/Moses/moses_template.html~3';
LOI[45] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Act~7~17~images/bible_images/Moses/moses_template.html~3';
LOI[46] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Act~7~32~images/bible_images/Moses/moses_template.html~3';
LOI[47] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Act~7~2~images/bible_images/Moses/moses_template.html~3i';
LOI[48] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Act~7~8~images/bible_images/Moses/moses_template.html~3i';
LOI[49] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Act~7~16~images/bible_images/Moses/moses_template.html~3i';
LOI[50] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Act~7~17~images/bible_images/Moses/moses_template.html~3i';
LOI[51] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Act~7~32~images/bible_images/Moses/moses_template.html~3i';
LOI[52] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~Act~7~8~images/bible_images/Moses/moses_template.html~3a';
LOI[53] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~Act~7~32~images/bible_images/Moses/moses_template.html~3a';
LOI[54] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Act~7~2~images/bible_images/Moses/moses_template.html~3a';
LOI[55] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Act~7~16~images/bible_images/Moses/moses_template.html~3a';
LOI[56] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Act~7~17~images/bible_images/Moses/moses_template.html~3a';
LOI[57] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Act~7~8~images/bible_images/Moses/moses_template.html~4';
LOI[58] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Act~7~32~images/bible_images/Moses/moses_template.html~4';
LOI[59] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Act~7~9~images/bible_images/Moses/moses_template.html~5';
LOI[60] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph,Pharaoh~~~~Act~7~13~images/bible_images/Moses/moses_template.html~5';
LOI[61] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Act~7~14~images/bible_images/Moses/moses_template.html~5';
LOI[62] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Act~7~18~images/bible_images/Moses/moses_template.html~5';
LOI[63] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Act~7~10~images/bible_images/Moses/moses_template.html~5';
LOI[64] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Act~7~20~images/bible_images/Moses/moses_template.html~6';
LOI[65] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Act~7~22~images/bible_images/Moses/moses_template.html~6';
LOI[66] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Act~7~29~images/bible_images/Moses/moses_template.html~6';
LOI[67] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Act~7~31~images/bible_images/Moses/moses_template.html~6';
LOI[68] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Act~7~32~images/bible_images/Moses/moses_template.html~6';
LOI[69] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Act~7~35~images/bible_images/Moses/moses_template.html~6';
LOI[70] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Act~7~37~images/bible_images/Moses/moses_template.html~6';
LOI[71] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Act~7~40~images/bible_images/Moses/moses_template.html~6';
LOI[72] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Act~7~44~images/bible_images/Moses/moses_template.html~6';
LOI[73] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Act~7~20~images/bible_images/Moses/moses_template.html~7';
LOI[74] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Act~7~22~images/bible_images/Moses/moses_template.html~7';
LOI[75] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Act~7~29~images/bible_images/Moses/moses_template.html~7';
LOI[76] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Act~7~31~images/bible_images/Moses/moses_template.html~7';
LOI[77] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Act~7~32~images/bible_images/Moses/moses_template.html~7';
LOI[78] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Act~7~35~images/bible_images/Moses/moses_template.html~7';
LOI[79] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Act~7~37~images/bible_images/Moses/moses_template.html~7';
LOI[80] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Act~7~40~images/bible_images/Moses/moses_template.html~7';
LOI[81] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Act~7~44~images/bible_images/Moses/moses_template.html~7';
LOI[82] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Act~7~20~images/bible_images/Moses/moses_template.html~9';
LOI[83] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Act~7~22~images/bible_images/Moses/moses_template.html~9';
LOI[84] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Act~7~29~images/bible_images/Moses/moses_template.html~9';
LOI[85] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Act~7~31~images/bible_images/Moses/moses_template.html~9';
LOI[86] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Act~7~32~images/bible_images/Moses/moses_template.html~9';
LOI[87] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Act~7~35~images/bible_images/Moses/moses_template.html~9';
LOI[88] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Act~7~37~images/bible_images/Moses/moses_template.html~9';
LOI[89] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Act~7~40~images/bible_images/Moses/moses_template.html~9';
LOI[90] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Act~7~44~images/bible_images/Moses/moses_template.html~9';
LOI[91] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Act~7~20~images/bible_images/Moses/moses_template.html~10';
LOI[92] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Act~7~22~images/bible_images/Moses/moses_template.html~10';
LOI[93] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Act~7~29~images/bible_images/Moses/moses_template.html~10';
LOI[94] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Act~7~31~images/bible_images/Moses/moses_template.html~10';
LOI[95] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Act~7~32~images/bible_images/Moses/moses_template.html~10';
LOI[96] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Act~7~35~images/bible_images/Moses/moses_template.html~10';
LOI[97] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Act~7~37~images/bible_images/Moses/moses_template.html~10';
LOI[98] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Act~7~40~images/bible_images/Moses/moses_template.html~10';
LOI[99] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Act~7~44~images/bible_images/Moses/moses_template.html~10';
LOI[100] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Act~7~20~images/bible_images/Moses/moses_template.html~11';
LOI[101] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Act~7~22~images/bible_images/Moses/moses_template.html~11';
LOI[102] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Act~7~29~images/bible_images/Moses/moses_template.html~11';
LOI[103] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Act~7~31~images/bible_images/Moses/moses_template.html~11';
LOI[104] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Act~7~32~images/bible_images/Moses/moses_template.html~11';
LOI[105] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Act~7~35~images/bible_images/Moses/moses_template.html~11';
LOI[106] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Act~7~37~images/bible_images/Moses/moses_template.html~11';
LOI[107] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Act~7~40~images/bible_images/Moses/moses_template.html~11';
LOI[108] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Act~7~44~images/bible_images/Moses/moses_template.html~11';
LOI[109] = 'image~Bible~Images~Saul and David (engraving) key=Saul~~~~Act~7~58~images/bible_images/Kings/kings_template.html~1';
LOI[110] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Act~7~45~images/bible_images/Kings/kings_template.html~1';
LOI[111] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Act~7~45~images/bible_images/Kings/kings_template.html~2';
LOI[112] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~Act~7~47~images/bible_images/Kings/kings_template.html~3';
LOI[113] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~Act~7~47~images/bible_images/Kings/kings_template.html~4';
LOI[114] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Act~7~43~images/bible_images/Kings/kings_template.html~7';
LOI[115] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~1';
LOI[116] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~2';
LOI[117] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~3';
LOI[118] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~4';
LOI[119] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~5';
LOI[120] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~6';
LOI[121] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~7';
LOI[122] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~8';
LOI[123] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~9';
LOI[124] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~10';
LOI[125] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~11';
LOI[126] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~12';
LOI[127] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~13';
LOI[128] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~14';
LOI[129] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~Act~7~47~images/bible_images/Song/song_template.html~15';
LOI[130] = 'image~Bible~Images~The Death of Stephen~~~~Act~7~59~images/bible_images/Acts/acts_template.html~1';
LOI[131] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~Act~7~58~images/bible_images/Acts/acts_template.html~1';
LOI[132] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~Act~7~58~images/bible_images/Acts/acts_template.html~2';
LOI[133] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Act~7~43~images/bible_images/Temple/temple_template.html~2';
LOI[134] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Act~7~44~images/bible_images/Temple/temple_template.html~2';
LOI[135] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Act~7~46~images/bible_images/Temple/temple_template.html~2';
LOI[136] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Act~7~43~images/bible_images/Temple/temple_template.html~3';
LOI[137] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Act~7~44~images/bible_images/Temple/temple_template.html~3';
LOI[138] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Act~7~46~images/bible_images/Temple/temple_template.html~3';
