var LOI = [];
LOI[0] = 'hymn~20~BECAUSE I KNEW NOT WHEN MY LIFE WAS GOOD~htm_b_i_biknwmlw.html';
LOI[1] = 'hymn~28~ALMOST~htm_a_l_almost.html';
LOI[2] = 'hymn~28~ALMOST PERSUADED~htm_a_l_almostpe.html';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~Act~26~14~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~26~4~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~26~10~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~26~20~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Act~26~21~images/maps/Otest/otest_template.html~3a';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~26~4~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~26~10~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~26~20~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Act~26~21~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~26~4~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~26~10~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~26~20~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~26~1~images/maps/Journeys/journeys_template.html~1';
LOI[16] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~26~24~images/maps/Journeys/journeys_template.html~1';
LOI[17] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~26~28~images/maps/Journeys/journeys_template.html~1';
LOI[18] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~26~29~images/maps/Journeys/journeys_template.html~1';
LOI[19] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~26~1~images/maps/Journeys/journeys_template.html~2';
LOI[20] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~26~24~images/maps/Journeys/journeys_template.html~2';
LOI[21] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~26~28~images/maps/Journeys/journeys_template.html~2';
LOI[22] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~26~29~images/maps/Journeys/journeys_template.html~2';
LOI[23] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~26~1~images/maps/Journeys/journeys_template.html~3';
LOI[24] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~26~24~images/maps/Journeys/journeys_template.html~3';
LOI[25] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~26~28~images/maps/Journeys/journeys_template.html~3';
LOI[26] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~26~29~images/maps/Journeys/journeys_template.html~3';
LOI[27] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~26~4~images/places/Israel/israel_template.html~11';
LOI[28] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~26~10~images/places/Israel/israel_template.html~11';
LOI[29] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~26~20~images/places/Israel/israel_template.html~11';
LOI[30] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~26~4~images/places/Israel/israel_template.html~12';
LOI[31] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~26~10~images/places/Israel/israel_template.html~12';
LOI[32] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~26~20~images/places/Israel/israel_template.html~12';
LOI[33] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~26~4~images/places/Israel/israel_template.html~13';
LOI[34] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~26~10~images/places/Israel/israel_template.html~13';
LOI[35] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~26~20~images/places/Israel/israel_template.html~13';
LOI[36] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~26~4~images/places/Israel/israel_template.html~14';
LOI[37] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~26~10~images/places/Israel/israel_template.html~14';
LOI[38] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~26~20~images/places/Israel/israel_template.html~14';
LOI[39] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~26~4~images/places/Israel/israel_template.html~17';
LOI[40] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~26~10~images/places/Israel/israel_template.html~17';
LOI[41] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~26~20~images/places/Israel/israel_template.html~17';
LOI[42] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Act~26~22~images/bible_images/Moses/moses_template.html~6';
LOI[43] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Act~26~22~images/bible_images/Moses/moses_template.html~7';
LOI[44] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Act~26~22~images/bible_images/Moses/moses_template.html~9';
LOI[45] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Act~26~22~images/bible_images/Moses/moses_template.html~10';
LOI[46] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Act~26~22~images/bible_images/Moses/moses_template.html~11';
LOI[47] = 'image~Bible~Images~Saul and David (engraving) key=Saul~~~~Act~26~14~images/bible_images/Kings/kings_template.html~1';
LOI[48] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~Act~26~14~images/bible_images/Acts/acts_template.html~1';
LOI[49] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~26~1~images/bible_images/Acts/acts_template.html~2';
LOI[50] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~26~24~images/bible_images/Acts/acts_template.html~2';
LOI[51] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~26~28~images/bible_images/Acts/acts_template.html~2';
LOI[52] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~26~29~images/bible_images/Acts/acts_template.html~2';
LOI[53] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~Act~26~14~images/bible_images/Acts/acts_template.html~2';
LOI[54] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Act~26~21~images/bible_images/Temple/temple_template.html~1';
LOI[55] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Act~26~21~images/bible_images/Temple/temple_template.html~2';
