var LOI = [];
LOI[0] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~19~21~images/maps/Otest/otest_template.html~3a';
LOI[1] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Act~19~27~images/maps/Otest/otest_template.html~3a';
LOI[2] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~19~21~images/maps/Otest/otest_template.html~3b';
LOI[3] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Act~19~27~images/maps/Otest/otest_template.html~3b';
LOI[4] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~19~21~images/maps/Otest/otest_template.html~4';
LOI[5] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~19~1~images/maps/Journeys/journeys_template.html~1';
LOI[6] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~19~4~images/maps/Journeys/journeys_template.html~1';
LOI[7] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~19~6~images/maps/Journeys/journeys_template.html~1';
LOI[8] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~19~11~images/maps/Journeys/journeys_template.html~1';
LOI[9] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~19~13~images/maps/Journeys/journeys_template.html~1';
LOI[10] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~19~15~images/maps/Journeys/journeys_template.html~1';
LOI[11] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~19~21~images/maps/Journeys/journeys_template.html~1';
LOI[12] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~19~26~images/maps/Journeys/journeys_template.html~1';
LOI[13] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~19~30~images/maps/Journeys/journeys_template.html~1';
LOI[14] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~19~1~images/maps/Journeys/journeys_template.html~2';
LOI[15] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~19~4~images/maps/Journeys/journeys_template.html~2';
LOI[16] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~19~6~images/maps/Journeys/journeys_template.html~2';
LOI[17] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~19~11~images/maps/Journeys/journeys_template.html~2';
LOI[18] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~19~13~images/maps/Journeys/journeys_template.html~2';
LOI[19] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~19~15~images/maps/Journeys/journeys_template.html~2';
LOI[20] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul,Achaia~~~~Act~19~21~images/maps/Journeys/journeys_template.html~2';
LOI[21] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul,Ephesus~~~~Act~19~26~images/maps/Journeys/journeys_template.html~2';
LOI[22] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~Act~19~30~images/maps/Journeys/journeys_template.html~2';
LOI[23] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Timotheus~~~~Act~19~22~images/maps/Journeys/journeys_template.html~2';
LOI[24] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Ephesus~~~~Act~19~17~images/maps/Journeys/journeys_template.html~2';
LOI[25] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Ephesus~~~~Act~19~35~images/maps/Journeys/journeys_template.html~2';
LOI[26] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~1~images/maps/Journeys/journeys_template.html~3';
LOI[27] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~2~images/maps/Journeys/journeys_template.html~3';
LOI[28] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~3~images/maps/Journeys/journeys_template.html~3';
LOI[29] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~4~images/maps/Journeys/journeys_template.html~3';
LOI[30] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~5~images/maps/Journeys/journeys_template.html~3';
LOI[31] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~6~images/maps/Journeys/journeys_template.html~3';
LOI[32] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~7~images/maps/Journeys/journeys_template.html~3';
LOI[33] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~8~images/maps/Journeys/journeys_template.html~3';
LOI[34] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~9~images/maps/Journeys/journeys_template.html~3';
LOI[35] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~10~images/maps/Journeys/journeys_template.html~3';
LOI[36] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~11~images/maps/Journeys/journeys_template.html~3';
LOI[37] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~12~images/maps/Journeys/journeys_template.html~3';
LOI[38] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~13~images/maps/Journeys/journeys_template.html~3';
LOI[39] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~14~images/maps/Journeys/journeys_template.html~3';
LOI[40] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~15~images/maps/Journeys/journeys_template.html~3';
LOI[41] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~16~images/maps/Journeys/journeys_template.html~3';
LOI[42] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~17~images/maps/Journeys/journeys_template.html~3';
LOI[43] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~18~images/maps/Journeys/journeys_template.html~3';
LOI[44] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~19~images/maps/Journeys/journeys_template.html~3';
LOI[45] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~20~images/maps/Journeys/journeys_template.html~3';
LOI[46] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~21~images/maps/Journeys/journeys_template.html~3';
LOI[47] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~22~images/maps/Journeys/journeys_template.html~3';
LOI[48] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~23~images/maps/Journeys/journeys_template.html~3';
LOI[49] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~24~images/maps/Journeys/journeys_template.html~3';
LOI[50] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~25~images/maps/Journeys/journeys_template.html~3';
LOI[51] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~26~images/maps/Journeys/journeys_template.html~3';
LOI[52] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~27~images/maps/Journeys/journeys_template.html~3';
LOI[53] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~28~images/maps/Journeys/journeys_template.html~3';
LOI[54] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~29~images/maps/Journeys/journeys_template.html~3';
LOI[55] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~30~images/maps/Journeys/journeys_template.html~3';
LOI[56] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~31~images/maps/Journeys/journeys_template.html~3';
LOI[57] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~32~images/maps/Journeys/journeys_template.html~3';
LOI[58] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~33~images/maps/Journeys/journeys_template.html~3';
LOI[59] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~34~images/maps/Journeys/journeys_template.html~3';
LOI[60] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~35~images/maps/Journeys/journeys_template.html~3';
LOI[61] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~36~images/maps/Journeys/journeys_template.html~3';
LOI[62] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~37~images/maps/Journeys/journeys_template.html~3';
LOI[63] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~38~images/maps/Journeys/journeys_template.html~3';
LOI[64] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~39~images/maps/Journeys/journeys_template.html~3';
LOI[65] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~40~images/maps/Journeys/journeys_template.html~3';
LOI[66] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~19~41~images/maps/Journeys/journeys_template.html~3';
LOI[67] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~19~21~images/places/Israel/israel_template.html~11';
LOI[68] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~19~21~images/places/Israel/israel_template.html~12';
LOI[69] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~19~21~images/places/Israel/israel_template.html~13';
LOI[70] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~19~21~images/places/Israel/israel_template.html~14';
LOI[71] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~19~21~images/places/Israel/israel_template.html~17';
LOI[72] = 'image~Bible~Images~The Leper Healed (engraving) key=miracles~~~~Act~19~11~images/bible_images/Miracles/miracles_template.html~1';
LOI[73] = 'image~Bible~Images~Man With Palsy Healed (engraving) key=miracles~~~~Act~19~11~images/bible_images/Miracles/miracles_template.html~2';
LOI[74] = 'image~Bible~Images~The Raising of Jairus\' Daughter (engraving) key=miracles~~~~Act~19~11~images/bible_images/Miracles/miracles_template.html~3';
LOI[75] = 'image~Bible~Images~The Paralytic Healed (engraving) key=miracles~~~~Act~19~11~images/bible_images/Miracles/miracles_template.html~4';
LOI[76] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving) key=miracles~~~~Act~19~11~images/bible_images/Miracles/miracles_template.html~5';
LOI[77] = 'image~Bible~Images~Jesus Walking on the Sea (engraving) key=miracles~~~~Act~19~11~images/bible_images/Miracles/miracles_template.html~6';
LOI[78] = 'image~Bible~Images~Healing Demoniac Daughter (engraving) key=miracles~~~~Act~19~11~images/bible_images/Miracles/miracles_template.html~7';
LOI[79] = 'image~Bible~Images~Deaf Man Hears (engraving) key=miracles~~~~Act~19~11~images/bible_images/Miracles/miracles_template.html~8';
LOI[80] = 'image~Bible~Images~Man Born Blind Healed (engraving) key=miracles~~~~Act~19~11~images/bible_images/Miracles/miracles_template.html~9';
LOI[81] = 'image~Bible~Images~Jesus Healing Ten Lepers (engraving) key=miracles~~~~Act~19~11~images/bible_images/Miracles/miracles_template.html~10';
LOI[82] = 'image~Bible~Images~Jesus Heals Bartimaeus (engraving) key=miracles~~~~Act~19~11~images/bible_images/Miracles/miracles_template.html~11';
LOI[83] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~19~1~images/bible_images/Acts/acts_template.html~2';
LOI[84] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~19~4~images/bible_images/Acts/acts_template.html~2';
LOI[85] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~19~6~images/bible_images/Acts/acts_template.html~2';
LOI[86] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~19~11~images/bible_images/Acts/acts_template.html~2';
LOI[87] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~19~13~images/bible_images/Acts/acts_template.html~2';
LOI[88] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~19~15~images/bible_images/Acts/acts_template.html~2';
LOI[89] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~19~21~images/bible_images/Acts/acts_template.html~2';
LOI[90] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~19~26~images/bible_images/Acts/acts_template.html~2';
LOI[91] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~19~30~images/bible_images/Acts/acts_template.html~2';
LOI[92] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Act~19~27~images/bible_images/Temple/temple_template.html~1';
LOI[93] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Act~19~27~images/bible_images/Temple/temple_template.html~2';
