var LOI = [];
LOI[0] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Act~18~21~images/maps/Otest/otest_template.html~3a';
LOI[1] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Act~18~21~images/maps/Otest/otest_template.html~3b';
LOI[2] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Act~18~21~images/maps/Otest/otest_template.html~4';
LOI[3] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~18~1~images/maps/Journeys/journeys_template.html~1';
LOI[4] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~18~5~images/maps/Journeys/journeys_template.html~1';
LOI[5] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~18~9~images/maps/Journeys/journeys_template.html~1';
LOI[6] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~18~12~images/maps/Journeys/journeys_template.html~1';
LOI[7] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~18~14~images/maps/Journeys/journeys_template.html~1';
LOI[8] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Act~18~18~images/maps/Journeys/journeys_template.html~1';
LOI[9] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Antioch~~~~Act~18~22~images/maps/Journeys/journeys_template.html~1';
LOI[10] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~1~images/maps/Journeys/journeys_template.html~2';
LOI[11] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~2~images/maps/Journeys/journeys_template.html~2';
LOI[12] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~3~images/maps/Journeys/journeys_template.html~2';
LOI[13] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~4~images/maps/Journeys/journeys_template.html~2';
LOI[14] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~5~images/maps/Journeys/journeys_template.html~2';
LOI[15] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~6~images/maps/Journeys/journeys_template.html~2';
LOI[16] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~7~images/maps/Journeys/journeys_template.html~2';
LOI[17] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~8~images/maps/Journeys/journeys_template.html~2';
LOI[18] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~9~images/maps/Journeys/journeys_template.html~2';
LOI[19] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~10~images/maps/Journeys/journeys_template.html~2';
LOI[20] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~11~images/maps/Journeys/journeys_template.html~2';
LOI[21] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~12~images/maps/Journeys/journeys_template.html~2';
LOI[22] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~13~images/maps/Journeys/journeys_template.html~2';
LOI[23] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~14~images/maps/Journeys/journeys_template.html~2';
LOI[24] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~15~images/maps/Journeys/journeys_template.html~2';
LOI[25] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~16~images/maps/Journeys/journeys_template.html~2';
LOI[26] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~17~images/maps/Journeys/journeys_template.html~2';
LOI[27] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~18~images/maps/Journeys/journeys_template.html~2';
LOI[28] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~19~images/maps/Journeys/journeys_template.html~2';
LOI[29] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~20~images/maps/Journeys/journeys_template.html~2';
LOI[30] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~21~images/maps/Journeys/journeys_template.html~2';
LOI[31] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~Act~18~22~images/maps/Journeys/journeys_template.html~2';
LOI[32] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Aquila,Priscilla~~~~Act~18~26~images/maps/Journeys/journeys_template.html~2';
LOI[33] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Phrygia,Galatia~~~~Act~18~23~images/maps/Journeys/journeys_template.html~2';
LOI[34] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Ephesus~~~~Act~18~24~images/maps/Journeys/journeys_template.html~2';
LOI[35] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Achaia~~~~Act~18~27~images/maps/Journeys/journeys_template.html~2';
LOI[36] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~18~23~images/maps/Journeys/journeys_template.html~3';
LOI[37] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~18~24~images/maps/Journeys/journeys_template.html~3';
LOI[38] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~18~25~images/maps/Journeys/journeys_template.html~3';
LOI[39] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~18~26~images/maps/Journeys/journeys_template.html~3';
LOI[40] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~18~27~images/maps/Journeys/journeys_template.html~3';
LOI[41] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~Act~18~28~images/maps/Journeys/journeys_template.html~3';
LOI[42] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul,Corinth~~~~Act~18~1~images/maps/Journeys/journeys_template.html~3';
LOI[43] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul,Macedonia~~~~Act~18~5~images/maps/Journeys/journeys_template.html~3';
LOI[44] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~18~9~images/maps/Journeys/journeys_template.html~3';
LOI[45] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul,Achaia~~~~Act~18~12~images/maps/Journeys/journeys_template.html~3';
LOI[46] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~18~14~images/maps/Journeys/journeys_template.html~3';
LOI[47] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~Act~18~18~images/maps/Journeys/journeys_template.html~3';
LOI[48] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Antioch~~~~Act~18~22~images/maps/Journeys/journeys_template.html~3';
LOI[49] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Ephesus~~~~Act~18~19~images/maps/Journeys/journeys_template.html~3';
LOI[50] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Ephesus~~~~Act~18~21~images/maps/Journeys/journeys_template.html~3';
LOI[51] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Act~18~21~images/places/Israel/israel_template.html~11';
LOI[52] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Act~18~21~images/places/Israel/israel_template.html~12';
LOI[53] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Act~18~21~images/places/Israel/israel_template.html~13';
LOI[54] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Act~18~21~images/places/Israel/israel_template.html~14';
LOI[55] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Act~18~21~images/places/Israel/israel_template.html~17';
LOI[56] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~18~1~images/bible_images/Acts/acts_template.html~2';
LOI[57] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~18~5~images/bible_images/Acts/acts_template.html~2';
LOI[58] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~18~9~images/bible_images/Acts/acts_template.html~2';
LOI[59] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~18~12~images/bible_images/Acts/acts_template.html~2';
LOI[60] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~18~14~images/bible_images/Acts/acts_template.html~2';
LOI[61] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Act~18~18~images/bible_images/Acts/acts_template.html~2';
