var LOI = [];
LOI[0] = 'hymn~24~ON THIS NIGHT, MOST HOLY~htm_o_n_onthisni.html';
LOI[1] = 'hymn~24~SEE THE DESTINED DAY ARISE~htm_s_e_seetdest.html';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Act~3~12~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Act~3~12~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Samuel~~~~Act~3~24~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Act~3~1~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Act~3~2~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Act~3~3~images/maps/Otest/otest_template.html~3a';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Act~3~8~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Act~3~10~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Act~3~1~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Act~3~2~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Act~3~3~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Act~3~8~images/maps/Otest/otest_template.html~3b';
LOI[14] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Act~3~10~images/maps/Otest/otest_template.html~3b';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Act~3~12~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Act~3~12~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Act~3~12~images/maps/Christ/christ_template.html~1';
LOI[18] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Act~3~13~images/places/Israel/israel_template.html~8';
LOI[19] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Act~3~25~images/places/Israel/israel_template.html~8';
LOI[20] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Act~3~13~images/bible_images/Moses/moses_template.html~3';
LOI[21] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Act~3~25~images/bible_images/Moses/moses_template.html~3';
LOI[22] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Act~3~13~images/bible_images/Moses/moses_template.html~3i';
LOI[23] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Act~3~25~images/bible_images/Moses/moses_template.html~3i';
LOI[24] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~Act~3~13~images/bible_images/Moses/moses_template.html~3a';
LOI[25] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Act~3~25~images/bible_images/Moses/moses_template.html~3a';
LOI[26] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Act~3~13~images/bible_images/Moses/moses_template.html~4';
LOI[27] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Act~3~22~images/bible_images/Moses/moses_template.html~6';
LOI[28] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Act~3~22~images/bible_images/Moses/moses_template.html~7';
LOI[29] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Act~3~22~images/bible_images/Moses/moses_template.html~9';
LOI[30] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Act~3~22~images/bible_images/Moses/moses_template.html~10';
LOI[31] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Act~3~22~images/bible_images/Moses/moses_template.html~11';
LOI[32] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Act~3~1~images/bible_images/Temple/temple_template.html~1';
LOI[33] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Act~3~2~images/bible_images/Temple/temple_template.html~1';
LOI[34] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Act~3~3~images/bible_images/Temple/temple_template.html~1';
LOI[35] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Act~3~8~images/bible_images/Temple/temple_template.html~1';
LOI[36] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Act~3~10~images/bible_images/Temple/temple_template.html~1';
LOI[37] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Act~3~1~images/bible_images/Temple/temple_template.html~2';
LOI[38] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Act~3~2~images/bible_images/Temple/temple_template.html~2';
LOI[39] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Act~3~3~images/bible_images/Temple/temple_template.html~2';
LOI[40] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Act~3~8~images/bible_images/Temple/temple_template.html~2';
LOI[41] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Act~3~10~images/bible_images/Temple/temple_template.html~2';
