var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Amo~3~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Amo~3~12~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Amo~3~14~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Amo~3~1~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Amo~3~12~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Amo~3~14~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Amo~3~1~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Amo~3~12~images/maps/Otest/otest_template.html~3c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Amo~3~14~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Amo~3~1~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Amo~3~12~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Amo~3~14~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Amo~3~1~images/maps/Otest/otest_template.html~5';
LOI[13] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Amo~3~9~images/maps/Otest/otest_template.html~5';
LOI[14] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Amo~3~1~images/maps/Christ/christ_template.html~1';
LOI[15] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel,Samaria~~~~Amo~3~12~images/maps/Christ/christ_template.html~1';
LOI[16] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Amo~3~14~images/maps/Christ/christ_template.html~1';
LOI[17] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Amo~3~9~images/maps/Christ/christ_template.html~1';
