var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Amo~8~2~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Dan~~~~Amo~8~14~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Amo~8~2~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Dan~~~~Amo~8~14~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Amo~8~3~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Amo~8~3~images/maps/Otest/otest_template.html~3b';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Amo~8~2~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Amo~8~2~images/maps/Otest/otest_template.html~4';
LOI[8] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Amo~8~8~images/maps/Otest/otest_template.html~5';
LOI[9] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Amo~8~2~images/maps/Christ/christ_template.html~1';
LOI[10] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Amo~8~14~images/maps/Christ/christ_template.html~1';
LOI[11] = 'image~Bible~Places~Beer-Sheeba (engraving) key=Beersheba~~~~Amo~8~14~images/places/Israel/israel_template.html~7';
LOI[12] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Amo~8~3~images/bible_images/Temple/temple_template.html~1';
LOI[13] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Amo~8~3~images/bible_images/Temple/temple_template.html~2';
