var LOI = [];
LOI[0] = 'hymn~5~NOW BLESSING, HONOR, GLORY, PRAISE~htm_n_o_now_bhgp.html';
LOI[1] = 'hymn~5~STAND UP AND BLESS THE LORD~htm_s_t_standup.html';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Neh~9~1~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Neh~9~2~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Neh~9~1~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Neh~9~2~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Og~~~~Neh~9~22~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~9~1~images/maps/Otest/otest_template.html~3c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~9~2~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~9~1~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~9~2~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Neh~9~9~images/maps/Otest/otest_template.html~5';
LOI[12] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Neh~9~18~images/maps/Otest/otest_template.html~5';
LOI[13] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Sinai~~~~Neh~9~13~images/maps/Otest/otest_template.html~5';
LOI[14] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~9~1~images/maps/Christ/christ_template.html~1';
LOI[15] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~9~2~images/maps/Christ/christ_template.html~1';
LOI[16] = 'image~Bible~Maps~Divisions of Palestine (map) key=Bashan~~~~Neh~9~22~images/maps/Christ/christ_template.html~1';
LOI[17] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Neh~9~7~images/places/Israel/israel_template.html~8';
LOI[18] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Neh~9~7~images/bible_images/Moses/moses_template.html~3';
LOI[19] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Neh~9~7~images/bible_images/Moses/moses_template.html~3i';
LOI[20] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Neh~9~7~images/bible_images/Moses/moses_template.html~3a';
LOI[21] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Neh~9~10~images/bible_images/Moses/moses_template.html~5';
LOI[22] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Neh~9~14~images/bible_images/Moses/moses_template.html~6';
LOI[23] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Neh~9~14~images/bible_images/Moses/moses_template.html~7';
LOI[24] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Neh~9~14~images/bible_images/Moses/moses_template.html~9';
LOI[25] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Neh~9~14~images/bible_images/Moses/moses_template.html~10';
LOI[26] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Neh~9~14~images/bible_images/Moses/moses_template.html~11';
