var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Elam~~~~Neh~10~14~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Neh~10~33~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Levi~~~~Neh~10~39~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Neh~10~33~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Levi~~~~Neh~10~39~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~10~33~images/maps/Otest/otest_template.html~3c';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~10~39~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~10~33~images/maps/Otest/otest_template.html~4';
LOI[8] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~10~39~images/maps/Otest/otest_template.html~4';
LOI[9] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~10~33~images/maps/Christ/christ_template.html~1';
LOI[10] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~10~39~images/maps/Christ/christ_template.html~1';
LOI[11] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Neh~10~29~images/bible_images/Moses/moses_template.html~6';
LOI[12] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Neh~10~29~images/bible_images/Moses/moses_template.html~7';
LOI[13] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Neh~10~29~images/bible_images/Moses/moses_template.html~9';
LOI[14] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Neh~10~29~images/bible_images/Moses/moses_template.html~10';
LOI[15] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Neh~10~29~images/bible_images/Moses/moses_template.html~11';
LOI[16] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Daniel~~~~Neh~10~6~images/bible_images/Daniel/daniel_template.html~1';
LOI[17] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Neh~10~6~images/bible_images/Daniel/daniel_template.html~2';
LOI[18] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Neh~10~6~images/bible_images/Daniel/daniel_template.html~3';
LOI[19] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Neh~10~6~images/bible_images/Daniel/daniel_template.html~4';
LOI[20] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Neh~10~6~images/bible_images/Daniel/daniel_template.html~5';
LOI[21] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Neh~10~6~images/bible_images/Daniel/daniel_template.html~6';
