var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~4~10~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~4~16~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~4~10~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~4~16~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~4~7~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~4~8~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~4~22~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~4~7~images/maps/Otest/otest_template.html~3b';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~4~8~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~4~22~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~4~7~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~4~8~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~4~22~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Divisions of Palestine (map) key=Samaria~~~~Neh~4~2~images/maps/Christ/christ_template.html~1';
LOI[14] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~4~7~images/places/Israel/israel_template.html~11';
LOI[15] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~4~8~images/places/Israel/israel_template.html~11';
LOI[16] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~4~22~images/places/Israel/israel_template.html~11';
LOI[17] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~4~7~images/places/Israel/israel_template.html~12';
LOI[18] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~4~8~images/places/Israel/israel_template.html~12';
LOI[19] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~4~22~images/places/Israel/israel_template.html~12';
LOI[20] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~4~7~images/places/Israel/israel_template.html~13';
LOI[21] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~4~8~images/places/Israel/israel_template.html~13';
LOI[22] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~4~22~images/places/Israel/israel_template.html~13';
LOI[23] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~4~7~images/places/Israel/israel_template.html~14';
LOI[24] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~4~8~images/places/Israel/israel_template.html~14';
LOI[25] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~4~22~images/places/Israel/israel_template.html~14';
LOI[26] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~4~7~images/places/Israel/israel_template.html~17';
LOI[27] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~4~8~images/places/Israel/israel_template.html~17';
LOI[28] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~4~22~images/places/Israel/israel_template.html~17';
