var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Eber~~~~Neh~12~20~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Elam~~~~Neh~12~42~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Neh~12~47~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Levi~~~~Neh~12~23~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~12~8~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~12~31~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~12~32~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah,Benjamin~~~~Neh~12~34~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~12~36~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~12~44~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Neh~12~14~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Neh~12~39~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Neh~12~47~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Levi~~~~Neh~12~23~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~12~8~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~12~31~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~12~32~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah,Benjamin~~~~Neh~12~34~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~12~36~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~12~44~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Neh~12~14~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~Neh~12~39~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~12~27~images/maps/Otest/otest_template.html~3a';
LOI[23] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~12~28~images/maps/Otest/otest_template.html~3a';
LOI[24] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~12~29~images/maps/Otest/otest_template.html~3a';
LOI[25] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~12~43~images/maps/Otest/otest_template.html~3a';
LOI[26] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~12~27~images/maps/Otest/otest_template.html~3b';
LOI[27] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~12~28~images/maps/Otest/otest_template.html~3b';
LOI[28] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~12~29~images/maps/Otest/otest_template.html~3b';
LOI[29] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~12~43~images/maps/Otest/otest_template.html~3b';
LOI[30] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~12~47~images/maps/Otest/otest_template.html~3c';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~12~47~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~12~27~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~12~28~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~12~29~images/maps/Otest/otest_template.html~4';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~12~43~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~12~47~images/maps/Christ/christ_template.html~1';
LOI[37] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~12~27~images/places/Israel/israel_template.html~11';
LOI[38] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~12~28~images/places/Israel/israel_template.html~11';
LOI[39] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~12~29~images/places/Israel/israel_template.html~11';
LOI[40] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~12~43~images/places/Israel/israel_template.html~11';
LOI[41] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~12~27~images/places/Israel/israel_template.html~12';
LOI[42] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~12~28~images/places/Israel/israel_template.html~12';
LOI[43] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~12~29~images/places/Israel/israel_template.html~12';
LOI[44] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~12~43~images/places/Israel/israel_template.html~12';
LOI[45] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~12~27~images/places/Israel/israel_template.html~13';
LOI[46] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~12~28~images/places/Israel/israel_template.html~13';
LOI[47] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~12~29~images/places/Israel/israel_template.html~13';
LOI[48] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~12~43~images/places/Israel/israel_template.html~13';
LOI[49] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~12~27~images/places/Israel/israel_template.html~14';
LOI[50] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~12~28~images/places/Israel/israel_template.html~14';
LOI[51] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~12~29~images/places/Israel/israel_template.html~14';
LOI[52] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~12~43~images/places/Israel/israel_template.html~14';
LOI[53] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~12~27~images/places/Israel/israel_template.html~17';
LOI[54] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~12~28~images/places/Israel/israel_template.html~17';
LOI[55] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~12~29~images/places/Israel/israel_template.html~17';
LOI[56] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~12~43~images/places/Israel/israel_template.html~17';
LOI[57] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Neh~12~14~images/bible_images/Moses/moses_template.html~5';
LOI[58] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Neh~12~24~images/bible_images/Kings/kings_template.html~1';
LOI[59] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Neh~12~36~images/bible_images/Kings/kings_template.html~1';
LOI[60] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Neh~12~37~images/bible_images/Kings/kings_template.html~1';
LOI[61] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Neh~12~45~images/bible_images/Kings/kings_template.html~1';
LOI[62] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Neh~12~46~images/bible_images/Kings/kings_template.html~1';
LOI[63] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Neh~12~24~images/bible_images/Kings/kings_template.html~2';
LOI[64] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Neh~12~36~images/bible_images/Kings/kings_template.html~2';
LOI[65] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Neh~12~37~images/bible_images/Kings/kings_template.html~2';
LOI[66] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Neh~12~45~images/bible_images/Kings/kings_template.html~2';
LOI[67] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Neh~12~46~images/bible_images/Kings/kings_template.html~2';
LOI[68] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~Neh~12~45~images/bible_images/Kings/kings_template.html~3';
LOI[69] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~Neh~12~45~images/bible_images/Kings/kings_template.html~4';
LOI[70] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~1';
LOI[71] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~2';
LOI[72] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~3';
LOI[73] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~4';
LOI[74] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~5';
LOI[75] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~6';
LOI[76] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~7';
LOI[77] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~8';
LOI[78] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~9';
LOI[79] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~10';
LOI[80] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~11';
LOI[81] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~12';
LOI[82] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~13';
LOI[83] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~14';
LOI[84] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~Neh~12~45~images/bible_images/Song/song_template.html~15';
