var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Neh~8~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Neh~8~14~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Neh~8~17~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Neh~8~16~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Neh~8~1~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Neh~8~14~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Neh~8~17~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~Neh~8~16~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~8~15~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~8~15~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~8~1~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~8~14~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~8~17~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~8~1~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~8~14~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~8~17~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~8~15~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~8~1~images/maps/Christ/christ_template.html~1';
LOI[18] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~8~14~images/maps/Christ/christ_template.html~1';
LOI[19] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~8~17~images/maps/Christ/christ_template.html~1';
LOI[20] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~8~15~images/places/Israel/israel_template.html~11';
LOI[21] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~8~15~images/places/Israel/israel_template.html~12';
LOI[22] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~8~15~images/places/Israel/israel_template.html~13';
LOI[23] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~8~15~images/places/Israel/israel_template.html~14';
LOI[24] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~8~15~images/places/Israel/israel_template.html~17';
LOI[25] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Neh~8~1~images/bible_images/Moses/moses_template.html~6';
LOI[26] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Neh~8~14~images/bible_images/Moses/moses_template.html~6';
LOI[27] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Neh~8~1~images/bible_images/Moses/moses_template.html~7';
LOI[28] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Neh~8~14~images/bible_images/Moses/moses_template.html~7';
LOI[29] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Neh~8~1~images/bible_images/Moses/moses_template.html~9';
LOI[30] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Neh~8~14~images/bible_images/Moses/moses_template.html~9';
LOI[31] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Neh~8~1~images/bible_images/Moses/moses_template.html~10';
LOI[32] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Neh~8~14~images/bible_images/Moses/moses_template.html~10';
LOI[33] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Neh~8~1~images/bible_images/Moses/moses_template.html~11';
LOI[34] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Neh~8~14~images/bible_images/Moses/moses_template.html~11';
