var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~Neh~3~23~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~Neh~3~23~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~3~8~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~3~9~images/maps/Otest/otest_template.html~3a';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~3~12~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~3~8~images/maps/Otest/otest_template.html~3b';
LOI[6] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~3~9~images/maps/Otest/otest_template.html~3b';
LOI[7] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~3~12~images/maps/Otest/otest_template.html~3b';
LOI[8] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~3~8~images/maps/Otest/otest_template.html~4';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~3~9~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~3~12~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~Neh~3~2~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Neh~3~2~images/places/Israel/israel_template.html~9';
LOI[13] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~3~8~images/places/Israel/israel_template.html~11';
LOI[14] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~3~9~images/places/Israel/israel_template.html~11';
LOI[15] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~3~12~images/places/Israel/israel_template.html~11';
LOI[16] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~3~8~images/places/Israel/israel_template.html~12';
LOI[17] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~3~9~images/places/Israel/israel_template.html~12';
LOI[18] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~3~12~images/places/Israel/israel_template.html~12';
LOI[19] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~3~8~images/places/Israel/israel_template.html~13';
LOI[20] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~3~9~images/places/Israel/israel_template.html~13';
LOI[21] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~3~12~images/places/Israel/israel_template.html~13';
LOI[22] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~3~8~images/places/Israel/israel_template.html~14';
LOI[23] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~3~9~images/places/Israel/israel_template.html~14';
LOI[24] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~3~12~images/places/Israel/israel_template.html~14';
LOI[25] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~3~8~images/places/Israel/israel_template.html~17';
LOI[26] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~3~9~images/places/Israel/israel_template.html~17';
LOI[27] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~3~12~images/places/Israel/israel_template.html~17';
LOI[28] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Neh~3~15~images/bible_images/Kings/kings_template.html~1';
LOI[29] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Neh~3~16~images/bible_images/Kings/kings_template.html~1';
LOI[30] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Neh~3~15~images/bible_images/Kings/kings_template.html~2';
LOI[31] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Neh~3~16~images/bible_images/Kings/kings_template.html~2';
