var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Neh~13~2~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Neh~13~3~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Neh~13~18~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Neh~13~26~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~13~12~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~13~15~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~13~16~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~13~17~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Neh~13~2~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Neh~13~3~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Neh~13~18~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Neh~13~26~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~13~12~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~13~15~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~13~16~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~13~17~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~13~6~images/maps/Otest/otest_template.html~3a';
LOI[17] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~13~7~images/maps/Otest/otest_template.html~3a';
LOI[18] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~13~15~images/maps/Otest/otest_template.html~3a';
LOI[19] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~13~16~images/maps/Otest/otest_template.html~3a';
LOI[20] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~13~19~images/maps/Otest/otest_template.html~3a';
LOI[21] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~13~20~images/maps/Otest/otest_template.html~3a';
LOI[22] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~13~6~images/maps/Otest/otest_template.html~3b';
LOI[23] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~13~7~images/maps/Otest/otest_template.html~3b';
LOI[24] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~13~15~images/maps/Otest/otest_template.html~3b';
LOI[25] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~13~16~images/maps/Otest/otest_template.html~3b';
LOI[26] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~13~19~images/maps/Otest/otest_template.html~3b';
LOI[27] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~13~20~images/maps/Otest/otest_template.html~3b';
LOI[28] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~13~2~images/maps/Otest/otest_template.html~3c';
LOI[29] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~13~3~images/maps/Otest/otest_template.html~3c';
LOI[30] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~13~18~images/maps/Otest/otest_template.html~3c';
LOI[31] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~13~26~images/maps/Otest/otest_template.html~3c';
LOI[32] = 'image~Bible~Maps~Middle Palestine (map) key=Tyre~~~~Neh~13~16~images/maps/Otest/otest_template.html~3c';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~13~2~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~13~3~images/maps/Otest/otest_template.html~4';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~13~18~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~13~26~images/maps/Otest/otest_template.html~4';
LOI[37] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~13~6~images/maps/Otest/otest_template.html~4';
LOI[38] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~13~7~images/maps/Otest/otest_template.html~4';
LOI[39] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~13~15~images/maps/Otest/otest_template.html~4';
LOI[40] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~13~16~images/maps/Otest/otest_template.html~4';
LOI[41] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~13~19~images/maps/Otest/otest_template.html~4';
LOI[42] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~13~20~images/maps/Otest/otest_template.html~4';
LOI[43] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Neh~13~23~images/maps/Otest/otest_template.html~4';
LOI[44] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~13~2~images/maps/Christ/christ_template.html~1';
LOI[45] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~13~3~images/maps/Christ/christ_template.html~1';
LOI[46] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~13~18~images/maps/Christ/christ_template.html~1';
LOI[47] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~13~26~images/maps/Christ/christ_template.html~1';
LOI[48] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Tyre~~~~Neh~13~16~images/maps/Journeys/journeys_template.html~3';
LOI[49] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~13~6~images/places/Israel/israel_template.html~11';
LOI[50] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~13~7~images/places/Israel/israel_template.html~11';
LOI[51] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~13~15~images/places/Israel/israel_template.html~11';
LOI[52] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~13~16~images/places/Israel/israel_template.html~11';
LOI[53] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~13~19~images/places/Israel/israel_template.html~11';
LOI[54] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~13~20~images/places/Israel/israel_template.html~11';
LOI[55] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~13~6~images/places/Israel/israel_template.html~12';
LOI[56] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~13~7~images/places/Israel/israel_template.html~12';
LOI[57] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~13~15~images/places/Israel/israel_template.html~12';
LOI[58] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~13~16~images/places/Israel/israel_template.html~12';
LOI[59] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~13~19~images/places/Israel/israel_template.html~12';
LOI[60] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~13~20~images/places/Israel/israel_template.html~12';
LOI[61] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~13~6~images/places/Israel/israel_template.html~13';
LOI[62] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~13~7~images/places/Israel/israel_template.html~13';
LOI[63] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~13~15~images/places/Israel/israel_template.html~13';
LOI[64] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~13~16~images/places/Israel/israel_template.html~13';
LOI[65] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~13~19~images/places/Israel/israel_template.html~13';
LOI[66] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~13~20~images/places/Israel/israel_template.html~13';
LOI[67] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~13~6~images/places/Israel/israel_template.html~14';
LOI[68] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~13~7~images/places/Israel/israel_template.html~14';
LOI[69] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~13~15~images/places/Israel/israel_template.html~14';
LOI[70] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~13~16~images/places/Israel/israel_template.html~14';
LOI[71] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~13~19~images/places/Israel/israel_template.html~14';
LOI[72] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~13~20~images/places/Israel/israel_template.html~14';
LOI[73] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~13~6~images/places/Israel/israel_template.html~17';
LOI[74] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~13~7~images/places/Israel/israel_template.html~17';
LOI[75] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~13~15~images/places/Israel/israel_template.html~17';
LOI[76] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~13~16~images/places/Israel/israel_template.html~17';
LOI[77] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~13~19~images/places/Israel/israel_template.html~17';
LOI[78] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~13~20~images/places/Israel/israel_template.html~17';
LOI[79] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Neh~13~1~images/bible_images/Moses/moses_template.html~6';
LOI[80] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Neh~13~1~images/bible_images/Moses/moses_template.html~7';
LOI[81] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Neh~13~1~images/bible_images/Moses/moses_template.html~9';
LOI[82] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Neh~13~1~images/bible_images/Moses/moses_template.html~10';
LOI[83] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Neh~13~1~images/bible_images/Moses/moses_template.html~11';
LOI[84] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~Neh~13~26~images/bible_images/Kings/kings_template.html~3';
LOI[85] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~Neh~13~26~images/bible_images/Kings/kings_template.html~4';
LOI[86] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Neh~13~6~images/bible_images/Kings/kings_template.html~7';
LOI[87] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~1';
LOI[88] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~2';
LOI[89] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~3';
LOI[90] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~4';
LOI[91] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~5';
LOI[92] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~6';
LOI[93] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~7';
LOI[94] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~8';
LOI[95] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~9';
LOI[96] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~10';
LOI[97] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~11';
LOI[98] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~12';
LOI[99] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~13';
LOI[100] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~14';
LOI[101] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~Neh~13~26~images/bible_images/Song/song_template.html~15';
