var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Elam~~~~Neh~7~12~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Elam~~~~Neh~7~34~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Neh~7~7~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Neh~7~61~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Neh~7~73~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~7~6~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Neh~7~7~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Neh~7~61~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Neh~7~73~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~7~6~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~7~2~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~7~3~images/maps/Otest/otest_template.html~3a';
LOI[12] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~7~6~images/maps/Otest/otest_template.html~3a';
LOI[13] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~7~2~images/maps/Otest/otest_template.html~3b';
LOI[14] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~7~3~images/maps/Otest/otest_template.html~3b';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~7~6~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~7~7~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~7~61~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Neh~7~73~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~7~7~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~7~61~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Neh~7~73~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~7~2~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~7~3~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~7~6~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~Neh~7~26~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~Neh~7~36~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Nebo~~~~Neh~7~33~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~7~7~images/maps/Christ/christ_template.html~1';
LOI[29] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~7~61~images/maps/Christ/christ_template.html~1';
LOI[30] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Neh~7~73~images/maps/Christ/christ_template.html~1';
LOI[31] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Neh~7~36~images/places/Israel/israel_template.html~9';
LOI[32] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~7~2~images/places/Israel/israel_template.html~11';
LOI[33] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~7~3~images/places/Israel/israel_template.html~11';
LOI[34] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~7~6~images/places/Israel/israel_template.html~11';
LOI[35] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~7~2~images/places/Israel/israel_template.html~12';
LOI[36] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~7~3~images/places/Israel/israel_template.html~12';
LOI[37] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~7~6~images/places/Israel/israel_template.html~12';
LOI[38] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~7~2~images/places/Israel/israel_template.html~13';
LOI[39] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~7~3~images/places/Israel/israel_template.html~13';
LOI[40] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~7~6~images/places/Israel/israel_template.html~13';
LOI[41] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~7~2~images/places/Israel/israel_template.html~14';
LOI[42] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~7~3~images/places/Israel/israel_template.html~14';
LOI[43] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~7~6~images/places/Israel/israel_template.html~14';
LOI[44] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~7~2~images/places/Israel/israel_template.html~17';
LOI[45] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~7~3~images/places/Israel/israel_template.html~17';
LOI[46] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~7~6~images/places/Israel/israel_template.html~17';
LOI[47] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Nebo~~~~Neh~7~33~images/bible_images/Moses/moses_template.html~10';
LOI[48] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Nebo~~~~Neh~7~33~images/bible_images/Moses/moses_template.html~11';
LOI[49] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Neh~7~6~images/bible_images/Kings/kings_template.html~7';
LOI[50] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~Neh~7~6~images/bible_images/Daniel/daniel_template.html~1';
LOI[51] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Nebuchadnezzar~~~~Neh~7~6~images/bible_images/Daniel/daniel_template.html~3';
