var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~6~7~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~6~17~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Neh~6~18~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~6~7~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~6~17~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Neh~6~18~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Neh~6~7~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Neh~6~10~images/maps/Otest/otest_template.html~3a';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Neh~6~11~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Neh~6~7~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Neh~6~10~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Neh~6~11~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Neh~6~7~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Neh~6~7~images/places/Israel/israel_template.html~11';
LOI[14] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Neh~6~7~images/places/Israel/israel_template.html~12';
LOI[15] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Neh~6~7~images/places/Israel/israel_template.html~13';
LOI[16] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Neh~6~7~images/places/Israel/israel_template.html~14';
LOI[17] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Neh~6~7~images/places/Israel/israel_template.html~17';
LOI[18] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Neh~6~10~images/bible_images/Temple/temple_template.html~1';
LOI[19] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Neh~6~11~images/bible_images/Temple/temple_template.html~1';
LOI[20] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Neh~6~10~images/bible_images/Temple/temple_template.html~2';
LOI[21] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Neh~6~11~images/bible_images/Temple/temple_template.html~2';
