var LOI = [];
LOI[0] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Dan~4~6~images/bible_images/Kings/kings_template.html~7';
LOI[1] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Dan~4~29~images/bible_images/Kings/kings_template.html~7';
LOI[2] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Dan~4~30~images/bible_images/Kings/kings_template.html~7';
LOI[3] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Daniel~~~~Dan~4~8~images/bible_images/Daniel/daniel_template.html~1';
LOI[4] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Daniel~~~~Dan~4~19~images/bible_images/Daniel/daniel_template.html~1';
LOI[5] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~Dan~4~1~images/bible_images/Daniel/daniel_template.html~1';
LOI[6] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~Dan~4~4~images/bible_images/Daniel/daniel_template.html~1';
LOI[7] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~Dan~4~18~images/bible_images/Daniel/daniel_template.html~1';
LOI[8] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~Dan~4~28~images/bible_images/Daniel/daniel_template.html~1';
LOI[9] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~Dan~4~31~images/bible_images/Daniel/daniel_template.html~1';
LOI[10] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~Dan~4~33~images/bible_images/Daniel/daniel_template.html~1';
LOI[11] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~Dan~4~34~images/bible_images/Daniel/daniel_template.html~1';
LOI[12] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Nebuchadnezzar~~~~Dan~4~37~images/bible_images/Daniel/daniel_template.html~1';
LOI[13] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~4~8~images/bible_images/Daniel/daniel_template.html~2';
LOI[14] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~4~19~images/bible_images/Daniel/daniel_template.html~2';
LOI[15] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~1~images/bible_images/Daniel/daniel_template.html~3';
LOI[16] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~2~images/bible_images/Daniel/daniel_template.html~3';
LOI[17] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~3~images/bible_images/Daniel/daniel_template.html~3';
LOI[18] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~4~images/bible_images/Daniel/daniel_template.html~3';
LOI[19] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~5~images/bible_images/Daniel/daniel_template.html~3';
LOI[20] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~6~images/bible_images/Daniel/daniel_template.html~3';
LOI[21] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~7~images/bible_images/Daniel/daniel_template.html~3';
LOI[22] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~8~images/bible_images/Daniel/daniel_template.html~3';
LOI[23] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~9~images/bible_images/Daniel/daniel_template.html~3';
LOI[24] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~10~images/bible_images/Daniel/daniel_template.html~3';
LOI[25] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~11~images/bible_images/Daniel/daniel_template.html~3';
LOI[26] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~12~images/bible_images/Daniel/daniel_template.html~3';
LOI[27] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~13~images/bible_images/Daniel/daniel_template.html~3';
LOI[28] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~14~images/bible_images/Daniel/daniel_template.html~3';
LOI[29] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~15~images/bible_images/Daniel/daniel_template.html~3';
LOI[30] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~16~images/bible_images/Daniel/daniel_template.html~3';
LOI[31] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~17~images/bible_images/Daniel/daniel_template.html~3';
LOI[32] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~18~images/bible_images/Daniel/daniel_template.html~3';
LOI[33] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~19~images/bible_images/Daniel/daniel_template.html~3';
LOI[34] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~20~images/bible_images/Daniel/daniel_template.html~3';
LOI[35] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~21~images/bible_images/Daniel/daniel_template.html~3';
LOI[36] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~22~images/bible_images/Daniel/daniel_template.html~3';
LOI[37] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~23~images/bible_images/Daniel/daniel_template.html~3';
LOI[38] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~24~images/bible_images/Daniel/daniel_template.html~3';
LOI[39] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~25~images/bible_images/Daniel/daniel_template.html~3';
LOI[40] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~26~images/bible_images/Daniel/daniel_template.html~3';
LOI[41] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~27~images/bible_images/Daniel/daniel_template.html~3';
LOI[42] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~28~images/bible_images/Daniel/daniel_template.html~3';
LOI[43] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~29~images/bible_images/Daniel/daniel_template.html~3';
LOI[44] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~30~images/bible_images/Daniel/daniel_template.html~3';
LOI[45] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~31~images/bible_images/Daniel/daniel_template.html~3';
LOI[46] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~32~images/bible_images/Daniel/daniel_template.html~3';
LOI[47] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~33~images/bible_images/Daniel/daniel_template.html~3';
LOI[48] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~34~images/bible_images/Daniel/daniel_template.html~3';
LOI[49] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~35~images/bible_images/Daniel/daniel_template.html~3';
LOI[50] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~36~images/bible_images/Daniel/daniel_template.html~3';
LOI[51] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance~~~~Dan~4~37~images/bible_images/Daniel/daniel_template.html~3';
LOI[52] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~4~8~images/bible_images/Daniel/daniel_template.html~4';
LOI[53] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~4~19~images/bible_images/Daniel/daniel_template.html~4';
LOI[54] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~4~8~images/bible_images/Daniel/daniel_template.html~5';
LOI[55] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~4~19~images/bible_images/Daniel/daniel_template.html~5';
LOI[56] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~4~8~images/bible_images/Daniel/daniel_template.html~6';
LOI[57] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~4~19~images/bible_images/Daniel/daniel_template.html~6';
