var LOI = [];
LOI[0] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Daniel~~~~Dan~10~1~images/bible_images/Daniel/daniel_template.html~1';
LOI[1] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Daniel~~~~Dan~10~2~images/bible_images/Daniel/daniel_template.html~1';
LOI[2] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Daniel~~~~Dan~10~7~images/bible_images/Daniel/daniel_template.html~1';
LOI[3] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Daniel~~~~Dan~10~11~images/bible_images/Daniel/daniel_template.html~1';
LOI[4] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Daniel~~~~Dan~10~12~images/bible_images/Daniel/daniel_template.html~1';
LOI[5] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~10~1~images/bible_images/Daniel/daniel_template.html~2';
LOI[6] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~10~2~images/bible_images/Daniel/daniel_template.html~2';
LOI[7] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~10~7~images/bible_images/Daniel/daniel_template.html~2';
LOI[8] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~10~11~images/bible_images/Daniel/daniel_template.html~2';
LOI[9] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~10~12~images/bible_images/Daniel/daniel_template.html~2';
LOI[10] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~10~1~images/bible_images/Daniel/daniel_template.html~3';
LOI[11] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~10~2~images/bible_images/Daniel/daniel_template.html~3';
LOI[12] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~10~7~images/bible_images/Daniel/daniel_template.html~3';
LOI[13] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~10~11~images/bible_images/Daniel/daniel_template.html~3';
LOI[14] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~10~12~images/bible_images/Daniel/daniel_template.html~3';
LOI[15] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~10~1~images/bible_images/Daniel/daniel_template.html~4';
LOI[16] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~10~2~images/bible_images/Daniel/daniel_template.html~4';
LOI[17] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~10~7~images/bible_images/Daniel/daniel_template.html~4';
LOI[18] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~10~11~images/bible_images/Daniel/daniel_template.html~4';
LOI[19] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~10~12~images/bible_images/Daniel/daniel_template.html~4';
LOI[20] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~10~1~images/bible_images/Daniel/daniel_template.html~5';
LOI[21] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~10~2~images/bible_images/Daniel/daniel_template.html~5';
LOI[22] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~10~7~images/bible_images/Daniel/daniel_template.html~5';
LOI[23] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~10~11~images/bible_images/Daniel/daniel_template.html~5';
LOI[24] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~10~12~images/bible_images/Daniel/daniel_template.html~5';
LOI[25] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~10~1~images/bible_images/Daniel/daniel_template.html~6';
LOI[26] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~10~2~images/bible_images/Daniel/daniel_template.html~6';
LOI[27] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~10~7~images/bible_images/Daniel/daniel_template.html~6';
LOI[28] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~10~11~images/bible_images/Daniel/daniel_template.html~6';
LOI[29] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~10~12~images/bible_images/Daniel/daniel_template.html~6';
