var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Dan~9~7~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Dan~9~11~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Dan~9~20~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Dan~9~7~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Dan~9~11~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Dan~9~20~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Dan~9~2~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Dan~9~7~images/maps/Otest/otest_template.html~3a';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Dan~9~12~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Dan~9~16~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Dan~9~25~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Dan~9~2~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Dan~9~7~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Dan~9~12~images/maps/Otest/otest_template.html~3b';
LOI[14] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Dan~9~16~images/maps/Otest/otest_template.html~3b';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Dan~9~25~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Dan~9~7~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Dan~9~11~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Dan~9~20~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jerusalem~~~~Dan~9~7~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Dan~9~11~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Dan~9~20~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Dan~9~2~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Dan~9~12~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Dan~9~16~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Dan~9~25~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Dan~9~15~images/maps/Otest/otest_template.html~5';
LOI[27] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Dan~9~7~images/maps/Christ/christ_template.html~1';
LOI[28] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Dan~9~11~images/maps/Christ/christ_template.html~1';
LOI[29] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Dan~9~20~images/maps/Christ/christ_template.html~1';
LOI[30] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Dan~9~2~images/places/Israel/israel_template.html~11';
LOI[31] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Dan~9~7~images/places/Israel/israel_template.html~11';
LOI[32] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Dan~9~12~images/places/Israel/israel_template.html~11';
LOI[33] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Dan~9~16~images/places/Israel/israel_template.html~11';
LOI[34] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Dan~9~25~images/places/Israel/israel_template.html~11';
LOI[35] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Dan~9~2~images/places/Israel/israel_template.html~12';
LOI[36] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Dan~9~7~images/places/Israel/israel_template.html~12';
LOI[37] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Dan~9~12~images/places/Israel/israel_template.html~12';
LOI[38] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Dan~9~16~images/places/Israel/israel_template.html~12';
LOI[39] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Dan~9~25~images/places/Israel/israel_template.html~12';
LOI[40] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Dan~9~2~images/places/Israel/israel_template.html~13';
LOI[41] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Dan~9~7~images/places/Israel/israel_template.html~13';
LOI[42] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Dan~9~12~images/places/Israel/israel_template.html~13';
LOI[43] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Dan~9~16~images/places/Israel/israel_template.html~13';
LOI[44] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Dan~9~25~images/places/Israel/israel_template.html~13';
LOI[45] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Dan~9~2~images/places/Israel/israel_template.html~14';
LOI[46] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Dan~9~7~images/places/Israel/israel_template.html~14';
LOI[47] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Dan~9~12~images/places/Israel/israel_template.html~14';
LOI[48] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Dan~9~16~images/places/Israel/israel_template.html~14';
LOI[49] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Dan~9~25~images/places/Israel/israel_template.html~14';
LOI[50] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Dan~9~2~images/places/Israel/israel_template.html~17';
LOI[51] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Dan~9~7~images/places/Israel/israel_template.html~17';
LOI[52] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Dan~9~12~images/places/Israel/israel_template.html~17';
LOI[53] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Dan~9~16~images/places/Israel/israel_template.html~17';
LOI[54] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Dan~9~25~images/places/Israel/israel_template.html~17';
LOI[55] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Dan~9~11~images/bible_images/Moses/moses_template.html~6';
LOI[56] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Dan~9~13~images/bible_images/Moses/moses_template.html~6';
LOI[57] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Dan~9~11~images/bible_images/Moses/moses_template.html~7';
LOI[58] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Dan~9~13~images/bible_images/Moses/moses_template.html~7';
LOI[59] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Dan~9~11~images/bible_images/Moses/moses_template.html~9';
LOI[60] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Dan~9~13~images/bible_images/Moses/moses_template.html~9';
LOI[61] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Dan~9~11~images/bible_images/Moses/moses_template.html~10';
LOI[62] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Dan~9~13~images/bible_images/Moses/moses_template.html~10';
LOI[63] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Dan~9~11~images/bible_images/Moses/moses_template.html~11';
LOI[64] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Dan~9~13~images/bible_images/Moses/moses_template.html~11';
LOI[65] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Daniel~~~~Dan~9~2~images/bible_images/Daniel/daniel_template.html~1';
LOI[66] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Daniel~~~~Dan~9~22~images/bible_images/Daniel/daniel_template.html~1';
LOI[67] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~9~2~images/bible_images/Daniel/daniel_template.html~2';
LOI[68] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~9~22~images/bible_images/Daniel/daniel_template.html~2';
LOI[69] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~9~2~images/bible_images/Daniel/daniel_template.html~3';
LOI[70] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~9~22~images/bible_images/Daniel/daniel_template.html~3';
LOI[71] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~9~2~images/bible_images/Daniel/daniel_template.html~4';
LOI[72] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~9~22~images/bible_images/Daniel/daniel_template.html~4';
LOI[73] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~9~2~images/bible_images/Daniel/daniel_template.html~5';
LOI[74] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~9~22~images/bible_images/Daniel/daniel_template.html~5';
LOI[75] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~9~2~images/bible_images/Daniel/daniel_template.html~6';
LOI[76] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~9~22~images/bible_images/Daniel/daniel_template.html~6';
