var LOI = [];
LOI[0] = 'hymn~20~O LORD, WE PRAISE THEE~htm_o_l_olordwe.html';
LOI[1] = 'hymn~23~MY GOD, I THANK THEE~htm_m_y_mygoditt.html';
LOI[2] = 'hymn~47~O GOD OF GOD~htm_o_g_ogodogod.html';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Dan~2~25~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Dan~2~25~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~19~images/charts/Bible/bible_template.html~1';
LOI[6] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~20~images/charts/Bible/bible_template.html~1';
LOI[7] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~21~images/charts/Bible/bible_template.html~1';
LOI[8] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~22~images/charts/Bible/bible_template.html~1';
LOI[9] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~23~images/charts/Bible/bible_template.html~1';
LOI[10] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~24~images/charts/Bible/bible_template.html~1';
LOI[11] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~25~images/charts/Bible/bible_template.html~1';
LOI[12] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~26~images/charts/Bible/bible_template.html~1';
LOI[13] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~27~images/charts/Bible/bible_template.html~1';
LOI[14] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~28~images/charts/Bible/bible_template.html~1';
LOI[15] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~29~images/charts/Bible/bible_template.html~1';
LOI[16] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~30~images/charts/Bible/bible_template.html~1';
LOI[17] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~31~images/charts/Bible/bible_template.html~1';
LOI[18] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~32~images/charts/Bible/bible_template.html~1';
LOI[19] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~33~images/charts/Bible/bible_template.html~1';
LOI[20] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~34~images/charts/Bible/bible_template.html~1';
LOI[21] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~35~images/charts/Bible/bible_template.html~1';
LOI[22] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~36~images/charts/Bible/bible_template.html~1';
LOI[23] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~37~images/charts/Bible/bible_template.html~1';
LOI[24] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~38~images/charts/Bible/bible_template.html~1';
LOI[25] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~39~images/charts/Bible/bible_template.html~1';
LOI[26] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~40~images/charts/Bible/bible_template.html~1';
LOI[27] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~41~images/charts/Bible/bible_template.html~1';
LOI[28] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~42~images/charts/Bible/bible_template.html~1';
LOI[29] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~43~images/charts/Bible/bible_template.html~1';
LOI[30] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~44~images/charts/Bible/bible_template.html~1';
LOI[31] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Dan~2~45~images/charts/Bible/bible_template.html~1';
LOI[32] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Dan~2~12~images/bible_images/Kings/kings_template.html~7';
LOI[33] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Dan~2~14~images/bible_images/Kings/kings_template.html~7';
LOI[34] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Dan~2~18~images/bible_images/Kings/kings_template.html~7';
LOI[35] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Dan~2~24~images/bible_images/Kings/kings_template.html~7';
LOI[36] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Dan~2~48~images/bible_images/Kings/kings_template.html~7';
LOI[37] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Dan~2~49~images/bible_images/Kings/kings_template.html~7';
LOI[38] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~1~images/bible_images/Daniel/daniel_template.html~1';
LOI[39] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~2~images/bible_images/Daniel/daniel_template.html~1';
LOI[40] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~3~images/bible_images/Daniel/daniel_template.html~1';
LOI[41] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~4~images/bible_images/Daniel/daniel_template.html~1';
LOI[42] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~5~images/bible_images/Daniel/daniel_template.html~1';
LOI[43] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~6~images/bible_images/Daniel/daniel_template.html~1';
LOI[44] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~7~images/bible_images/Daniel/daniel_template.html~1';
LOI[45] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~8~images/bible_images/Daniel/daniel_template.html~1';
LOI[46] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~9~images/bible_images/Daniel/daniel_template.html~1';
LOI[47] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~10~images/bible_images/Daniel/daniel_template.html~1';
LOI[48] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~11~images/bible_images/Daniel/daniel_template.html~1';
LOI[49] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~12~images/bible_images/Daniel/daniel_template.html~1';
LOI[50] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~13~images/bible_images/Daniel/daniel_template.html~1';
LOI[51] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~14~images/bible_images/Daniel/daniel_template.html~1';
LOI[52] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~15~images/bible_images/Daniel/daniel_template.html~1';
LOI[53] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~16~images/bible_images/Daniel/daniel_template.html~1';
LOI[54] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~17~images/bible_images/Daniel/daniel_template.html~1';
LOI[55] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~18~images/bible_images/Daniel/daniel_template.html~1';
LOI[56] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~19~images/bible_images/Daniel/daniel_template.html~1';
LOI[57] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~20~images/bible_images/Daniel/daniel_template.html~1';
LOI[58] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~21~images/bible_images/Daniel/daniel_template.html~1';
LOI[59] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~22~images/bible_images/Daniel/daniel_template.html~1';
LOI[60] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~23~images/bible_images/Daniel/daniel_template.html~1';
LOI[61] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~24~images/bible_images/Daniel/daniel_template.html~1';
LOI[62] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~25~images/bible_images/Daniel/daniel_template.html~1';
LOI[63] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~26~images/bible_images/Daniel/daniel_template.html~1';
LOI[64] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~27~images/bible_images/Daniel/daniel_template.html~1';
LOI[65] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~28~images/bible_images/Daniel/daniel_template.html~1';
LOI[66] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~29~images/bible_images/Daniel/daniel_template.html~1';
LOI[67] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~30~images/bible_images/Daniel/daniel_template.html~1';
LOI[68] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~31~images/bible_images/Daniel/daniel_template.html~1';
LOI[69] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~32~images/bible_images/Daniel/daniel_template.html~1';
LOI[70] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~33~images/bible_images/Daniel/daniel_template.html~1';
LOI[71] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~34~images/bible_images/Daniel/daniel_template.html~1';
LOI[72] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~35~images/bible_images/Daniel/daniel_template.html~1';
LOI[73] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~36~images/bible_images/Daniel/daniel_template.html~1';
LOI[74] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~37~images/bible_images/Daniel/daniel_template.html~1';
LOI[75] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~38~images/bible_images/Daniel/daniel_template.html~1';
LOI[76] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~39~images/bible_images/Daniel/daniel_template.html~1';
LOI[77] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~40~images/bible_images/Daniel/daniel_template.html~1';
LOI[78] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~41~images/bible_images/Daniel/daniel_template.html~1';
LOI[79] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~42~images/bible_images/Daniel/daniel_template.html~1';
LOI[80] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~43~images/bible_images/Daniel/daniel_template.html~1';
LOI[81] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~44~images/bible_images/Daniel/daniel_template.html~1';
LOI[82] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~45~images/bible_images/Daniel/daniel_template.html~1';
LOI[83] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~46~images/bible_images/Daniel/daniel_template.html~1';
LOI[84] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~47~images/bible_images/Daniel/daniel_template.html~1';
LOI[85] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~48~images/bible_images/Daniel/daniel_template.html~1';
LOI[86] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream~~~~Dan~2~49~images/bible_images/Daniel/daniel_template.html~1';
LOI[87] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~13~images/bible_images/Daniel/daniel_template.html~2';
LOI[88] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~14~images/bible_images/Daniel/daniel_template.html~2';
LOI[89] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~15~images/bible_images/Daniel/daniel_template.html~2';
LOI[90] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~16~images/bible_images/Daniel/daniel_template.html~2';
LOI[91] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~17~images/bible_images/Daniel/daniel_template.html~2';
LOI[92] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~18~images/bible_images/Daniel/daniel_template.html~2';
LOI[93] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~19~images/bible_images/Daniel/daniel_template.html~2';
LOI[94] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~20~images/bible_images/Daniel/daniel_template.html~2';
LOI[95] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~24~images/bible_images/Daniel/daniel_template.html~2';
LOI[96] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~25~images/bible_images/Daniel/daniel_template.html~2';
LOI[97] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~26~images/bible_images/Daniel/daniel_template.html~2';
LOI[98] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~27~images/bible_images/Daniel/daniel_template.html~2';
LOI[99] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~46~images/bible_images/Daniel/daniel_template.html~2';
LOI[100] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~47~images/bible_images/Daniel/daniel_template.html~2';
LOI[101] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Dan~2~48~images/bible_images/Daniel/daniel_template.html~2';
LOI[102] = 'image~Bible~Images~The Fiery Furnace (engraving)~~~~Dan~2~49~images/bible_images/Daniel/daniel_template.html~2';
LOI[103] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~13~images/bible_images/Daniel/daniel_template.html~3';
LOI[104] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~14~images/bible_images/Daniel/daniel_template.html~3';
LOI[105] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~15~images/bible_images/Daniel/daniel_template.html~3';
LOI[106] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~16~images/bible_images/Daniel/daniel_template.html~3';
LOI[107] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~17~images/bible_images/Daniel/daniel_template.html~3';
LOI[108] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~18~images/bible_images/Daniel/daniel_template.html~3';
LOI[109] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~19~images/bible_images/Daniel/daniel_template.html~3';
LOI[110] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~20~images/bible_images/Daniel/daniel_template.html~3';
LOI[111] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~24~images/bible_images/Daniel/daniel_template.html~3';
LOI[112] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~25~images/bible_images/Daniel/daniel_template.html~3';
LOI[113] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~26~images/bible_images/Daniel/daniel_template.html~3';
LOI[114] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~27~images/bible_images/Daniel/daniel_template.html~3';
LOI[115] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel,Nebuchadnezzar~~~~Dan~2~46~images/bible_images/Daniel/daniel_template.html~3';
LOI[116] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~47~images/bible_images/Daniel/daniel_template.html~3';
LOI[117] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~48~images/bible_images/Daniel/daniel_template.html~3';
LOI[118] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Dan~2~49~images/bible_images/Daniel/daniel_template.html~3';
LOI[119] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Nebuchadnezzar~~~~Dan~2~1~images/bible_images/Daniel/daniel_template.html~3';
LOI[120] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Nebuchadnezzar~~~~Dan~2~28~images/bible_images/Daniel/daniel_template.html~3';
LOI[121] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~13~images/bible_images/Daniel/daniel_template.html~4';
LOI[122] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~14~images/bible_images/Daniel/daniel_template.html~4';
LOI[123] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~15~images/bible_images/Daniel/daniel_template.html~4';
LOI[124] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~16~images/bible_images/Daniel/daniel_template.html~4';
LOI[125] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~17~images/bible_images/Daniel/daniel_template.html~4';
LOI[126] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~18~images/bible_images/Daniel/daniel_template.html~4';
LOI[127] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~19~images/bible_images/Daniel/daniel_template.html~4';
LOI[128] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~20~images/bible_images/Daniel/daniel_template.html~4';
LOI[129] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~24~images/bible_images/Daniel/daniel_template.html~4';
LOI[130] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~25~images/bible_images/Daniel/daniel_template.html~4';
LOI[131] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~26~images/bible_images/Daniel/daniel_template.html~4';
LOI[132] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~27~images/bible_images/Daniel/daniel_template.html~4';
LOI[133] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~46~images/bible_images/Daniel/daniel_template.html~4';
LOI[134] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~47~images/bible_images/Daniel/daniel_template.html~4';
LOI[135] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~48~images/bible_images/Daniel/daniel_template.html~4';
LOI[136] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Dan~2~49~images/bible_images/Daniel/daniel_template.html~4';
LOI[137] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~13~images/bible_images/Daniel/daniel_template.html~5';
LOI[138] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~14~images/bible_images/Daniel/daniel_template.html~5';
LOI[139] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~15~images/bible_images/Daniel/daniel_template.html~5';
LOI[140] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~16~images/bible_images/Daniel/daniel_template.html~5';
LOI[141] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~17~images/bible_images/Daniel/daniel_template.html~5';
LOI[142] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~18~images/bible_images/Daniel/daniel_template.html~5';
LOI[143] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~19~images/bible_images/Daniel/daniel_template.html~5';
LOI[144] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~20~images/bible_images/Daniel/daniel_template.html~5';
LOI[145] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~24~images/bible_images/Daniel/daniel_template.html~5';
LOI[146] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~25~images/bible_images/Daniel/daniel_template.html~5';
LOI[147] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~26~images/bible_images/Daniel/daniel_template.html~5';
LOI[148] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~27~images/bible_images/Daniel/daniel_template.html~5';
LOI[149] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~46~images/bible_images/Daniel/daniel_template.html~5';
LOI[150] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~47~images/bible_images/Daniel/daniel_template.html~5';
LOI[151] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~48~images/bible_images/Daniel/daniel_template.html~5';
LOI[152] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Dan~2~49~images/bible_images/Daniel/daniel_template.html~5';
LOI[153] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~13~images/bible_images/Daniel/daniel_template.html~6';
LOI[154] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~14~images/bible_images/Daniel/daniel_template.html~6';
LOI[155] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~15~images/bible_images/Daniel/daniel_template.html~6';
LOI[156] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~16~images/bible_images/Daniel/daniel_template.html~6';
LOI[157] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~17~images/bible_images/Daniel/daniel_template.html~6';
LOI[158] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~18~images/bible_images/Daniel/daniel_template.html~6';
LOI[159] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~19~images/bible_images/Daniel/daniel_template.html~6';
LOI[160] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~20~images/bible_images/Daniel/daniel_template.html~6';
LOI[161] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~24~images/bible_images/Daniel/daniel_template.html~6';
LOI[162] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~25~images/bible_images/Daniel/daniel_template.html~6';
LOI[163] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~26~images/bible_images/Daniel/daniel_template.html~6';
LOI[164] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~27~images/bible_images/Daniel/daniel_template.html~6';
LOI[165] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~46~images/bible_images/Daniel/daniel_template.html~6';
LOI[166] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~47~images/bible_images/Daniel/daniel_template.html~6';
LOI[167] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~48~images/bible_images/Daniel/daniel_template.html~6';
LOI[168] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Dan~2~49~images/bible_images/Daniel/daniel_template.html~6';
