var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map)~~~~1Ch~1~4~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map)~~~~1Ch~1~5~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~The World as Known to the Hebrews (map)~~~~1Ch~1~8~images/maps/Otest/otest_template.html~1a';
LOI[3] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Shem,Elam~~~~1Ch~1~17~images/maps/Otest/otest_template.html~1a';
LOI[4] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Shem~~~~1Ch~1~24~images/maps/Otest/otest_template.html~1a';
LOI[5] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Eber~~~~1Ch~1~18~images/maps/Otest/otest_template.html~1a';
LOI[6] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Eber,Joktan~~~~1Ch~1~19~images/maps/Otest/otest_template.html~1a';
LOI[7] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Eber~~~~1Ch~1~25~images/maps/Otest/otest_template.html~1a';
LOI[8] = 'image~Bible~Maps~The World as Known to the Hebrews (map)~~~~1Ch~1~9~images/maps/Otest/otest_template.html~1a';
LOI[9] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Cush~~~~1Ch~1~10~images/maps/Otest/otest_template.html~1a';
LOI[10] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Lehabim,Mizraim~~~~1Ch~1~11~images/maps/Otest/otest_template.html~1a';
LOI[11] = 'image~Bible~Maps~The World as Known to the Hebrews (map)~~~~1Ch~1~23~images/maps/Otest/otest_template.html~1a';
LOI[12] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Jobab~~~~1Ch~1~44~images/maps/Otest/otest_template.html~1a';
LOI[13] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Jobab~~~~1Ch~1~45~images/maps/Otest/otest_template.html~1a';
LOI[14] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Sheba,Abimael~~~~1Ch~1~22~images/maps/Otest/otest_template.html~1a';
LOI[15] = 'image~Bible~Maps~The World as Known to the Hebrews (map)~~~~1Ch~1~32~images/maps/Otest/otest_template.html~1a';
LOI[16] = 'image~Bible~Maps~The World as Known to the Hebrews (map)~~~~1Ch~1~12~images/maps/Otest/otest_template.html~1a';
LOI[17] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~1Ch~1~33~images/maps/Otest/otest_template.html~1a';
LOI[18] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~1Ch~1~46~images/maps/Otest/otest_template.html~1a';
LOI[19] = 'image~Bible~Maps~The World as Known to the Hebrews (map)~~~~1Ch~1~21~images/maps/Otest/otest_template.html~1a';
LOI[20] = 'image~Bible~Maps~The World as Known to the Hebrews (map)~~~~1Ch~1~20~images/maps/Otest/otest_template.html~1a';
LOI[21] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~1Ch~1~28~images/maps/Otest/otest_template.html~1a';
LOI[22] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael,Kedar~~~~1Ch~1~29~images/maps/Otest/otest_template.html~1a';
LOI[23] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~1Ch~1~31~images/maps/Otest/otest_template.html~1a';
LOI[24] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Dumah~~~~1Ch~1~30~images/maps/Otest/otest_template.html~1a';
LOI[25] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Gomer,Riphath~~~~1Ch~1~6~images/maps/Otest/otest_template.html~1a';
LOI[26] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Javan~~~~1Ch~1~7~images/maps/Otest/otest_template.html~1a';
LOI[27] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~1~34~images/maps/Otest/otest_template.html~1b';
LOI[28] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~1~43~images/maps/Otest/otest_template.html~1b';
LOI[29] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~1~34~images/maps/Otest/otest_template.html~1c';
LOI[30] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~1~43~images/maps/Otest/otest_template.html~1c';
LOI[31] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~1~34~images/maps/Otest/otest_template.html~3c';
LOI[32] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~1~43~images/maps/Otest/otest_template.html~3c';
LOI[33] = 'image~Bible~Maps~Middle Palestine (map) key=Ebal~~~~1Ch~1~22~images/maps/Otest/otest_template.html~3c';
LOI[34] = 'image~Bible~Maps~Middle Palestine (map) key=Ebal~~~~1Ch~1~40~images/maps/Otest/otest_template.html~3c';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~1~34~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~1~43~images/maps/Otest/otest_template.html~4';
LOI[37] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~1Ch~1~46~images/maps/Otest/otest_template.html~4';
LOI[38] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~1~34~images/maps/Christ/christ_template.html~1';
LOI[39] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~1~43~images/maps/Christ/christ_template.html~1';
LOI[40] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~1Ch~1~27~images/places/Israel/israel_template.html~8';
LOI[41] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~1Ch~1~28~images/places/Israel/israel_template.html~8';
LOI[42] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~1Ch~1~34~images/places/Israel/israel_template.html~8';
LOI[43] = 'image~Bible~Images~The Judgement of Adam and Eve (engraving) key=Adam~~~~1Ch~1~1~images/bible_images/Moses/moses_template.html~1b';
LOI[44] = 'image~Bible~Images~The Deluge (engraving) key=Noah~~~~1Ch~1~4~images/bible_images/Moses/moses_template.html~1';
LOI[45] = 'image~Bible~Images~Noah\'s Sacrifice (engraving) key=Noah~~~~1Ch~1~4~images/bible_images/Moses/moses_template.html~2';
LOI[46] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~1Ch~1~27~images/bible_images/Moses/moses_template.html~3';
LOI[47] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~1Ch~1~28~images/bible_images/Moses/moses_template.html~3';
LOI[48] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~1Ch~1~34~images/bible_images/Moses/moses_template.html~3';
LOI[49] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~1Ch~1~27~images/bible_images/Moses/moses_template.html~3i';
LOI[50] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~1Ch~1~28~images/bible_images/Moses/moses_template.html~3i';
LOI[51] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~1Ch~1~34~images/bible_images/Moses/moses_template.html~3i';
LOI[52] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~1Ch~1~28~images/bible_images/Moses/moses_template.html~3a';
LOI[53] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~1Ch~1~34~images/bible_images/Moses/moses_template.html~3a';
LOI[54] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~1Ch~1~27~images/bible_images/Moses/moses_template.html~3a';
LOI[55] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Nahor~~~~1Ch~1~26~images/bible_images/Moses/moses_template.html~4';
LOI[56] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~1Ch~1~28~images/bible_images/Moses/moses_template.html~4';
LOI[57] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~1Ch~1~34~images/bible_images/Moses/moses_template.html~4';
LOI[58] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~1Ch~1~12~images/bible_images/Samson/samson_template.html~6';
LOI[59] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Sheba~~~~1Ch~1~9~images/bible_images/Kings/kings_template.html~4';
LOI[60] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Sheba~~~~1Ch~1~22~images/bible_images/Kings/kings_template.html~4';
LOI[61] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Sheba~~~~1Ch~1~32~images/bible_images/Kings/kings_template.html~4';
