var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Eber~~~~1Ch~8~12~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Jobab~~~~1Ch~8~9~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Jobab~~~~1Ch~8~18~images/maps/Otest/otest_template.html~1a';
LOI[3] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ishmael~~~~1Ch~8~38~images/maps/Otest/otest_template.html~1a';
LOI[4] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Elam~~~~1Ch~8~24~images/maps/Otest/otest_template.html~1a';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~1Ch~8~1~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~1Ch~8~40~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~1Ch~8~1~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~1Ch~8~40~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Ch~8~33~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~1Ch~8~28~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~1Ch~8~32~images/maps/Otest/otest_template.html~3a';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~1Ch~8~28~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~1Ch~8~32~images/maps/Otest/otest_template.html~3b';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~1Ch~8~28~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~1Ch~8~32~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~1Ch~8~8~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~1Ch~8~28~images/places/Israel/israel_template.html~11';
LOI[18] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~1Ch~8~32~images/places/Israel/israel_template.html~11';
LOI[19] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~1Ch~8~28~images/places/Israel/israel_template.html~12';
LOI[20] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~1Ch~8~32~images/places/Israel/israel_template.html~12';
LOI[21] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~1Ch~8~28~images/places/Israel/israel_template.html~13';
LOI[22] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~1Ch~8~32~images/places/Israel/israel_template.html~13';
LOI[23] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~1Ch~8~28~images/places/Israel/israel_template.html~14';
LOI[24] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~1Ch~8~32~images/places/Israel/israel_template.html~14';
LOI[25] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~1Ch~8~28~images/places/Israel/israel_template.html~17';
LOI[26] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~1Ch~8~32~images/places/Israel/israel_template.html~17';
LOI[27] = 'image~Bible~Images~Saul and David (engraving) key=Saul~~~~1Ch~8~33~images/bible_images/Kings/kings_template.html~1';
LOI[28] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Ch~8~33~images/bible_images/Acts/acts_template.html~1';
LOI[29] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Ch~8~33~images/bible_images/Acts/acts_template.html~2';
