var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~1Ch~2~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~2~7~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~1Ch~2~3~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~1Ch~2~4~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~1Ch~2~10~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~1Ch~2~2~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~1Ch~2~1~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~2~7~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~1Ch~2~3~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~1Ch~2~4~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~1Ch~2~10~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~1Ch~2~2~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Cities of Refuge (map) key=Hebron~~~~1Ch~2~42~images/maps/Otest/otest_template.html~2';
LOI[13] = 'image~Bible~Maps~Cities of Refuge (map) key=Hebron~~~~1Ch~2~43~images/maps/Otest/otest_template.html~2';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~2~1~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~2~7~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~1Ch~2~21~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~1Ch~2~22~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~1Ch~2~23~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~2~1~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~2~7~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~1Ch~2~51~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~1Ch~2~54~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~1Ch~2~21~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~1Ch~2~22~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~1Ch~2~23~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~2~1~images/maps/Christ/christ_template.html~1';
LOI[27] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~2~7~images/maps/Christ/christ_template.html~1';
LOI[28] = 'image~Bible~Places~Hebron (engraving) key=Hebron~~~~1Ch~2~42~images/places/Israel/israel_template.html~16';
LOI[29] = 'image~Bible~Places~Hebron (engraving) key=Hebron~~~~1Ch~2~43~images/places/Israel/israel_template.html~16';
LOI[30] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~1Ch~2~2~images/bible_images/Moses/moses_template.html~5';
LOI[31] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~2~15~images/bible_images/Kings/kings_template.html~1';
LOI[32] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~2~15~images/bible_images/Kings/kings_template.html~2';
