var LOI = [];
LOI[0] = 'hymn~10~MORE ABOUT JESUS~htm_m_o_morabout.html';
LOI[1] = 'hymn~25~SPLENDOR AND MAJESTY~htm_s_p_splendor.html';
LOI[2] = 'hymn~29~WHEN THE GREAT SUN SINKS TO HIS REST~htm_w_h_e_whentgsn.html';
LOI[3] = 'hymn~33~O THOU IN WHOSE PRESENCE~htm_o_t_othouwho.html';
LOI[4] = 'hymn~34~BLESSED REDEEMER (2)~htm_b_l_blessred.html';
LOI[5] = 'hymn~34~GOD IS SO GOOD~htm_g_i_gissgood.html';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~16~3~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~16~4~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~16~13~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~16~17~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~16~36~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~16~40~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~16~3~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~16~4~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~16~13~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~16~17~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~16~36~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~16~40~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~16~3~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~16~4~images/maps/Otest/otest_template.html~3c';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~16~13~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~16~17~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~16~36~images/maps/Otest/otest_template.html~3c';
LOI[23] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~16~40~images/maps/Otest/otest_template.html~3c';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~16~3~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~16~4~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~16~13~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~16~17~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~16~36~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~16~40~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~16~3~images/maps/Christ/christ_template.html~1';
LOI[31] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~16~4~images/maps/Christ/christ_template.html~1';
LOI[32] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~16~13~images/maps/Christ/christ_template.html~1';
LOI[33] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~16~17~images/maps/Christ/christ_template.html~1';
LOI[34] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~16~36~images/maps/Christ/christ_template.html~1';
LOI[35] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~16~40~images/maps/Christ/christ_template.html~1';
LOI[36] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~1Ch~16~16~images/places/Israel/israel_template.html~8';
LOI[37] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~1Ch~16~16~images/bible_images/Moses/moses_template.html~3';
LOI[38] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~1Ch~16~18~images/bible_images/Moses/moses_template.html~3i';
LOI[39] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~1Ch~16~16~images/bible_images/Moses/moses_template.html~3i';
LOI[40] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~1Ch~16~16~images/bible_images/Moses/moses_template.html~3a';
LOI[41] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~1Ch~16~16~images/bible_images/Moses/moses_template.html~4';
LOI[42] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~16~1~images/bible_images/Kings/kings_template.html~1';
LOI[43] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~16~2~images/bible_images/Kings/kings_template.html~1';
LOI[44] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~16~7~images/bible_images/Kings/kings_template.html~1';
LOI[45] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~16~43~images/bible_images/Kings/kings_template.html~1';
LOI[46] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~16~1~images/bible_images/Kings/kings_template.html~2';
LOI[47] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~16~2~images/bible_images/Kings/kings_template.html~2';
LOI[48] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~16~7~images/bible_images/Kings/kings_template.html~2';
LOI[49] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~16~43~images/bible_images/Kings/kings_template.html~2';
LOI[50] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~1Ch~16~39~images/bible_images/Temple/temple_template.html~2';
LOI[51] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~1Ch~16~39~images/bible_images/Temple/temple_template.html~3';
LOI[52] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~1Ch~16~1~images/bible_images/Temple/temple_template.html~4';
LOI[53] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~1Ch~16~4~images/bible_images/Temple/temple_template.html~4';
LOI[54] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~1Ch~16~6~images/bible_images/Temple/temple_template.html~4';
LOI[55] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~1Ch~16~37~images/bible_images/Temple/temple_template.html~4';
