var LOI = [];
LOI[0] = 'hymn~20~HE WILL ANSWER EVERY PRAYER~htm_h_w_hwillaep.html';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Sheba~~~~1Ch~5~13~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Hagarites~~~~1Ch~5~10~images/maps/Otest/otest_template.html~1a';
LOI[3] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Hagarites~~~~1Ch~5~19~images/maps/Otest/otest_template.html~1a';
LOI[4] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Hagarites~~~~1Ch~5~20~images/maps/Otest/otest_template.html~1a';
LOI[5] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Gog~~~~1Ch~5~4~images/maps/Otest/otest_template.html~1a';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~1Ch~5~1~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Reuben~~~~1Ch~5~3~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~1Ch~5~17~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Manasseh~~~~1Ch~5~26~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Reuben,Manasseh~~~~1Ch~5~18~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~1Ch~5~2~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Gad~~~~1Ch~5~11~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Manasseh~~~~1Ch~5~23~images/maps/Otest/otest_template.html~1b';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~1Ch~5~1~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Reuben~~~~1Ch~5~3~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~1Ch~5~17~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Manasseh~~~~1Ch~5~26~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Reuben,Manasseh~~~~1Ch~5~18~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~1Ch~5~2~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Gad~~~~1Ch~5~11~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Manasseh~~~~1Ch~5~23~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Ch~5~10~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~5~1~images/maps/Otest/otest_template.html~3c';
LOI[24] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~5~3~images/maps/Otest/otest_template.html~3c';
LOI[25] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~5~17~images/maps/Otest/otest_template.html~3c';
LOI[26] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~5~26~images/maps/Otest/otest_template.html~3c';
LOI[27] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~1Ch~5~9~images/maps/Otest/otest_template.html~3c';
LOI[28] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~1Ch~5~10~images/maps/Otest/otest_template.html~3c';
LOI[29] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~1Ch~5~14~images/maps/Otest/otest_template.html~3c';
LOI[30] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead,Sharon~~~~1Ch~5~16~images/maps/Otest/otest_template.html~3c';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~5~1~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~5~3~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~5~17~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~5~26~images/maps/Otest/otest_template.html~4';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~1Ch~5~9~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~1Ch~5~10~images/maps/Otest/otest_template.html~4';
LOI[37] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~1Ch~5~14~images/maps/Otest/otest_template.html~4';
LOI[38] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead,Sharon~~~~1Ch~5~16~images/maps/Otest/otest_template.html~4';
LOI[39] = 'image~Bible~Maps~Southern Palestine (map) key=Nebo~~~~1Ch~5~8~images/maps/Otest/otest_template.html~4';
LOI[40] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~5~1~images/maps/Christ/christ_template.html~1';
LOI[41] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~5~3~images/maps/Christ/christ_template.html~1';
LOI[42] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~5~17~images/maps/Christ/christ_template.html~1';
LOI[43] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~5~26~images/maps/Christ/christ_template.html~1';
LOI[44] = 'image~Bible~Maps~Divisions of Palestine (map) key=Bashan~~~~1Ch~5~11~images/maps/Christ/christ_template.html~1';
LOI[45] = 'image~Bible~Maps~Divisions of Palestine (map) key=Bashan~~~~1Ch~5~12~images/maps/Christ/christ_template.html~1';
LOI[46] = 'image~Bible~Maps~Divisions of Palestine (map) key=Bashan~~~~1Ch~5~16~images/maps/Christ/christ_template.html~1';
LOI[47] = 'image~Bible~Maps~Divisions of Palestine (map) key=Bashan~~~~1Ch~5~23~images/maps/Christ/christ_template.html~1';
LOI[48] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~1Ch~5~1~images/bible_images/Moses/moses_template.html~5';
LOI[49] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Nebo~~~~1Ch~5~8~images/bible_images/Moses/moses_template.html~10';
LOI[50] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Nebo~~~~1Ch~5~8~images/bible_images/Moses/moses_template.html~11';
LOI[51] = 'image~Bible~Images~Saul and David (engraving) key=Saul~~~~1Ch~5~10~images/bible_images/Kings/kings_template.html~1';
LOI[52] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Sheba~~~~1Ch~5~13~images/bible_images/Kings/kings_template.html~4';
LOI[53] = 'image~Bible~Images~Rehoboam and Jeroboam (engraving) key=Jeroboam~~~~1Ch~5~17~images/bible_images/Kings/kings_template.html~5';
LOI[54] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Ch~5~10~images/bible_images/Acts/acts_template.html~1';
LOI[55] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Ch~5~10~images/bible_images/Acts/acts_template.html~2';
