var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~13~2~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~13~5~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~1Ch~13~6~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~13~8~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~13~2~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~13~5~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~1Ch~13~6~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~13~8~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Ch~13~3~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~13~2~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~13~5~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~13~6~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~13~8~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~13~2~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~13~5~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~13~6~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~13~8~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~1Ch~13~5~images/maps/Otest/otest_template.html~5';
LOI[18] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~13~2~images/maps/Christ/christ_template.html~1';
LOI[19] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~13~5~images/maps/Christ/christ_template.html~1';
LOI[20] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~13~6~images/maps/Christ/christ_template.html~1';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~13~8~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Images~Saul and David (engraving) key=Saul~~~~1Ch~13~3~images/bible_images/Kings/kings_template.html~1';
LOI[23] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~13~1~images/bible_images/Kings/kings_template.html~1';
LOI[24] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~13~2~images/bible_images/Kings/kings_template.html~1';
LOI[25] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~13~5~images/bible_images/Kings/kings_template.html~1';
LOI[26] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~13~6~images/bible_images/Kings/kings_template.html~1';
LOI[27] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~13~8~images/bible_images/Kings/kings_template.html~1';
LOI[28] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~13~11~images/bible_images/Kings/kings_template.html~1';
LOI[29] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~13~12~images/bible_images/Kings/kings_template.html~1';
LOI[30] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~13~13~images/bible_images/Kings/kings_template.html~1';
LOI[31] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~13~1~images/bible_images/Kings/kings_template.html~2';
LOI[32] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~13~2~images/bible_images/Kings/kings_template.html~2';
LOI[33] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~13~5~images/bible_images/Kings/kings_template.html~2';
LOI[34] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~13~6~images/bible_images/Kings/kings_template.html~2';
LOI[35] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~13~8~images/bible_images/Kings/kings_template.html~2';
LOI[36] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~13~11~images/bible_images/Kings/kings_template.html~2';
LOI[37] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~13~12~images/bible_images/Kings/kings_template.html~2';
LOI[38] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~13~13~images/bible_images/Kings/kings_template.html~2';
LOI[39] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Ch~13~3~images/bible_images/Acts/acts_template.html~1';
LOI[40] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Ch~13~3~images/bible_images/Acts/acts_template.html~2';
LOI[41] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~1Ch~13~3~images/bible_images/Temple/temple_template.html~4';
LOI[42] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~1Ch~13~5~images/bible_images/Temple/temple_template.html~4';
LOI[43] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~1Ch~13~6~images/bible_images/Temple/temple_template.html~4';
LOI[44] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~1Ch~13~7~images/bible_images/Temple/temple_template.html~4';
LOI[45] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~1Ch~13~9~images/bible_images/Temple/temple_template.html~4';
LOI[46] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~1Ch~13~10~images/bible_images/Temple/temple_template.html~4';
LOI[47] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~1Ch~13~12~images/bible_images/Temple/temple_template.html~4';
LOI[48] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~1Ch~13~13~images/bible_images/Temple/temple_template.html~4';
LOI[49] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~1Ch~13~14~images/bible_images/Temple/temple_template.html~4';
