var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~1Ch~7~29~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Issachar~~~~1Ch~7~1~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Issachar~~~~1Ch~7~5~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Asher~~~~1Ch~7~30~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Asher~~~~1Ch~7~40~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Naphtali~~~~1Ch~7~13~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~1Ch~7~20~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~1Ch~7~22~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Manasseh~~~~1Ch~7~14~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Manasseh~~~~1Ch~7~17~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~1Ch~7~6~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~1Ch~7~10~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~1Ch~7~29~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Issachar~~~~1Ch~7~1~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Issachar~~~~1Ch~7~5~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Asher~~~~1Ch~7~30~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Asher~~~~1Ch~7~40~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Naphtali~~~~1Ch~7~13~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~1Ch~7~20~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~1Ch~7~22~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Manasseh~~~~1Ch~7~14~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Manasseh~~~~1Ch~7~17~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~1Ch~7~6~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~1Ch~7~10~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Cities of Refuge (map) key=Bezer~~~~1Ch~7~37~images/maps/Otest/otest_template.html~2';
LOI[25] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~1Ch~7~19~images/maps/Otest/otest_template.html~2';
LOI[26] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~1Ch~7~28~images/maps/Otest/otest_template.html~2';
LOI[27] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~7~29~images/maps/Otest/otest_template.html~3c';
LOI[28] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~1Ch~7~14~images/maps/Otest/otest_template.html~3c';
LOI[29] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~1Ch~7~17~images/maps/Otest/otest_template.html~3c';
LOI[30] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~7~29~images/maps/Otest/otest_template.html~4';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~1Ch~7~14~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~1Ch~7~17~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Gaza~~~~1Ch~7~28~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~7~29~images/maps/Christ/christ_template.html~1';
LOI[35] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~1Ch~7~29~images/bible_images/Moses/moses_template.html~5';
LOI[36] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~7~2~images/bible_images/Kings/kings_template.html~1';
LOI[37] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~7~2~images/bible_images/Kings/kings_template.html~2';
