var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Elam~~~~1Ch~26~3~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~26~29~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~26~30~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Issachar~~~~1Ch~26~5~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Manasseh~~~~1Ch~26~32~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~26~29~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~26~30~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Issachar~~~~1Ch~26~5~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Manasseh~~~~1Ch~26~32~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul,Samuel~~~~1Ch~26~28~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~26~29~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel,Jordan~~~~1Ch~26~30~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~1Ch~26~31~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~26~29~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~26~30~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~1Ch~26~31~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~26~29~images/maps/Christ/christ_template.html~1';
LOI[17] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~26~30~images/maps/Christ/christ_template.html~1';
LOI[18] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~1Ch~26~14~images/bible_images/Moses/moses_template.html~3i';
LOI[19] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~1Ch~26~16~images/bible_images/Moses/moses_template.html~3i';
LOI[20] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~1Ch~26~24~images/bible_images/Moses/moses_template.html~6';
LOI[21] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~1Ch~26~24~images/bible_images/Moses/moses_template.html~7';
LOI[22] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~1Ch~26~24~images/bible_images/Moses/moses_template.html~9';
LOI[23] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~1Ch~26~24~images/bible_images/Moses/moses_template.html~10';
LOI[24] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~1Ch~26~24~images/bible_images/Moses/moses_template.html~11';
LOI[25] = 'image~Bible~Images~Saul and David (engraving) key=Saul~~~~1Ch~26~28~images/bible_images/Kings/kings_template.html~1';
LOI[26] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~26~26~images/bible_images/Kings/kings_template.html~1';
LOI[27] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~26~31~images/bible_images/Kings/kings_template.html~1';
LOI[28] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~26~32~images/bible_images/Kings/kings_template.html~1';
LOI[29] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~26~26~images/bible_images/Kings/kings_template.html~2';
LOI[30] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~26~31~images/bible_images/Kings/kings_template.html~2';
LOI[31] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~26~32~images/bible_images/Kings/kings_template.html~2';
LOI[32] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Ch~26~28~images/bible_images/Acts/acts_template.html~1';
LOI[33] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Ch~26~28~images/bible_images/Acts/acts_template.html~2';
