var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Ch~20~7~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Ch~20~7~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~1Ch~20~1~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~1Ch~20~3~images/maps/Otest/otest_template.html~3a';
LOI[4] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~1Ch~20~1~images/maps/Otest/otest_template.html~3b';
LOI[5] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~1Ch~20~3~images/maps/Otest/otest_template.html~3b';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Ch~20~7~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Ch~20~7~images/maps/Otest/otest_template.html~4';
LOI[8] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~1Ch~20~1~images/maps/Otest/otest_template.html~4';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~1Ch~20~3~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Ch~20~7~images/maps/Christ/christ_template.html~1';
LOI[11] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~1Ch~20~1~images/places/Israel/israel_template.html~11';
LOI[12] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~1Ch~20~3~images/places/Israel/israel_template.html~11';
LOI[13] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~1Ch~20~1~images/places/Israel/israel_template.html~12';
LOI[14] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~1Ch~20~3~images/places/Israel/israel_template.html~12';
LOI[15] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~1Ch~20~1~images/places/Israel/israel_template.html~13';
LOI[16] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~1Ch~20~3~images/places/Israel/israel_template.html~13';
LOI[17] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~1Ch~20~1~images/places/Israel/israel_template.html~14';
LOI[18] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~1Ch~20~3~images/places/Israel/israel_template.html~14';
LOI[19] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~1Ch~20~1~images/places/Israel/israel_template.html~17';
LOI[20] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~1Ch~20~3~images/places/Israel/israel_template.html~17';
LOI[21] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~1Ch~20~4~images/bible_images/Samson/samson_template.html~6';
LOI[22] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~1Ch~20~5~images/bible_images/Samson/samson_template.html~6';
LOI[23] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~20~1~images/bible_images/Kings/kings_template.html~1';
LOI[24] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~20~2~images/bible_images/Kings/kings_template.html~1';
LOI[25] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~20~3~images/bible_images/Kings/kings_template.html~1';
LOI[26] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Ch~20~8~images/bible_images/Kings/kings_template.html~1';
LOI[27] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~20~1~images/bible_images/Kings/kings_template.html~2';
LOI[28] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~20~2~images/bible_images/Kings/kings_template.html~2';
LOI[29] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~20~3~images/bible_images/Kings/kings_template.html~2';
LOI[30] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Ch~20~8~images/bible_images/Kings/kings_template.html~2';
