var LOI = [];
LOI[0] = 'hymn~19~WIN THEM ONE BY ONE~htm_w_i_winthem1.html';
LOI[1] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~1Cr~9~13~images/maps/Otest/otest_template.html~3a';
LOI[2] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~1Cr~9~13~images/maps/Otest/otest_template.html~3b';
LOI[3] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Barnabas~~~~1Cr~9~6~images/maps/Journeys/journeys_template.html~1';
LOI[4] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Barnabas~~~~1Cr~9~6~images/maps/Journeys/journeys_template.html~2';
LOI[5] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~1Cr~9~9~images/bible_images/Moses/moses_template.html~6';
LOI[6] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~1Cr~9~9~images/bible_images/Moses/moses_template.html~7';
LOI[7] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~1Cr~9~9~images/bible_images/Moses/moses_template.html~9';
LOI[8] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~1Cr~9~9~images/bible_images/Moses/moses_template.html~10';
LOI[9] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~1Cr~9~9~images/bible_images/Moses/moses_template.html~11';
LOI[10] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~1Cr~9~13~images/bible_images/Temple/temple_template.html~1';
LOI[11] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~1Cr~9~13~images/bible_images/Temple/temple_template.html~2';
