var LOI = [];
LOI[0] = 'hymn~4~AGAIN THE LORD&#8217;S OWN DAY IS HERE~htm_a_t_atlodish.html';
LOI[1] = 'hymn~4~YES, THE REDEEMER ROSE~htm_y_e_yesthred.html';
LOI[2] = 'hymn~20~ASLEEP IN JESUS~htm_a_s_asleepin.html';
LOI[3] = 'hymn~20~AWAKE, GLAD SOUL~htm_a_g_agsawake.html';
LOI[4] = 'hymn~20~CHRIST THE LORD IS RISEN TODAY (2)~htm_c_h_christtl.html';
LOI[5] = 'hymn~20~HEARTS TO HEAVEN AND VOICES RAISE~htm_h_e_heartsto.html';
LOI[6] = 'hymn~20~SING WITH ALL THE SAINTS IN GLORY~htm_s_i_singwith.html';
LOI[7] = 'hymn~20~THOU HALLOWED CHOSEN MORN OF PRAISE~htm_t_h_o_thouhmcp.html';
LOI[8] = 'hymn~22~AND ARE WE YET ALIVE?~htm_a_n_andarewe.html';
LOI[9] = 'hymn~26~THE MORNING PURPLES ALL THE SKY~htm_m_o_mornpurp.html';
LOI[10] = 'hymn~51~THE GREAT ARCHANGEL&#8217;S TRUMP~htm_g_r_greatarc.html';
LOI[11] = 'hymn~51~IN THE TWINKLING OF AN EYE~htm_t_w_twinklin.html';
LOI[12] = 'hymn~51~SOON WILL OUR SAVIOR FROM HEAVEN APPEAR~htm_s_o_soonwill.html';
LOI[13] = 'hymn~51~WE ARE GOING DOWN THE VALLEY~htm_w_e_wergoing.html';
LOI[14] = 'hymn~52~DAY OF JUDGMENT! DAY OF WONDERS!~htm_d_a_dayjdayw.html';
LOI[15] = 'hymn~55~CHRIST JESUS LAY IN DEATH&#8217;S STRONG BANDS~htm_c_j_cjlayind.html';
LOI[16] = 'hymn~55~THE FRIEND OF SINNERS DIES~htm_f_r_friendof.html';
LOI[17] = 'hymn~55~HALLELUJAH UNTO JESUS~htm_h_u_huntojes.html';
LOI[18] = 'hymn~55~JESUS, THINE ALL VICTORIOUS LOVE~htm_j_t_jtavlove.html';
LOI[19] = 'hymn~55~LIKE THE GOLDEN SUN ASCENDING~htm_l_i_likegold.html';
LOI[20] = 'hymn~55~THE LORD IS RISEN INDEED!~htm_l_o_lordisri.html';
LOI[21] = 'hymn~55~NO DYING THERE~htm_n_o_nodyingt.html';
LOI[22] = 'hymn~57~WELCOME, THOU VICTOR IN THE STRIFE~htm_w_e_welcomet.html';
LOI[23] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Ephesus~~~~1Cr~15~32~images/maps/Journeys/journeys_template.html~2';
LOI[24] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Ephesus~~~~1Cr~15~32~images/maps/Journeys/journeys_template.html~3';
LOI[25] = 'image~Bible~Images~The Judgement of Adam and Eve (engraving) key=Adam~~~~1Cr~15~22~images/bible_images/Moses/moses_template.html~1b';
LOI[26] = 'image~Bible~Images~The Judgement of Adam and Eve (engraving) key=Adam~~~~1Cr~15~45~images/bible_images/Moses/moses_template.html~1b';
