var LOI = [];
LOI[0] = 'hymn~18~SINNERS, WILL YOU SCORN THE MESSAGE~htm_s_w_swystmsg.html';
LOI[1] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~1Cr~1~1~images/maps/Journeys/journeys_template.html~1';
LOI[2] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~1Cr~1~12~images/maps/Journeys/journeys_template.html~1';
LOI[3] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~1Cr~1~13~images/maps/Journeys/journeys_template.html~1';
LOI[4] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~1Cr~1~1~images/maps/Journeys/journeys_template.html~2';
LOI[5] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~1Cr~1~12~images/maps/Journeys/journeys_template.html~2';
LOI[6] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~1Cr~1~13~images/maps/Journeys/journeys_template.html~2';
LOI[7] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Corinth~~~~1Cr~1~2~images/maps/Journeys/journeys_template.html~2';
LOI[8] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~1Cr~1~1~images/maps/Journeys/journeys_template.html~3';
LOI[9] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul,Apollos~~~~1Cr~1~12~images/maps/Journeys/journeys_template.html~3';
LOI[10] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~1Cr~1~13~images/maps/Journeys/journeys_template.html~3';
LOI[11] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Corinth~~~~1Cr~1~2~images/maps/Journeys/journeys_template.html~3';
LOI[12] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~1Cr~1~1~images/bible_images/Acts/acts_template.html~2';
LOI[13] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~1Cr~1~12~images/bible_images/Acts/acts_template.html~2';
LOI[14] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~1Cr~1~13~images/bible_images/Acts/acts_template.html~2';
