var LOI = [];
LOI[0] = 'hymn~13~AM I A SOLDIER OF THE CROSS?~htm_a_m_amiasold.html';
LOI[1] = 'hymn~13~WHEN THE BATTLE&#8217;S OVER~htm_w_h_e_whenbatt.html';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~1Cr~16~3~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~1Cr~16~3~images/maps/Otest/otest_template.html~3b';
LOI[4] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~1Cr~16~3~images/maps/Otest/otest_template.html~4';
LOI[5] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~1Cr~16~21~images/maps/Journeys/journeys_template.html~1';
LOI[6] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul~~~~1Cr~16~21~images/maps/Journeys/journeys_template.html~2';
LOI[7] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Timotheus~~~~1Cr~16~10~images/maps/Journeys/journeys_template.html~2';
LOI[8] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Timotheus~~~~1Cr~16~24~images/maps/Journeys/journeys_template.html~2';
LOI[9] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Aquila,Priscilla~~~~1Cr~16~19~images/maps/Journeys/journeys_template.html~2';
LOI[10] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Galatia~~~~1Cr~16~1~images/maps/Journeys/journeys_template.html~2';
LOI[11] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Ephesus~~~~1Cr~16~8~images/maps/Journeys/journeys_template.html~2';
LOI[12] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Achaia~~~~1Cr~16~15~images/maps/Journeys/journeys_template.html~2';
LOI[13] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~1Cr~16~21~images/maps/Journeys/journeys_template.html~3';
LOI[14] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Apollos~~~~1Cr~16~12~images/maps/Journeys/journeys_template.html~3';
LOI[15] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Ephesus~~~~1Cr~16~8~images/maps/Journeys/journeys_template.html~3';
LOI[16] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Galatia~~~~1Cr~16~1~images/maps/Journeys/journeys_template.html~3';
LOI[17] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Philippi~~~~1Cr~16~24~images/maps/Journeys/journeys_template.html~3';
LOI[18] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Macedonia~~~~1Cr~16~5~images/maps/Journeys/journeys_template.html~3';
LOI[19] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Achaia~~~~1Cr~16~15~images/maps/Journeys/journeys_template.html~3';
LOI[20] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Asia~~~~1Cr~16~19~images/maps/Journeys/journeys_template.html~3';
LOI[21] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~1Cr~16~3~images/places/Israel/israel_template.html~11';
LOI[22] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~1Cr~16~3~images/places/Israel/israel_template.html~12';
LOI[23] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~1Cr~16~3~images/places/Israel/israel_template.html~13';
LOI[24] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~1Cr~16~3~images/places/Israel/israel_template.html~14';
LOI[25] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~1Cr~16~3~images/places/Israel/israel_template.html~17';
LOI[26] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~1Cr~16~21~images/bible_images/Acts/acts_template.html~2';
