var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~35~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~35~4~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~35~20~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~35~29~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Exd~35~30~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Dan~~~~Exd~35~34~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~35~1~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~35~4~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~35~20~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~35~29~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Exd~35~30~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Dan~~~~Exd~35~34~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~35~1~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~35~4~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~35~20~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~35~29~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~35~30~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~35~1~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~35~4~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~35~20~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~35~29~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~35~30~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~35~1~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~35~4~images/maps/Christ/christ_template.html~1';
LOI[24] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~35~20~images/maps/Christ/christ_template.html~1';
LOI[25] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~35~29~images/maps/Christ/christ_template.html~1';
LOI[26] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~35~30~images/maps/Christ/christ_template.html~1';
LOI[27] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~35~1~images/bible_images/Moses/moses_template.html~6';
LOI[28] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~35~4~images/bible_images/Moses/moses_template.html~6';
LOI[29] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~35~20~images/bible_images/Moses/moses_template.html~6';
LOI[30] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~35~29~images/bible_images/Moses/moses_template.html~6';
LOI[31] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~35~30~images/bible_images/Moses/moses_template.html~6';
LOI[32] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~35~1~images/bible_images/Moses/moses_template.html~7';
LOI[33] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~35~4~images/bible_images/Moses/moses_template.html~7';
LOI[34] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~35~20~images/bible_images/Moses/moses_template.html~7';
LOI[35] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~35~29~images/bible_images/Moses/moses_template.html~7';
LOI[36] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~35~30~images/bible_images/Moses/moses_template.html~7';
LOI[37] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~35~1~images/bible_images/Moses/moses_template.html~9';
LOI[38] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~35~4~images/bible_images/Moses/moses_template.html~9';
LOI[39] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~35~20~images/bible_images/Moses/moses_template.html~9';
LOI[40] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~35~29~images/bible_images/Moses/moses_template.html~9';
LOI[41] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~35~30~images/bible_images/Moses/moses_template.html~9';
LOI[42] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~35~1~images/bible_images/Moses/moses_template.html~10';
LOI[43] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~35~4~images/bible_images/Moses/moses_template.html~10';
LOI[44] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~35~20~images/bible_images/Moses/moses_template.html~10';
LOI[45] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~35~29~images/bible_images/Moses/moses_template.html~10';
LOI[46] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~35~30~images/bible_images/Moses/moses_template.html~10';
LOI[47] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~35~1~images/bible_images/Moses/moses_template.html~11';
LOI[48] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~35~4~images/bible_images/Moses/moses_template.html~11';
LOI[49] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~35~20~images/bible_images/Moses/moses_template.html~11';
LOI[50] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~35~29~images/bible_images/Moses/moses_template.html~11';
LOI[51] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~35~30~images/bible_images/Moses/moses_template.html~11';
LOI[52] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Exd~35~11~images/bible_images/Temple/temple_template.html~2';
LOI[53] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Exd~35~15~images/bible_images/Temple/temple_template.html~2';
LOI[54] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Exd~35~18~images/bible_images/Temple/temple_template.html~2';
LOI[55] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Exd~35~21~images/bible_images/Temple/temple_template.html~2';
LOI[56] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Exd~35~11~images/bible_images/Temple/temple_template.html~3';
LOI[57] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Exd~35~15~images/bible_images/Temple/temple_template.html~3';
LOI[58] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Exd~35~18~images/bible_images/Temple/temple_template.html~3';
LOI[59] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Exd~35~21~images/bible_images/Temple/temple_template.html~3';
LOI[60] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Exd~35~12~images/bible_images/Temple/temple_template.html~4';
