var LOI = [];
LOI[0] = 'hymn~13~AS NOW THY CHILDREN LOWLY KNEEL~htm_a_s_asnowthy.html';
LOI[1] = 'hymn~22~BY FAITH WE FIND THE PLACE ABOVE~htm_b_y_byfaithw.html';
LOI[2] = 'hymn~22~HE HIDETH MY SOUL~htm_h_e_hehideth.html';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~33~5~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~33~6~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~33~5~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~33~6~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~33~5~images/maps/Otest/otest_template.html~3c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~33~6~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~33~5~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~33~6~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~33~1~images/maps/Otest/otest_template.html~5';
LOI[12] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Horeb~~~~Exd~33~6~images/maps/Otest/otest_template.html~5';
LOI[13] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~33~5~images/maps/Christ/christ_template.html~1';
LOI[14] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~33~6~images/maps/Christ/christ_template.html~1';
LOI[15] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Exd~33~1~images/places/Israel/israel_template.html~8';
LOI[16] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Exd~33~1~images/bible_images/Moses/moses_template.html~3';
LOI[17] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Exd~33~1~images/bible_images/Moses/moses_template.html~3i';
LOI[18] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~Exd~33~1~images/bible_images/Moses/moses_template.html~3a';
LOI[19] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Exd~33~1~images/bible_images/Moses/moses_template.html~4';
LOI[20] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~33~1~images/bible_images/Moses/moses_template.html~6';
LOI[21] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~33~5~images/bible_images/Moses/moses_template.html~6';
LOI[22] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~33~7~images/bible_images/Moses/moses_template.html~6';
LOI[23] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~33~8~images/bible_images/Moses/moses_template.html~6';
LOI[24] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~33~9~images/bible_images/Moses/moses_template.html~6';
LOI[25] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~33~11~images/bible_images/Moses/moses_template.html~6';
LOI[26] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~33~12~images/bible_images/Moses/moses_template.html~6';
LOI[27] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~33~17~images/bible_images/Moses/moses_template.html~6';
LOI[28] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~33~1~images/bible_images/Moses/moses_template.html~7';
LOI[29] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~33~5~images/bible_images/Moses/moses_template.html~7';
LOI[30] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~33~7~images/bible_images/Moses/moses_template.html~7';
LOI[31] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~33~8~images/bible_images/Moses/moses_template.html~7';
LOI[32] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~33~9~images/bible_images/Moses/moses_template.html~7';
LOI[33] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~33~11~images/bible_images/Moses/moses_template.html~7';
LOI[34] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~33~12~images/bible_images/Moses/moses_template.html~7';
LOI[35] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~33~17~images/bible_images/Moses/moses_template.html~7';
LOI[36] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~33~1~images/bible_images/Moses/moses_template.html~9';
LOI[37] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~33~5~images/bible_images/Moses/moses_template.html~9';
LOI[38] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~33~7~images/bible_images/Moses/moses_template.html~9';
LOI[39] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~33~8~images/bible_images/Moses/moses_template.html~9';
LOI[40] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~33~9~images/bible_images/Moses/moses_template.html~9';
LOI[41] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~33~11~images/bible_images/Moses/moses_template.html~9';
LOI[42] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~33~12~images/bible_images/Moses/moses_template.html~9';
LOI[43] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~33~17~images/bible_images/Moses/moses_template.html~9';
LOI[44] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~33~1~images/bible_images/Moses/moses_template.html~10';
LOI[45] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~33~5~images/bible_images/Moses/moses_template.html~10';
LOI[46] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~33~7~images/bible_images/Moses/moses_template.html~10';
LOI[47] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~33~8~images/bible_images/Moses/moses_template.html~10';
LOI[48] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~33~9~images/bible_images/Moses/moses_template.html~10';
LOI[49] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~33~11~images/bible_images/Moses/moses_template.html~10';
LOI[50] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~33~12~images/bible_images/Moses/moses_template.html~10';
LOI[51] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~33~17~images/bible_images/Moses/moses_template.html~10';
LOI[52] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~33~1~images/bible_images/Moses/moses_template.html~11';
LOI[53] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~33~5~images/bible_images/Moses/moses_template.html~11';
LOI[54] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~33~7~images/bible_images/Moses/moses_template.html~11';
LOI[55] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~33~8~images/bible_images/Moses/moses_template.html~11';
LOI[56] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~33~9~images/bible_images/Moses/moses_template.html~11';
LOI[57] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~33~11~images/bible_images/Moses/moses_template.html~11';
LOI[58] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~33~12~images/bible_images/Moses/moses_template.html~11';
LOI[59] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~33~17~images/bible_images/Moses/moses_template.html~11';
LOI[60] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Exd~33~7~images/bible_images/Temple/temple_template.html~2';
LOI[61] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Exd~33~8~images/bible_images/Temple/temple_template.html~2';
LOI[62] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Exd~33~9~images/bible_images/Temple/temple_template.html~2';
LOI[63] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Exd~33~10~images/bible_images/Temple/temple_template.html~2';
LOI[64] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Exd~33~11~images/bible_images/Temple/temple_template.html~2';
LOI[65] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Exd~33~7~images/bible_images/Temple/temple_template.html~3';
LOI[66] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Exd~33~8~images/bible_images/Temple/temple_template.html~3';
LOI[67] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Exd~33~9~images/bible_images/Temple/temple_template.html~3';
LOI[68] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Exd~33~10~images/bible_images/Temple/temple_template.html~3';
LOI[69] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Exd~33~11~images/bible_images/Temple/temple_template.html~3';
