var LOI = [];
LOI[0] = 'hymn~1~ANOTHER SIX DAYS&#8217; WORK IS DONE~htm_a_n_another6.html';
LOI[1] = 'hymn~1~SAFELY THROUGH ANOTHER WEEK~htm_s_a_safelyth.html';
LOI[2] = 'hymn~1~WELCOME, DELIGHTFUL MORN~htm_w_e_l_welcomed.html';
LOI[3] = 'hymn~1~WITH JOY WE HAIL THE SACRED DAY~htm_w_i_t_withjoyw.html';
LOI[4] = 'hymn~2~THAT MAN A GODLY LIFE MIGHT LIVE~htm_t_h_thatmana.html';
LOI[5] = 'hymn~10~COME, LET US ALL WITH ONE ACCORD~htm_c_l_clusawoa.html';
LOI[6] = 'hymn~10~HAIL, HAPPY MORNING~htm_h_a_hailhapp.html';
LOI[7] = 'hymn~10~HAIL TO THE SABBATH DAY~htm_h_a_hailsabb.html';
LOI[8] = 'hymn~10~O DAY OF REST AND GLADNESS~htm_o_d_odayrest.html';
LOI[9] = 'hymn~10~THIS IS THE DAY OF LIGHT~htm_t_h_i_thisistd.html';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~20~22~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~20~22~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~20~22~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~20~22~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~20~2~images/maps/Otest/otest_template.html~5';
LOI[15] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~20~22~images/maps/Christ/christ_template.html~1';
LOI[16] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~20~19~images/bible_images/Moses/moses_template.html~6';
LOI[17] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~20~20~images/bible_images/Moses/moses_template.html~6';
LOI[18] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~20~21~images/bible_images/Moses/moses_template.html~6';
LOI[19] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~20~22~images/bible_images/Moses/moses_template.html~6';
LOI[20] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~20~19~images/bible_images/Moses/moses_template.html~7';
LOI[21] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~20~20~images/bible_images/Moses/moses_template.html~7';
LOI[22] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~20~21~images/bible_images/Moses/moses_template.html~7';
LOI[23] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~20~22~images/bible_images/Moses/moses_template.html~7';
LOI[24] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~20~19~images/bible_images/Moses/moses_template.html~9';
LOI[25] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~20~20~images/bible_images/Moses/moses_template.html~9';
LOI[26] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~20~21~images/bible_images/Moses/moses_template.html~9';
LOI[27] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~20~22~images/bible_images/Moses/moses_template.html~9';
LOI[28] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~20~19~images/bible_images/Moses/moses_template.html~10';
LOI[29] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~20~20~images/bible_images/Moses/moses_template.html~10';
LOI[30] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~20~21~images/bible_images/Moses/moses_template.html~10';
LOI[31] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~20~22~images/bible_images/Moses/moses_template.html~10';
LOI[32] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~20~19~images/bible_images/Moses/moses_template.html~11';
LOI[33] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~20~20~images/bible_images/Moses/moses_template.html~11';
LOI[34] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~20~21~images/bible_images/Moses/moses_template.html~11';
LOI[35] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~20~22~images/bible_images/Moses/moses_template.html~11';
