var LOI = [];
LOI[0] = 'hymn~21~CAPTAIN OF ISRAEL&#8217;S HOST~htm_c_a_captaino.html';
LOI[1] = 'hymn~21~FORWARD! BE OUR WATCHWORD~htm_f_o_forwardb.html';
LOI[2] = 'hymn~21~GUIDE ME, O THOU GREAT JEHOVAH~htm_g_u_guideme.html';
LOI[3] = 'hymn~21~WHEN ISRAEL, OF THE LORD BELOVED~htm_w_i_wiolobel.html';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~13~2~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~13~18~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Joseph~~~~Exd~13~19~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~13~2~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~13~18~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Joseph~~~~Exd~13~19~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~13~2~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~13~18~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~13~19~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~13~2~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~13~18~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~13~19~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~13~3~images/maps/Otest/otest_template.html~5';
LOI[17] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~13~8~images/maps/Otest/otest_template.html~5';
LOI[18] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~13~9~images/maps/Otest/otest_template.html~5';
LOI[19] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~13~14~images/maps/Otest/otest_template.html~5';
LOI[20] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~13~15~images/maps/Otest/otest_template.html~5';
LOI[21] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~13~16~images/maps/Otest/otest_template.html~5';
LOI[22] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~13~17~images/maps/Otest/otest_template.html~5';
LOI[23] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~13~18~images/maps/Otest/otest_template.html~5';
LOI[24] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~13~2~images/maps/Christ/christ_template.html~1';
LOI[25] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~13~18~images/maps/Christ/christ_template.html~1';
LOI[26] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~13~19~images/maps/Christ/christ_template.html~1';
LOI[27] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Exd~13~19~images/bible_images/Moses/moses_template.html~5';
LOI[28] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Exd~13~15~images/bible_images/Moses/moses_template.html~5';
LOI[29] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Exd~13~17~images/bible_images/Moses/moses_template.html~5';
LOI[30] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~13~1~images/bible_images/Moses/moses_template.html~6';
LOI[31] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~13~3~images/bible_images/Moses/moses_template.html~6';
LOI[32] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~13~19~images/bible_images/Moses/moses_template.html~6';
LOI[33] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~13~1~images/bible_images/Moses/moses_template.html~7';
LOI[34] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~13~3~images/bible_images/Moses/moses_template.html~7';
LOI[35] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~13~19~images/bible_images/Moses/moses_template.html~7';
LOI[36] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~13~1~images/bible_images/Moses/moses_template.html~9';
LOI[37] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~13~3~images/bible_images/Moses/moses_template.html~9';
LOI[38] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~13~19~images/bible_images/Moses/moses_template.html~9';
LOI[39] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~13~1~images/bible_images/Moses/moses_template.html~10';
LOI[40] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~13~3~images/bible_images/Moses/moses_template.html~10';
LOI[41] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~13~19~images/bible_images/Moses/moses_template.html~10';
LOI[42] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~13~1~images/bible_images/Moses/moses_template.html~11';
LOI[43] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~13~3~images/bible_images/Moses/moses_template.html~11';
LOI[44] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~13~19~images/bible_images/Moses/moses_template.html~11';
LOI[45] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~Exd~13~17~images/bible_images/Samson/samson_template.html~6';
