var LOI = [];
LOI[0] = 'hymn~8~GOD HIMSELF IS WITH US~htm_g_h_ghimself.html';
LOI[1] = 'hymn~22~APPROACH, MY SOUL, THE MERCY SEAT~htm_a_p_approach.html';
LOI[2] = 'hymn~22~BEFORE THY MERCY SEAT, O LORD~htm_b_t_btmesolo.html';
LOI[3] = 'hymn~22~FROM EVERY STORMY WIND~htm_f_r_fromevsw.html';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~25~2~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~25~22~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~25~2~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~25~22~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~25~2~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~25~22~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~25~2~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~25~22~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~25~2~images/maps/Christ/christ_template.html~1';
LOI[13] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~25~22~images/maps/Christ/christ_template.html~1';
LOI[14] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~25~1~images/bible_images/Moses/moses_template.html~6';
LOI[15] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~25~1~images/bible_images/Moses/moses_template.html~7';
LOI[16] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~25~1~images/bible_images/Moses/moses_template.html~9';
LOI[17] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~25~1~images/bible_images/Moses/moses_template.html~10';
LOI[18] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~25~1~images/bible_images/Moses/moses_template.html~11';
LOI[19] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Exd~25~9~images/bible_images/Temple/temple_template.html~2';
LOI[20] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Exd~25~9~images/bible_images/Temple/temple_template.html~3';
LOI[21] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Exd~25~10~images/bible_images/Temple/temple_template.html~4';
LOI[22] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Exd~25~14~images/bible_images/Temple/temple_template.html~4';
LOI[23] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Exd~25~15~images/bible_images/Temple/temple_template.html~4';
LOI[24] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Exd~25~16~images/bible_images/Temple/temple_template.html~4';
LOI[25] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Exd~25~21~images/bible_images/Temple/temple_template.html~4';
LOI[26] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Exd~25~22~images/bible_images/Temple/temple_template.html~4';
