var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~10~20~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~10~23~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~10~20~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~10~23~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~10~20~images/maps/Otest/otest_template.html~3c';
LOI[5] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~10~23~images/maps/Otest/otest_template.html~3c';
LOI[6] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~10~20~images/maps/Otest/otest_template.html~4';
LOI[7] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~10~23~images/maps/Otest/otest_template.html~4';
LOI[8] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~10~2~images/maps/Otest/otest_template.html~5';
LOI[9] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~10~7~images/maps/Otest/otest_template.html~5';
LOI[10] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~10~12~images/maps/Otest/otest_template.html~5';
LOI[11] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~10~13~images/maps/Otest/otest_template.html~5';
LOI[12] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~10~14~images/maps/Otest/otest_template.html~5';
LOI[13] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~10~15~images/maps/Otest/otest_template.html~5';
LOI[14] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~10~19~images/maps/Otest/otest_template.html~5';
LOI[15] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~10~21~images/maps/Otest/otest_template.html~5';
LOI[16] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Exd~10~22~images/maps/Otest/otest_template.html~5';
LOI[17] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~10~20~images/maps/Christ/christ_template.html~1';
LOI[18] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~10~23~images/maps/Christ/christ_template.html~1';
LOI[19] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Exd~10~1~images/bible_images/Moses/moses_template.html~5';
LOI[20] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Exd~10~3~images/bible_images/Moses/moses_template.html~5';
LOI[21] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Exd~10~6~images/bible_images/Moses/moses_template.html~5';
LOI[22] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Exd~10~8~images/bible_images/Moses/moses_template.html~5';
LOI[23] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Exd~10~16~images/bible_images/Moses/moses_template.html~5';
LOI[24] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Exd~10~18~images/bible_images/Moses/moses_template.html~5';
LOI[25] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Exd~10~24~images/bible_images/Moses/moses_template.html~5';
LOI[26] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Exd~10~28~images/bible_images/Moses/moses_template.html~5';
LOI[27] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~10~1~images/bible_images/Moses/moses_template.html~6';
LOI[28] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~10~3~images/bible_images/Moses/moses_template.html~6';
LOI[29] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~10~8~images/bible_images/Moses/moses_template.html~6';
LOI[30] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~10~9~images/bible_images/Moses/moses_template.html~6';
LOI[31] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~10~12~images/bible_images/Moses/moses_template.html~6';
LOI[32] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~10~13~images/bible_images/Moses/moses_template.html~6';
LOI[33] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~10~16~images/bible_images/Moses/moses_template.html~6';
LOI[34] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~10~21~images/bible_images/Moses/moses_template.html~6';
LOI[35] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~10~22~images/bible_images/Moses/moses_template.html~6';
LOI[36] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~10~24~images/bible_images/Moses/moses_template.html~6';
LOI[37] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~10~25~images/bible_images/Moses/moses_template.html~6';
LOI[38] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Exd~10~29~images/bible_images/Moses/moses_template.html~6';
LOI[39] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~10~1~images/bible_images/Moses/moses_template.html~7';
LOI[40] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~10~3~images/bible_images/Moses/moses_template.html~7';
LOI[41] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~10~8~images/bible_images/Moses/moses_template.html~7';
LOI[42] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~10~9~images/bible_images/Moses/moses_template.html~7';
LOI[43] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~10~12~images/bible_images/Moses/moses_template.html~7';
LOI[44] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~10~13~images/bible_images/Moses/moses_template.html~7';
LOI[45] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~10~16~images/bible_images/Moses/moses_template.html~7';
LOI[46] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~10~21~images/bible_images/Moses/moses_template.html~7';
LOI[47] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~10~22~images/bible_images/Moses/moses_template.html~7';
LOI[48] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~10~24~images/bible_images/Moses/moses_template.html~7';
LOI[49] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~10~25~images/bible_images/Moses/moses_template.html~7';
LOI[50] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Exd~10~29~images/bible_images/Moses/moses_template.html~7';
LOI[51] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~10~1~images/bible_images/Moses/moses_template.html~9';
LOI[52] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~10~3~images/bible_images/Moses/moses_template.html~9';
LOI[53] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~10~8~images/bible_images/Moses/moses_template.html~9';
LOI[54] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~10~9~images/bible_images/Moses/moses_template.html~9';
LOI[55] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~10~12~images/bible_images/Moses/moses_template.html~9';
LOI[56] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~10~13~images/bible_images/Moses/moses_template.html~9';
LOI[57] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~10~16~images/bible_images/Moses/moses_template.html~9';
LOI[58] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~10~21~images/bible_images/Moses/moses_template.html~9';
LOI[59] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~10~22~images/bible_images/Moses/moses_template.html~9';
LOI[60] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~10~24~images/bible_images/Moses/moses_template.html~9';
LOI[61] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~10~25~images/bible_images/Moses/moses_template.html~9';
LOI[62] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Exd~10~29~images/bible_images/Moses/moses_template.html~9';
LOI[63] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~10~1~images/bible_images/Moses/moses_template.html~10';
LOI[64] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~10~3~images/bible_images/Moses/moses_template.html~10';
LOI[65] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~10~8~images/bible_images/Moses/moses_template.html~10';
LOI[66] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~10~9~images/bible_images/Moses/moses_template.html~10';
LOI[67] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~10~12~images/bible_images/Moses/moses_template.html~10';
LOI[68] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~10~13~images/bible_images/Moses/moses_template.html~10';
LOI[69] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~10~16~images/bible_images/Moses/moses_template.html~10';
LOI[70] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~10~21~images/bible_images/Moses/moses_template.html~10';
LOI[71] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~10~22~images/bible_images/Moses/moses_template.html~10';
LOI[72] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~10~24~images/bible_images/Moses/moses_template.html~10';
LOI[73] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~10~25~images/bible_images/Moses/moses_template.html~10';
LOI[74] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Exd~10~29~images/bible_images/Moses/moses_template.html~10';
LOI[75] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~10~1~images/bible_images/Moses/moses_template.html~11';
LOI[76] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~10~3~images/bible_images/Moses/moses_template.html~11';
LOI[77] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~10~8~images/bible_images/Moses/moses_template.html~11';
LOI[78] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~10~9~images/bible_images/Moses/moses_template.html~11';
LOI[79] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~10~12~images/bible_images/Moses/moses_template.html~11';
LOI[80] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~10~13~images/bible_images/Moses/moses_template.html~11';
LOI[81] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~10~16~images/bible_images/Moses/moses_template.html~11';
LOI[82] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~10~21~images/bible_images/Moses/moses_template.html~11';
LOI[83] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~10~22~images/bible_images/Moses/moses_template.html~11';
LOI[84] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~10~24~images/bible_images/Moses/moses_template.html~11';
LOI[85] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~10~25~images/bible_images/Moses/moses_template.html~11';
LOI[86] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Exd~10~29~images/bible_images/Moses/moses_template.html~11';
