var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~27~20~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Exd~27~21~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~27~20~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Exd~27~21~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~27~20~images/maps/Otest/otest_template.html~3c';
LOI[5] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Exd~27~21~images/maps/Otest/otest_template.html~3c';
LOI[6] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~27~20~images/maps/Otest/otest_template.html~4';
LOI[7] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Exd~27~21~images/maps/Otest/otest_template.html~4';
LOI[8] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~27~20~images/maps/Christ/christ_template.html~1';
LOI[9] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Exd~27~21~images/maps/Christ/christ_template.html~1';
LOI[10] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Exd~27~9~images/bible_images/Temple/temple_template.html~2';
LOI[11] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Exd~27~19~images/bible_images/Temple/temple_template.html~2';
LOI[12] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Exd~27~21~images/bible_images/Temple/temple_template.html~2';
LOI[13] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Exd~27~9~images/bible_images/Temple/temple_template.html~3';
LOI[14] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Exd~27~19~images/bible_images/Temple/temple_template.html~3';
LOI[15] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Exd~27~21~images/bible_images/Temple/temple_template.html~3';
