var LOI = [];
LOI[0] = 'hymn~17~WHAT STAR IS THIS, WITH BEAMS SO BRIGHT?~htm_w_h_whatstar.html';
LOI[1] = 'hymn~17~WHEN MARSHALED ON THE NIGHTLY PLAIN~htm_w_h_e_whenmars.html';
LOI[2] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Eber~~~~Num~24~24~images/maps/Otest/otest_template.html~1a';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~24~1~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~24~2~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~24~5~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~24~17~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~24~18~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~24~1~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~24~2~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~24~5~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~24~17~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~24~18~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~24~1~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~24~2~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~24~5~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~24~17~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~24~18~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~24~1~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~24~2~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~24~5~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Moab~~~~Num~24~17~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~24~18~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Num~24~8~images/maps/Otest/otest_template.html~5';
LOI[24] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~24~1~images/maps/Christ/christ_template.html~1';
LOI[25] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~24~2~images/maps/Christ/christ_template.html~1';
LOI[26] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~24~5~images/maps/Christ/christ_template.html~1';
LOI[27] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~24~17~images/maps/Christ/christ_template.html~1';
LOI[28] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~24~18~images/maps/Christ/christ_template.html~1';
