var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~34~2~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~34~13~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~34~29~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Num~34~14~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Simeon~~~~Num~34~20~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Num~34~19~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Zebulun~~~~Num~34~25~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Issachar~~~~Num~34~26~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Dan~~~~Num~34~22~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Asher~~~~Num~34~27~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Naphtali~~~~Num~34~28~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph,Manasseh~~~~Num~34~23~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Num~34~24~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~Num~34~21~images/maps/Otest/otest_template.html~1b';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~34~2~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~34~13~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~34~29~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Num~34~14~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Simeon~~~~Num~34~20~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Num~34~19~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Zebulun~~~~Num~34~25~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Issachar~~~~Num~34~26~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Dan~~~~Num~34~22~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Asher~~~~Num~34~27~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Naphtali~~~~Num~34~28~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph,Manasseh~~~~Num~34~23~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~Num~34~24~images/maps/Otest/otest_template.html~1c';
LOI[27] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~Num~34~21~images/maps/Otest/otest_template.html~1c';
LOI[28] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~34~2~images/maps/Otest/otest_template.html~3c';
LOI[29] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~34~13~images/maps/Otest/otest_template.html~3c';
LOI[30] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~34~29~images/maps/Otest/otest_template.html~3c';
LOI[31] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Num~34~12~images/maps/Otest/otest_template.html~3c';
LOI[32] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Num~34~15~images/maps/Otest/otest_template.html~3c';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~34~2~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~34~13~images/maps/Otest/otest_template.html~4';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~34~29~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~Num~34~15~images/maps/Otest/otest_template.html~4';
LOI[37] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Num~34~5~images/maps/Otest/otest_template.html~5';
LOI[38] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Hor~~~~Num~34~7~images/maps/Otest/otest_template.html~5';
LOI[39] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Hor~~~~Num~34~8~images/maps/Otest/otest_template.html~5';
LOI[40] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~34~2~images/maps/Christ/christ_template.html~1';
LOI[41] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~34~13~images/maps/Christ/christ_template.html~1';
LOI[42] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~34~29~images/maps/Christ/christ_template.html~1';
LOI[43] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Num~34~15~images/places/Israel/israel_template.html~9';
LOI[44] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Num~34~13~images/bible_images/Moses/moses_template.html~3i';
LOI[45] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Num~34~23~images/bible_images/Moses/moses_template.html~5';
LOI[46] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~34~1~images/bible_images/Moses/moses_template.html~6';
LOI[47] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~34~13~images/bible_images/Moses/moses_template.html~6';
LOI[48] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~34~16~images/bible_images/Moses/moses_template.html~6';
LOI[49] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~34~1~images/bible_images/Moses/moses_template.html~7';
LOI[50] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~34~13~images/bible_images/Moses/moses_template.html~7';
LOI[51] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~34~16~images/bible_images/Moses/moses_template.html~7';
LOI[52] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~34~1~images/bible_images/Moses/moses_template.html~9';
LOI[53] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~34~13~images/bible_images/Moses/moses_template.html~9';
LOI[54] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~34~16~images/bible_images/Moses/moses_template.html~9';
LOI[55] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~34~1~images/bible_images/Moses/moses_template.html~10';
LOI[56] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~34~13~images/bible_images/Moses/moses_template.html~10';
LOI[57] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~34~16~images/bible_images/Moses/moses_template.html~10';
LOI[58] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~34~1~images/bible_images/Moses/moses_template.html~11';
LOI[59] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~34~13~images/bible_images/Moses/moses_template.html~11';
LOI[60] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~34~16~images/bible_images/Moses/moses_template.html~11';
