var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~33~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~33~3~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~33~5~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~33~38~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~33~40~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~33~51~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~33~1~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~33~3~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~33~5~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~33~38~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~33~40~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~33~51~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~33~1~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~33~3~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~33~5~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~33~38~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~33~40~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Israel,Jordan~~~~Num~33~51~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Num~33~48~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Num~33~49~images/maps/Otest/otest_template.html~3c';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Num~33~50~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~33~1~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~33~3~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~33~5~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~33~38~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~33~40~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~33~51~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Num~33~44~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Moab,Jericho~~~~Num~33~48~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Num~33~49~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Southern Palestine (map) key=Moab,Jericho~~~~Num~33~50~images/maps/Otest/otest_template.html~4';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Nebo~~~~Num~33~47~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Num~33~1~images/maps/Otest/otest_template.html~5';
LOI[33] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt,Hor~~~~Num~33~38~images/maps/Otest/otest_template.html~5';
LOI[34] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Sinai~~~~Num~33~15~images/maps/Otest/otest_template.html~5';
LOI[35] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Sinai~~~~Num~33~16~images/maps/Otest/otest_template.html~5';
LOI[36] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Hor~~~~Num~33~37~images/maps/Otest/otest_template.html~5';
LOI[37] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Hor~~~~Num~33~39~images/maps/Otest/otest_template.html~5';
LOI[38] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Hor~~~~Num~33~41~images/maps/Otest/otest_template.html~5';
LOI[39] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~33~1~images/maps/Christ/christ_template.html~1';
LOI[40] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~33~3~images/maps/Christ/christ_template.html~1';
LOI[41] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~33~5~images/maps/Christ/christ_template.html~1';
LOI[42] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~33~38~images/maps/Christ/christ_template.html~1';
LOI[43] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~33~40~images/maps/Christ/christ_template.html~1';
LOI[44] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~33~51~images/maps/Christ/christ_template.html~1';
LOI[45] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Num~33~48~images/places/Israel/israel_template.html~9';
LOI[46] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Num~33~50~images/places/Israel/israel_template.html~9';
LOI[47] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Num~33~54~images/bible_images/Moses/moses_template.html~3i';
LOI[48] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~33~1~images/bible_images/Moses/moses_template.html~6';
LOI[49] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~33~2~images/bible_images/Moses/moses_template.html~6';
LOI[50] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~33~50~images/bible_images/Moses/moses_template.html~6';
LOI[51] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~33~1~images/bible_images/Moses/moses_template.html~7';
LOI[52] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~33~2~images/bible_images/Moses/moses_template.html~7';
LOI[53] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~33~50~images/bible_images/Moses/moses_template.html~7';
LOI[54] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~33~1~images/bible_images/Moses/moses_template.html~9';
LOI[55] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~33~2~images/bible_images/Moses/moses_template.html~9';
LOI[56] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~33~50~images/bible_images/Moses/moses_template.html~9';
LOI[57] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~33~1~images/bible_images/Moses/moses_template.html~10';
LOI[58] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~33~2~images/bible_images/Moses/moses_template.html~10';
LOI[59] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~33~50~images/bible_images/Moses/moses_template.html~10';
LOI[60] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Nebo~~~~Num~33~47~images/bible_images/Moses/moses_template.html~10';
LOI[61] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~33~1~images/bible_images/Moses/moses_template.html~11';
LOI[62] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~33~2~images/bible_images/Moses/moses_template.html~11';
LOI[63] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~33~50~images/bible_images/Moses/moses_template.html~11';
LOI[64] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Nebo~~~~Num~33~47~images/bible_images/Moses/moses_template.html~11';
