var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~4~46~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Levi~~~~Num~4~2~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~4~46~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Levi~~~~Num~4~2~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~4~46~images/maps/Otest/otest_template.html~3c';
LOI[5] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~4~46~images/maps/Otest/otest_template.html~4';
LOI[6] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~4~46~images/maps/Christ/christ_template.html~1';
LOI[7] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~4~1~images/bible_images/Moses/moses_template.html~6';
LOI[8] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~4~17~images/bible_images/Moses/moses_template.html~6';
LOI[9] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~4~21~images/bible_images/Moses/moses_template.html~6';
LOI[10] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~4~34~images/bible_images/Moses/moses_template.html~6';
LOI[11] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~4~37~images/bible_images/Moses/moses_template.html~6';
LOI[12] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~4~41~images/bible_images/Moses/moses_template.html~6';
LOI[13] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~4~45~images/bible_images/Moses/moses_template.html~6';
LOI[14] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~4~46~images/bible_images/Moses/moses_template.html~6';
LOI[15] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~4~49~images/bible_images/Moses/moses_template.html~6';
LOI[16] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~4~1~images/bible_images/Moses/moses_template.html~7';
LOI[17] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~4~17~images/bible_images/Moses/moses_template.html~7';
LOI[18] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~4~21~images/bible_images/Moses/moses_template.html~7';
LOI[19] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~4~34~images/bible_images/Moses/moses_template.html~7';
LOI[20] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~4~37~images/bible_images/Moses/moses_template.html~7';
LOI[21] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~4~41~images/bible_images/Moses/moses_template.html~7';
LOI[22] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~4~45~images/bible_images/Moses/moses_template.html~7';
LOI[23] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~4~46~images/bible_images/Moses/moses_template.html~7';
LOI[24] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~4~49~images/bible_images/Moses/moses_template.html~7';
LOI[25] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~4~1~images/bible_images/Moses/moses_template.html~9';
LOI[26] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~4~17~images/bible_images/Moses/moses_template.html~9';
LOI[27] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~4~21~images/bible_images/Moses/moses_template.html~9';
LOI[28] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~4~34~images/bible_images/Moses/moses_template.html~9';
LOI[29] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~4~37~images/bible_images/Moses/moses_template.html~9';
LOI[30] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~4~41~images/bible_images/Moses/moses_template.html~9';
LOI[31] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~4~45~images/bible_images/Moses/moses_template.html~9';
LOI[32] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~4~46~images/bible_images/Moses/moses_template.html~9';
LOI[33] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~4~49~images/bible_images/Moses/moses_template.html~9';
LOI[34] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~4~1~images/bible_images/Moses/moses_template.html~10';
LOI[35] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~4~17~images/bible_images/Moses/moses_template.html~10';
LOI[36] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~4~21~images/bible_images/Moses/moses_template.html~10';
LOI[37] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~4~34~images/bible_images/Moses/moses_template.html~10';
LOI[38] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~4~37~images/bible_images/Moses/moses_template.html~10';
LOI[39] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~4~41~images/bible_images/Moses/moses_template.html~10';
LOI[40] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~4~45~images/bible_images/Moses/moses_template.html~10';
LOI[41] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~4~46~images/bible_images/Moses/moses_template.html~10';
LOI[42] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~4~49~images/bible_images/Moses/moses_template.html~10';
LOI[43] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~4~1~images/bible_images/Moses/moses_template.html~11';
LOI[44] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~4~17~images/bible_images/Moses/moses_template.html~11';
LOI[45] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~4~21~images/bible_images/Moses/moses_template.html~11';
LOI[46] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~4~34~images/bible_images/Moses/moses_template.html~11';
LOI[47] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~4~37~images/bible_images/Moses/moses_template.html~11';
LOI[48] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~4~41~images/bible_images/Moses/moses_template.html~11';
LOI[49] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~4~45~images/bible_images/Moses/moses_template.html~11';
LOI[50] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~4~46~images/bible_images/Moses/moses_template.html~11';
LOI[51] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~4~49~images/bible_images/Moses/moses_template.html~11';
LOI[52] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~3~images/bible_images/Temple/temple_template.html~2';
LOI[53] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~4~images/bible_images/Temple/temple_template.html~2';
LOI[54] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~15~images/bible_images/Temple/temple_template.html~2';
LOI[55] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~16~images/bible_images/Temple/temple_template.html~2';
LOI[56] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~23~images/bible_images/Temple/temple_template.html~2';
LOI[57] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~25~images/bible_images/Temple/temple_template.html~2';
LOI[58] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~26~images/bible_images/Temple/temple_template.html~2';
LOI[59] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~28~images/bible_images/Temple/temple_template.html~2';
LOI[60] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~30~images/bible_images/Temple/temple_template.html~2';
LOI[61] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~31~images/bible_images/Temple/temple_template.html~2';
LOI[62] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~33~images/bible_images/Temple/temple_template.html~2';
LOI[63] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~35~images/bible_images/Temple/temple_template.html~2';
LOI[64] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~37~images/bible_images/Temple/temple_template.html~2';
LOI[65] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~39~images/bible_images/Temple/temple_template.html~2';
LOI[66] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~41~images/bible_images/Temple/temple_template.html~2';
LOI[67] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~43~images/bible_images/Temple/temple_template.html~2';
LOI[68] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~4~47~images/bible_images/Temple/temple_template.html~2';
LOI[69] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~3~images/bible_images/Temple/temple_template.html~3';
LOI[70] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~4~images/bible_images/Temple/temple_template.html~3';
LOI[71] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~15~images/bible_images/Temple/temple_template.html~3';
LOI[72] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~16~images/bible_images/Temple/temple_template.html~3';
LOI[73] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~23~images/bible_images/Temple/temple_template.html~3';
LOI[74] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~25~images/bible_images/Temple/temple_template.html~3';
LOI[75] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~26~images/bible_images/Temple/temple_template.html~3';
LOI[76] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~28~images/bible_images/Temple/temple_template.html~3';
LOI[77] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~30~images/bible_images/Temple/temple_template.html~3';
LOI[78] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~31~images/bible_images/Temple/temple_template.html~3';
LOI[79] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~33~images/bible_images/Temple/temple_template.html~3';
LOI[80] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~35~images/bible_images/Temple/temple_template.html~3';
LOI[81] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~37~images/bible_images/Temple/temple_template.html~3';
LOI[82] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~39~images/bible_images/Temple/temple_template.html~3';
LOI[83] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~41~images/bible_images/Temple/temple_template.html~3';
LOI[84] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~43~images/bible_images/Temple/temple_template.html~3';
LOI[85] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~4~47~images/bible_images/Temple/temple_template.html~3';
LOI[86] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Num~4~5~images/bible_images/Temple/temple_template.html~4';
