var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~23~7~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~23~10~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~23~21~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~23~23~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~23~7~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~23~10~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~23~21~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~23~23~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~23~7~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~23~10~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~23~21~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~23~23~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Moab~~~~Num~23~7~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~23~10~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~23~21~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~23~23~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Num~23~6~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Num~23~17~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Num~23~22~images/maps/Otest/otest_template.html~5';
LOI[19] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~23~7~images/maps/Christ/christ_template.html~1';
LOI[20] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~23~10~images/maps/Christ/christ_template.html~1';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~23~21~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~23~23~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Pisgah~~~~Num~23~14~images/bible_images/Moses/moses_template.html~10';
LOI[24] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Pisgah~~~~Num~23~14~images/bible_images/Moses/moses_template.html~11';
