var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~3~8~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~3~9~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~3~12~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~3~13~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~3~38~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~3~40~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~3~41~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~3~42~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~3~45~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~3~46~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Num~3~50~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Levi~~~~Num~3~6~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Levi~~~~Num~3~15~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Levi~~~~Num~3~17~images/maps/Otest/otest_template.html~1b';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~3~8~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~3~9~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~3~12~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~3~13~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~3~38~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~3~40~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~3~41~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~3~42~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~3~45~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~3~46~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Num~3~50~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Levi~~~~Num~3~6~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Levi~~~~Num~3~15~images/maps/Otest/otest_template.html~1c';
LOI[27] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Levi~~~~Num~3~17~images/maps/Otest/otest_template.html~1c';
LOI[28] = 'image~Bible~Maps~Cities of Refuge (map) key=Hebron~~~~Num~3~19~images/maps/Otest/otest_template.html~2';
LOI[29] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~3~8~images/maps/Otest/otest_template.html~3c';
LOI[30] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~3~9~images/maps/Otest/otest_template.html~3c';
LOI[31] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~3~12~images/maps/Otest/otest_template.html~3c';
LOI[32] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~3~13~images/maps/Otest/otest_template.html~3c';
LOI[33] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~3~38~images/maps/Otest/otest_template.html~3c';
LOI[34] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~3~40~images/maps/Otest/otest_template.html~3c';
LOI[35] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~3~41~images/maps/Otest/otest_template.html~3c';
LOI[36] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~3~42~images/maps/Otest/otest_template.html~3c';
LOI[37] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~3~45~images/maps/Otest/otest_template.html~3c';
LOI[38] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~3~46~images/maps/Otest/otest_template.html~3c';
LOI[39] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Num~3~50~images/maps/Otest/otest_template.html~3c';
LOI[40] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~3~8~images/maps/Otest/otest_template.html~4';
LOI[41] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~3~9~images/maps/Otest/otest_template.html~4';
LOI[42] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~3~12~images/maps/Otest/otest_template.html~4';
LOI[43] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~3~13~images/maps/Otest/otest_template.html~4';
LOI[44] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~3~38~images/maps/Otest/otest_template.html~4';
LOI[45] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~3~40~images/maps/Otest/otest_template.html~4';
LOI[46] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~3~41~images/maps/Otest/otest_template.html~4';
LOI[47] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~3~42~images/maps/Otest/otest_template.html~4';
LOI[48] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~3~45~images/maps/Otest/otest_template.html~4';
LOI[49] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~3~46~images/maps/Otest/otest_template.html~4';
LOI[50] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Num~3~50~images/maps/Otest/otest_template.html~4';
LOI[51] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Num~3~13~images/maps/Otest/otest_template.html~5';
LOI[52] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Sinai~~~~Num~3~1~images/maps/Otest/otest_template.html~5';
LOI[53] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Sinai~~~~Num~3~4~images/maps/Otest/otest_template.html~5';
LOI[54] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Sinai~~~~Num~3~14~images/maps/Otest/otest_template.html~5';
LOI[55] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~3~8~images/maps/Christ/christ_template.html~1';
LOI[56] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~3~9~images/maps/Christ/christ_template.html~1';
LOI[57] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~3~12~images/maps/Christ/christ_template.html~1';
LOI[58] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~3~13~images/maps/Christ/christ_template.html~1';
LOI[59] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~3~38~images/maps/Christ/christ_template.html~1';
LOI[60] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~3~40~images/maps/Christ/christ_template.html~1';
LOI[61] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~3~41~images/maps/Christ/christ_template.html~1';
LOI[62] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~3~42~images/maps/Christ/christ_template.html~1';
LOI[63] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~3~45~images/maps/Christ/christ_template.html~1';
LOI[64] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~3~46~images/maps/Christ/christ_template.html~1';
LOI[65] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Num~3~50~images/maps/Christ/christ_template.html~1';
LOI[66] = 'image~Bible~Places~Hebron (engraving) key=Hebron~~~~Num~3~19~images/places/Israel/israel_template.html~16';
LOI[67] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~3~1~images/bible_images/Moses/moses_template.html~6';
LOI[68] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~3~5~images/bible_images/Moses/moses_template.html~6';
LOI[69] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~3~11~images/bible_images/Moses/moses_template.html~6';
LOI[70] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~3~14~images/bible_images/Moses/moses_template.html~6';
LOI[71] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~3~16~images/bible_images/Moses/moses_template.html~6';
LOI[72] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~3~38~images/bible_images/Moses/moses_template.html~6';
LOI[73] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~3~39~images/bible_images/Moses/moses_template.html~6';
LOI[74] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~3~40~images/bible_images/Moses/moses_template.html~6';
LOI[75] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~3~42~images/bible_images/Moses/moses_template.html~6';
LOI[76] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~3~44~images/bible_images/Moses/moses_template.html~6';
LOI[77] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~3~49~images/bible_images/Moses/moses_template.html~6';
LOI[78] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Num~3~51~images/bible_images/Moses/moses_template.html~6';
LOI[79] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~3~1~images/bible_images/Moses/moses_template.html~7';
LOI[80] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~3~5~images/bible_images/Moses/moses_template.html~7';
LOI[81] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~3~11~images/bible_images/Moses/moses_template.html~7';
LOI[82] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~3~14~images/bible_images/Moses/moses_template.html~7';
LOI[83] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~3~16~images/bible_images/Moses/moses_template.html~7';
LOI[84] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~3~38~images/bible_images/Moses/moses_template.html~7';
LOI[85] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~3~39~images/bible_images/Moses/moses_template.html~7';
LOI[86] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~3~40~images/bible_images/Moses/moses_template.html~7';
LOI[87] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~3~42~images/bible_images/Moses/moses_template.html~7';
LOI[88] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~3~44~images/bible_images/Moses/moses_template.html~7';
LOI[89] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~3~49~images/bible_images/Moses/moses_template.html~7';
LOI[90] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Num~3~51~images/bible_images/Moses/moses_template.html~7';
LOI[91] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~3~1~images/bible_images/Moses/moses_template.html~9';
LOI[92] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~3~5~images/bible_images/Moses/moses_template.html~9';
LOI[93] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~3~11~images/bible_images/Moses/moses_template.html~9';
LOI[94] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~3~14~images/bible_images/Moses/moses_template.html~9';
LOI[95] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~3~16~images/bible_images/Moses/moses_template.html~9';
LOI[96] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~3~38~images/bible_images/Moses/moses_template.html~9';
LOI[97] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~3~39~images/bible_images/Moses/moses_template.html~9';
LOI[98] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~3~40~images/bible_images/Moses/moses_template.html~9';
LOI[99] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~3~42~images/bible_images/Moses/moses_template.html~9';
LOI[100] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~3~44~images/bible_images/Moses/moses_template.html~9';
LOI[101] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~3~49~images/bible_images/Moses/moses_template.html~9';
LOI[102] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Num~3~51~images/bible_images/Moses/moses_template.html~9';
LOI[103] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~3~1~images/bible_images/Moses/moses_template.html~10';
LOI[104] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~3~5~images/bible_images/Moses/moses_template.html~10';
LOI[105] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~3~11~images/bible_images/Moses/moses_template.html~10';
LOI[106] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~3~14~images/bible_images/Moses/moses_template.html~10';
LOI[107] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~3~16~images/bible_images/Moses/moses_template.html~10';
LOI[108] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~3~38~images/bible_images/Moses/moses_template.html~10';
LOI[109] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~3~39~images/bible_images/Moses/moses_template.html~10';
LOI[110] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~3~40~images/bible_images/Moses/moses_template.html~10';
LOI[111] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~3~42~images/bible_images/Moses/moses_template.html~10';
LOI[112] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~3~44~images/bible_images/Moses/moses_template.html~10';
LOI[113] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~3~49~images/bible_images/Moses/moses_template.html~10';
LOI[114] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Num~3~51~images/bible_images/Moses/moses_template.html~10';
LOI[115] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~3~1~images/bible_images/Moses/moses_template.html~11';
LOI[116] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~3~5~images/bible_images/Moses/moses_template.html~11';
LOI[117] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~3~11~images/bible_images/Moses/moses_template.html~11';
LOI[118] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~3~14~images/bible_images/Moses/moses_template.html~11';
LOI[119] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~3~16~images/bible_images/Moses/moses_template.html~11';
LOI[120] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~3~38~images/bible_images/Moses/moses_template.html~11';
LOI[121] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~3~39~images/bible_images/Moses/moses_template.html~11';
LOI[122] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~3~40~images/bible_images/Moses/moses_template.html~11';
LOI[123] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~3~42~images/bible_images/Moses/moses_template.html~11';
LOI[124] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~3~44~images/bible_images/Moses/moses_template.html~11';
LOI[125] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~3~49~images/bible_images/Moses/moses_template.html~11';
LOI[126] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Num~3~51~images/bible_images/Moses/moses_template.html~11';
LOI[127] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~3~7~images/bible_images/Temple/temple_template.html~2';
LOI[128] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~3~8~images/bible_images/Temple/temple_template.html~2';
LOI[129] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~3~23~images/bible_images/Temple/temple_template.html~2';
LOI[130] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~3~25~images/bible_images/Temple/temple_template.html~2';
LOI[131] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~3~26~images/bible_images/Temple/temple_template.html~2';
LOI[132] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~3~29~images/bible_images/Temple/temple_template.html~2';
LOI[133] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~3~35~images/bible_images/Temple/temple_template.html~2';
LOI[134] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~3~36~images/bible_images/Temple/temple_template.html~2';
LOI[135] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Num~3~38~images/bible_images/Temple/temple_template.html~2';
LOI[136] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~3~7~images/bible_images/Temple/temple_template.html~3';
LOI[137] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~3~8~images/bible_images/Temple/temple_template.html~3';
LOI[138] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~3~23~images/bible_images/Temple/temple_template.html~3';
LOI[139] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~3~25~images/bible_images/Temple/temple_template.html~3';
LOI[140] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~3~26~images/bible_images/Temple/temple_template.html~3';
LOI[141] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~3~29~images/bible_images/Temple/temple_template.html~3';
LOI[142] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~3~35~images/bible_images/Temple/temple_template.html~3';
LOI[143] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~3~36~images/bible_images/Temple/temple_template.html~3';
LOI[144] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Num~3~38~images/bible_images/Temple/temple_template.html~3';
LOI[145] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Num~3~31~images/bible_images/Temple/temple_template.html~4';
