var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Deu~24~7~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Deu~24~7~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Deu~24~7~images/maps/Otest/otest_template.html~3c';
LOI[3] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Deu~24~7~images/maps/Otest/otest_template.html~4';
LOI[4] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Deu~24~9~images/maps/Otest/otest_template.html~5';
LOI[5] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Deu~24~18~images/maps/Otest/otest_template.html~5';
LOI[6] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Deu~24~22~images/maps/Otest/otest_template.html~5';
LOI[7] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Deu~24~7~images/maps/Christ/christ_template.html~1';
LOI[8] = 'image~Bible~Images~Miriam\'s Song (engraving) key=Miriam~~~~Deu~24~9~images/bible_images/Moses/moses_template.html~8';
