var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Deu~19~13~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Deu~19~13~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Cities of Refuge (map)~~~~Deu~19~2~images/maps/Otest/otest_template.html~2';
LOI[3] = 'image~Bible~Maps~Cities of Refuge (map)~~~~Deu~19~3~images/maps/Otest/otest_template.html~2';
LOI[4] = 'image~Bible~Maps~Cities of Refuge (map)~~~~Deu~19~4~images/maps/Otest/otest_template.html~2';
LOI[5] = 'image~Bible~Maps~Cities of Refuge (map)~~~~Deu~19~5~images/maps/Otest/otest_template.html~2';
LOI[6] = 'image~Bible~Maps~Cities of Refuge (map)~~~~Deu~19~6~images/maps/Otest/otest_template.html~2';
LOI[7] = 'image~Bible~Maps~Cities of Refuge (map)~~~~Deu~19~7~images/maps/Otest/otest_template.html~2';
LOI[8] = 'image~Bible~Maps~Cities of Refuge (map)~~~~Deu~19~8~images/maps/Otest/otest_template.html~2';
LOI[9] = 'image~Bible~Maps~Cities of Refuge (map)~~~~Deu~19~9~images/maps/Otest/otest_template.html~2';
LOI[10] = 'image~Bible~Maps~Cities of Refuge (map)~~~~Deu~19~10~images/maps/Otest/otest_template.html~2';
LOI[11] = 'image~Bible~Maps~Cities of Refuge (map)~~~~Deu~19~11~images/maps/Otest/otest_template.html~2';
LOI[12] = 'image~Bible~Maps~Cities of Refuge (map)~~~~Deu~19~12~images/maps/Otest/otest_template.html~2';
LOI[13] = 'image~Bible~Maps~Cities of Refuge (map)~~~~Deu~19~13~images/maps/Otest/otest_template.html~2';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Deu~19~13~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Deu~19~13~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Deu~19~13~images/maps/Christ/christ_template.html~1';
