var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Deu~9~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Deu~9~1~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Middle Palestine (map) key=Israel,Jordan~~~~Deu~9~1~images/maps/Otest/otest_template.html~3c';
LOI[3] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Deu~9~1~images/maps/Otest/otest_template.html~4';
LOI[4] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Deu~9~7~images/maps/Otest/otest_template.html~5';
LOI[5] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Deu~9~12~images/maps/Otest/otest_template.html~5';
LOI[6] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Deu~9~26~images/maps/Otest/otest_template.html~5';
LOI[7] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Horeb~~~~Deu~9~8~images/maps/Otest/otest_template.html~5';
LOI[8] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Deu~9~1~images/maps/Christ/christ_template.html~1';
LOI[9] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Deu~9~5~images/places/Israel/israel_template.html~8';
LOI[10] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Deu~9~27~images/places/Israel/israel_template.html~8';
LOI[11] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Deu~9~5~images/bible_images/Moses/moses_template.html~3';
LOI[12] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Deu~9~27~images/bible_images/Moses/moses_template.html~3';
LOI[13] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Deu~9~5~images/bible_images/Moses/moses_template.html~3i';
LOI[14] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Deu~9~27~images/bible_images/Moses/moses_template.html~3i';
LOI[15] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~Deu~9~5~images/bible_images/Moses/moses_template.html~3a';
LOI[16] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~Deu~9~27~images/bible_images/Moses/moses_template.html~3a';
LOI[17] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Deu~9~5~images/bible_images/Moses/moses_template.html~4';
LOI[18] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Deu~9~27~images/bible_images/Moses/moses_template.html~4';
