var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Deu~27~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Deu~27~9~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Deu~27~14~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Deu~27~13~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Deu~27~12~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Deu~27~1~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Deu~27~9~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Deu~27~14~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Deu~27~13~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Deu~27~12~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Deu~27~1~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Deu~27~9~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Deu~27~14~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Gerizim,Jordan~~~~Deu~27~12~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Ebal,Jordan~~~~Deu~27~4~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Ebal~~~~Deu~27~13~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Deu~27~2~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Deu~27~1~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Deu~27~9~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Deu~27~14~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Deu~27~1~images/maps/Christ/christ_template.html~1';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Deu~27~9~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Deu~27~14~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Deu~27~12~images/bible_images/Moses/moses_template.html~5';
LOI[24] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Deu~27~1~images/bible_images/Moses/moses_template.html~6';
LOI[25] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Deu~27~9~images/bible_images/Moses/moses_template.html~6';
LOI[26] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Deu~27~11~images/bible_images/Moses/moses_template.html~6';
LOI[27] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Deu~27~1~images/bible_images/Moses/moses_template.html~7';
LOI[28] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Deu~27~9~images/bible_images/Moses/moses_template.html~7';
LOI[29] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Deu~27~11~images/bible_images/Moses/moses_template.html~7';
LOI[30] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Deu~27~1~images/bible_images/Moses/moses_template.html~9';
LOI[31] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Deu~27~9~images/bible_images/Moses/moses_template.html~9';
LOI[32] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Deu~27~11~images/bible_images/Moses/moses_template.html~9';
LOI[33] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Deu~27~1~images/bible_images/Moses/moses_template.html~10';
LOI[34] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Deu~27~9~images/bible_images/Moses/moses_template.html~10';
LOI[35] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Deu~27~11~images/bible_images/Moses/moses_template.html~10';
LOI[36] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Deu~27~1~images/bible_images/Moses/moses_template.html~11';
LOI[37] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Deu~27~9~images/bible_images/Moses/moses_template.html~11';
LOI[38] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Deu~27~11~images/bible_images/Moses/moses_template.html~11';
