var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Deu~2~12~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Deu~2~12~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Deu~2~12~images/maps/Otest/otest_template.html~3c';
LOI[3] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~Deu~2~36~images/maps/Otest/otest_template.html~3c';
LOI[4] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Deu~2~29~images/maps/Otest/otest_template.html~3c';
LOI[5] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Deu~2~12~images/maps/Otest/otest_template.html~4';
LOI[6] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~Deu~2~36~images/maps/Otest/otest_template.html~4';
LOI[7] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Deu~2~8~images/maps/Otest/otest_template.html~4';
LOI[8] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Deu~2~18~images/maps/Otest/otest_template.html~4';
LOI[9] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Deu~2~12~images/maps/Christ/christ_template.html~1';
LOI[10] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Deu~2~9~images/bible_images/Moses/moses_template.html~3i';
LOI[11] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Deu~2~19~images/bible_images/Moses/moses_template.html~3i';
