var LOI = [];
LOI[0] = 'hymn~2~HIGHER GROUND~htm_h_i_highergr.html';
LOI[1] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Zion~~~~Mic~4~2~images/maps/Otest/otest_template.html~3a';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Zion~~~~Mic~4~8~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Mic~4~7~images/maps/Otest/otest_template.html~3a';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Mic~4~10~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Mic~4~11~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Mic~4~13~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Zion~~~~Mic~4~2~images/maps/Otest/otest_template.html~3b';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Zion~~~~Mic~4~8~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Mic~4~7~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Mic~4~10~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Mic~4~11~images/maps/Otest/otest_template.html~3b';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Mic~4~13~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Mic~4~2~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Mic~4~8~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Mic~4~2~images/places/Israel/israel_template.html~11';
LOI[16] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Mic~4~8~images/places/Israel/israel_template.html~11';
LOI[17] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Mic~4~2~images/places/Israel/israel_template.html~12';
LOI[18] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Mic~4~8~images/places/Israel/israel_template.html~12';
LOI[19] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Mic~4~2~images/places/Israel/israel_template.html~13';
LOI[20] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Mic~4~8~images/places/Israel/israel_template.html~13';
LOI[21] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Mic~4~2~images/places/Israel/israel_template.html~14';
LOI[22] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Mic~4~8~images/places/Israel/israel_template.html~14';
LOI[23] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Mic~4~2~images/places/Israel/israel_template.html~17';
LOI[24] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Mic~4~8~images/places/Israel/israel_template.html~17';
LOI[25] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Mic~4~10~images/bible_images/Kings/kings_template.html~7';
