var LOI = [];
LOI[0] = 'hymn~3~FATHER OF MERCIES, IN THY WORD~htm_f_a_fatofmer.html';
LOI[1] = 'hymn~3~JESUS, LOVER OF MY SOUL~htm_j_l_jlmysoul.html';
LOI[2] = 'hymn~20~HYMN OF PROMISE~htm_h_y_hymnprom.html';
LOI[3] = 'hymn~21~I AM PRAYING FOR YOU~htm_i_a_iampray.html';
LOI[4] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~2Cr~1~1~images/maps/Journeys/journeys_template.html~1';
LOI[5] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map)~~~~2Cr~1~1~images/maps/Journeys/journeys_template.html~2';
LOI[6] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Timotheus~~~~2Cr~1~19~images/maps/Journeys/journeys_template.html~2';
LOI[7] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Corinth~~~~2Cr~1~23~images/maps/Journeys/journeys_template.html~2';
LOI[8] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map)~~~~2Cr~1~1~images/maps/Journeys/journeys_template.html~3';
LOI[9] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Macedonia~~~~2Cr~1~16~images/maps/Journeys/journeys_template.html~3';
LOI[10] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Asia~~~~2Cr~1~8~images/maps/Journeys/journeys_template.html~3';
LOI[11] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Corinth~~~~2Cr~1~23~images/maps/Journeys/journeys_template.html~3';
LOI[12] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart) key=tribulation~~~~2Cr~1~4~images/charts/Bible/bible_template.html~1';
LOI[13] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~2Cr~1~1~images/bible_images/Acts/acts_template.html~2';
