var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~14~4~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jdg~14~4~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~14~4~images/maps/Otest/otest_template.html~3c';
LOI[3] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~14~4~images/maps/Otest/otest_template.html~4';
LOI[4] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~14~4~images/maps/Christ/christ_template.html~1';
LOI[5] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~14~1~images/bible_images/Samson/samson_template.html~1a';
LOI[6] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~14~3~images/bible_images/Samson/samson_template.html~1a';
LOI[7] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~14~5~images/bible_images/Samson/samson_template.html~1a';
LOI[8] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~14~7~images/bible_images/Samson/samson_template.html~1a';
LOI[9] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~14~10~images/bible_images/Samson/samson_template.html~1a';
LOI[10] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~14~12~images/bible_images/Samson/samson_template.html~1a';
LOI[11] = 'image~Bible~Images~Samson Killing the Lion (engraving)~~~~Jdg~14~1~images/bible_images/Samson/samson_template.html~1b';
LOI[12] = 'image~Bible~Images~Samson Killing the Lion (engraving)~~~~Jdg~14~2~images/bible_images/Samson/samson_template.html~1b';
LOI[13] = 'image~Bible~Images~Samson Killing the Lion (engraving)~~~~Jdg~14~3~images/bible_images/Samson/samson_template.html~1b';
LOI[14] = 'image~Bible~Images~Samson Killing the Lion (engraving)~~~~Jdg~14~4~images/bible_images/Samson/samson_template.html~1b';
LOI[15] = 'image~Bible~Images~Samson Killing the Lion (engraving)~~~~Jdg~14~5~images/bible_images/Samson/samson_template.html~1b';
LOI[16] = 'image~Bible~Images~Samson Killing the Lion (engraving)~~~~Jdg~14~6~images/bible_images/Samson/samson_template.html~1b';
LOI[17] = 'image~Bible~Images~Samson Killing the Lion (engraving)~~~~Jdg~14~7~images/bible_images/Samson/samson_template.html~1b';
LOI[18] = 'image~Bible~Images~Samson Killing the Lion (engraving) key=Samson~~~~Jdg~14~10~images/bible_images/Samson/samson_template.html~1b';
LOI[19] = 'image~Bible~Images~Samson Killing the Lion (engraving) key=Samson~~~~Jdg~14~12~images/bible_images/Samson/samson_template.html~1b';
LOI[20] = 'image~Bible~Images~Samson Finding Honey (engraving)~~~~Jdg~14~8~images/bible_images/Samson/samson_template.html~2';
LOI[21] = 'image~Bible~Images~Samson Finding Honey (engraving)~~~~Jdg~14~9~images/bible_images/Samson/samson_template.html~2';
LOI[22] = 'image~Bible~Images~Samson Finding Honey (engraving)~~~~Jdg~14~10~images/bible_images/Samson/samson_template.html~2';
LOI[23] = 'image~Bible~Images~Samson Finding Honey (engraving)~~~~Jdg~14~11~images/bible_images/Samson/samson_template.html~2';
LOI[24] = 'image~Bible~Images~Samson Finding Honey (engraving)~~~~Jdg~14~12~images/bible_images/Samson/samson_template.html~2';
LOI[25] = 'image~Bible~Images~Samson Finding Honey (engraving)~~~~Jdg~14~13~images/bible_images/Samson/samson_template.html~2';
LOI[26] = 'image~Bible~Images~Samson Finding Honey (engraving)~~~~Jdg~14~14~images/bible_images/Samson/samson_template.html~2';
LOI[27] = 'image~Bible~Images~Samson Finding Honey (engraving)~~~~Jdg~14~15~images/bible_images/Samson/samson_template.html~2';
LOI[28] = 'image~Bible~Images~Samson Finding Honey (engraving)~~~~Jdg~14~16~images/bible_images/Samson/samson_template.html~2';
LOI[29] = 'image~Bible~Images~Samson Finding Honey (engraving)~~~~Jdg~14~17~images/bible_images/Samson/samson_template.html~2';
LOI[30] = 'image~Bible~Images~Samson Finding Honey (engraving)~~~~Jdg~14~18~images/bible_images/Samson/samson_template.html~2';
LOI[31] = 'image~Bible~Images~Samson Finding Honey (engraving)~~~~Jdg~14~19~images/bible_images/Samson/samson_template.html~2';
LOI[32] = 'image~Bible~Images~Samson Finding Honey (engraving)~~~~Jdg~14~20~images/bible_images/Samson/samson_template.html~2';
LOI[33] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Jdg~14~1~images/bible_images/Samson/samson_template.html~2';
LOI[34] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Jdg~14~3~images/bible_images/Samson/samson_template.html~2';
LOI[35] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Jdg~14~5~images/bible_images/Samson/samson_template.html~2';
LOI[36] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Jdg~14~7~images/bible_images/Samson/samson_template.html~2';
LOI[37] = 'image~Bible~Images~Samson and the 300 Foxes (engraving) key=Samson~~~~Jdg~14~1~images/bible_images/Samson/samson_template.html~3';
LOI[38] = 'image~Bible~Images~Samson and the 300 Foxes (engraving) key=Samson~~~~Jdg~14~3~images/bible_images/Samson/samson_template.html~3';
LOI[39] = 'image~Bible~Images~Samson and the 300 Foxes (engraving) key=Samson~~~~Jdg~14~5~images/bible_images/Samson/samson_template.html~3';
LOI[40] = 'image~Bible~Images~Samson and the 300 Foxes (engraving) key=Samson~~~~Jdg~14~7~images/bible_images/Samson/samson_template.html~3';
LOI[41] = 'image~Bible~Images~Samson and the 300 Foxes (engraving) key=Samson~~~~Jdg~14~10~images/bible_images/Samson/samson_template.html~3';
LOI[42] = 'image~Bible~Images~Samson and the 300 Foxes (engraving) key=Samson~~~~Jdg~14~12~images/bible_images/Samson/samson_template.html~3';
LOI[43] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~14~1~images/bible_images/Samson/samson_template.html~4';
LOI[44] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~14~3~images/bible_images/Samson/samson_template.html~4';
LOI[45] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~14~5~images/bible_images/Samson/samson_template.html~4';
LOI[46] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~14~7~images/bible_images/Samson/samson_template.html~4';
LOI[47] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~14~10~images/bible_images/Samson/samson_template.html~4';
LOI[48] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~14~12~images/bible_images/Samson/samson_template.html~4';
LOI[49] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~14~1~images/bible_images/Samson/samson_template.html~5';
LOI[50] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~14~3~images/bible_images/Samson/samson_template.html~5';
LOI[51] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~14~5~images/bible_images/Samson/samson_template.html~5';
LOI[52] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~14~7~images/bible_images/Samson/samson_template.html~5';
LOI[53] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~14~10~images/bible_images/Samson/samson_template.html~5';
LOI[54] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~14~12~images/bible_images/Samson/samson_template.html~5';
LOI[55] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson,Philistines~~~~Jdg~14~1~images/bible_images/Samson/samson_template.html~6';
LOI[56] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson,Philistines~~~~Jdg~14~3~images/bible_images/Samson/samson_template.html~6';
LOI[57] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson~~~~Jdg~14~5~images/bible_images/Samson/samson_template.html~6';
LOI[58] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson~~~~Jdg~14~7~images/bible_images/Samson/samson_template.html~6';
LOI[59] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson~~~~Jdg~14~10~images/bible_images/Samson/samson_template.html~6';
LOI[60] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson~~~~Jdg~14~12~images/bible_images/Samson/samson_template.html~6';
LOI[61] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~Jdg~14~2~images/bible_images/Samson/samson_template.html~6';
LOI[62] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~Jdg~14~4~images/bible_images/Samson/samson_template.html~6';
LOI[63] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~14~1~images/bible_images/Samson/samson_template.html~7';
LOI[64] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~14~3~images/bible_images/Samson/samson_template.html~7';
LOI[65] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~14~5~images/bible_images/Samson/samson_template.html~7';
LOI[66] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~14~7~images/bible_images/Samson/samson_template.html~7';
LOI[67] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~14~10~images/bible_images/Samson/samson_template.html~7';
LOI[68] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~14~12~images/bible_images/Samson/samson_template.html~7';
LOI[69] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~14~1~images/bible_images/Samson/samson_template.html~8';
LOI[70] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~14~3~images/bible_images/Samson/samson_template.html~8';
LOI[71] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~14~5~images/bible_images/Samson/samson_template.html~8';
LOI[72] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~14~7~images/bible_images/Samson/samson_template.html~8';
LOI[73] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~14~10~images/bible_images/Samson/samson_template.html~8';
LOI[74] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~14~12~images/bible_images/Samson/samson_template.html~8';
