var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~15~20~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jdg~15~9~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jdg~15~10~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jdg~15~11~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jdg~15~20~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jdg~15~9~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jdg~15~10~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jdg~15~11~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~15~20~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~15~20~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~15~20~images/maps/Christ/christ_template.html~1';
LOI[11] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~15~1~images/bible_images/Samson/samson_template.html~1a';
LOI[12] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~15~3~images/bible_images/Samson/samson_template.html~1a';
LOI[13] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~15~4~images/bible_images/Samson/samson_template.html~1a';
LOI[14] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~15~6~images/bible_images/Samson/samson_template.html~1a';
LOI[15] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~15~7~images/bible_images/Samson/samson_template.html~1a';
LOI[16] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~15~10~images/bible_images/Samson/samson_template.html~1a';
LOI[17] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~15~11~images/bible_images/Samson/samson_template.html~1a';
LOI[18] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~15~12~images/bible_images/Samson/samson_template.html~1a';
LOI[19] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Jdg~15~16~images/bible_images/Samson/samson_template.html~1a';
LOI[20] = 'image~Bible~Images~Samson Killing the Lion (engraving) key=Samson~~~~Jdg~15~1~images/bible_images/Samson/samson_template.html~1b';
LOI[21] = 'image~Bible~Images~Samson Killing the Lion (engraving) key=Samson~~~~Jdg~15~3~images/bible_images/Samson/samson_template.html~1b';
LOI[22] = 'image~Bible~Images~Samson Killing the Lion (engraving) key=Samson~~~~Jdg~15~4~images/bible_images/Samson/samson_template.html~1b';
LOI[23] = 'image~Bible~Images~Samson Killing the Lion (engraving) key=Samson~~~~Jdg~15~6~images/bible_images/Samson/samson_template.html~1b';
LOI[24] = 'image~Bible~Images~Samson Killing the Lion (engraving) key=Samson~~~~Jdg~15~7~images/bible_images/Samson/samson_template.html~1b';
LOI[25] = 'image~Bible~Images~Samson Killing the Lion (engraving) key=Samson~~~~Jdg~15~10~images/bible_images/Samson/samson_template.html~1b';
LOI[26] = 'image~Bible~Images~Samson Killing the Lion (engraving) key=Samson~~~~Jdg~15~11~images/bible_images/Samson/samson_template.html~1b';
LOI[27] = 'image~Bible~Images~Samson Killing the Lion (engraving) key=Samson~~~~Jdg~15~12~images/bible_images/Samson/samson_template.html~1b';
LOI[28] = 'image~Bible~Images~Samson Killing the Lion (engraving) key=Samson~~~~Jdg~15~16~images/bible_images/Samson/samson_template.html~1b';
LOI[29] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Jdg~15~1~images/bible_images/Samson/samson_template.html~2';
LOI[30] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Jdg~15~3~images/bible_images/Samson/samson_template.html~2';
LOI[31] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Jdg~15~4~images/bible_images/Samson/samson_template.html~2';
LOI[32] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Jdg~15~6~images/bible_images/Samson/samson_template.html~2';
LOI[33] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Jdg~15~7~images/bible_images/Samson/samson_template.html~2';
LOI[34] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Jdg~15~10~images/bible_images/Samson/samson_template.html~2';
LOI[35] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Jdg~15~11~images/bible_images/Samson/samson_template.html~2';
LOI[36] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Jdg~15~12~images/bible_images/Samson/samson_template.html~2';
LOI[37] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Jdg~15~16~images/bible_images/Samson/samson_template.html~2';
LOI[38] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~1~images/bible_images/Samson/samson_template.html~3';
LOI[39] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~2~images/bible_images/Samson/samson_template.html~3';
LOI[40] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~3~images/bible_images/Samson/samson_template.html~3';
LOI[41] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~4~images/bible_images/Samson/samson_template.html~3';
LOI[42] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~5~images/bible_images/Samson/samson_template.html~3';
LOI[43] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~6~images/bible_images/Samson/samson_template.html~3';
LOI[44] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~7~images/bible_images/Samson/samson_template.html~3';
LOI[45] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~8~images/bible_images/Samson/samson_template.html~3';
LOI[46] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~9~images/bible_images/Samson/samson_template.html~3';
LOI[47] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~10~images/bible_images/Samson/samson_template.html~3';
LOI[48] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~11~images/bible_images/Samson/samson_template.html~3';
LOI[49] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~12~images/bible_images/Samson/samson_template.html~3';
LOI[50] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~13~images/bible_images/Samson/samson_template.html~3';
LOI[51] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~14~images/bible_images/Samson/samson_template.html~3';
LOI[52] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~15~images/bible_images/Samson/samson_template.html~3';
LOI[53] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~16~images/bible_images/Samson/samson_template.html~3';
LOI[54] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~17~images/bible_images/Samson/samson_template.html~3';
LOI[55] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~18~images/bible_images/Samson/samson_template.html~3';
LOI[56] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~19~images/bible_images/Samson/samson_template.html~3';
LOI[57] = 'image~Bible~Images~Samson and the 300 Foxes (engraving)~~~~Jdg~15~20~images/bible_images/Samson/samson_template.html~3';
LOI[58] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~15~1~images/bible_images/Samson/samson_template.html~4';
LOI[59] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~15~3~images/bible_images/Samson/samson_template.html~4';
LOI[60] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~15~4~images/bible_images/Samson/samson_template.html~4';
LOI[61] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~15~6~images/bible_images/Samson/samson_template.html~4';
LOI[62] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~15~7~images/bible_images/Samson/samson_template.html~4';
LOI[63] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~15~10~images/bible_images/Samson/samson_template.html~4';
LOI[64] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~15~11~images/bible_images/Samson/samson_template.html~4';
LOI[65] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~15~12~images/bible_images/Samson/samson_template.html~4';
LOI[66] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~15~16~images/bible_images/Samson/samson_template.html~4';
LOI[67] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~15~1~images/bible_images/Samson/samson_template.html~5';
LOI[68] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~15~3~images/bible_images/Samson/samson_template.html~5';
LOI[69] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~15~4~images/bible_images/Samson/samson_template.html~5';
LOI[70] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~15~6~images/bible_images/Samson/samson_template.html~5';
LOI[71] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~15~7~images/bible_images/Samson/samson_template.html~5';
LOI[72] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~15~10~images/bible_images/Samson/samson_template.html~5';
LOI[73] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~15~11~images/bible_images/Samson/samson_template.html~5';
LOI[74] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~15~12~images/bible_images/Samson/samson_template.html~5';
LOI[75] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~15~16~images/bible_images/Samson/samson_template.html~5';
LOI[76] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson~~~~Jdg~15~1~images/bible_images/Samson/samson_template.html~6';
LOI[77] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson,Philistines~~~~Jdg~15~3~images/bible_images/Samson/samson_template.html~6';
LOI[78] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson~~~~Jdg~15~4~images/bible_images/Samson/samson_template.html~6';
LOI[79] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson,Philistines~~~~Jdg~15~6~images/bible_images/Samson/samson_template.html~6';
LOI[80] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson~~~~Jdg~15~7~images/bible_images/Samson/samson_template.html~6';
LOI[81] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson~~~~Jdg~15~10~images/bible_images/Samson/samson_template.html~6';
LOI[82] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson,Philistines~~~~Jdg~15~11~images/bible_images/Samson/samson_template.html~6';
LOI[83] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson,Philistines~~~~Jdg~15~12~images/bible_images/Samson/samson_template.html~6';
LOI[84] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson~~~~Jdg~15~16~images/bible_images/Samson/samson_template.html~6';
LOI[85] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~Jdg~15~5~images/bible_images/Samson/samson_template.html~6';
LOI[86] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~Jdg~15~9~images/bible_images/Samson/samson_template.html~6';
LOI[87] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~Jdg~15~14~images/bible_images/Samson/samson_template.html~6';
LOI[88] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~Jdg~15~20~images/bible_images/Samson/samson_template.html~6';
LOI[89] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~15~1~images/bible_images/Samson/samson_template.html~7';
LOI[90] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~15~3~images/bible_images/Samson/samson_template.html~7';
LOI[91] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~15~4~images/bible_images/Samson/samson_template.html~7';
LOI[92] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~15~6~images/bible_images/Samson/samson_template.html~7';
LOI[93] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~15~7~images/bible_images/Samson/samson_template.html~7';
LOI[94] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~15~10~images/bible_images/Samson/samson_template.html~7';
LOI[95] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~15~11~images/bible_images/Samson/samson_template.html~7';
LOI[96] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~15~12~images/bible_images/Samson/samson_template.html~7';
LOI[97] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~15~16~images/bible_images/Samson/samson_template.html~7';
LOI[98] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~15~1~images/bible_images/Samson/samson_template.html~8';
LOI[99] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~15~3~images/bible_images/Samson/samson_template.html~8';
LOI[100] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~15~4~images/bible_images/Samson/samson_template.html~8';
LOI[101] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~15~6~images/bible_images/Samson/samson_template.html~8';
LOI[102] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~15~7~images/bible_images/Samson/samson_template.html~8';
LOI[103] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~15~10~images/bible_images/Samson/samson_template.html~8';
LOI[104] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~15~11~images/bible_images/Samson/samson_template.html~8';
LOI[105] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~15~12~images/bible_images/Samson/samson_template.html~8';
LOI[106] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~15~16~images/bible_images/Samson/samson_template.html~8';
