var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~Jdg~9~17~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~9~22~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~9~55~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jdg~9~22~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jdg~9~55~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~1~images/maps/Otest/otest_template.html~2';
LOI[6] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~2~images/maps/Otest/otest_template.html~2';
LOI[7] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~3~images/maps/Otest/otest_template.html~2';
LOI[8] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~6~images/maps/Otest/otest_template.html~2';
LOI[9] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~7~images/maps/Otest/otest_template.html~2';
LOI[10] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~18~images/maps/Otest/otest_template.html~2';
LOI[11] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~20~images/maps/Otest/otest_template.html~2';
LOI[12] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~23~images/maps/Otest/otest_template.html~2';
LOI[13] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~24~images/maps/Otest/otest_template.html~2';
LOI[14] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~25~images/maps/Otest/otest_template.html~2';
LOI[15] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~26~images/maps/Otest/otest_template.html~2';
LOI[16] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~28~images/maps/Otest/otest_template.html~2';
LOI[17] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~31~images/maps/Otest/otest_template.html~2';
LOI[18] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~34~images/maps/Otest/otest_template.html~2';
LOI[19] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~39~images/maps/Otest/otest_template.html~2';
LOI[20] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~41~images/maps/Otest/otest_template.html~2';
LOI[21] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~46~images/maps/Otest/otest_template.html~2';
LOI[22] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~47~images/maps/Otest/otest_template.html~2';
LOI[23] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~49~images/maps/Otest/otest_template.html~2';
LOI[24] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~9~57~images/maps/Otest/otest_template.html~2';
LOI[25] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~9~22~images/maps/Otest/otest_template.html~3c';
LOI[26] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~9~55~images/maps/Otest/otest_template.html~3c';
LOI[27] = 'image~Bible~Maps~Middle Palestine (map) key=Gerizim~~~~Jdg~9~7~images/maps/Otest/otest_template.html~3c';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~9~22~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~9~55~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~9~22~images/maps/Christ/christ_template.html~1';
LOI[31] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~9~55~images/maps/Christ/christ_template.html~1';
