var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~4~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~4~3~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~4~4~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Ephraim~~~~Jdg~4~5~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jdg~4~6~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~4~23~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~4~24~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Zebulun,Naphtali~~~~Jdg~4~10~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~1~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~2~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~3~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~4~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~5~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~6~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~7~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~8~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~9~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~10~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~11~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~12~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~13~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~14~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~15~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~16~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~17~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~18~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~19~images/maps/Otest/otest_template.html~1c';
LOI[27] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~20~images/maps/Otest/otest_template.html~1c';
LOI[28] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~21~images/maps/Otest/otest_template.html~1c';
LOI[29] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~22~images/maps/Otest/otest_template.html~1c';
LOI[30] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~23~images/maps/Otest/otest_template.html~1c';
LOI[31] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~4~24~images/maps/Otest/otest_template.html~1c';
LOI[32] = 'image~Bible~Maps~Cities of Refuge (map) key=Kedesh~~~~Jdg~4~9~images/maps/Otest/otest_template.html~2';
LOI[33] = 'image~Bible~Maps~Cities of Refuge (map) key=Kedesh~~~~Jdg~4~10~images/maps/Otest/otest_template.html~2';
LOI[34] = 'image~Bible~Maps~Cities of Refuge (map) key=Kedesh~~~~Jdg~4~11~images/maps/Otest/otest_template.html~2';
LOI[35] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~4~1~images/maps/Otest/otest_template.html~3c';
LOI[36] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~4~3~images/maps/Otest/otest_template.html~3c';
LOI[37] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~4~4~images/maps/Otest/otest_template.html~3c';
LOI[38] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~4~5~images/maps/Otest/otest_template.html~3c';
LOI[39] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~4~6~images/maps/Otest/otest_template.html~3c';
LOI[40] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~4~23~images/maps/Otest/otest_template.html~3c';
LOI[41] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~4~24~images/maps/Otest/otest_template.html~3c';
LOI[42] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~4~1~images/maps/Otest/otest_template.html~4';
LOI[43] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~4~3~images/maps/Otest/otest_template.html~4';
LOI[44] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~4~4~images/maps/Otest/otest_template.html~4';
LOI[45] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~4~5~images/maps/Otest/otest_template.html~4';
LOI[46] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~4~6~images/maps/Otest/otest_template.html~4';
LOI[47] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~4~23~images/maps/Otest/otest_template.html~4';
LOI[48] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~4~24~images/maps/Otest/otest_template.html~4';
LOI[49] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~4~1~images/maps/Christ/christ_template.html~1';
LOI[50] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~4~3~images/maps/Christ/christ_template.html~1';
LOI[51] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~4~4~images/maps/Christ/christ_template.html~1';
LOI[52] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~4~5~images/maps/Christ/christ_template.html~1';
LOI[53] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~4~6~images/maps/Christ/christ_template.html~1';
LOI[54] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~4~23~images/maps/Christ/christ_template.html~1';
LOI[55] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~4~24~images/maps/Christ/christ_template.html~1';
LOI[56] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jdg~4~11~images/bible_images/Moses/moses_template.html~6';
LOI[57] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jdg~4~11~images/bible_images/Moses/moses_template.html~7';
LOI[58] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jdg~4~11~images/bible_images/Moses/moses_template.html~9';
LOI[59] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jdg~4~11~images/bible_images/Moses/moses_template.html~10';
LOI[60] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jdg~4~11~images/bible_images/Moses/moses_template.html~11';
