var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~Jdg~6~1~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~Jdg~6~2~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~6~1~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~6~2~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~6~3~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~6~4~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~6~6~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~6~7~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~6~8~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~6~14~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Manasseh~~~~Jdg~6~15~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~6~36~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~6~37~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jdg~6~35~images/maps/Otest/otest_template.html~1b';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~1~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~2~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~3~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~4~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~5~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~6~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~7~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~8~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~9~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~10~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~11~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~12~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~13~images/maps/Otest/otest_template.html~1c';
LOI[27] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~14~images/maps/Otest/otest_template.html~1c';
LOI[28] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~15~images/maps/Otest/otest_template.html~1c';
LOI[29] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~16~images/maps/Otest/otest_template.html~1c';
LOI[30] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~17~images/maps/Otest/otest_template.html~1c';
LOI[31] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~18~images/maps/Otest/otest_template.html~1c';
LOI[32] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~19~images/maps/Otest/otest_template.html~1c';
LOI[33] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~20~images/maps/Otest/otest_template.html~1c';
LOI[34] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~21~images/maps/Otest/otest_template.html~1c';
LOI[35] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~22~images/maps/Otest/otest_template.html~1c';
LOI[36] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~23~images/maps/Otest/otest_template.html~1c';
LOI[37] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~24~images/maps/Otest/otest_template.html~1c';
LOI[38] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~25~images/maps/Otest/otest_template.html~1c';
LOI[39] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~26~images/maps/Otest/otest_template.html~1c';
LOI[40] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~27~images/maps/Otest/otest_template.html~1c';
LOI[41] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~28~images/maps/Otest/otest_template.html~1c';
LOI[42] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~29~images/maps/Otest/otest_template.html~1c';
LOI[43] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~30~images/maps/Otest/otest_template.html~1c';
LOI[44] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~31~images/maps/Otest/otest_template.html~1c';
LOI[45] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~32~images/maps/Otest/otest_template.html~1c';
LOI[46] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~33~images/maps/Otest/otest_template.html~1c';
LOI[47] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~34~images/maps/Otest/otest_template.html~1c';
LOI[48] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~35~images/maps/Otest/otest_template.html~1c';
LOI[49] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~36~images/maps/Otest/otest_template.html~1c';
LOI[50] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~37~images/maps/Otest/otest_template.html~1c';
LOI[51] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~38~images/maps/Otest/otest_template.html~1c';
LOI[52] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~39~images/maps/Otest/otest_template.html~1c';
LOI[53] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~6~40~images/maps/Otest/otest_template.html~1c';
LOI[54] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~6~1~images/maps/Otest/otest_template.html~3c';
LOI[55] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~6~2~images/maps/Otest/otest_template.html~3c';
LOI[56] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~6~3~images/maps/Otest/otest_template.html~3c';
LOI[57] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~6~4~images/maps/Otest/otest_template.html~3c';
LOI[58] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~6~6~images/maps/Otest/otest_template.html~3c';
LOI[59] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~6~7~images/maps/Otest/otest_template.html~3c';
LOI[60] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~6~8~images/maps/Otest/otest_template.html~3c';
LOI[61] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~6~14~images/maps/Otest/otest_template.html~3c';
LOI[62] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~6~15~images/maps/Otest/otest_template.html~3c';
LOI[63] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~6~36~images/maps/Otest/otest_template.html~3c';
LOI[64] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~6~37~images/maps/Otest/otest_template.html~3c';
LOI[65] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~6~1~images/maps/Otest/otest_template.html~4';
LOI[66] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~6~2~images/maps/Otest/otest_template.html~4';
LOI[67] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~6~3~images/maps/Otest/otest_template.html~4';
LOI[68] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Gaza~~~~Jdg~6~4~images/maps/Otest/otest_template.html~4';
LOI[69] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~6~6~images/maps/Otest/otest_template.html~4';
LOI[70] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~6~7~images/maps/Otest/otest_template.html~4';
LOI[71] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~6~8~images/maps/Otest/otest_template.html~4';
LOI[72] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~6~14~images/maps/Otest/otest_template.html~4';
LOI[73] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~6~15~images/maps/Otest/otest_template.html~4';
LOI[74] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~6~36~images/maps/Otest/otest_template.html~4';
LOI[75] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~6~37~images/maps/Otest/otest_template.html~4';
LOI[76] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jdg~6~8~images/maps/Otest/otest_template.html~5';
LOI[77] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jdg~6~13~images/maps/Otest/otest_template.html~5';
LOI[78] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~6~1~images/maps/Christ/christ_template.html~1';
LOI[79] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~6~2~images/maps/Christ/christ_template.html~1';
LOI[80] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~6~3~images/maps/Christ/christ_template.html~1';
LOI[81] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~6~4~images/maps/Christ/christ_template.html~1';
LOI[82] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~6~6~images/maps/Christ/christ_template.html~1';
LOI[83] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~6~7~images/maps/Christ/christ_template.html~1';
LOI[84] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~6~8~images/maps/Christ/christ_template.html~1';
LOI[85] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~6~14~images/maps/Christ/christ_template.html~1';
LOI[86] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~6~15~images/maps/Christ/christ_template.html~1';
LOI[87] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~6~36~images/maps/Christ/christ_template.html~1';
LOI[88] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~6~37~images/maps/Christ/christ_template.html~1';
LOI[89] = 'image~Bible~Images~The Leper Healed (engraving) key=miracles~~~~Jdg~6~13~images/bible_images/Miracles/miracles_template.html~1';
LOI[90] = 'image~Bible~Images~Man With Palsy Healed (engraving) key=miracles~~~~Jdg~6~13~images/bible_images/Miracles/miracles_template.html~2';
LOI[91] = 'image~Bible~Images~The Raising of Jairus\' Daughter (engraving) key=miracles~~~~Jdg~6~13~images/bible_images/Miracles/miracles_template.html~3';
LOI[92] = 'image~Bible~Images~The Paralytic Healed (engraving) key=miracles~~~~Jdg~6~13~images/bible_images/Miracles/miracles_template.html~4';
LOI[93] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving) key=miracles~~~~Jdg~6~13~images/bible_images/Miracles/miracles_template.html~5';
LOI[94] = 'image~Bible~Images~Jesus Walking on the Sea (engraving) key=miracles~~~~Jdg~6~13~images/bible_images/Miracles/miracles_template.html~6';
LOI[95] = 'image~Bible~Images~Healing Demoniac Daughter (engraving) key=miracles~~~~Jdg~6~13~images/bible_images/Miracles/miracles_template.html~7';
LOI[96] = 'image~Bible~Images~Deaf Man Hears (engraving) key=miracles~~~~Jdg~6~13~images/bible_images/Miracles/miracles_template.html~8';
LOI[97] = 'image~Bible~Images~Man Born Blind Healed (engraving) key=miracles~~~~Jdg~6~13~images/bible_images/Miracles/miracles_template.html~9';
LOI[98] = 'image~Bible~Images~Jesus Healing Ten Lepers (engraving) key=miracles~~~~Jdg~6~13~images/bible_images/Miracles/miracles_template.html~10';
LOI[99] = 'image~Bible~Images~Jesus Heals Bartimaeus (engraving) key=miracles~~~~Jdg~6~13~images/bible_images/Miracles/miracles_template.html~11';
