var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~13~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~13~5~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Dan~~~~Jdg~13~25~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jdg~13~1~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jdg~13~5~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Dan~~~~Jdg~13~25~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~13~1~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~13~5~images/maps/Otest/otest_template.html~3c';
LOI[8] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~13~1~images/maps/Otest/otest_template.html~4';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~13~5~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~13~1~images/maps/Christ/christ_template.html~1';
LOI[11] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~13~5~images/maps/Christ/christ_template.html~1';
LOI[12] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~1~images/bible_images/Samson/samson_template.html~1a';
LOI[13] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~2~images/bible_images/Samson/samson_template.html~1a';
LOI[14] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~3~images/bible_images/Samson/samson_template.html~1a';
LOI[15] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~4~images/bible_images/Samson/samson_template.html~1a';
LOI[16] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~5~images/bible_images/Samson/samson_template.html~1a';
LOI[17] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~6~images/bible_images/Samson/samson_template.html~1a';
LOI[18] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~7~images/bible_images/Samson/samson_template.html~1a';
LOI[19] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~8~images/bible_images/Samson/samson_template.html~1a';
LOI[20] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~9~images/bible_images/Samson/samson_template.html~1a';
LOI[21] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~10~images/bible_images/Samson/samson_template.html~1a';
LOI[22] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~11~images/bible_images/Samson/samson_template.html~1a';
LOI[23] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~12~images/bible_images/Samson/samson_template.html~1a';
LOI[24] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~13~images/bible_images/Samson/samson_template.html~1a';
LOI[25] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~14~images/bible_images/Samson/samson_template.html~1a';
LOI[26] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~15~images/bible_images/Samson/samson_template.html~1a';
LOI[27] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~16~images/bible_images/Samson/samson_template.html~1a';
LOI[28] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~17~images/bible_images/Samson/samson_template.html~1a';
LOI[29] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~18~images/bible_images/Samson/samson_template.html~1a';
LOI[30] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~19~images/bible_images/Samson/samson_template.html~1a';
LOI[31] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~20~images/bible_images/Samson/samson_template.html~1a';
LOI[32] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~21~images/bible_images/Samson/samson_template.html~1a';
LOI[33] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~22~images/bible_images/Samson/samson_template.html~1a';
LOI[34] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~23~images/bible_images/Samson/samson_template.html~1a';
LOI[35] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~24~images/bible_images/Samson/samson_template.html~1a';
LOI[36] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving)~~~~Jdg~13~25~images/bible_images/Samson/samson_template.html~1a';
LOI[37] = 'image~Bible~Images~Samson Killing the Lion (engraving) key=Samson~~~~Jdg~13~24~images/bible_images/Samson/samson_template.html~1b';
LOI[38] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Jdg~13~24~images/bible_images/Samson/samson_template.html~2';
LOI[39] = 'image~Bible~Images~Samson and the 300 Foxes (engraving) key=Samson~~~~Jdg~13~24~images/bible_images/Samson/samson_template.html~3';
LOI[40] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Jdg~13~24~images/bible_images/Samson/samson_template.html~4';
LOI[41] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Jdg~13~24~images/bible_images/Samson/samson_template.html~5';
LOI[42] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson~~~~Jdg~13~24~images/bible_images/Samson/samson_template.html~6';
LOI[43] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~Jdg~13~1~images/bible_images/Samson/samson_template.html~6';
LOI[44] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~Jdg~13~5~images/bible_images/Samson/samson_template.html~6';
LOI[45] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Jdg~13~24~images/bible_images/Samson/samson_template.html~7';
LOI[46] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Jdg~13~24~images/bible_images/Samson/samson_template.html~8';
