var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~Jdg~8~3~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~Jdg~8~5~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~Jdg~8~12~images/maps/Otest/otest_template.html~1a';
LOI[3] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~Jdg~8~22~images/maps/Otest/otest_template.html~1a';
LOI[4] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~Jdg~8~26~images/maps/Otest/otest_template.html~1a';
LOI[5] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~Jdg~8~28~images/maps/Otest/otest_template.html~1a';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~8~22~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~8~27~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~8~28~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~8~33~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~8~34~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~8~35~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Jdg~8~1~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Jdg~8~2~images/maps/Otest/otest_template.html~1b';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~1~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~2~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~3~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~4~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~5~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~6~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~7~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~8~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~9~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~10~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~11~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~12~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~13~images/maps/Otest/otest_template.html~1c';
LOI[27] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~14~images/maps/Otest/otest_template.html~1c';
LOI[28] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~15~images/maps/Otest/otest_template.html~1c';
LOI[29] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~16~images/maps/Otest/otest_template.html~1c';
LOI[30] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~17~images/maps/Otest/otest_template.html~1c';
LOI[31] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~18~images/maps/Otest/otest_template.html~1c';
LOI[32] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~19~images/maps/Otest/otest_template.html~1c';
LOI[33] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~20~images/maps/Otest/otest_template.html~1c';
LOI[34] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~21~images/maps/Otest/otest_template.html~1c';
LOI[35] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~22~images/maps/Otest/otest_template.html~1c';
LOI[36] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~23~images/maps/Otest/otest_template.html~1c';
LOI[37] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~24~images/maps/Otest/otest_template.html~1c';
LOI[38] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~25~images/maps/Otest/otest_template.html~1c';
LOI[39] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~26~images/maps/Otest/otest_template.html~1c';
LOI[40] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~27~images/maps/Otest/otest_template.html~1c';
LOI[41] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~28~images/maps/Otest/otest_template.html~1c';
LOI[42] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~29~images/maps/Otest/otest_template.html~1c';
LOI[43] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~30~images/maps/Otest/otest_template.html~1c';
LOI[44] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~31~images/maps/Otest/otest_template.html~1c';
LOI[45] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~32~images/maps/Otest/otest_template.html~1c';
LOI[46] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~33~images/maps/Otest/otest_template.html~1c';
LOI[47] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~34~images/maps/Otest/otest_template.html~1c';
LOI[48] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~8~35~images/maps/Otest/otest_template.html~1c';
LOI[49] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jdg~8~31~images/maps/Otest/otest_template.html~2';
LOI[50] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~8~22~images/maps/Otest/otest_template.html~3c';
LOI[51] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~8~27~images/maps/Otest/otest_template.html~3c';
LOI[52] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~8~28~images/maps/Otest/otest_template.html~3c';
LOI[53] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~8~33~images/maps/Otest/otest_template.html~3c';
LOI[54] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~8~34~images/maps/Otest/otest_template.html~3c';
LOI[55] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~8~35~images/maps/Otest/otest_template.html~3c';
LOI[56] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Jdg~8~4~images/maps/Otest/otest_template.html~3c';
LOI[57] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~8~22~images/maps/Otest/otest_template.html~4';
LOI[58] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~8~27~images/maps/Otest/otest_template.html~4';
LOI[59] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~8~28~images/maps/Otest/otest_template.html~4';
LOI[60] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~8~33~images/maps/Otest/otest_template.html~4';
LOI[61] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~8~34~images/maps/Otest/otest_template.html~4';
LOI[62] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~8~35~images/maps/Otest/otest_template.html~4';
LOI[63] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~8~22~images/maps/Christ/christ_template.html~1';
LOI[64] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~8~27~images/maps/Christ/christ_template.html~1';
LOI[65] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~8~28~images/maps/Christ/christ_template.html~1';
LOI[66] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~8~33~images/maps/Christ/christ_template.html~1';
LOI[67] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~8~34~images/maps/Christ/christ_template.html~1';
LOI[68] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~8~35~images/maps/Christ/christ_template.html~1';
