var LOI = [];
LOI[0] = 'hymn~29~THE SWORD OF THE LORD~htm_s_w_swordlor.html';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~Jdg~7~8~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~Jdg~7~13~images/maps/Otest/otest_template.html~1a';
LOI[3] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~Jdg~7~14~images/maps/Otest/otest_template.html~1a';
LOI[4] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~Jdg~7~15~images/maps/Otest/otest_template.html~1a';
LOI[5] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Midian~~~~Jdg~7~25~images/maps/Otest/otest_template.html~1a';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~7~2~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~7~8~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~7~14~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~7~15~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jdg~7~23~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Jdg~7~24~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~1~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~2~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~3~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~4~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~5~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~6~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~7~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~8~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~9~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~10~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~11~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~12~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~13~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~14~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~15~images/maps/Otest/otest_template.html~1c';
LOI[27] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~16~images/maps/Otest/otest_template.html~1c';
LOI[28] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~17~images/maps/Otest/otest_template.html~1c';
LOI[29] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~18~images/maps/Otest/otest_template.html~1c';
LOI[30] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~19~images/maps/Otest/otest_template.html~1c';
LOI[31] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~20~images/maps/Otest/otest_template.html~1c';
LOI[32] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~21~images/maps/Otest/otest_template.html~1c';
LOI[33] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~22~images/maps/Otest/otest_template.html~1c';
LOI[34] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~23~images/maps/Otest/otest_template.html~1c';
LOI[35] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~24~images/maps/Otest/otest_template.html~1c';
LOI[36] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jdg~7~25~images/maps/Otest/otest_template.html~1c';
LOI[37] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~7~2~images/maps/Otest/otest_template.html~3c';
LOI[38] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~7~8~images/maps/Otest/otest_template.html~3c';
LOI[39] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~7~14~images/maps/Otest/otest_template.html~3c';
LOI[40] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~7~15~images/maps/Otest/otest_template.html~3c';
LOI[41] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~7~23~images/maps/Otest/otest_template.html~3c';
LOI[42] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~Jdg~7~3~images/maps/Otest/otest_template.html~3c';
LOI[43] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Jdg~7~24~images/maps/Otest/otest_template.html~3c';
LOI[44] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Jdg~7~25~images/maps/Otest/otest_template.html~3c';
LOI[45] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~7~2~images/maps/Otest/otest_template.html~4';
LOI[46] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~7~8~images/maps/Otest/otest_template.html~4';
LOI[47] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~7~14~images/maps/Otest/otest_template.html~4';
LOI[48] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~7~15~images/maps/Otest/otest_template.html~4';
LOI[49] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~7~23~images/maps/Otest/otest_template.html~4';
LOI[50] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~Jdg~7~3~images/maps/Otest/otest_template.html~4';
LOI[51] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~7~2~images/maps/Christ/christ_template.html~1';
LOI[52] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~7~8~images/maps/Christ/christ_template.html~1';
LOI[53] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~7~14~images/maps/Christ/christ_template.html~1';
LOI[54] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~7~15~images/maps/Christ/christ_template.html~1';
LOI[55] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~7~23~images/maps/Christ/christ_template.html~1';
