var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Ephraim~~~~Jdg~19~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~19~12~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~19~29~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~19~30~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Jdg~19~16~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Jdg~19~18~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~Jdg~19~14~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Ephraim~~~~Jdg~19~1~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jdg~19~12~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jdg~19~29~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jdg~19~30~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~Jdg~19~16~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~Jdg~19~18~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~Jdg~19~14~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jdg~19~10~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jdg~19~10~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~19~1~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~19~12~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~19~29~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~19~30~images/maps/Otest/otest_template.html~3c';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~19~1~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~19~12~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~19~29~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~19~30~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jdg~19~10~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jdg~19~30~images/maps/Otest/otest_template.html~5';
LOI[26] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~19~1~images/maps/Christ/christ_template.html~1';
LOI[27] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~19~12~images/maps/Christ/christ_template.html~1';
LOI[28] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~19~29~images/maps/Christ/christ_template.html~1';
LOI[29] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~19~30~images/maps/Christ/christ_template.html~1';
LOI[30] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jdg~19~10~images/places/Israel/israel_template.html~11';
LOI[31] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jdg~19~10~images/places/Israel/israel_template.html~12';
LOI[32] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jdg~19~10~images/places/Israel/israel_template.html~13';
LOI[33] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jdg~19~10~images/places/Israel/israel_template.html~14';
LOI[34] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jdg~19~10~images/places/Israel/israel_template.html~17';
