var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jdg~17~6~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Jdg~17~7~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Jdg~17~1~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Jdg~17~8~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jdg~17~6~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Jdg~17~7~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~Jdg~17~1~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~Jdg~17~8~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jdg~17~6~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jdg~17~6~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jdg~17~6~images/maps/Christ/christ_template.html~1';
