var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~6~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~6~18~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~6~23~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~6~25~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~6~1~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~6~18~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~6~23~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~6~25~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~6~1~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~6~18~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~6~23~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~6~25~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jericho~~~~Jos~6~1~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~6~18~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~6~23~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jericho~~~~Jos~6~25~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~Jos~6~2~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~Jos~6~26~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~6~1~images/maps/Christ/christ_template.html~1';
LOI[19] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~6~18~images/maps/Christ/christ_template.html~1';
LOI[20] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~6~23~images/maps/Christ/christ_template.html~1';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~6~25~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Jos~6~1~images/places/Israel/israel_template.html~9';
LOI[23] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Jos~6~2~images/places/Israel/israel_template.html~9';
LOI[24] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Jos~6~25~images/places/Israel/israel_template.html~9';
LOI[25] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Jos~6~26~images/places/Israel/israel_template.html~9';
LOI[26] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Jos~6~4~images/bible_images/Temple/temple_template.html~4';
LOI[27] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Jos~6~6~images/bible_images/Temple/temple_template.html~4';
LOI[28] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Jos~6~7~images/bible_images/Temple/temple_template.html~4';
LOI[29] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Jos~6~8~images/bible_images/Temple/temple_template.html~4';
LOI[30] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Jos~6~9~images/bible_images/Temple/temple_template.html~4';
LOI[31] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Jos~6~11~images/bible_images/Temple/temple_template.html~4';
LOI[32] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Jos~6~12~images/bible_images/Temple/temple_template.html~4';
LOI[33] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Jos~6~13~images/bible_images/Temple/temple_template.html~4';
