var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~12~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Manasseh~~~~Jos~12~6~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~12~7~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~12~1~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Manasseh~~~~Jos~12~6~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~12~7~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Og~~~~Jos~12~4~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Cities of Refuge (map) key=Hebron~~~~Jos~12~10~images/maps/Otest/otest_template.html~2';
LOI[8] = 'image~Bible~Maps~Cities of Refuge (map) key=Kedesh~~~~Jos~12~22~images/maps/Otest/otest_template.html~2';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jos~12~10~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jos~12~10~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel,Jordan~~~~Jos~12~1~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~12~6~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel,Jordan~~~~Jos~12~7~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~Jos~12~2~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~Jos~12~5~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Carmel~~~~Jos~12~22~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~12~1~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~12~6~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~12~7~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jos~12~10~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~Jos~12~2~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~Jos~12~5~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~Jos~12~9~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~12~1~images/maps/Christ/christ_template.html~1';
LOI[25] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~12~6~images/maps/Christ/christ_template.html~1';
LOI[26] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~12~7~images/maps/Christ/christ_template.html~1';
LOI[27] = 'image~Bible~Maps~Divisions of Palestine (map) key=Bashan~~~~Jos~12~4~images/maps/Christ/christ_template.html~1';
LOI[28] = 'image~Bible~Maps~Divisions of Palestine (map) key=Bashan~~~~Jos~12~5~images/maps/Christ/christ_template.html~1';
LOI[29] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Jos~12~9~images/places/Israel/israel_template.html~9';
LOI[30] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jos~12~10~images/places/Israel/israel_template.html~11';
LOI[31] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jos~12~10~images/places/Israel/israel_template.html~12';
LOI[32] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jos~12~10~images/places/Israel/israel_template.html~13';
LOI[33] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jos~12~10~images/places/Israel/israel_template.html~14';
LOI[34] = 'image~Bible~Places~Hebron (engraving) key=Hebron~~~~Jos~12~10~images/places/Israel/israel_template.html~16';
LOI[35] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jos~12~10~images/places/Israel/israel_template.html~17';
LOI[36] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jos~12~6~images/bible_images/Moses/moses_template.html~6';
LOI[37] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jos~12~6~images/bible_images/Moses/moses_template.html~7';
LOI[38] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jos~12~6~images/bible_images/Moses/moses_template.html~9';
LOI[39] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jos~12~6~images/bible_images/Moses/moses_template.html~10';
LOI[40] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jos~12~6~images/bible_images/Moses/moses_template.html~11';
LOI[41] = 'image~Bible~Images~Capture of Lachish by Sennacherib (clay tablet) key=Lachish~~~~Jos~12~11~images/bible_images/History/history_template.html~1';
