var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~2~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~3~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~4~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~5~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~6~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~7~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~8~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~9~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~10~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~11~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~12~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~13~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~14~images/maps/Otest/otest_template.html~1b';
LOI[14] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~15~images/maps/Otest/otest_template.html~1b';
LOI[15] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~16~images/maps/Otest/otest_template.html~1b';
LOI[16] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~17~images/maps/Otest/otest_template.html~1b';
LOI[17] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~17~18~images/maps/Otest/otest_template.html~1b';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~1~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~2~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~3~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~4~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~5~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~6~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~7~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~8~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~9~images/maps/Otest/otest_template.html~1c';
LOI[27] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~10~images/maps/Otest/otest_template.html~1c';
LOI[28] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~11~images/maps/Otest/otest_template.html~1c';
LOI[29] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~12~images/maps/Otest/otest_template.html~1c';
LOI[30] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~13~images/maps/Otest/otest_template.html~1c';
LOI[31] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~14~images/maps/Otest/otest_template.html~1c';
LOI[32] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~15~images/maps/Otest/otest_template.html~1c';
LOI[33] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~16~images/maps/Otest/otest_template.html~1c';
LOI[34] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~17~images/maps/Otest/otest_template.html~1c';
LOI[35] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~17~18~images/maps/Otest/otest_template.html~1c';
LOI[36] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jos~17~2~images/maps/Otest/otest_template.html~2';
LOI[37] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jos~17~7~images/maps/Otest/otest_template.html~2';
LOI[38] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~17~13~images/maps/Otest/otest_template.html~3c';
LOI[39] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~Jos~17~1~images/maps/Otest/otest_template.html~3c';
LOI[40] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~Jos~17~3~images/maps/Otest/otest_template.html~3c';
LOI[41] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead,Jordan~~~~Jos~17~5~images/maps/Otest/otest_template.html~3c';
LOI[42] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~Jos~17~6~images/maps/Otest/otest_template.html~3c';
LOI[43] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~17~13~images/maps/Otest/otest_template.html~4';
LOI[44] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~Jos~17~1~images/maps/Otest/otest_template.html~4';
LOI[45] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~Jos~17~3~images/maps/Otest/otest_template.html~4';
LOI[46] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~Jos~17~5~images/maps/Otest/otest_template.html~4';
LOI[47] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~Jos~17~6~images/maps/Otest/otest_template.html~4';
LOI[48] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~17~13~images/maps/Christ/christ_template.html~1';
LOI[49] = 'image~Bible~Maps~Divisions of Palestine (map) key=Bashan~~~~Jos~17~1~images/maps/Christ/christ_template.html~1';
LOI[50] = 'image~Bible~Maps~Divisions of Palestine (map) key=Bashan~~~~Jos~17~5~images/maps/Christ/christ_template.html~1';
LOI[51] = 'image~Bible~Images~The Deluge (engraving) key=Noah~~~~Jos~17~3~images/bible_images/Moses/moses_template.html~1';
LOI[52] = 'image~Bible~Images~Noah\'s Sacrifice (engraving) key=Noah~~~~Jos~17~3~images/bible_images/Moses/moses_template.html~2';
LOI[53] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Jos~17~1~images/bible_images/Moses/moses_template.html~3i';
LOI[54] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Jos~17~2~images/bible_images/Moses/moses_template.html~3i';
LOI[55] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Jos~17~14~images/bible_images/Moses/moses_template.html~3i';
LOI[56] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Jos~17~17~images/bible_images/Moses/moses_template.html~3i';
LOI[57] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Jos~17~1~images/bible_images/Moses/moses_template.html~5';
LOI[58] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Jos~17~2~images/bible_images/Moses/moses_template.html~5';
LOI[59] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Jos~17~14~images/bible_images/Moses/moses_template.html~5';
LOI[60] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Jos~17~16~images/bible_images/Moses/moses_template.html~5';
LOI[61] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Jos~17~17~images/bible_images/Moses/moses_template.html~5';
LOI[62] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jos~17~4~images/bible_images/Moses/moses_template.html~6';
LOI[63] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jos~17~4~images/bible_images/Moses/moses_template.html~7';
LOI[64] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jos~17~4~images/bible_images/Moses/moses_template.html~9';
LOI[65] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jos~17~4~images/bible_images/Moses/moses_template.html~10';
LOI[66] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jos~17~4~images/bible_images/Moses/moses_template.html~11';
