var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~16~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~16~2~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~16~3~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~16~4~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~16~5~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~16~6~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~16~7~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~16~8~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~16~9~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~16~10~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~16~1~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~16~2~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~16~3~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~16~4~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~16~5~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~16~6~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~16~7~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~16~8~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~16~9~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~16~10~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Jos~16~1~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Jos~16~7~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~Jos~16~1~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~Jos~16~7~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Jos~16~1~images/places/Israel/israel_template.html~9';
LOI[25] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Jos~16~7~images/places/Israel/israel_template.html~9';
LOI[26] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Jos~16~1~images/bible_images/Moses/moses_template.html~3i';
LOI[27] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Jos~16~1~images/bible_images/Moses/moses_template.html~5';
LOI[28] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Jos~16~4~images/bible_images/Moses/moses_template.html~5';
