var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~8~10~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~8~14~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~8~15~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~8~17~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~8~21~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~8~22~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~8~24~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~8~27~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~8~30~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~8~31~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~8~32~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~8~33~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~8~35~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~8~10~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~8~14~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~8~15~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~8~17~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~8~21~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~8~22~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~8~24~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~8~27~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~8~30~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~8~31~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~8~32~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~8~33~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~8~35~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~8~10~images/maps/Otest/otest_template.html~3c';
LOI[27] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~8~14~images/maps/Otest/otest_template.html~3c';
LOI[28] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~8~15~images/maps/Otest/otest_template.html~3c';
LOI[29] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~8~17~images/maps/Otest/otest_template.html~3c';
LOI[30] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~8~21~images/maps/Otest/otest_template.html~3c';
LOI[31] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~8~22~images/maps/Otest/otest_template.html~3c';
LOI[32] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~8~24~images/maps/Otest/otest_template.html~3c';
LOI[33] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~8~27~images/maps/Otest/otest_template.html~3c';
LOI[34] = 'image~Bible~Maps~Middle Palestine (map) key=Israel,Ebal~~~~Jos~8~30~images/maps/Otest/otest_template.html~3c';
LOI[35] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~8~31~images/maps/Otest/otest_template.html~3c';
LOI[36] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~8~32~images/maps/Otest/otest_template.html~3c';
LOI[37] = 'image~Bible~Maps~Middle Palestine (map)~~~~Jos~8~33~images/maps/Otest/otest_template.html~3c';
LOI[38] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~8~35~images/maps/Otest/otest_template.html~3c';
LOI[39] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~8~10~images/maps/Otest/otest_template.html~4';
LOI[40] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~8~14~images/maps/Otest/otest_template.html~4';
LOI[41] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~8~15~images/maps/Otest/otest_template.html~4';
LOI[42] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~8~17~images/maps/Otest/otest_template.html~4';
LOI[43] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~8~21~images/maps/Otest/otest_template.html~4';
LOI[44] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~8~22~images/maps/Otest/otest_template.html~4';
LOI[45] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~8~24~images/maps/Otest/otest_template.html~4';
LOI[46] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~8~27~images/maps/Otest/otest_template.html~4';
LOI[47] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~8~30~images/maps/Otest/otest_template.html~4';
LOI[48] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~8~31~images/maps/Otest/otest_template.html~4';
LOI[49] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~8~32~images/maps/Otest/otest_template.html~4';
LOI[50] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~8~33~images/maps/Otest/otest_template.html~4';
LOI[51] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~8~35~images/maps/Otest/otest_template.html~4';
LOI[52] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~Jos~8~2~images/maps/Otest/otest_template.html~4';
LOI[53] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~8~10~images/maps/Christ/christ_template.html~1';
LOI[54] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~8~14~images/maps/Christ/christ_template.html~1';
LOI[55] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~8~15~images/maps/Christ/christ_template.html~1';
LOI[56] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~8~17~images/maps/Christ/christ_template.html~1';
LOI[57] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~8~21~images/maps/Christ/christ_template.html~1';
LOI[58] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~8~22~images/maps/Christ/christ_template.html~1';
LOI[59] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~8~24~images/maps/Christ/christ_template.html~1';
LOI[60] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~8~27~images/maps/Christ/christ_template.html~1';
LOI[61] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~8~30~images/maps/Christ/christ_template.html~1';
LOI[62] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~8~31~images/maps/Christ/christ_template.html~1';
LOI[63] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~8~32~images/maps/Christ/christ_template.html~1';
LOI[64] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~8~33~images/maps/Christ/christ_template.html~1';
LOI[65] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~8~35~images/maps/Christ/christ_template.html~1';
LOI[66] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Jos~8~2~images/places/Israel/israel_template.html~9';
LOI[67] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jos~8~31~images/bible_images/Moses/moses_template.html~6';
LOI[68] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jos~8~32~images/bible_images/Moses/moses_template.html~6';
LOI[69] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jos~8~33~images/bible_images/Moses/moses_template.html~6';
LOI[70] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jos~8~35~images/bible_images/Moses/moses_template.html~6';
LOI[71] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jos~8~31~images/bible_images/Moses/moses_template.html~7';
LOI[72] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jos~8~32~images/bible_images/Moses/moses_template.html~7';
LOI[73] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jos~8~33~images/bible_images/Moses/moses_template.html~7';
LOI[74] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jos~8~35~images/bible_images/Moses/moses_template.html~7';
LOI[75] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jos~8~31~images/bible_images/Moses/moses_template.html~9';
LOI[76] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jos~8~32~images/bible_images/Moses/moses_template.html~9';
LOI[77] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jos~8~33~images/bible_images/Moses/moses_template.html~9';
LOI[78] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jos~8~35~images/bible_images/Moses/moses_template.html~9';
LOI[79] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jos~8~31~images/bible_images/Moses/moses_template.html~10';
LOI[80] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jos~8~32~images/bible_images/Moses/moses_template.html~10';
LOI[81] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jos~8~33~images/bible_images/Moses/moses_template.html~10';
LOI[82] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jos~8~35~images/bible_images/Moses/moses_template.html~10';
LOI[83] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jos~8~31~images/bible_images/Moses/moses_template.html~11';
LOI[84] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jos~8~32~images/bible_images/Moses/moses_template.html~11';
LOI[85] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jos~8~33~images/bible_images/Moses/moses_template.html~11';
LOI[86] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jos~8~35~images/bible_images/Moses/moses_template.html~11';
LOI[87] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Jos~8~33~images/bible_images/Temple/temple_template.html~4';
