var LOI = [];
LOI[0] = 'hymn~15~CHOOSE YE TODAY~htm_c_h_chooseye.html';
LOI[1] = 'hymn~15~HAPPY THE HOME WHEN GOD IS THERE~htm_h_a_hapyhome.html';
LOI[2] = 'hymn~15~ONCE TO EVERY MAN AND NATION~htm_o_n_oncetoev.html';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~24~1~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~24~2~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~24~9~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~24~23~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Jos~24~31~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Joseph~~~~Jos~24~32~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Jos~24~30~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Ephraim~~~~Jos~24~33~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~24~1~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~24~2~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~24~9~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~24~23~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Jos~24~31~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Joseph~~~~Jos~24~32~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~Jos~24~30~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Ephraim~~~~Jos~24~33~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jos~24~1~images/maps/Otest/otest_template.html~2';
LOI[20] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jos~24~25~images/maps/Otest/otest_template.html~2';
LOI[21] = 'image~Bible~Maps~Cities of Refuge (map) key=Shechem~~~~Jos~24~32~images/maps/Otest/otest_template.html~2';
LOI[22] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~24~1~images/maps/Otest/otest_template.html~3c';
LOI[23] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~24~2~images/maps/Otest/otest_template.html~3c';
LOI[24] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~24~9~images/maps/Otest/otest_template.html~3c';
LOI[25] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~24~23~images/maps/Otest/otest_template.html~3c';
LOI[26] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~24~31~images/maps/Otest/otest_template.html~3c';
LOI[27] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~24~32~images/maps/Otest/otest_template.html~3c';
LOI[28] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Jos~24~8~images/maps/Otest/otest_template.html~3c';
LOI[29] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Jos~24~11~images/maps/Otest/otest_template.html~3c';
LOI[30] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~24~1~images/maps/Otest/otest_template.html~4';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~24~2~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Moab~~~~Jos~24~9~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~24~23~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~24~31~images/maps/Otest/otest_template.html~4';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~24~32~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~Jos~24~11~images/maps/Otest/otest_template.html~4';
LOI[37] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jos~24~4~images/maps/Otest/otest_template.html~5';
LOI[38] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jos~24~5~images/maps/Otest/otest_template.html~5';
LOI[39] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jos~24~6~images/maps/Otest/otest_template.html~5';
LOI[40] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jos~24~7~images/maps/Otest/otest_template.html~5';
LOI[41] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jos~24~14~images/maps/Otest/otest_template.html~5';
LOI[42] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jos~24~17~images/maps/Otest/otest_template.html~5';
LOI[43] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Jos~24~32~images/maps/Otest/otest_template.html~5';
LOI[44] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~24~1~images/maps/Christ/christ_template.html~1';
LOI[45] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~24~2~images/maps/Christ/christ_template.html~1';
LOI[46] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~24~9~images/maps/Christ/christ_template.html~1';
LOI[47] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~24~23~images/maps/Christ/christ_template.html~1';
LOI[48] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~24~31~images/maps/Christ/christ_template.html~1';
LOI[49] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~24~32~images/maps/Christ/christ_template.html~1';
LOI[50] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Jos~24~2~images/places/Israel/israel_template.html~8';
LOI[51] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Jos~24~3~images/places/Israel/israel_template.html~8';
LOI[52] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Jos~24~11~images/places/Israel/israel_template.html~9';
LOI[53] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Jos~24~2~images/bible_images/Moses/moses_template.html~3';
LOI[54] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Jos~24~3~images/bible_images/Moses/moses_template.html~3';
LOI[55] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Jos~24~2~images/bible_images/Moses/moses_template.html~3i';
LOI[56] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Jos~24~3~images/bible_images/Moses/moses_template.html~3i';
LOI[57] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac,Abraham~~~~Jos~24~3~images/bible_images/Moses/moses_template.html~3a';
LOI[58] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac~~~~Jos~24~4~images/bible_images/Moses/moses_template.html~3a';
LOI[59] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Jos~24~2~images/bible_images/Moses/moses_template.html~3a';
LOI[60] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Jos~24~3~images/bible_images/Moses/moses_template.html~4';
LOI[61] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Jos~24~4~images/bible_images/Moses/moses_template.html~4';
LOI[62] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Jos~24~32~images/bible_images/Moses/moses_template.html~5';
LOI[63] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jos~24~5~images/bible_images/Moses/moses_template.html~6';
LOI[64] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jos~24~5~images/bible_images/Moses/moses_template.html~7';
LOI[65] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jos~24~5~images/bible_images/Moses/moses_template.html~9';
LOI[66] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jos~24~5~images/bible_images/Moses/moses_template.html~10';
LOI[67] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jos~24~5~images/bible_images/Moses/moses_template.html~11';
