var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~2~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~3~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~4~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~5~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~6~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~7~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~8~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~9~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~10~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~11~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~12~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~13~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~14~images/maps/Otest/otest_template.html~1b';
LOI[14] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~15~images/maps/Otest/otest_template.html~1b';
LOI[15] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~16~images/maps/Otest/otest_template.html~1b';
LOI[16] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~17~images/maps/Otest/otest_template.html~1b';
LOI[17] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~18~images/maps/Otest/otest_template.html~1b';
LOI[18] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~19~images/maps/Otest/otest_template.html~1b';
LOI[19] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~20~images/maps/Otest/otest_template.html~1b';
LOI[20] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~21~images/maps/Otest/otest_template.html~1b';
LOI[21] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~22~images/maps/Otest/otest_template.html~1b';
LOI[22] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~23~images/maps/Otest/otest_template.html~1b';
LOI[23] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~24~images/maps/Otest/otest_template.html~1b';
LOI[24] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~25~images/maps/Otest/otest_template.html~1b';
LOI[25] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~26~images/maps/Otest/otest_template.html~1b';
LOI[26] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~27~images/maps/Otest/otest_template.html~1b';
LOI[27] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Jos~18~28~images/maps/Otest/otest_template.html~1b';
LOI[28] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~1~images/maps/Otest/otest_template.html~1c';
LOI[29] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~2~images/maps/Otest/otest_template.html~1c';
LOI[30] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~3~images/maps/Otest/otest_template.html~1c';
LOI[31] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~4~images/maps/Otest/otest_template.html~1c';
LOI[32] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~5~images/maps/Otest/otest_template.html~1c';
LOI[33] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~6~images/maps/Otest/otest_template.html~1c';
LOI[34] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~7~images/maps/Otest/otest_template.html~1c';
LOI[35] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~8~images/maps/Otest/otest_template.html~1c';
LOI[36] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~9~images/maps/Otest/otest_template.html~1c';
LOI[37] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~10~images/maps/Otest/otest_template.html~1c';
LOI[38] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~11~images/maps/Otest/otest_template.html~1c';
LOI[39] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~12~images/maps/Otest/otest_template.html~1c';
LOI[40] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~13~images/maps/Otest/otest_template.html~1c';
LOI[41] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~14~images/maps/Otest/otest_template.html~1c';
LOI[42] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~15~images/maps/Otest/otest_template.html~1c';
LOI[43] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~16~images/maps/Otest/otest_template.html~1c';
LOI[44] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~17~images/maps/Otest/otest_template.html~1c';
LOI[45] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~18~images/maps/Otest/otest_template.html~1c';
LOI[46] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~19~images/maps/Otest/otest_template.html~1c';
LOI[47] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~20~images/maps/Otest/otest_template.html~1c';
LOI[48] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~21~images/maps/Otest/otest_template.html~1c';
LOI[49] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~22~images/maps/Otest/otest_template.html~1c';
LOI[50] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~23~images/maps/Otest/otest_template.html~1c';
LOI[51] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~24~images/maps/Otest/otest_template.html~1c';
LOI[52] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~25~images/maps/Otest/otest_template.html~1c';
LOI[53] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~26~images/maps/Otest/otest_template.html~1c';
LOI[54] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~27~images/maps/Otest/otest_template.html~1c';
LOI[55] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Jos~18~28~images/maps/Otest/otest_template.html~1c';
LOI[56] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Jos~18~28~images/maps/Otest/otest_template.html~3a';
LOI[57] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Hinnom~~~~Jos~18~16~images/maps/Otest/otest_template.html~3a';
LOI[58] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Jos~18~28~images/maps/Otest/otest_template.html~3b';
LOI[59] = 'image~Bible~Maps~Modern Jerusalem (map) key=Hinnom~~~~Jos~18~16~images/maps/Otest/otest_template.html~3b';
LOI[60] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~18~1~images/maps/Otest/otest_template.html~3c';
LOI[61] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~18~2~images/maps/Otest/otest_template.html~3c';
LOI[62] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~18~3~images/maps/Otest/otest_template.html~3c';
LOI[63] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Jos~18~10~images/maps/Otest/otest_template.html~3c';
LOI[64] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Jos~18~7~images/maps/Otest/otest_template.html~3c';
LOI[65] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Jos~18~12~images/maps/Otest/otest_template.html~3c';
LOI[66] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Jos~18~19~images/maps/Otest/otest_template.html~3c';
LOI[67] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~Jos~18~20~images/maps/Otest/otest_template.html~3c';
LOI[68] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~18~1~images/maps/Otest/otest_template.html~4';
LOI[69] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~18~2~images/maps/Otest/otest_template.html~4';
LOI[70] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~18~3~images/maps/Otest/otest_template.html~4';
LOI[71] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Jos~18~10~images/maps/Otest/otest_template.html~4';
LOI[72] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Jos~18~28~images/maps/Otest/otest_template.html~4';
LOI[73] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~Jos~18~12~images/maps/Otest/otest_template.html~4';
LOI[74] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~Jos~18~21~images/maps/Otest/otest_template.html~4';
LOI[75] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~18~1~images/maps/Christ/christ_template.html~1';
LOI[76] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~18~2~images/maps/Christ/christ_template.html~1';
LOI[77] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~18~3~images/maps/Christ/christ_template.html~1';
LOI[78] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Jos~18~10~images/maps/Christ/christ_template.html~1';
LOI[79] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Jos~18~12~images/places/Israel/israel_template.html~9';
LOI[80] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Jos~18~21~images/places/Israel/israel_template.html~9';
LOI[81] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Jos~18~28~images/places/Israel/israel_template.html~11';
LOI[82] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Jos~18~28~images/places/Israel/israel_template.html~12';
LOI[83] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Jos~18~28~images/places/Israel/israel_template.html~13';
LOI[84] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Jos~18~28~images/places/Israel/israel_template.html~14';
LOI[85] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Jos~18~28~images/places/Israel/israel_template.html~17';
LOI[86] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Jos~18~11~images/bible_images/Moses/moses_template.html~3i';
LOI[87] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Jos~18~5~images/bible_images/Moses/moses_template.html~5';
LOI[88] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Jos~18~11~images/bible_images/Moses/moses_template.html~5';
LOI[89] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Jos~18~7~images/bible_images/Moses/moses_template.html~6';
LOI[90] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Jos~18~7~images/bible_images/Moses/moses_template.html~7';
LOI[91] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Jos~18~7~images/bible_images/Moses/moses_template.html~9';
LOI[92] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Jos~18~7~images/bible_images/Moses/moses_template.html~10';
LOI[93] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Jos~18~7~images/bible_images/Moses/moses_template.html~11';
LOI[94] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Jos~18~1~images/bible_images/Temple/temple_template.html~2';
LOI[95] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Jos~18~1~images/bible_images/Temple/temple_template.html~3';
