var LOI = [];
LOI[0] = 'hymn~3~THE HOPE OF THE COMING OF THE LORD~htm_h_o_hopecome.html';
LOI[1] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~1Th~1~1~images/maps/Journeys/journeys_template.html~1';
LOI[2] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul,Timotheus~~~~1Th~1~1~images/maps/Journeys/journeys_template.html~2';
LOI[3] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Achaia~~~~1Th~1~7~images/maps/Journeys/journeys_template.html~2';
LOI[4] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Achaia~~~~1Th~1~8~images/maps/Journeys/journeys_template.html~2';
LOI[5] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul~~~~1Th~1~1~images/maps/Journeys/journeys_template.html~3';
LOI[6] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Macedonia,Achaia~~~~1Th~1~7~images/maps/Journeys/journeys_template.html~3';
LOI[7] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Macedonia,Achaia~~~~1Th~1~8~images/maps/Journeys/journeys_template.html~3';
LOI[8] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~1Th~1~1~images/bible_images/Acts/acts_template.html~2';
