var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Sa~27~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Sa~27~12~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~1Sa~27~6~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~1Sa~27~10~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Saul~~~~1Sa~27~1~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Sa~27~12~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~1Sa~27~6~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~1Sa~27~10~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Sa~27~4~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Sa~27~1~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Sa~27~12~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Sa~27~1~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Sa~27~12~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt,Shur~~~~1Sa~27~8~images/maps/Otest/otest_template.html~5';
LOI[14] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Sa~27~1~images/maps/Christ/christ_template.html~1';
LOI[15] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Sa~27~12~images/maps/Christ/christ_template.html~1';
LOI[16] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~1Sa~27~1~images/bible_images/Samson/samson_template.html~6';
LOI[17] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~1Sa~27~7~images/bible_images/Samson/samson_template.html~6';
LOI[18] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~1Sa~27~11~images/bible_images/Samson/samson_template.html~6';
LOI[19] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~1Sa~27~1~images/bible_images/Kings/kings_template.html~1';
LOI[20] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~1Sa~27~4~images/bible_images/Kings/kings_template.html~1';
LOI[21] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~27~2~images/bible_images/Kings/kings_template.html~1';
LOI[22] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~27~3~images/bible_images/Kings/kings_template.html~1';
LOI[23] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~27~5~images/bible_images/Kings/kings_template.html~1';
LOI[24] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~27~7~images/bible_images/Kings/kings_template.html~1';
LOI[25] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~27~8~images/bible_images/Kings/kings_template.html~1';
LOI[26] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~27~9~images/bible_images/Kings/kings_template.html~1';
LOI[27] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~27~10~images/bible_images/Kings/kings_template.html~1';
LOI[28] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~27~11~images/bible_images/Kings/kings_template.html~1';
LOI[29] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~27~12~images/bible_images/Kings/kings_template.html~1';
LOI[30] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~27~1~images/bible_images/Kings/kings_template.html~2';
LOI[31] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~27~2~images/bible_images/Kings/kings_template.html~2';
LOI[32] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~27~3~images/bible_images/Kings/kings_template.html~2';
LOI[33] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~27~4~images/bible_images/Kings/kings_template.html~2';
LOI[34] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~27~5~images/bible_images/Kings/kings_template.html~2';
LOI[35] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~27~7~images/bible_images/Kings/kings_template.html~2';
LOI[36] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~27~8~images/bible_images/Kings/kings_template.html~2';
LOI[37] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~27~9~images/bible_images/Kings/kings_template.html~2';
LOI[38] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~27~10~images/bible_images/Kings/kings_template.html~2';
LOI[39] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~27~11~images/bible_images/Kings/kings_template.html~2';
LOI[40] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~27~12~images/bible_images/Kings/kings_template.html~2';
LOI[41] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~27~1~images/bible_images/Acts/acts_template.html~1';
LOI[42] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~27~4~images/bible_images/Acts/acts_template.html~1';
LOI[43] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~27~1~images/bible_images/Acts/acts_template.html~2';
LOI[44] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~27~4~images/bible_images/Acts/acts_template.html~2';
