var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Sa~26~2~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Sa~26~15~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~1Sa~26~20~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Saul~~~~1Sa~26~2~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Sa~26~15~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~1Sa~26~20~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Sa~26~1~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Sa~26~3~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Sa~26~4~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Sa~26~5~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Sa~26~6~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Sa~26~7~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Sa~26~17~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Sa~26~21~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Sa~26~25~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Sa~26~2~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Sa~26~15~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~1Sa~26~20~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Sa~26~2~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Sa~26~15~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~1Sa~26~20~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Sa~26~2~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Sa~26~15~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~1Sa~26~20~images/maps/Christ/christ_template.html~1';
LOI[24] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart) key=tribulation~~~~1Sa~26~24~images/charts/Bible/bible_template.html~1';
LOI[25] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~1Sa~26~1~images/bible_images/Kings/kings_template.html~1';
LOI[26] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~1Sa~26~2~images/bible_images/Kings/kings_template.html~1';
LOI[27] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~1Sa~26~3~images/bible_images/Kings/kings_template.html~1';
LOI[28] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~1Sa~26~4~images/bible_images/Kings/kings_template.html~1';
LOI[29] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~1Sa~26~5~images/bible_images/Kings/kings_template.html~1';
LOI[30] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~1Sa~26~6~images/bible_images/Kings/kings_template.html~1';
LOI[31] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~1Sa~26~7~images/bible_images/Kings/kings_template.html~1';
LOI[32] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~1Sa~26~17~images/bible_images/Kings/kings_template.html~1';
LOI[33] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~1Sa~26~21~images/bible_images/Kings/kings_template.html~1';
LOI[34] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~1Sa~26~25~images/bible_images/Kings/kings_template.html~1';
LOI[35] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~26~8~images/bible_images/Kings/kings_template.html~1';
LOI[36] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~26~9~images/bible_images/Kings/kings_template.html~1';
LOI[37] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~26~10~images/bible_images/Kings/kings_template.html~1';
LOI[38] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~26~12~images/bible_images/Kings/kings_template.html~1';
LOI[39] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~26~13~images/bible_images/Kings/kings_template.html~1';
LOI[40] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~26~14~images/bible_images/Kings/kings_template.html~1';
LOI[41] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~26~15~images/bible_images/Kings/kings_template.html~1';
LOI[42] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~26~22~images/bible_images/Kings/kings_template.html~1';
LOI[43] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~1~images/bible_images/Kings/kings_template.html~2';
LOI[44] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~2~images/bible_images/Kings/kings_template.html~2';
LOI[45] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~3~images/bible_images/Kings/kings_template.html~2';
LOI[46] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~4~images/bible_images/Kings/kings_template.html~2';
LOI[47] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~5~images/bible_images/Kings/kings_template.html~2';
LOI[48] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~6~images/bible_images/Kings/kings_template.html~2';
LOI[49] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~7~images/bible_images/Kings/kings_template.html~2';
LOI[50] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~8~images/bible_images/Kings/kings_template.html~2';
LOI[51] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~9~images/bible_images/Kings/kings_template.html~2';
LOI[52] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~10~images/bible_images/Kings/kings_template.html~2';
LOI[53] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~12~images/bible_images/Kings/kings_template.html~2';
LOI[54] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~13~images/bible_images/Kings/kings_template.html~2';
LOI[55] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~14~images/bible_images/Kings/kings_template.html~2';
LOI[56] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~15~images/bible_images/Kings/kings_template.html~2';
LOI[57] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~17~images/bible_images/Kings/kings_template.html~2';
LOI[58] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~21~images/bible_images/Kings/kings_template.html~2';
LOI[59] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~22~images/bible_images/Kings/kings_template.html~2';
LOI[60] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~26~25~images/bible_images/Kings/kings_template.html~2';
LOI[61] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~26~1~images/bible_images/Acts/acts_template.html~1';
LOI[62] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~26~2~images/bible_images/Acts/acts_template.html~1';
LOI[63] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~26~3~images/bible_images/Acts/acts_template.html~1';
LOI[64] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~26~4~images/bible_images/Acts/acts_template.html~1';
LOI[65] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~26~5~images/bible_images/Acts/acts_template.html~1';
LOI[66] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~26~6~images/bible_images/Acts/acts_template.html~1';
LOI[67] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~26~7~images/bible_images/Acts/acts_template.html~1';
LOI[68] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~26~17~images/bible_images/Acts/acts_template.html~1';
LOI[69] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~26~21~images/bible_images/Acts/acts_template.html~1';
LOI[70] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~26~25~images/bible_images/Acts/acts_template.html~1';
LOI[71] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~26~1~images/bible_images/Acts/acts_template.html~2';
LOI[72] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~26~2~images/bible_images/Acts/acts_template.html~2';
LOI[73] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~26~3~images/bible_images/Acts/acts_template.html~2';
LOI[74] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~26~4~images/bible_images/Acts/acts_template.html~2';
LOI[75] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~26~5~images/bible_images/Acts/acts_template.html~2';
LOI[76] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~26~6~images/bible_images/Acts/acts_template.html~2';
LOI[77] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~26~7~images/bible_images/Acts/acts_template.html~2';
LOI[78] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~26~17~images/bible_images/Acts/acts_template.html~2';
LOI[79] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~26~21~images/bible_images/Acts/acts_template.html~2';
LOI[80] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~26~25~images/bible_images/Acts/acts_template.html~2';
