var LOI = [];
LOI[0] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Sa~21~7~images/maps/Otest/otest_template.html~1c';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Sa~21~10~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~1Sa~21~11~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Images~Saul and David (engraving) key=Saul~~~~1Sa~21~7~images/bible_images/Kings/kings_template.html~1';
LOI[4] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~1Sa~21~10~images/bible_images/Kings/kings_template.html~1';
LOI[5] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~1Sa~21~11~images/bible_images/Kings/kings_template.html~1';
LOI[6] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~21~1~images/bible_images/Kings/kings_template.html~1';
LOI[7] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~21~2~images/bible_images/Kings/kings_template.html~1';
LOI[8] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~21~4~images/bible_images/Kings/kings_template.html~1';
LOI[9] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~21~5~images/bible_images/Kings/kings_template.html~1';
LOI[10] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~21~8~images/bible_images/Kings/kings_template.html~1';
LOI[11] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~21~9~images/bible_images/Kings/kings_template.html~1';
LOI[12] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~1Sa~21~12~images/bible_images/Kings/kings_template.html~1';
LOI[13] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~21~1~images/bible_images/Kings/kings_template.html~2';
LOI[14] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~21~2~images/bible_images/Kings/kings_template.html~2';
LOI[15] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~21~4~images/bible_images/Kings/kings_template.html~2';
LOI[16] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~21~5~images/bible_images/Kings/kings_template.html~2';
LOI[17] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~21~8~images/bible_images/Kings/kings_template.html~2';
LOI[18] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~21~9~images/bible_images/Kings/kings_template.html~2';
LOI[19] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~21~10~images/bible_images/Kings/kings_template.html~2';
LOI[20] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~21~11~images/bible_images/Kings/kings_template.html~2';
LOI[21] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~1Sa~21~12~images/bible_images/Kings/kings_template.html~2';
LOI[22] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~21~7~images/bible_images/Acts/acts_template.html~1';
LOI[23] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~21~10~images/bible_images/Acts/acts_template.html~1';
LOI[24] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~1Sa~21~11~images/bible_images/Acts/acts_template.html~1';
LOI[25] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~21~7~images/bible_images/Acts/acts_template.html~2';
LOI[26] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~21~10~images/bible_images/Acts/acts_template.html~2';
LOI[27] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~1Sa~21~11~images/bible_images/Acts/acts_template.html~2';
