var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~11~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Sa~11~11~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Sa~11~1~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Sa~11~11~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Sa~11~1~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Sa~11~12~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Sa~11~1~images/maps/Otest/otest_template.html~3b';
LOI[7] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Sa~11~12~images/maps/Otest/otest_template.html~3b';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~11~1~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~11~11~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jerusalem~~~~2Sa~11~1~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~11~11~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Sa~11~12~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~11~1~images/maps/Christ/christ_template.html~1';
LOI[14] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~11~11~images/maps/Christ/christ_template.html~1';
LOI[15] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Sa~11~1~images/places/Israel/israel_template.html~11';
LOI[16] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Sa~11~12~images/places/Israel/israel_template.html~11';
LOI[17] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Sa~11~1~images/places/Israel/israel_template.html~12';
LOI[18] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Sa~11~12~images/places/Israel/israel_template.html~12';
LOI[19] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Sa~11~1~images/places/Israel/israel_template.html~13';
LOI[20] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Sa~11~12~images/places/Israel/israel_template.html~13';
LOI[21] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Sa~11~1~images/places/Israel/israel_template.html~14';
LOI[22] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Sa~11~12~images/places/Israel/israel_template.html~14';
LOI[23] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Sa~11~1~images/places/Israel/israel_template.html~17';
LOI[24] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Sa~11~12~images/places/Israel/israel_template.html~17';
LOI[25] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~1~images/bible_images/Kings/kings_template.html~1';
LOI[26] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~2~images/bible_images/Kings/kings_template.html~1';
LOI[27] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~3~images/bible_images/Kings/kings_template.html~1';
LOI[28] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~4~images/bible_images/Kings/kings_template.html~1';
LOI[29] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~5~images/bible_images/Kings/kings_template.html~1';
LOI[30] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~6~images/bible_images/Kings/kings_template.html~1';
LOI[31] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~7~images/bible_images/Kings/kings_template.html~1';
LOI[32] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~8~images/bible_images/Kings/kings_template.html~1';
LOI[33] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~10~images/bible_images/Kings/kings_template.html~1';
LOI[34] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~11~images/bible_images/Kings/kings_template.html~1';
LOI[35] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~12~images/bible_images/Kings/kings_template.html~1';
LOI[36] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~13~images/bible_images/Kings/kings_template.html~1';
LOI[37] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~14~images/bible_images/Kings/kings_template.html~1';
LOI[38] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~17~images/bible_images/Kings/kings_template.html~1';
LOI[39] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~18~images/bible_images/Kings/kings_template.html~1';
LOI[40] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~22~images/bible_images/Kings/kings_template.html~1';
LOI[41] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~23~images/bible_images/Kings/kings_template.html~1';
LOI[42] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~25~images/bible_images/Kings/kings_template.html~1';
LOI[43] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~11~27~images/bible_images/Kings/kings_template.html~1';
LOI[44] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~1~images/bible_images/Kings/kings_template.html~2';
LOI[45] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~2~images/bible_images/Kings/kings_template.html~2';
LOI[46] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~3~images/bible_images/Kings/kings_template.html~2';
LOI[47] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~4~images/bible_images/Kings/kings_template.html~2';
LOI[48] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~5~images/bible_images/Kings/kings_template.html~2';
LOI[49] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~6~images/bible_images/Kings/kings_template.html~2';
LOI[50] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~7~images/bible_images/Kings/kings_template.html~2';
LOI[51] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~8~images/bible_images/Kings/kings_template.html~2';
LOI[52] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~10~images/bible_images/Kings/kings_template.html~2';
LOI[53] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~11~images/bible_images/Kings/kings_template.html~2';
LOI[54] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~12~images/bible_images/Kings/kings_template.html~2';
LOI[55] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~13~images/bible_images/Kings/kings_template.html~2';
LOI[56] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~14~images/bible_images/Kings/kings_template.html~2';
LOI[57] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~17~images/bible_images/Kings/kings_template.html~2';
LOI[58] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~18~images/bible_images/Kings/kings_template.html~2';
LOI[59] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~22~images/bible_images/Kings/kings_template.html~2';
LOI[60] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~23~images/bible_images/Kings/kings_template.html~2';
LOI[61] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~25~images/bible_images/Kings/kings_template.html~2';
LOI[62] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~11~27~images/bible_images/Kings/kings_template.html~2';
LOI[63] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~2Sa~11~11~images/bible_images/Temple/temple_template.html~4';
