var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~2Sa~4~2~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~2Sa~4~2~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~2Sa~4~4~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~2Sa~4~8~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~2Sa~4~10~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Cities of Refuge (map) key=Hebron~~~~2Sa~4~1~images/maps/Otest/otest_template.html~2';
LOI[6] = 'image~Bible~Maps~Cities of Refuge (map) key=Hebron~~~~2Sa~4~8~images/maps/Otest/otest_template.html~2';
LOI[7] = 'image~Bible~Maps~Cities of Refuge (map) key=Hebron~~~~2Sa~4~12~images/maps/Otest/otest_template.html~2';
LOI[8] = 'image~Bible~Places~Hebron (engraving) key=Hebron~~~~2Sa~4~1~images/places/Israel/israel_template.html~16';
LOI[9] = 'image~Bible~Places~Hebron (engraving) key=Hebron~~~~2Sa~4~8~images/places/Israel/israel_template.html~16';
LOI[10] = 'image~Bible~Places~Hebron (engraving) key=Hebron~~~~2Sa~4~12~images/places/Israel/israel_template.html~16';
LOI[11] = 'image~Bible~Images~Saul and David (engraving) key=Saul~~~~2Sa~4~4~images/bible_images/Kings/kings_template.html~1';
LOI[12] = 'image~Bible~Images~Saul and David (engraving) key=Saul,David~~~~2Sa~4~8~images/bible_images/Kings/kings_template.html~1';
LOI[13] = 'image~Bible~Images~Saul and David (engraving) key=Saul~~~~2Sa~4~10~images/bible_images/Kings/kings_template.html~1';
LOI[14] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~4~9~images/bible_images/Kings/kings_template.html~1';
LOI[15] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~4~12~images/bible_images/Kings/kings_template.html~1';
LOI[16] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~4~8~images/bible_images/Kings/kings_template.html~2';
LOI[17] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~4~9~images/bible_images/Kings/kings_template.html~2';
LOI[18] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~4~12~images/bible_images/Kings/kings_template.html~2';
LOI[19] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~2Sa~4~4~images/bible_images/Acts/acts_template.html~1';
LOI[20] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~2Sa~4~8~images/bible_images/Acts/acts_template.html~1';
LOI[21] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~2Sa~4~10~images/bible_images/Acts/acts_template.html~1';
LOI[22] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~2Sa~4~4~images/bible_images/Acts/acts_template.html~2';
LOI[23] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~2Sa~4~8~images/bible_images/Acts/acts_template.html~2';
LOI[24] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~2Sa~4~10~images/bible_images/Acts/acts_template.html~2';
