var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~5~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~5~2~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~5~3~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Sa~5~5~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~5~12~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~5~17~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Sa~5~1~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Saul~~~~2Sa~5~2~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Sa~5~3~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Sa~5~5~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Sa~5~12~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Sa~5~17~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Cities of Refuge (map) key=Hebron~~~~2Sa~5~1~images/maps/Otest/otest_template.html~2';
LOI[13] = 'image~Bible~Maps~Cities of Refuge (map) key=Hebron~~~~2Sa~5~3~images/maps/Otest/otest_template.html~2';
LOI[14] = 'image~Bible~Maps~Cities of Refuge (map) key=Hebron~~~~2Sa~5~5~images/maps/Otest/otest_template.html~2';
LOI[15] = 'image~Bible~Maps~Cities of Refuge (map) key=Hebron~~~~2Sa~5~13~images/maps/Otest/otest_template.html~2';
LOI[16] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Sa~5~5~images/maps/Otest/otest_template.html~3a';
LOI[17] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Sa~5~6~images/maps/Otest/otest_template.html~3a';
LOI[18] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Sa~5~13~images/maps/Otest/otest_template.html~3a';
LOI[19] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Sa~5~14~images/maps/Otest/otest_template.html~3a';
LOI[20] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~2Sa~5~7~images/maps/Otest/otest_template.html~3a';
LOI[21] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Sa~5~5~images/maps/Otest/otest_template.html~3b';
LOI[22] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Sa~5~6~images/maps/Otest/otest_template.html~3b';
LOI[23] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Sa~5~13~images/maps/Otest/otest_template.html~3b';
LOI[24] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Sa~5~14~images/maps/Otest/otest_template.html~3b';
LOI[25] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~2Sa~5~7~images/maps/Otest/otest_template.html~3b';
LOI[26] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~5~1~images/maps/Otest/otest_template.html~3c';
LOI[27] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~5~2~images/maps/Otest/otest_template.html~3c';
LOI[28] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~5~3~images/maps/Otest/otest_template.html~3c';
LOI[29] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~5~5~images/maps/Otest/otest_template.html~3c';
LOI[30] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~5~12~images/maps/Otest/otest_template.html~3c';
LOI[31] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~5~17~images/maps/Otest/otest_template.html~3c';
LOI[32] = 'image~Bible~Maps~Middle Palestine (map) key=Hiram,Tyre~~~~2Sa~5~11~images/maps/Otest/otest_template.html~3c';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~5~1~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~5~2~images/maps/Otest/otest_template.html~4';
LOI[35] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~5~3~images/maps/Otest/otest_template.html~4';
LOI[36] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jerusalem~~~~2Sa~5~5~images/maps/Otest/otest_template.html~4';
LOI[37] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~5~12~images/maps/Otest/otest_template.html~4';
LOI[38] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~5~17~images/maps/Otest/otest_template.html~4';
LOI[39] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Sa~5~6~images/maps/Otest/otest_template.html~4';
LOI[40] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Sa~5~13~images/maps/Otest/otest_template.html~4';
LOI[41] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Sa~5~14~images/maps/Otest/otest_template.html~4';
LOI[42] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~5~1~images/maps/Christ/christ_template.html~1';
LOI[43] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~5~2~images/maps/Christ/christ_template.html~1';
LOI[44] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~5~3~images/maps/Christ/christ_template.html~1';
LOI[45] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~5~5~images/maps/Christ/christ_template.html~1';
LOI[46] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~5~12~images/maps/Christ/christ_template.html~1';
LOI[47] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~5~17~images/maps/Christ/christ_template.html~1';
LOI[48] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Tyre~~~~2Sa~5~11~images/maps/Journeys/journeys_template.html~3';
LOI[49] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Sa~5~5~images/places/Israel/israel_template.html~11';
LOI[50] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Sa~5~6~images/places/Israel/israel_template.html~11';
LOI[51] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Sa~5~13~images/places/Israel/israel_template.html~11';
LOI[52] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Sa~5~14~images/places/Israel/israel_template.html~11';
LOI[53] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Sa~5~5~images/places/Israel/israel_template.html~12';
LOI[54] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Sa~5~6~images/places/Israel/israel_template.html~12';
LOI[55] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Sa~5~13~images/places/Israel/israel_template.html~12';
LOI[56] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Sa~5~14~images/places/Israel/israel_template.html~12';
LOI[57] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Sa~5~5~images/places/Israel/israel_template.html~13';
LOI[58] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Sa~5~6~images/places/Israel/israel_template.html~13';
LOI[59] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Sa~5~13~images/places/Israel/israel_template.html~13';
LOI[60] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Sa~5~14~images/places/Israel/israel_template.html~13';
LOI[61] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Sa~5~5~images/places/Israel/israel_template.html~14';
LOI[62] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Sa~5~6~images/places/Israel/israel_template.html~14';
LOI[63] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Sa~5~13~images/places/Israel/israel_template.html~14';
LOI[64] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Sa~5~14~images/places/Israel/israel_template.html~14';
LOI[65] = 'image~Bible~Places~Hebron (engraving) key=Hebron~~~~2Sa~5~1~images/places/Israel/israel_template.html~16';
LOI[66] = 'image~Bible~Places~Hebron (engraving) key=Hebron~~~~2Sa~5~3~images/places/Israel/israel_template.html~16';
LOI[67] = 'image~Bible~Places~Hebron (engraving) key=Hebron~~~~2Sa~5~5~images/places/Israel/israel_template.html~16';
LOI[68] = 'image~Bible~Places~Hebron (engraving) key=Hebron~~~~2Sa~5~13~images/places/Israel/israel_template.html~16';
LOI[69] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Sa~5~5~images/places/Israel/israel_template.html~17';
LOI[70] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Sa~5~6~images/places/Israel/israel_template.html~17';
LOI[71] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Sa~5~13~images/places/Israel/israel_template.html~17';
LOI[72] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Sa~5~14~images/places/Israel/israel_template.html~17';
LOI[73] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Sa~5~17~images/bible_images/Samson/samson_template.html~6';
LOI[74] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Sa~5~18~images/bible_images/Samson/samson_template.html~6';
LOI[75] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Sa~5~19~images/bible_images/Samson/samson_template.html~6';
LOI[76] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Sa~5~22~images/bible_images/Samson/samson_template.html~6';
LOI[77] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Sa~5~24~images/bible_images/Samson/samson_template.html~6';
LOI[78] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Sa~5~25~images/bible_images/Samson/samson_template.html~6';
LOI[79] = 'image~Bible~Images~Saul and David (engraving) key=Saul~~~~2Sa~5~2~images/bible_images/Kings/kings_template.html~1';
LOI[80] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~1~images/bible_images/Kings/kings_template.html~1';
LOI[81] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~3~images/bible_images/Kings/kings_template.html~1';
LOI[82] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~4~images/bible_images/Kings/kings_template.html~1';
LOI[83] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~6~images/bible_images/Kings/kings_template.html~1';
LOI[84] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~7~images/bible_images/Kings/kings_template.html~1';
LOI[85] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~8~images/bible_images/Kings/kings_template.html~1';
LOI[86] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~9~images/bible_images/Kings/kings_template.html~1';
LOI[87] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~10~images/bible_images/Kings/kings_template.html~1';
LOI[88] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~11~images/bible_images/Kings/kings_template.html~1';
LOI[89] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~12~images/bible_images/Kings/kings_template.html~1';
LOI[90] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~13~images/bible_images/Kings/kings_template.html~1';
LOI[91] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~17~images/bible_images/Kings/kings_template.html~1';
LOI[92] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~19~images/bible_images/Kings/kings_template.html~1';
LOI[93] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~20~images/bible_images/Kings/kings_template.html~1';
LOI[94] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~21~images/bible_images/Kings/kings_template.html~1';
LOI[95] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~23~images/bible_images/Kings/kings_template.html~1';
LOI[96] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~5~25~images/bible_images/Kings/kings_template.html~1';
LOI[97] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~1~images/bible_images/Kings/kings_template.html~2';
LOI[98] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~3~images/bible_images/Kings/kings_template.html~2';
LOI[99] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~4~images/bible_images/Kings/kings_template.html~2';
LOI[100] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~6~images/bible_images/Kings/kings_template.html~2';
LOI[101] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~7~images/bible_images/Kings/kings_template.html~2';
LOI[102] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~8~images/bible_images/Kings/kings_template.html~2';
LOI[103] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~9~images/bible_images/Kings/kings_template.html~2';
LOI[104] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~10~images/bible_images/Kings/kings_template.html~2';
LOI[105] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~11~images/bible_images/Kings/kings_template.html~2';
LOI[106] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~12~images/bible_images/Kings/kings_template.html~2';
LOI[107] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~13~images/bible_images/Kings/kings_template.html~2';
LOI[108] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~17~images/bible_images/Kings/kings_template.html~2';
LOI[109] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~19~images/bible_images/Kings/kings_template.html~2';
LOI[110] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~20~images/bible_images/Kings/kings_template.html~2';
LOI[111] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~21~images/bible_images/Kings/kings_template.html~2';
LOI[112] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~23~images/bible_images/Kings/kings_template.html~2';
LOI[113] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~5~25~images/bible_images/Kings/kings_template.html~2';
LOI[114] = 'image~Bible~Images~King Solomon (engraving) key=Solomon~~~~2Sa~5~14~images/bible_images/Kings/kings_template.html~3';
LOI[115] = 'image~Bible~Images~Solomon and Queen of Sheba (engraving) key=Solomon~~~~2Sa~5~14~images/bible_images/Kings/kings_template.html~4';
LOI[116] = 'image~Bible~Images~The Song of Songs, which is Solomon\'s... key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~1';
LOI[117] = 'image~Bible~Images~Let him kiss me...(color plate) key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~2';
LOI[118] = 'image~Bible~Images~I am black, but comely...(color plate) key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~3';
LOI[119] = 'image~Bible~Images~O thou whom my soul loveth...(color plate) key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~4';
LOI[120] = 'image~Bible~Images~I have compared thee...(color plate) key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~5';
LOI[121] = 'image~Bible~Images~A bundle of myrhh...(color plate) key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~6';
LOI[122] = 'image~Bible~Images~I am a rose of Sharon...(color plate) key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~7';
LOI[123] = 'image~Bible~Images~As the apple tree among...(color plate) key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~8';
LOI[124] = 'image~Bible~Images~The voice of my beloved!...(color plate) key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~9';
LOI[125] = 'image~Bible~Images~By night on my bed...(color plate) key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~10';
LOI[126] = 'image~Bible~Images~Who is this that cometh up...(color plate) key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~11';
LOI[127] = 'image~Bible~Images~Behold thou art fair, my love...(color plate) key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~12';
LOI[128] = 'image~Bible~Images~Thou are all fair, my love...(color plate) key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~13';
LOI[129] = 'image~Bible~Images~I was asleep, but my heart waked...(color plate) key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~14';
LOI[130] = 'image~Bible~Images~The watchmen that go about...(color plate) key=Solomon~~~~2Sa~5~14~images/bible_images/Song/song_template.html~15';
LOI[131] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~2Sa~5~2~images/bible_images/Acts/acts_template.html~1';
LOI[132] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~2Sa~5~2~images/bible_images/Acts/acts_template.html~2';
