var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Sa~24~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Dan~~~~2Sa~24~2~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~24~4~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~2Sa~24~9~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Dan~~~~2Sa~24~15~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~24~25~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~2Sa~24~7~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Gad~~~~2Sa~24~5~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Gad~~~~2Sa~24~11~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Gad~~~~2Sa~24~13~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Gad~~~~2Sa~24~14~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Gad~~~~2Sa~24~18~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Gad~~~~2Sa~24~19~images/maps/Otest/otest_template.html~1b';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Sa~24~1~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Dan~~~~2Sa~24~2~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Sa~24~4~images/maps/Otest/otest_template.html~1c';
LOI[16] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~2Sa~24~9~images/maps/Otest/otest_template.html~1c';
LOI[17] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Dan~~~~2Sa~24~15~images/maps/Otest/otest_template.html~1c';
LOI[18] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Sa~24~25~images/maps/Otest/otest_template.html~1c';
LOI[19] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~2Sa~24~7~images/maps/Otest/otest_template.html~1c';
LOI[20] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Gad~~~~2Sa~24~5~images/maps/Otest/otest_template.html~1c';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Gad~~~~2Sa~24~11~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Gad~~~~2Sa~24~13~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Gad~~~~2Sa~24~14~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Gad~~~~2Sa~24~18~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Gad~~~~2Sa~24~19~images/maps/Otest/otest_template.html~1c';
LOI[26] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Sa~24~8~images/maps/Otest/otest_template.html~3a';
LOI[27] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Sa~24~16~images/maps/Otest/otest_template.html~3a';
LOI[28] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Sa~24~8~images/maps/Otest/otest_template.html~3b';
LOI[29] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Sa~24~16~images/maps/Otest/otest_template.html~3b';
LOI[30] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~24~1~images/maps/Otest/otest_template.html~3c';
LOI[31] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~24~2~images/maps/Otest/otest_template.html~3c';
LOI[32] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~24~4~images/maps/Otest/otest_template.html~3c';
LOI[33] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~24~9~images/maps/Otest/otest_template.html~3c';
LOI[34] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~24~15~images/maps/Otest/otest_template.html~3c';
LOI[35] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~24~25~images/maps/Otest/otest_template.html~3c';
LOI[36] = 'image~Bible~Maps~Middle Palestine (map) key=Gilead~~~~2Sa~24~6~images/maps/Otest/otest_template.html~3c';
LOI[37] = 'image~Bible~Maps~Middle Palestine (map) key=Tyre~~~~2Sa~24~7~images/maps/Otest/otest_template.html~3c';
LOI[38] = 'image~Bible~Maps~Middle Palestine (map) key=Jordan~~~~2Sa~24~5~images/maps/Otest/otest_template.html~3c';
LOI[39] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~24~1~images/maps/Otest/otest_template.html~4';
LOI[40] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~24~2~images/maps/Otest/otest_template.html~4';
LOI[41] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~24~4~images/maps/Otest/otest_template.html~4';
LOI[42] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~24~9~images/maps/Otest/otest_template.html~4';
LOI[43] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~24~15~images/maps/Otest/otest_template.html~4';
LOI[44] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~24~25~images/maps/Otest/otest_template.html~4';
LOI[45] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Sa~24~8~images/maps/Otest/otest_template.html~4';
LOI[46] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Sa~24~16~images/maps/Otest/otest_template.html~4';
LOI[47] = 'image~Bible~Maps~Southern Palestine (map) key=Gilead~~~~2Sa~24~6~images/maps/Otest/otest_template.html~4';
LOI[48] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~24~1~images/maps/Christ/christ_template.html~1';
LOI[49] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~24~2~images/maps/Christ/christ_template.html~1';
LOI[50] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~24~4~images/maps/Christ/christ_template.html~1';
LOI[51] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~24~9~images/maps/Christ/christ_template.html~1';
LOI[52] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~24~15~images/maps/Christ/christ_template.html~1';
LOI[53] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~24~25~images/maps/Christ/christ_template.html~1';
LOI[54] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Tyre~~~~2Sa~24~7~images/maps/Journeys/journeys_template.html~3';
LOI[55] = 'image~Bible~Places~Beer-Sheeba (engraving) key=Beersheba~~~~2Sa~24~2~images/places/Israel/israel_template.html~7';
LOI[56] = 'image~Bible~Places~Beer-Sheeba (engraving) key=Beersheba~~~~2Sa~24~7~images/places/Israel/israel_template.html~7';
LOI[57] = 'image~Bible~Places~Beer-Sheeba (engraving) key=Beersheba~~~~2Sa~24~15~images/places/Israel/israel_template.html~7';
LOI[58] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Sa~24~8~images/places/Israel/israel_template.html~11';
LOI[59] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Sa~24~16~images/places/Israel/israel_template.html~11';
LOI[60] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Sa~24~8~images/places/Israel/israel_template.html~12';
LOI[61] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Sa~24~16~images/places/Israel/israel_template.html~12';
LOI[62] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Sa~24~8~images/places/Israel/israel_template.html~13';
LOI[63] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Sa~24~16~images/places/Israel/israel_template.html~13';
LOI[64] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Sa~24~8~images/places/Israel/israel_template.html~14';
LOI[65] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Sa~24~16~images/places/Israel/israel_template.html~14';
LOI[66] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Sa~24~8~images/places/Israel/israel_template.html~17';
LOI[67] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Sa~24~16~images/places/Israel/israel_template.html~17';
LOI[68] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~24~1~images/bible_images/Kings/kings_template.html~1';
LOI[69] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~24~10~images/bible_images/Kings/kings_template.html~1';
LOI[70] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~24~11~images/bible_images/Kings/kings_template.html~1';
LOI[71] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~24~12~images/bible_images/Kings/kings_template.html~1';
LOI[72] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~24~13~images/bible_images/Kings/kings_template.html~1';
LOI[73] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~24~14~images/bible_images/Kings/kings_template.html~1';
LOI[74] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~24~17~images/bible_images/Kings/kings_template.html~1';
LOI[75] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~24~18~images/bible_images/Kings/kings_template.html~1';
LOI[76] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~24~19~images/bible_images/Kings/kings_template.html~1';
LOI[77] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~24~21~images/bible_images/Kings/kings_template.html~1';
LOI[78] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~24~22~images/bible_images/Kings/kings_template.html~1';
LOI[79] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~24~24~images/bible_images/Kings/kings_template.html~1';
LOI[80] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~24~25~images/bible_images/Kings/kings_template.html~1';
LOI[81] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~24~1~images/bible_images/Kings/kings_template.html~2';
LOI[82] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~24~10~images/bible_images/Kings/kings_template.html~2';
LOI[83] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~24~11~images/bible_images/Kings/kings_template.html~2';
LOI[84] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~24~12~images/bible_images/Kings/kings_template.html~2';
LOI[85] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~24~13~images/bible_images/Kings/kings_template.html~2';
LOI[86] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~24~14~images/bible_images/Kings/kings_template.html~2';
LOI[87] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~24~17~images/bible_images/Kings/kings_template.html~2';
LOI[88] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~24~18~images/bible_images/Kings/kings_template.html~2';
LOI[89] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~24~19~images/bible_images/Kings/kings_template.html~2';
LOI[90] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~24~21~images/bible_images/Kings/kings_template.html~2';
LOI[91] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~24~22~images/bible_images/Kings/kings_template.html~2';
LOI[92] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~24~24~images/bible_images/Kings/kings_template.html~2';
LOI[93] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~24~25~images/bible_images/Kings/kings_template.html~2';
