var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~15~2~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~15~6~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~15~10~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~15~13~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Sa~15~2~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Sa~15~6~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Sa~15~10~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Sa~15~13~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Cities of Refuge (map) key=Hebron~~~~2Sa~15~7~images/maps/Otest/otest_template.html~2';
LOI[9] = 'image~Bible~Maps~Cities of Refuge (map) key=Hebron~~~~2Sa~15~9~images/maps/Otest/otest_template.html~2';
LOI[10] = 'image~Bible~Maps~Cities of Refuge (map) key=Hebron~~~~2Sa~15~10~images/maps/Otest/otest_template.html~2';
LOI[11] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Sa~15~8~images/maps/Otest/otest_template.html~3a';
LOI[12] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Sa~15~11~images/maps/Otest/otest_template.html~3a';
LOI[13] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Sa~15~14~images/maps/Otest/otest_template.html~3a';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Sa~15~29~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~2Sa~15~37~images/maps/Otest/otest_template.html~3a';
LOI[16] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Sa~15~8~images/maps/Otest/otest_template.html~3b';
LOI[17] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Sa~15~11~images/maps/Otest/otest_template.html~3b';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Sa~15~14~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Sa~15~29~images/maps/Otest/otest_template.html~3b';
LOI[20] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~2Sa~15~37~images/maps/Otest/otest_template.html~3b';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~15~2~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~15~6~images/maps/Otest/otest_template.html~3c';
LOI[23] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~15~10~images/maps/Otest/otest_template.html~3c';
LOI[24] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~15~13~images/maps/Otest/otest_template.html~3c';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~15~2~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~15~6~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~15~10~images/maps/Otest/otest_template.html~4';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~15~13~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Sa~15~8~images/maps/Otest/otest_template.html~4';
LOI[30] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Sa~15~11~images/maps/Otest/otest_template.html~4';
LOI[31] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Sa~15~14~images/maps/Otest/otest_template.html~4';
LOI[32] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Sa~15~29~images/maps/Otest/otest_template.html~4';
LOI[33] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~2Sa~15~37~images/maps/Otest/otest_template.html~4';
LOI[34] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~15~2~images/maps/Christ/christ_template.html~1';
LOI[35] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~15~6~images/maps/Christ/christ_template.html~1';
LOI[36] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~15~10~images/maps/Christ/christ_template.html~1';
LOI[37] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~15~13~images/maps/Christ/christ_template.html~1';
LOI[38] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~2Sa~15~8~images/maps/Journeys/journeys_template.html~2';
LOI[39] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Sa~15~8~images/places/Israel/israel_template.html~11';
LOI[40] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Sa~15~11~images/places/Israel/israel_template.html~11';
LOI[41] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Sa~15~14~images/places/Israel/israel_template.html~11';
LOI[42] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Sa~15~29~images/places/Israel/israel_template.html~11';
LOI[43] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~2Sa~15~37~images/places/Israel/israel_template.html~11';
LOI[44] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Sa~15~8~images/places/Israel/israel_template.html~12';
LOI[45] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Sa~15~11~images/places/Israel/israel_template.html~12';
LOI[46] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Sa~15~14~images/places/Israel/israel_template.html~12';
LOI[47] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Sa~15~29~images/places/Israel/israel_template.html~12';
LOI[48] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~2Sa~15~37~images/places/Israel/israel_template.html~12';
LOI[49] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Sa~15~8~images/places/Israel/israel_template.html~13';
LOI[50] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Sa~15~11~images/places/Israel/israel_template.html~13';
LOI[51] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Sa~15~14~images/places/Israel/israel_template.html~13';
LOI[52] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Sa~15~29~images/places/Israel/israel_template.html~13';
LOI[53] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~2Sa~15~37~images/places/Israel/israel_template.html~13';
LOI[54] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Sa~15~8~images/places/Israel/israel_template.html~14';
LOI[55] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Sa~15~11~images/places/Israel/israel_template.html~14';
LOI[56] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Sa~15~14~images/places/Israel/israel_template.html~14';
LOI[57] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Sa~15~29~images/places/Israel/israel_template.html~14';
LOI[58] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~2Sa~15~37~images/places/Israel/israel_template.html~14';
LOI[59] = 'image~Bible~Places~Hebron (engraving) key=Hebron~~~~2Sa~15~7~images/places/Israel/israel_template.html~16';
LOI[60] = 'image~Bible~Places~Hebron (engraving) key=Hebron~~~~2Sa~15~9~images/places/Israel/israel_template.html~16';
LOI[61] = 'image~Bible~Places~Hebron (engraving) key=Hebron~~~~2Sa~15~10~images/places/Israel/israel_template.html~16';
LOI[62] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Sa~15~8~images/places/Israel/israel_template.html~17';
LOI[63] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Sa~15~11~images/places/Israel/israel_template.html~17';
LOI[64] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Sa~15~14~images/places/Israel/israel_template.html~17';
LOI[65] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Sa~15~29~images/places/Israel/israel_template.html~17';
LOI[66] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~2Sa~15~37~images/places/Israel/israel_template.html~17';
LOI[67] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~15~13~images/bible_images/Kings/kings_template.html~1';
LOI[68] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~15~14~images/bible_images/Kings/kings_template.html~1';
LOI[69] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~15~22~images/bible_images/Kings/kings_template.html~1';
LOI[70] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~15~30~images/bible_images/Kings/kings_template.html~1';
LOI[71] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~15~31~images/bible_images/Kings/kings_template.html~1';
LOI[72] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~15~32~images/bible_images/Kings/kings_template.html~1';
LOI[73] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~15~33~images/bible_images/Kings/kings_template.html~1';
LOI[74] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=Absalom~~~~2Sa~15~1~images/bible_images/Kings/kings_template.html~2';
LOI[75] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=Absalom~~~~2Sa~15~2~images/bible_images/Kings/kings_template.html~2';
LOI[76] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=Absalom~~~~2Sa~15~3~images/bible_images/Kings/kings_template.html~2';
LOI[77] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=Absalom~~~~2Sa~15~4~images/bible_images/Kings/kings_template.html~2';
LOI[78] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=Absalom~~~~2Sa~15~6~images/bible_images/Kings/kings_template.html~2';
LOI[79] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=Absalom~~~~2Sa~15~7~images/bible_images/Kings/kings_template.html~2';
LOI[80] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=Absalom~~~~2Sa~15~10~images/bible_images/Kings/kings_template.html~2';
LOI[81] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=Absalom~~~~2Sa~15~11~images/bible_images/Kings/kings_template.html~2';
LOI[82] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=Absalom~~~~2Sa~15~12~images/bible_images/Kings/kings_template.html~2';
LOI[83] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=Absalom,David~~~~2Sa~15~13~images/bible_images/Kings/kings_template.html~2';
LOI[84] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=Absalom,David~~~~2Sa~15~14~images/bible_images/Kings/kings_template.html~2';
LOI[85] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=Absalom,David~~~~2Sa~15~31~images/bible_images/Kings/kings_template.html~2';
LOI[86] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=Absalom~~~~2Sa~15~34~images/bible_images/Kings/kings_template.html~2';
LOI[87] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=Absalom~~~~2Sa~15~37~images/bible_images/Kings/kings_template.html~2';
LOI[88] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~15~22~images/bible_images/Kings/kings_template.html~2';
LOI[89] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~15~30~images/bible_images/Kings/kings_template.html~2';
LOI[90] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~15~32~images/bible_images/Kings/kings_template.html~2';
LOI[91] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~15~33~images/bible_images/Kings/kings_template.html~2';
LOI[92] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~2Sa~15~24~images/bible_images/Temple/temple_template.html~4';
LOI[93] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~2Sa~15~25~images/bible_images/Temple/temple_template.html~4';
LOI[94] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~2Sa~15~29~images/bible_images/Temple/temple_template.html~4';
