var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~23~1~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~23~3~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~2Sa~23~9~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Benjamin~~~~2Sa~23~29~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Sa~23~1~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Sa~23~3~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~2Sa~23~9~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Benjamin~~~~2Sa~23~29~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~23~1~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~23~3~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~2Sa~23~9~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~23~1~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~23~3~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~2Sa~23~9~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~2Sa~23~14~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~2Sa~23~15~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~2Sa~23~16~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~2Sa~23~24~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~2Sa~23~20~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~23~1~images/maps/Christ/christ_template.html~1';
LOI[20] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~23~3~images/maps/Christ/christ_template.html~1';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~2Sa~23~9~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Sa~23~9~images/bible_images/Samson/samson_template.html~6';
LOI[23] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Sa~23~10~images/bible_images/Samson/samson_template.html~6';
LOI[24] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Sa~23~11~images/bible_images/Samson/samson_template.html~6';
LOI[25] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Sa~23~12~images/bible_images/Samson/samson_template.html~6';
LOI[26] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Sa~23~13~images/bible_images/Samson/samson_template.html~6';
LOI[27] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Sa~23~14~images/bible_images/Samson/samson_template.html~6';
LOI[28] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Philistines~~~~2Sa~23~16~images/bible_images/Samson/samson_template.html~6';
LOI[29] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~23~1~images/bible_images/Kings/kings_template.html~1';
LOI[30] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~23~8~images/bible_images/Kings/kings_template.html~1';
LOI[31] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~23~9~images/bible_images/Kings/kings_template.html~1';
LOI[32] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~23~13~images/bible_images/Kings/kings_template.html~1';
LOI[33] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~23~14~images/bible_images/Kings/kings_template.html~1';
LOI[34] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~23~15~images/bible_images/Kings/kings_template.html~1';
LOI[35] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~23~16~images/bible_images/Kings/kings_template.html~1';
LOI[36] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~2Sa~23~23~images/bible_images/Kings/kings_template.html~1';
LOI[37] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~23~1~images/bible_images/Kings/kings_template.html~2';
LOI[38] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~23~8~images/bible_images/Kings/kings_template.html~2';
LOI[39] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~23~9~images/bible_images/Kings/kings_template.html~2';
LOI[40] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~23~13~images/bible_images/Kings/kings_template.html~2';
LOI[41] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~23~14~images/bible_images/Kings/kings_template.html~2';
LOI[42] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~23~15~images/bible_images/Kings/kings_template.html~2';
LOI[43] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~23~16~images/bible_images/Kings/kings_template.html~2';
LOI[44] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~2Sa~23~23~images/bible_images/Kings/kings_template.html~2';
