var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Rth~4~7~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Rth~4~11~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Rth~4~14~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Rth~4~12~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Rth~4~7~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Rth~4~11~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Rth~4~14~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Rth~4~12~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Rth~4~7~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Rth~4~11~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Rth~4~14~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Rth~4~7~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Bethlehem~~~~Rth~4~11~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Rth~4~14~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Rth~4~3~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Rth~4~7~images/maps/Christ/christ_template.html~1';
LOI[16] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Rth~4~11~images/maps/Christ/christ_template.html~1';
LOI[17] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Rth~4~14~images/maps/Christ/christ_template.html~1';
LOI[18] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~1~images/bible_images/Ruth/ruth_template.html~1';
LOI[19] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~2~images/bible_images/Ruth/ruth_template.html~1';
LOI[20] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~3~images/bible_images/Ruth/ruth_template.html~1';
LOI[21] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~4~images/bible_images/Ruth/ruth_template.html~1';
LOI[22] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~5~images/bible_images/Ruth/ruth_template.html~1';
LOI[23] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~6~images/bible_images/Ruth/ruth_template.html~1';
LOI[24] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~7~images/bible_images/Ruth/ruth_template.html~1';
LOI[25] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~8~images/bible_images/Ruth/ruth_template.html~1';
LOI[26] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~9~images/bible_images/Ruth/ruth_template.html~1';
LOI[27] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~10~images/bible_images/Ruth/ruth_template.html~1';
LOI[28] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~11~images/bible_images/Ruth/ruth_template.html~1';
LOI[29] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~12~images/bible_images/Ruth/ruth_template.html~1';
LOI[30] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~13~images/bible_images/Ruth/ruth_template.html~1';
LOI[31] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~14~images/bible_images/Ruth/ruth_template.html~1';
LOI[32] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~15~images/bible_images/Ruth/ruth_template.html~1';
LOI[33] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~16~images/bible_images/Ruth/ruth_template.html~1';
LOI[34] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~17~images/bible_images/Ruth/ruth_template.html~1';
LOI[35] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~18~images/bible_images/Ruth/ruth_template.html~1';
LOI[36] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~19~images/bible_images/Ruth/ruth_template.html~1';
LOI[37] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~20~images/bible_images/Ruth/ruth_template.html~1';
LOI[38] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~21~images/bible_images/Ruth/ruth_template.html~1';
LOI[39] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~4~22~images/bible_images/Ruth/ruth_template.html~1';
LOI[40] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Rth~4~17~images/bible_images/Kings/kings_template.html~1';
LOI[41] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Rth~4~22~images/bible_images/Kings/kings_template.html~1';
LOI[42] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Rth~4~17~images/bible_images/Kings/kings_template.html~2';
LOI[43] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Rth~4~22~images/bible_images/Kings/kings_template.html~2';
