var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Rth~2~12~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Rth~2~12~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Rth~2~12~images/maps/Otest/otest_template.html~3c';
LOI[3] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Rth~2~12~images/maps/Otest/otest_template.html~4';
LOI[4] = 'image~Bible~Maps~Southern Palestine (map) key=Bethlehem~~~~Rth~2~4~images/maps/Otest/otest_template.html~4';
LOI[5] = 'image~Bible~Maps~Southern Palestine (map) key=Moab~~~~Rth~2~6~images/maps/Otest/otest_template.html~4';
LOI[6] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Rth~2~12~images/maps/Christ/christ_template.html~1';
LOI[7] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~2~1~images/bible_images/Ruth/ruth_template.html~1';
LOI[8] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~2~2~images/bible_images/Ruth/ruth_template.html~1';
LOI[9] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~2~17~images/bible_images/Ruth/ruth_template.html~1';
LOI[10] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~2~18~images/bible_images/Ruth/ruth_template.html~1';
LOI[11] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~2~19~images/bible_images/Ruth/ruth_template.html~1';
LOI[12] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~2~20~images/bible_images/Ruth/ruth_template.html~1';
LOI[13] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~2~21~images/bible_images/Ruth/ruth_template.html~1';
LOI[14] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~2~22~images/bible_images/Ruth/ruth_template.html~1';
LOI[15] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~2~23~images/bible_images/Ruth/ruth_template.html~1';
LOI[16] = 'image~Bible~Images~Ruth and Naomi (engraving) key=Ruth~~~~Rth~2~8~images/bible_images/Ruth/ruth_template.html~1';
LOI[17] = 'image~Bible~Images~Ruth and Naomi (engraving) key=Naomi~~~~Rth~2~6~images/bible_images/Ruth/ruth_template.html~1';
