var LOI = [];
LOI[0] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~3~1~images/bible_images/Ruth/ruth_template.html~1';
LOI[1] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~3~2~images/bible_images/Ruth/ruth_template.html~1';
LOI[2] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~3~3~images/bible_images/Ruth/ruth_template.html~1';
LOI[3] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~3~4~images/bible_images/Ruth/ruth_template.html~1';
LOI[4] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~3~5~images/bible_images/Ruth/ruth_template.html~1';
LOI[5] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~3~6~images/bible_images/Ruth/ruth_template.html~1';
LOI[6] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~3~15~images/bible_images/Ruth/ruth_template.html~1';
LOI[7] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~3~16~images/bible_images/Ruth/ruth_template.html~1';
LOI[8] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~3~17~images/bible_images/Ruth/ruth_template.html~1';
LOI[9] = 'image~Bible~Images~Ruth and Naomi (engraving)~~~~Rth~3~18~images/bible_images/Ruth/ruth_template.html~1';
LOI[10] = 'image~Bible~Images~Ruth and Naomi (engraving) key=Ruth~~~~Rth~3~9~images/bible_images/Ruth/ruth_template.html~1';
