var LOI = [];
LOI[0] = 'hymn~2~TRUSTING JESUS (2)~htm_t_r_trustingj.html';
LOI[1] = 'hymn~4~GRACE AND TRUTH SHALL MARK THE WAY~htm_g_a_gantsmtw.html';
LOI[2] = 'hymn~5~O THOU GOD OF MY SALVATION~htm_o_t_othougod.html';
LOI[3] = 'hymn~18~BEFORE THY THRONE, O GOD, WE KNEEL~htm_b_e_b4tthron.html';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Psa~25~22~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Psa~25~22~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~25~22~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Psa~25~22~images/maps/Otest/otest_template.html~4';
LOI[8] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~25~22~images/maps/Christ/christ_template.html~1';
LOI[9] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Psa~25~1~images/bible_images/Kings/kings_template.html~1';
LOI[10] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~25~1~images/bible_images/Kings/kings_template.html~2';
