var LOI = [];
LOI[0] = 'hymn~14~WHERE THE WRECKS WASH IN~htm_w_h_e_whertwwi.html';
LOI[1] = 'hymn~16~THY LOVINGKINDNESS, LORD, IS GOOD AND FREE~htm_t_l_tlkligaf.html';
LOI[2] = 'hymn~20~THE BROKEN HEART~htm_b_r_brokenhe.html';
LOI[3] = 'hymn~30~O LORD, ALL GLORIOUS, LIFE OF LIFE~htm_o_l_a_olaglife.html';
LOI[4] = 'hymn~34~ALL CREATURES OF OUR GOD AND KING~htm_a_c_acoogak.html';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Psa~69~6~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Psa~69~35~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Psa~69~6~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Psa~69~35~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Psa~69~35~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Psa~69~35~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~69~6~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Psa~69~6~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~69~6~images/maps/Christ/christ_template.html~1';
LOI[14] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Psa~69~1~images/bible_images/Kings/kings_template.html~1';
LOI[15] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~69~1~images/bible_images/Kings/kings_template.html~2';
