var LOI = [];
LOI[0] = 'hymn~1~PRAISE FOR THEE, LORD, IN ZION WAITS~htm_p_l_pl4thinz.html';
LOI[1] = 'hymn~1~PRAISE WAITS FOR THEE IN ZION~htm_p_r_praisewf.html';
LOI[2] = 'hymn~5~THY MIGHT SETS FAST THE MOUNTAINS~htm_t_h_y_thymisfm.html';
LOI[3] = 'hymn~11~OUR FESTIVE SONG~htm_o_u_ourfests.html';
LOI[4] = 'hymn~12~HILLS OF THE NORTH, REJOICE~htm_h_i_hillsnor.html';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Psa~65~4~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Psa~65~4~images/maps/Otest/otest_template.html~3b';
LOI[7] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Psa~65~1~images/bible_images/Kings/kings_template.html~1';
LOI[8] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~65~1~images/bible_images/Kings/kings_template.html~2';
LOI[9] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Psa~65~4~images/bible_images/Temple/temple_template.html~1';
LOI[10] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Psa~65~4~images/bible_images/Temple/temple_template.html~2';
