var LOI = [];
LOI[0] = 'hymn~1~GOD IS MY STRONG SALVATION~htm_g_i_gismystr.html';
LOI[1] = 'hymn~1~LORD OF MY LIFE!~htm_l_o_lofmylif.html';
LOI[2] = 'hymn~1~LORD OF OUR LIFE~htm_l_o_lordlife.html';
LOI[3] = 'hymn~3~SURROUNDED BY A HOST OF FOES~htm_s_u_surround.html';
LOI[4] = 'hymn~5~ANYWHERE WITH JESUS~htm_a_n_anywhere.html';
LOI[5] = 'hymn~5~HIDE ME~htm_h_i_hideme.html';
LOI[6] = 'hymn~6~I WILL SING MY MAKER&#8217;S PRAISES~htm_i_w_iwismymp.html';
LOI[7] = 'hymn~8~LORD, WE COME BEFORE THEE NOW~htm_l_o_lorwecom.html';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Psa~27~4~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Psa~27~4~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Psa~27~1~images/bible_images/Kings/kings_template.html~1';
LOI[11] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~27~1~images/bible_images/Kings/kings_template.html~2';
LOI[12] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Psa~27~4~images/bible_images/Temple/temple_template.html~1';
LOI[13] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Psa~27~5~images/bible_images/Temple/temple_template.html~2';
LOI[14] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Psa~27~6~images/bible_images/Temple/temple_template.html~2';
LOI[15] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Psa~27~4~images/bible_images/Temple/temple_template.html~2';
LOI[16] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Psa~27~5~images/bible_images/Temple/temple_template.html~3';
LOI[17] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Psa~27~6~images/bible_images/Temple/temple_template.html~3';
