var LOI = [];
LOI[0] = 'hymn~2~GOD LOVETH THE RIGHTEOUS~htm_g_l_glovethr.html';
LOI[1] = 'hymn~23~HOLD THOU MY HAND~htm_h_o_holdthou.html';
LOI[2] = 'hymn~23~O TAKE MY HAND, DEAR FATHER~htm_o_t_otakemyh.html';
LOI[3] = 'hymn~24~O GOD, HOW GOOD THOU ART~htm_o_h_ohowgood.html';
LOI[4] = 'hymn~25~IN SIN I ONCE HAD WANDERED~htm_i_n_insionce.html';
LOI[5] = 'hymn~25~LORD OF EARTH, THY FORMING HAND~htm_l_e_learthtf.html';
LOI[6] = 'hymn~25~NONE OTHER LAMB~htm_n_o_noneothr.html';
LOI[7] = 'hymn~25~O FLY TO HIM~htm_o_f_ofly2him.html';
LOI[8] = 'hymn~25~ONLY IN THEE~htm_o_o_oninthee.html';
LOI[9] = 'hymn~25~WAIT ON THE LORD~htm_w_a_waitlord.html';
LOI[10] = 'hymn~25~WHOM HAVE I IN HEAVEN?~htm_w_h_o_whomhave.html';
LOI[11] = 'hymn~28~DELAY NOT, O SINNER, DRAW NEAR~htm_d_e_delaynot.html';
LOI[12] = 'hymn~28~YE NEIGHBORS AND FRIENDS OF JESUS~htm_y_e_yeneighb.html';
LOI[13] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Psa~73~1~images/maps/Otest/otest_template.html~1b';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Psa~73~1~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~73~1~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Psa~73~1~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~73~1~images/maps/Christ/christ_template.html~1';
