var LOI = [];
LOI[0] = 'hymn~1~I WILL SING THE WONDROUS STORY~htm_i_w_iwilsing.html';
LOI[1] = 'hymn~1~IMMORTAL LOVE, FOREVER FULL~htm_i_m_immortal.html';
LOI[2] = 'hymn~1~LET US WITH A GLADSOME MIND~htm_l_e_letuglad.html';
LOI[3] = 'hymn~1~MY SONG FOREVER SHALL RECORD~htm_m_s_msongfsr.html';
LOI[4] = 'hymn~1~SHALL HYMNS OF GRATEFUL LOVE~htm_s_h_shogratl.html';
LOI[5] = 'hymn~1~WHEN ALL THY MERCIES, O MY GOD~htm_w_h_e_whenallt.html';
LOI[6] = 'hymn~5~GREAT GOD OF WONDERS~htm_g_r_greatgow.html';
LOI[7] = 'hymn~5~THE PRAISES OF THY WONDERS~htm_p_r_praisetw.html';
LOI[8] = 'hymn~15~RING, HAPPY BELLS OF EASTER TIME~htm_r_i_ringhapp.html';
LOI[9] = 'hymn~18~O SAVIOR, LORD, TO THEE WE PRAY~htm_o_s_osalttwp.html';
LOI[10] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Psa~89~18~images/maps/Otest/otest_template.html~1b';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Psa~89~18~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~89~18~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Psa~89~18~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~89~18~images/maps/Christ/christ_template.html~1';
LOI[15] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Psa~89~3~images/bible_images/Kings/kings_template.html~1';
LOI[16] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Psa~89~20~images/bible_images/Kings/kings_template.html~1';
LOI[17] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Psa~89~35~images/bible_images/Kings/kings_template.html~1';
LOI[18] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Psa~89~49~images/bible_images/Kings/kings_template.html~1';
LOI[19] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~89~3~images/bible_images/Kings/kings_template.html~2';
LOI[20] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~89~20~images/bible_images/Kings/kings_template.html~2';
LOI[21] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~89~35~images/bible_images/Kings/kings_template.html~2';
LOI[22] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~89~49~images/bible_images/Kings/kings_template.html~2';
