var LOI = [];
LOI[0] = 'hymn~3~I DO NOT ASK, O LORD~htm_i_d_idnotask.html';
LOI[1] = 'hymn~3~JESUS, MERCIFUL AND MILD~htm_j_m_jmercifum.html';
LOI[2] = 'hymn~5~O GOD OF TRUTH~htm_o_g_ogotruth.html';
LOI[3] = 'hymn~5~O GOD OF TRUTH, O LORD OF MIGHT~htm_o_g_ogodtrut.html';
LOI[4] = 'hymn~15~FATHER, I KNOW THAT ALL MY LIFE~htm_f_a_fatiknow.html';
LOI[5] = 'hymn~15~MY TIMES ARE IN THY HAND~htm_m_t_mtimesar.html';
LOI[6] = 'hymn~15~TOMORROW, LORD, IS THINE~htm_t_l_tlithine.html';
LOI[7] = 'hymn~20~IN THE SECRET OF HIS PRESENCE~htm_i_t_itsecret.html';
LOI[8] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Psa~31~1~images/bible_images/Kings/kings_template.html~1';
LOI[9] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~31~1~images/bible_images/Kings/kings_template.html~2';
