var LOI = [];
LOI[0] = 'hymn~1~GOD IS KNOWN AMONG HIS PEOPLE~htm_g_i_gisknown.html';
LOI[1] = 'hymn~2~BLESSED CITY, HEAVENLY SALEM~htm_b_l_blesscit.html';
LOI[2] = 'hymn~2~RISE, CROWNED WITH LIGHT~htm_r_i_risecrow.html';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Judah~~~~Psa~76~1~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Judah~~~~Psa~76~1~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Psa~76~2~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Psa~76~2~images/maps/Otest/otest_template.html~3b';
LOI[7] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~76~1~images/maps/Otest/otest_template.html~3c';
LOI[8] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Psa~76~1~images/maps/Otest/otest_template.html~4';
LOI[9] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~76~1~images/maps/Christ/christ_template.html~1';
LOI[10] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Psa~76~2~images/bible_images/Temple/temple_template.html~2';
LOI[11] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Psa~76~2~images/bible_images/Temple/temple_template.html~3';
