var LOI = [];
LOI[0] = 'hymn~1~ZION, FOUNDED ON THE MOUNTAINS~htm_z_i_zionfoun.html';
LOI[1] = 'hymn~3~GLORIOUS THINGS OF THEE ARE SPOKEN~htm_g_l_glorious.html';
LOI[2] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ethiopia~~~~Psa~87~4~images/maps/Otest/otest_template.html~1a';
LOI[3] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Psa~87~2~images/maps/Otest/otest_template.html~3a';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Psa~87~5~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Psa~87~2~images/maps/Otest/otest_template.html~3b';
LOI[6] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Psa~87~5~images/maps/Otest/otest_template.html~3b';
LOI[7] = 'image~Bible~Maps~Middle Palestine (map) key=Tyre~~~~Psa~87~4~images/maps/Otest/otest_template.html~3c';
LOI[8] = 'image~Bible~Maps~Southern Palestine (map) key=Philistia~~~~Psa~87~4~images/maps/Otest/otest_template.html~4';
LOI[9] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Tyre~~~~Psa~87~4~images/maps/Journeys/journeys_template.html~3';
LOI[10] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Psa~87~4~images/bible_images/Kings/kings_template.html~7';
