var LOI = [];
LOI[0] = 'hymn~1~THE GOD WHO SITS ENTHRONED ON HIGH~htm_g_o_godwsit.html';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Psa~14~7~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Psa~14~7~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Cities of Refuge (map) key=refuge~~~~Psa~14~6~images/maps/Otest/otest_template.html~2';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Psa~14~7~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Psa~14~7~images/maps/Otest/otest_template.html~3b';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~14~7~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Psa~14~7~images/maps/Otest/otest_template.html~4';
LOI[8] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~14~7~images/maps/Christ/christ_template.html~1';
LOI[9] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Psa~14~1~images/bible_images/Kings/kings_template.html~1';
LOI[10] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~14~1~images/bible_images/Kings/kings_template.html~2';
