var LOI = [];
LOI[0] = 'hymn~1~IF YOU WILL ONLY LET GOD GUIDE YOU~htm_i_f_ifyouwil.html';
LOI[1] = 'hymn~14~BE THOU MY GUARDIAN AND MY GUIDE~htm_b_t_btmyguar.html';
LOI[2] = 'hymn~14~FATHER OF LOVE~htm_f_a_fathlove.html';
LOI[3] = 'hymn~14~FROM GOD SHALL NAUGHT DIVIDE ME~htm_f_r_fromgods.html';
LOI[4] = 'hymn~14~THE GUIDING HAND~htm_g_u_guidingh.html';
LOI[5] = 'hymn~14~HOLY SPIRIT, FAITHFUL GUIDE~htm_h_o_holyspir.html';
LOI[6] = 'hymn~14~LEAD ME GENTLY HOME, FATHER~htm_l_e_leadmegh.html';
LOI[7] = 'hymn~14~LEAD US, HEAVENLY FATHER~htm_l_e_leadushf.html';
LOI[8] = 'hymn~14~LIFE&#8217;S RAILWAY TO HEAVEN~htm_l_r_lrailway.html';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Psa~48~11~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Psa~48~11~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Cities of Refuge (map) key=refuge~~~~Psa~48~3~images/maps/Otest/otest_template.html~2';
LOI[12] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Psa~48~9~images/maps/Otest/otest_template.html~3a';
LOI[13] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Psa~48~2~images/maps/Otest/otest_template.html~3a';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Psa~48~11~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Psa~48~12~images/maps/Otest/otest_template.html~3a';
LOI[16] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Psa~48~9~images/maps/Otest/otest_template.html~3b';
LOI[17] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Psa~48~2~images/maps/Otest/otest_template.html~3b';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Psa~48~11~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Psa~48~12~images/maps/Otest/otest_template.html~3b';
LOI[20] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Psa~48~9~images/bible_images/Temple/temple_template.html~1';
LOI[21] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Psa~48~9~images/bible_images/Temple/temple_template.html~2';
