var LOI = [];
LOI[0] = 'hymn~1~HE LEADETH ME~htm_h_l_hleademe.html';
LOI[1] = 'hymn~1~THE KING OF LOVE MY SHEPHERD IS~htm_k_i_kinglove.html';
LOI[2] = 'hymn~1~THE LORD IS MY SHEPHERD~htm_l_o_lordismy.html';
LOI[3] = 'hymn~1~THE LORD MY PASTURE SHALL PREPARE~htm_l_m_lmpastur.html';
LOI[4] = 'hymn~1~THE LORD&#8217;S MY SHEPHERD~htm_l_m_lmysheph.html';
LOI[5] = 'hymn~1~MY SHEPHERD WILL SUPPLY MY NEED~htm_m_s_mshpwill.html';
LOI[6] = 'hymn~4~IN HEAVENLY LOVE ABIDING~htm_i_n_inhlovea.html';
LOI[7] = 'hymn~4~STAND BY ME~htm_s_t_standbym.html';
LOI[8] = 'hymn~4~THERE&#8217;S A LIGHT IN THE VALLEY~htm_t_a_talitval.html';
LOI[9] = 'hymn~4~JESUS WALKED THIS LONESOME VALLEY~htm_l_o_lonesome.html';
LOI[10] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Psa~23~1~images/bible_images/Kings/kings_template.html~1';
LOI[11] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~23~1~images/bible_images/Kings/kings_template.html~2';
