var LOI = [];
LOI[0] = 'hymn~1~MAN WHO ONCE HAS FOUND ABODE~htm_m_a_manwohfa.html';
LOI[1] = 'hymn~2~STILL WILL WE TRUST~htm_s_t_stilwill.html';
LOI[2] = 'hymn~3~IN GRIEF AND FEAR, TO THEE, O LORD~htm_i_n_ingrieff.html';
LOI[3] = 'hymn~4~AS THE BIRD FLIES HOME~htm_a_t_atbfhome.html';
LOI[4] = 'hymn~4~DAY IS PAST AND OVER, THE~htm_d_a_dayispa.html';
LOI[5] = 'hymn~4~NOW REST BENEATH NIGHT&#8217;S SHADOW~htm_n_o_nowrestb.html';
LOI[6] = 'hymn~4~NOW THAT THE DAYLIGHT DIES AWAY~htm_n_o_nowddies.html';
LOI[7] = 'hymn~4~NOW THE DAY IS OVER~htm_n_o_nowtheda.html';
LOI[8] = 'hymn~4~ST. PATRICK&#8217;S BREASTPLATE~htm_s_t_stpatric.html';
LOI[9] = 'hymn~4~THE SHADOWS OF THE EVENING HOURS~htm_s_h_shadowso.html';
LOI[10] = 'hymn~4~TO THEE BEFORE THE CLOSE OF DAY~htm_t_o_totheeb4.html';
LOI[11] = 'hymn~5~BEFORE THE ENDING OF THE DAY~htm_b_e_beforend.html';
LOI[12] = 'hymn~5~HOLY FATHER, BLESS US~htm_h_f_hfblessu.html';
LOI[13] = 'hymn~5~THIS NIGHT, O LORD, WE BLESS THEE~htm_t_n_tnolwebt.html';
LOI[14] = 'hymn~11~AROUND THE THRONE OF GOD A BAND~htm_a_r_aroundtt.html';
LOI[15] = 'hymn~11~CALL JEHOVAH THY SALVATION~htm_c_a_calljeho.html';
LOI[16] = 'hymn~11~NOW ALL THE WOODS ARE SLEEPING~htm_n_o_nowalwas.html';
LOI[17] = 'hymn~11~ONWARD, CHRISTIAN, THOUGH THE REGION~htm_o_c_octtregn.html';
LOI[18] = 'hymn~11~SOFTLY SIGHS THE BREATH OF EVENING~htm_s_o_softlysb.html';
LOI[19] = 'image~Bible~Maps~Cities of Refuge (map) key=refuge~~~~Psa~91~2~images/maps/Otest/otest_template.html~2';
LOI[20] = 'image~Bible~Maps~Cities of Refuge (map) key=refuge~~~~Psa~91~9~images/maps/Otest/otest_template.html~2';
