var LOI = [];
LOI[0] = 'hymn~5~BE THOU, O GOD, EXALTED HIGH~htm_b_e_bethouog.html';
LOI[1] = 'hymn~10~IN BOUNDLESS MERCY~htm_i_n_inboundm.html';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Saul~~~~Psa~57~1~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Cities of Refuge (map) key=refuge~~~~Psa~57~1~images/maps/Otest/otest_template.html~2';
LOI[4] = 'image~Bible~Images~Saul and David (engraving)~~~~Psa~57~1~images/bible_images/Kings/kings_template.html~1';
LOI[5] = 'image~Bible~Images~Saul and David (engraving)~~~~Psa~57~2~images/bible_images/Kings/kings_template.html~1';
LOI[6] = 'image~Bible~Images~Saul and David (engraving)~~~~Psa~57~3~images/bible_images/Kings/kings_template.html~1';
LOI[7] = 'image~Bible~Images~Saul and David (engraving)~~~~Psa~57~4~images/bible_images/Kings/kings_template.html~1';
LOI[8] = 'image~Bible~Images~Saul and David (engraving)~~~~Psa~57~5~images/bible_images/Kings/kings_template.html~1';
LOI[9] = 'image~Bible~Images~Saul and David (engraving)~~~~Psa~57~6~images/bible_images/Kings/kings_template.html~1';
LOI[10] = 'image~Bible~Images~Saul and David (engraving)~~~~Psa~57~7~images/bible_images/Kings/kings_template.html~1';
LOI[11] = 'image~Bible~Images~Saul and David (engraving)~~~~Psa~57~8~images/bible_images/Kings/kings_template.html~1';
LOI[12] = 'image~Bible~Images~Saul and David (engraving)~~~~Psa~57~9~images/bible_images/Kings/kings_template.html~1';
LOI[13] = 'image~Bible~Images~Saul and David (engraving)~~~~Psa~57~10~images/bible_images/Kings/kings_template.html~1';
LOI[14] = 'image~Bible~Images~Saul and David (engraving)~~~~Psa~57~11~images/bible_images/Kings/kings_template.html~1';
LOI[15] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~57~1~images/bible_images/Kings/kings_template.html~2';
LOI[16] = 'image~Bible~Images~The Death of Stephen key=Saul~~~~Psa~57~1~images/bible_images/Acts/acts_template.html~1';
LOI[17] = 'image~Bible~Images~The Conversion of St. Paul key=Saul~~~~Psa~57~1~images/bible_images/Acts/acts_template.html~2';
