var LOI = [];
LOI[0] = 'hymn~1~REMEMBER NOT, O GOD~htm_r_e_remembno.html';
LOI[1] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Temple~~~~Psa~79~1~images/maps/Otest/otest_template.html~3a';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Psa~79~3~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Temple~~~~Psa~79~1~images/maps/Otest/otest_template.html~3b';
LOI[4] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Psa~79~3~images/maps/Otest/otest_template.html~3b';
LOI[5] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Psa~79~1~images/maps/Otest/otest_template.html~4';
LOI[6] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Psa~79~3~images/maps/Otest/otest_template.html~4';
LOI[7] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Psa~79~1~images/places/Israel/israel_template.html~11';
LOI[8] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Psa~79~3~images/places/Israel/israel_template.html~11';
LOI[9] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Psa~79~1~images/places/Israel/israel_template.html~12';
LOI[10] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Psa~79~3~images/places/Israel/israel_template.html~12';
LOI[11] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Psa~79~1~images/places/Israel/israel_template.html~13';
LOI[12] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Psa~79~3~images/places/Israel/israel_template.html~13';
LOI[13] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Psa~79~1~images/places/Israel/israel_template.html~14';
LOI[14] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Psa~79~3~images/places/Israel/israel_template.html~14';
LOI[15] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Psa~79~1~images/places/Israel/israel_template.html~17';
LOI[16] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Psa~79~3~images/places/Israel/israel_template.html~17';
LOI[17] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Psa~79~1~images/bible_images/Temple/temple_template.html~1';
LOI[18] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Psa~79~1~images/bible_images/Temple/temple_template.html~2';
