var LOI = [];
LOI[0] = 'hymn~16~FED UPON THE FINEST OF THE WHEAT~htm_f_i_finwheat.html';
LOI[1] = 'hymn~16~HONEY IN THE ROCK~htm_h_i_hintrock.html';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Psa~81~4~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Psa~81~8~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Psa~81~11~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Psa~81~13~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Psa~81~5~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Psa~81~4~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Psa~81~8~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Psa~81~11~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Psa~81~13~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Psa~81~5~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~81~4~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~81~8~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~81~11~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~81~13~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Psa~81~4~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Psa~81~8~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Psa~81~11~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Psa~81~13~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Psa~81~5~images/maps/Otest/otest_template.html~5';
LOI[21] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Psa~81~10~images/maps/Otest/otest_template.html~5';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~81~4~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~81~8~images/maps/Christ/christ_template.html~1';
LOI[24] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~81~11~images/maps/Christ/christ_template.html~1';
LOI[25] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~81~13~images/maps/Christ/christ_template.html~1';
LOI[26] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Psa~81~5~images/bible_images/Moses/moses_template.html~5';
LOI[27] = 'image~Bible~Images~Miriam\'s Song (engraving) key=timbrel~~~~Psa~81~2~images/bible_images/Moses/moses_template.html~8';
