var LOI = [];
LOI[0] = 'hymn~1~FROM DEPTHS OF WOE I RAISE TO THEE~htm_f_r_fromdepw.html';
LOI[1] = 'hymn~1~FROM THE DEPTHS DO I INVOKE THEE~htm_f_d_fdepthdi.html';
LOI[2] = 'hymn~1~LORD, FROM THE DEPTHS TO THEE I CRIED~htm_l_f_lftdttic.html';
LOI[3] = 'hymn~1~OUT OF MY BONDAGE, SORROW, AND NIGHT~htm_o_u_outofmyb.html';
LOI[4] = 'hymn~5~MY SAVIOR, ON THE WORD OF TRUTH~htm_m_s_msavotwt.html';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Psa~130~7~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Psa~130~8~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Psa~130~7~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Psa~130~8~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~130~7~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~130~8~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Psa~130~7~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Psa~130~8~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~130~7~images/maps/Christ/christ_template.html~1';
LOI[14] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~130~8~images/maps/Christ/christ_template.html~1';
