var LOI = [];
LOI[0] = 'hymn~1~O COULD I SPEAK THE MATCHLESS WORTH~htm_o_c_ocouldis.html';
LOI[1] = 'hymn~1~PRAISE YE THE LORD, &#8217;TIS GOOD TO RAISE~htm_p_y_pyetlort.html';
LOI[2] = 'hymn~1~REJOICE YE PEOPLE, HOMAGE GIVE~htm_r_e_rejoicey.html';
LOI[3] = 'hymn~1~WITH SONGS AND HONORS SOUNDING LOUD~htm_w_i_withsong.html';
LOI[4] = 'hymn~1~WITH GLADNESS WE WORSHIP~htm_w_i_withglad.html';
LOI[5] = 'hymn~5~INFINITE GOD, TO THEE WE RAISE~htm_i_n_infinite.html';
LOI[6] = 'hymn~16~ALL BEAUTIFUL THE MARCH OF DAYS~htm_a_l_allbeaut.html';
LOI[7] = 'hymn~16~&#8217;TIS WINTER NOW, THE FALLEN SNOW~htm_t_i_tiswintr.html';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Psa~147~2~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Psa~147~19~images/maps/Otest/otest_template.html~1b';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Psa~147~2~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Psa~147~19~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Psa~147~2~images/maps/Otest/otest_template.html~3a';
LOI[13] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Zion~~~~Psa~147~12~images/maps/Otest/otest_template.html~3a';
LOI[14] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Psa~147~2~images/maps/Otest/otest_template.html~3b';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Zion~~~~Psa~147~12~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~147~2~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~147~19~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jerusalem~~~~Psa~147~2~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Psa~147~19~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Psa~147~12~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~147~2~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~147~19~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Psa~147~2~images/places/Israel/israel_template.html~11';
LOI[24] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Psa~147~12~images/places/Israel/israel_template.html~11';
LOI[25] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Psa~147~2~images/places/Israel/israel_template.html~12';
LOI[26] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Psa~147~12~images/places/Israel/israel_template.html~12';
LOI[27] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Psa~147~2~images/places/Israel/israel_template.html~13';
LOI[28] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Psa~147~12~images/places/Israel/israel_template.html~13';
LOI[29] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Psa~147~2~images/places/Israel/israel_template.html~14';
LOI[30] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Psa~147~12~images/places/Israel/israel_template.html~14';
LOI[31] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Psa~147~2~images/places/Israel/israel_template.html~17';
LOI[32] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Psa~147~12~images/places/Israel/israel_template.html~17';
