var LOI = [];
LOI[0] = 'hymn~1~O &#8217;TWAS A JOYFUL SOUND TO HEAR~htm_o_t_otajoyfs.html';
LOI[1] = 'hymn~1~TO THY TEMPLE I REPAIR~htm_t_o_tothytem.html';
LOI[2] = 'hymn~6~PRAY THAT JERUSALEM MAY HAVE~htm_p_r_praythat.html';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Psa~122~4~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Psa~122~4~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Psa~122~2~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Psa~122~3~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Psa~122~6~images/maps/Otest/otest_template.html~3a';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Psa~122~2~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Psa~122~3~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Psa~122~6~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Psa~122~4~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Psa~122~4~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Psa~122~2~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Psa~122~3~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Psa~122~6~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Psa~122~4~images/maps/Christ/christ_template.html~1';
LOI[17] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Psa~122~2~images/places/Israel/israel_template.html~11';
LOI[18] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Psa~122~3~images/places/Israel/israel_template.html~11';
LOI[19] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Psa~122~6~images/places/Israel/israel_template.html~11';
LOI[20] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Psa~122~2~images/places/Israel/israel_template.html~12';
LOI[21] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Psa~122~3~images/places/Israel/israel_template.html~12';
LOI[22] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Psa~122~6~images/places/Israel/israel_template.html~12';
LOI[23] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Psa~122~2~images/places/Israel/israel_template.html~13';
LOI[24] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Psa~122~3~images/places/Israel/israel_template.html~13';
LOI[25] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Psa~122~6~images/places/Israel/israel_template.html~13';
LOI[26] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Psa~122~2~images/places/Israel/israel_template.html~14';
LOI[27] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Psa~122~3~images/places/Israel/israel_template.html~14';
LOI[28] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Psa~122~6~images/places/Israel/israel_template.html~14';
LOI[29] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Psa~122~2~images/places/Israel/israel_template.html~17';
LOI[30] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Psa~122~3~images/places/Israel/israel_template.html~17';
LOI[31] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Psa~122~6~images/places/Israel/israel_template.html~17';
LOI[32] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Psa~122~1~images/bible_images/Kings/kings_template.html~1';
LOI[33] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Psa~122~5~images/bible_images/Kings/kings_template.html~1';
LOI[34] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~122~1~images/bible_images/Kings/kings_template.html~2';
LOI[35] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~122~5~images/bible_images/Kings/kings_template.html~2';
