var LOI = [];
LOI[0] = 'hymn~1~O LORD, MY INMOST HEART AND THOUGHT~htm_o_l_olomihat.html';
LOI[1] = 'hymn~9~THOU LORD OF HOSTS~htm_t_h_o_thouloho.html';
LOI[2] = 'hymn~10~GREAT GOD, WE SING YOUR MIGHTY HAND~htm_g_g_ggwesing.html';
LOI[3] = 'hymn~12~GOD IS ALWAYS NEAR ME~htm_g_i_gisalway.html';
LOI[4] = 'hymn~12~O THOU TO WHOSE ALL SEARCHING SIGHT~htm_o_t_othoutow.html';
LOI[5] = 'hymn~12~PEACEFULLY ROUND US THE SHADOWS ARE FALLING~htm_p_e_perutsaf.html';
LOI[6] = 'hymn~14~ALL THAT I AM I OWE TO THEE~htm_a_l_allthati.html';
LOI[7] = 'hymn~14~MY GOD, HOW WONDERFUL YOU ARE~htm_m_y_mygodhow.html';
LOI[8] = 'hymn~18~STILL, STILL WITH THEE~htm_s_t_stilstil.html';
LOI[9] = 'hymn~24~FATHER, LEAD ME DAY BY DAY~htm_f_a_faleadme.html';
LOI[10] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Psa~139~1~images/bible_images/Kings/kings_template.html~1';
LOI[11] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Psa~139~1~images/bible_images/Kings/kings_template.html~2';
