var LOI = [];
LOI[0] = 'hymn~4~BEFORE THE THRONE OF GOD ABOVE~htm_b_e_beforetg.html';
LOI[1] = 'hymn~4~SWEET FLOW&#8217;RETS OF THE MARTYR BAND~htm_s_w_sweetflo.html';
LOI[2] = 'hymn~6~PRAISE THE LORD, EACH TRIBE AND NATION~htm_p_t_ptltribe.html';
LOI[3] = 'hymn~13~FOR ALL THE SAINTS~htm_f_a_fallthes.html';
LOI[4] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Rev~0~0~images/charts/Bible/bible_template.html~1';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Rev~14~15~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Rev~14~17~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Rev~14~15~images/maps/Otest/otest_template.html~3b';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Rev~14~17~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Rev~14~8~images/bible_images/Kings/kings_template.html~7';
LOI[10] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Rev~14~15~images/bible_images/Temple/temple_template.html~1';
LOI[11] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Rev~14~17~images/bible_images/Temple/temple_template.html~1';
LOI[12] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Rev~14~15~images/bible_images/Temple/temple_template.html~2';
LOI[13] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Rev~14~17~images/bible_images/Temple/temple_template.html~2';
