var LOI = [];
LOI[0] = 'hymn~1~SAFE UPON THE BILLOWY DEEP~htm_s_a_safeupon.html';
LOI[1] = 'hymn~2~CITY OF GOD, HOW BROAD AND FAR~htm_c_i_cityogod.html';
LOI[2] = 'hymn~2~JERUSALEM MY HAPPY HOME~htm_j_m_jmyhappy.html';
LOI[3] = 'hymn~2~JERUSALEM, THOU CITY BRIGHT~htm_j_c_jcitybri.html';
LOI[4] = 'hymn~2~O MOTHER DEAR, JERUSALEM~htm_o_m_omdjerus.html';
LOI[5] = 'hymn~2~WHEN THE TOILS OF LIFE ARE OVER~htm_w_t_wtolifao.html';
LOI[6] = 'hymn~3~GREAT KING OF GLORY, COME~htm_g_r_greatkog.html';
LOI[7] = 'hymn~4~JERUSALEM, JERUSALEM~htm_j_e_jerujeru.html';
LOI[8] = 'hymn~5~GLORY TO GOD! THE MORN APPOINTED BREAKS~htm_g_t_gtgotmab.html';
LOI[9] = 'hymn~5~O LIFE THAT MAKEST ALL THINGS NEW~htm_o_l_olifetha.html';
LOI[10] = 'hymn~10~HAIL THE GLORIOUS GOLDEN CITY~htm_h_g_hggolden.html';
LOI[11] = 'hymn~10~O HOLY CITY, SEEN OF JOHN~htm_o_h_oholycit.html';
LOI[12] = 'hymn~18~BEYOND THE SUNSET~htm_b_e_beyondss.html';
LOI[13] = 'hymn~18~BY THE GRACE OF GOD WE&#8217;LL MEET~htm_b_y_bytgrace.html';
LOI[14] = 'hymn~18~DAILY, DAILY, SING THE PRAISES~htm_d_a_dalydaly.html';
LOI[15] = 'hymn~18~FOR THEE, O DEAR, DEAR COUNTRY~htm_f_o_fortheeo.html';
LOI[16] = 'hymn~18~HOW BEAUTIFUL HEAVEN MUST BE~htm_h_b_hbeauthm.html';
LOI[17] = 'hymn~18~I WILL SING YOU A SONG~htm_i_w_iwsysong.html';
LOI[18] = 'hymn~18~JERUSALEM THE GOLDEN~htm_j_t_jtgolden.html';
LOI[19] = 'hymn~21~HE THE PEARLY GATES WILL OPEN~htm_h_t_htpearly.html';
LOI[20] = 'hymn~21~SING TO ME OF HEAVEN~htm_s_i_singtome.html';
LOI[21] = 'hymn~23~BEAUTIFUL ISLE OF SOMEWHERE~htm_b_e_beautisl.html';
LOI[22] = 'hymn~23~BEAUTIFUL VALLEY OF EDEN~htm_b_e_beautive.html';
LOI[23] = 'hymn~23~BY AND BY (1)~htm_b_y_byandby1.html';
LOI[24] = 'hymn~23~OH REALM OF LIGHT~htm_o_r_orealmli.html';
LOI[25] = 'hymn~23~ON JORDAN&#8217;S STORMY BANKS I STAND~htm_o_j_ojordsbi.html';
LOI[26] = 'hymn~23~THERE&#8217;LL BE NO DARK VALLEY~htm_t_h_therellb.html';
LOI[27] = 'hymn~25~NO NIGHT THERE~htm_n_n_nnighthr.html';
LOI[28] = 'hymn~25~WHERE THE GATES SWING OUTWARD NEVER~htm_w_g_wgsonevr.html';
LOI[29] = 'hymn~27~IS MY NAME WRITTEN THERE?~htm_i_s_ismyname.html';
LOI[30] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Rev~0~0~images/charts/Bible/bible_template.html~1';
LOI[31] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Rev~21~12~images/maps/Otest/otest_template.html~1b';
LOI[32] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Rev~21~12~images/maps/Otest/otest_template.html~1c';
LOI[33] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Rev~21~2~images/maps/Otest/otest_template.html~3a';
LOI[34] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Rev~21~10~images/maps/Otest/otest_template.html~3a';
LOI[35] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Rev~21~22~images/maps/Otest/otest_template.html~3a';
LOI[36] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Rev~21~2~images/maps/Otest/otest_template.html~3b';
LOI[37] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Rev~21~10~images/maps/Otest/otest_template.html~3b';
LOI[38] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Rev~21~22~images/maps/Otest/otest_template.html~3b';
LOI[39] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Rev~21~12~images/maps/Otest/otest_template.html~3c';
LOI[40] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Rev~21~12~images/maps/Otest/otest_template.html~4';
LOI[41] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Rev~21~2~images/maps/Otest/otest_template.html~4';
LOI[42] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Rev~21~10~images/maps/Otest/otest_template.html~4';
LOI[43] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Rev~21~12~images/maps/Christ/christ_template.html~1';
LOI[44] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Rev~21~2~images/places/Israel/israel_template.html~11';
LOI[45] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Rev~21~10~images/places/Israel/israel_template.html~11';
LOI[46] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Rev~21~2~images/places/Israel/israel_template.html~12';
LOI[47] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Rev~21~10~images/places/Israel/israel_template.html~12';
LOI[48] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Rev~21~2~images/places/Israel/israel_template.html~13';
LOI[49] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Rev~21~10~images/places/Israel/israel_template.html~13';
LOI[50] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Rev~21~2~images/places/Israel/israel_template.html~14';
LOI[51] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Rev~21~10~images/places/Israel/israel_template.html~14';
LOI[52] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Rev~21~2~images/places/Israel/israel_template.html~17';
LOI[53] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Rev~21~10~images/places/Israel/israel_template.html~17';
LOI[54] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Rev~21~22~images/bible_images/Temple/temple_template.html~1';
LOI[55] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Rev~21~3~images/bible_images/Temple/temple_template.html~2';
LOI[56] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Rev~21~22~images/bible_images/Temple/temple_template.html~2';
LOI[57] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Rev~21~3~images/bible_images/Temple/temple_template.html~3';
