var LOI = [];
LOI[0] = 'hymn~1~HALLELUJAH! LET PRAISES RING!~htm_h_l_hlpraisr.html';
LOI[1] = 'hymn~6~COME, THOU ALMIGHTY KING~htm_c_t_ctak.html';
LOI[2] = 'hymn~6~GOD, THE OMNIPOTENT!~htm_g_t_gtomnipo.html';
LOI[3] = 'hymn~6~HARK! THE SONG OF JUBILEE~htm_h_a_harksong.html';
LOI[4] = 'hymn~6~HOW OFT IN HOLY CONVERSE~htm_h_h_hholycon.html';
LOI[5] = 'hymn~7~THE SANDS OF TIME ARE SINKING~htm_s_a_sandtime.html';
LOI[6] = 'hymn~9~HERE, O MY LORD, I SEE THEE~htm_h_e_hereomyl.html';
LOI[7] = 'hymn~11~COME, THOU CONQUEROR OF THE NATIONS~htm_c_o_comtconq.html';
LOI[8] = 'hymn~12~CROWN HIM WITH MANY CROWNS~htm_c_r_crownhim.html';
LOI[9] = 'hymn~12~CROWNING DAY, THE~htm_c_r_crowning.html';
LOI[10] = 'hymn~13~O HEAVENLY WORD~htm_o_h_oheavnlw.html';
LOI[11] = 'hymn~16~KING OF KINGS~htm_k_i_kingking.html';
LOI[12] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Rev~0~0~images/charts/Bible/bible_template.html~1';
LOI[13] = 'image~Bible~Images~The Leper Healed (engraving) key=miracles~~~~Rev~19~20~images/bible_images/Miracles/miracles_template.html~1';
LOI[14] = 'image~Bible~Images~Man With Palsy Healed (engraving) key=miracles~~~~Rev~19~20~images/bible_images/Miracles/miracles_template.html~2';
LOI[15] = 'image~Bible~Images~The Raising of Jairus\' Daughter (engraving) key=miracles~~~~Rev~19~20~images/bible_images/Miracles/miracles_template.html~3';
LOI[16] = 'image~Bible~Images~The Paralytic Healed (engraving) key=miracles~~~~Rev~19~20~images/bible_images/Miracles/miracles_template.html~4';
LOI[17] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving) key=miracles~~~~Rev~19~20~images/bible_images/Miracles/miracles_template.html~5';
LOI[18] = 'image~Bible~Images~Jesus Walking on the Sea (engraving) key=miracles~~~~Rev~19~20~images/bible_images/Miracles/miracles_template.html~6';
LOI[19] = 'image~Bible~Images~Healing Demoniac Daughter (engraving) key=miracles~~~~Rev~19~20~images/bible_images/Miracles/miracles_template.html~7';
LOI[20] = 'image~Bible~Images~Deaf Man Hears (engraving) key=miracles~~~~Rev~19~20~images/bible_images/Miracles/miracles_template.html~8';
LOI[21] = 'image~Bible~Images~Man Born Blind Healed (engraving) key=miracles~~~~Rev~19~20~images/bible_images/Miracles/miracles_template.html~9';
LOI[22] = 'image~Bible~Images~Jesus Healing Ten Lepers (engraving) key=miracles~~~~Rev~19~20~images/bible_images/Miracles/miracles_template.html~10';
LOI[23] = 'image~Bible~Images~Jesus Heals Bartimaeus (engraving) key=miracles~~~~Rev~19~20~images/bible_images/Miracles/miracles_template.html~11';
