var LOI = [];
LOI[0] = 'hymn~5~THE LION OF JUDAH~htm_l_i_lionjuda.html';
LOI[1] = 'hymn~8~GOLDEN HARPS ARE SOUNDING~htm_g_h_gharpsas.html';
LOI[2] = 'hymn~9~ALL MORTAL VANITIES, BEGONE~htm_a_l_almortal.html';
LOI[3] = 'hymn~11~CHORUS OF FIRE~htm_c_h_chorusfi.html';
LOI[4] = 'hymn~11~COME, LET US JOIN OUR CHEERFUL SONGS~htm_c_o_comeletu.html';
LOI[5] = 'hymn~11~EVERLASTING HYMN, THE~htm_e_v_evlasthm.html';
LOI[6] = 'hymn~11~HARK, TEN THOUSAND HARPS AND VOICES~htm_h_a_harktent.html';
LOI[7] = 'hymn~11~HARK! TEN THOUSAND VOICES~htm_h_t_htenthou.html';
LOI[8] = 'hymn~11~HOLY, HOLY, IS WHAT THE ANGELS SING~htm_h_o_holholis.html';
LOI[9] = 'hymn~11~HOW SHALL I SING THAT MAJESTY~htm_h_o_howsisi.html';
LOI[10] = 'hymn~11~I HEARD A SOUND OF VOICES~htm_i_h_iheardsv.html';
LOI[11] = 'hymn~11~O FOR A THOUSAND TONGUES TO SING~htm_o_f_ofor1000.html';
LOI[12] = 'hymn~11~O THAT I HAD A THOUSAND VOICES~htm_o_t_othatiha.html';
LOI[13] = 'hymn~11~TEN THOUSAND TIMES TEN THOUSAND~htm_t_e_tenttent.html';
LOI[14] = 'hymn~11~A THOUSAND ORACLES DIVINE~htm_t_h_o_thordivi.html';
LOI[15] = 'hymn~11~YE HOLY ANGELS BRIGHT~htm_y_e_yeholyab.html';
LOI[16] = 'hymn~12~HE IS COMING~htm_h_e_heiscom2.html';
LOI[17] = 'hymn~12~WHAT EQUAL HONORS SHALL WE BRING~htm_w_h_whatequa.html';
LOI[18] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Rev~0~0~images/charts/Bible/bible_template.html~1';
LOI[19] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Rev~5~5~images/bible_images/Kings/kings_template.html~1';
LOI[20] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Rev~5~5~images/bible_images/Kings/kings_template.html~2';
