var LOI = [];
LOI[0] = 'hymn~9~COME, LET US JOIN OUR FRIENDS ABOVE~htm_c_o_comejoin.html';
LOI[1] = 'hymn~9~LOOK FOR ME!~htm_l_o_lookfome.html';
LOI[2] = 'hymn~11~OUR DAY OF PRAISE IS DONE~htm_o_u_ourdayop.html';
LOI[3] = 'hymn~13~WHO ARE THESE LIKE STARS APPEARING~htm_w_h_o_whoaretl.html';
LOI[4] = 'hymn~14~ARE YOU WASHED IN THE BLOOD?~htm_a_r_aruwashd.html';
LOI[5] = 'hymn~14~BEHOLD A HOST, ARRAYED IN WHITE~htm_b_e_beholdah.html';
LOI[6] = 'hymn~14~BLOOD-WASHED THRONG, THE~htm_b_l_bloodwat.html';
LOI[7] = 'hymn~14~HARK! THE SOUND OF HOLY VOICES~htm_h_s_hsoundhv.html';
LOI[8] = 'hymn~14~HOW BRIGHT THESE GLORIOUS SPIRITS SHINE~htm_t_g_tgmindsh.html';
LOI[9] = 'hymn~14~THERE IS POWER IN THE BLOOD~htm_t_h_therepow.html';
LOI[10] = 'hymn~17~ALL THE WAY MY SAVIOR LEADS ME~htm_a_l_altheway.html';
LOI[11] = 'hymn~17~DEEM NOT THAT THEY ARE BLEST ALONE~htm_d_e_deemnott.html';
LOI[12] = 'hymn~17~GATHERING OUT OF TEARS~htm_g_a_gathtear.html';
LOI[13] = 'hymn~17~THE LOST CHORD~htm_l_o_lostchor.html';
LOI[14] = 'hymn~17~LOVED ONE, FAREWELL~htm_l_o_lovedofw.html';
LOI[15] = 'hymn~17~WHEN GATHERING CLOUDS AROUND I VIEW~htm_w_h_e_whengath.html';
LOI[16] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Rev~0~0~images/charts/Bible/bible_template.html~1';
LOI[17] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Rev~7~4~images/maps/Otest/otest_template.html~1b';
LOI[18] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Reuben,Gad~~~~Rev~7~5~images/maps/Otest/otest_template.html~1b';
LOI[19] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map)~~~~Rev~7~7~images/maps/Otest/otest_template.html~1b';
LOI[20] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph,Benjamin~~~~Rev~7~8~images/maps/Otest/otest_template.html~1b';
LOI[21] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Rev~7~4~images/maps/Otest/otest_template.html~1c';
LOI[22] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Reuben,Gad~~~~Rev~7~5~images/maps/Otest/otest_template.html~1c';
LOI[23] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map)~~~~Rev~7~7~images/maps/Otest/otest_template.html~1c';
LOI[24] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph,Benjamin~~~~Rev~7~8~images/maps/Otest/otest_template.html~1c';
LOI[25] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Rev~7~15~images/maps/Otest/otest_template.html~3a';
LOI[26] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Rev~7~15~images/maps/Otest/otest_template.html~3b';
LOI[27] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Rev~7~4~images/maps/Otest/otest_template.html~3c';
LOI[28] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Rev~7~4~images/maps/Otest/otest_template.html~4';
LOI[29] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Rev~7~4~images/maps/Christ/christ_template.html~1';
LOI[30] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart) key=tribulation~~~~Rev~7~14~images/charts/Bible/bible_template.html~1';
LOI[31] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Rev~7~8~images/bible_images/Moses/moses_template.html~5';
LOI[32] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Rev~7~15~images/bible_images/Temple/temple_template.html~1';
LOI[33] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Rev~7~15~images/bible_images/Temple/temple_template.html~2';
