var LOI = [];
LOI[0] = 'hymn~4~O FOR A CLOSER WALK WITH GOD~htm_o_f_oforaclo.html';
LOI[1] = 'hymn~10~IN THE HOUR OF TRIAL~htm_i_n_inthehou.html';
LOI[2] = 'hymn~12~O WHAT THEIR JOY AND THEIR GLORY MUST BE~htm_o_w_owhatjoy.html';
LOI[3] = 'hymn~20~BEHOLD, A STRANGER AT THE DOOR!~htm_b_e_beholdas.html';
LOI[4] = 'hymn~20~BEHOLD ME STANDING AT THE DOOR~htm_b_e_beholdme.html';
LOI[5] = 'hymn~20~COME, LET US WHO IN CHRIST BELIEVE~htm_c_o_comeluwi.html';
LOI[6] = 'hymn~20~GOD CALLING YET~htm_g_c_gcalling.html';
LOI[7] = 'hymn~20~HAVE YOU ANY ROOM FOR JESUS?~htm_h_y_hyouanyr.html';
LOI[8] = 'hymn~20~LET HIM IN~htm_l_e_lethimin.html';
LOI[9] = 'hymn~20~LET JESUS COME INTO YOUR HEART~htm_l_e_letjesus.html';
LOI[10] = 'hymn~20~MASTER&#8217;S CALL, THE~htm_m_a_mastcall.html';
LOI[11] = 'hymn~20~O JESUS, THOU ART STANDING~htm_o_j_ojthouas.html';
LOI[12] = 'hymn~20~ONLY A STEP~htm_o_n_onlystep.html';
LOI[13] = 'hymn~20~SHALL I BE SAVED TONIGHT?~htm_s_h_shallibe.html';
LOI[14] = 'hymn~20~SINCE JESUS CAME INTO MY HEART~htm_s_i_sincejes.html';
LOI[15] = 'hymn~20~WHO AT MY DOOR IS STANDING?~htm_w_h_o_whoatmyd.html';
LOI[16] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Rev~0~0~images/charts/Bible/bible_template.html~1';
LOI[17] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Temple~~~~Rev~3~12~images/maps/Otest/otest_template.html~3a';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Temple~~~~Rev~3~12~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Rev~3~12~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Rev~3~12~images/places/Israel/israel_template.html~11';
LOI[21] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Rev~3~12~images/places/Israel/israel_template.html~12';
LOI[22] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Rev~3~12~images/places/Israel/israel_template.html~13';
LOI[23] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Rev~3~12~images/places/Israel/israel_template.html~14';
LOI[24] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Rev~3~12~images/places/Israel/israel_template.html~17';
LOI[25] = 'image~Bible~Images~The Creation (engraving) key=creation~~~~Rev~3~14~images/bible_images/Moses/moses_template.html~1a';
LOI[26] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Rev~3~7~images/bible_images/Kings/kings_template.html~1';
LOI[27] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Rev~3~7~images/bible_images/Kings/kings_template.html~2';
LOI[28] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Rev~3~12~images/bible_images/Temple/temple_template.html~1';
LOI[29] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Rev~3~12~images/bible_images/Temple/temple_template.html~2';
