var LOI = [];
LOI[0] = 'hymn~2~THE UNCLOUDED DAY~htm_u_n_uncloudd.html';
LOI[1] = 'hymn~7~O PARADISE!~htm_o_p_oparadis.html';
LOI[2] = 'hymn~10~FEAR NOT, O LITTLE FLOCK~htm_f_n_fnolflok.html';
LOI[3] = 'hymn~10~LAURELS, FRESH LAURELS~htm_l_a_laurelsf.html';
LOI[4] = 'hymn~10~LET OUR CHOIR NEW ANTHEMS RAISE~htm_l_e_letourch.html';
LOI[5] = 'hymn~17~A NEW NAME IN GLORY~htm_n_e_newnamei.html';
LOI[6] = 'hymn~17~O FOR A HEART TO PRAISE MY GOD~htm_o_f_oforhear.html';
LOI[7] = 'hymn~20~KUM BA YAH~htm_k_u_kumbayah.html';
LOI[8] = 'hymn~25~HOLD FAST TILL I COME~htm_h_o_holdfast.html';
LOI[9] = 'hymn~25~HOLD THE FORT~htm_h_o_holdfort.html';
LOI[10] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart)~~~~Rev~0~0~images/charts/Bible/bible_template.html~1';
LOI[11] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Rev~2~14~images/maps/Otest/otest_template.html~1b';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Rev~2~14~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Rev~2~14~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Rev~2~14~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Rev~2~14~images/maps/Christ/christ_template.html~1';
LOI[16] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Ephesus~~~~Rev~2~1~images/maps/Journeys/journeys_template.html~2';
LOI[17] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Ephesus~~~~Rev~2~1~images/maps/Journeys/journeys_template.html~3';
LOI[18] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart) key=tribulation~~~~Rev~2~9~images/charts/Bible/bible_template.html~1';
LOI[19] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart) key=tribulation~~~~Rev~2~10~images/charts/Bible/bible_template.html~1';
LOI[20] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart) key=tribulation~~~~Rev~2~22~images/charts/Bible/bible_template.html~1';
