var LOI = [];
LOI[0] = 'hymn~4~THE LORD IS RICH AND MERCIFUL~htm_l_o_lordrich.html';
LOI[1] = 'hymn~7~THE RIVER OF THY GRACE~htm_r_i_rivgrace.html';
LOI[2] = 'hymn~8~BY GRACE I&#8217;M SAVED~htm_b_y_bygracim.html';
LOI[3] = 'hymn~8~A MESSAGE SWEET IS BORNE TO ME~htm_m_s_msgsweet.html';
LOI[4] = 'hymn~8~NOT WHAT MY HANDS HAVE DONE~htm_n_w_nwhatmyh.html';
LOI[5] = 'hymn~22~O COME AND DWELL IN ME~htm_o_c_ocadwell.html';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Eph~2~12~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Eph~2~12~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Eph~2~21~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Eph~2~21~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Eph~2~12~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Eph~2~12~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Eph~2~12~images/maps/Christ/christ_template.html~1';
LOI[13] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Eph~2~21~images/bible_images/Temple/temple_template.html~1';
LOI[14] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Eph~2~21~images/bible_images/Temple/temple_template.html~2';
