var LOI = [];
LOI[0] = 'hymn~4~HOW VAST THE BENEFITS DIVINE~htm_h_v_hvasttbd.html';
LOI[1] = 'hymn~6~MY SOUL, REPEAT HIS PRAISE~htm_m_s_msrepeat.html';
LOI[2] = 'hymn~7~HOW HAPPY EVERY CHILD OF GRACE~htm_h_o_howhapec.html';
LOI[3] = 'hymn~13~SEAL US, O HOLY SPIRIT~htm_s_e_sealusoh.html';
LOI[4] = 'hymn~13~SPIRIT BLEST, WHO ART ADORED~htm_s_p_spiblest.html';
LOI[5] = 'hymn~21~JESUS, NAME OF WONDROUS LOVE~htm_j_n_jnamewol.html';
LOI[6] = 'image~Bible~Maps~Paul\'s First Missionary Journey (98K map) key=Paul~~~~Eph~1~1~images/maps/Journeys/journeys_template.html~1';
LOI[7] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Paul,Ephesus~~~~Eph~1~1~images/maps/Journeys/journeys_template.html~2';
LOI[8] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Paul,Ephesus~~~~Eph~1~1~images/maps/Journeys/journeys_template.html~3';
LOI[9] = 'image~Bible~Images~The Conversion of St. Paul key=Paul~~~~Eph~1~1~images/bible_images/Acts/acts_template.html~2';
