var LOI = [];
LOI[0] = 'hymn~4~BEULAH LAND~htm_b_e_beulah2.html';
LOI[1] = 'hymn~4~DWELLING IN BEULAH LAND~htm_d_w_dwbeulah.html';
LOI[2] = 'hymn~4~I HAVE ENTERED BEULAH LAND~htm_i_h_ihaveebl.html';
LOI[3] = 'hymn~5~WHAT IF IT WERE TODAY?~htm_w_h_a_whatifit.html';
LOI[4] = 'image~Bible~Maps~Cities of Refuge (map)~~~~Isa~62~10~images/maps/Otest/otest_template.html~2';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Isa~62~6~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Isa~62~7~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Isa~62~11~images/maps/Otest/otest_template.html~3a';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Isa~62~6~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Isa~62~7~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Isa~62~11~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Isa~62~6~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Isa~62~7~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Isa~62~6~images/places/Israel/israel_template.html~11';
LOI[14] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Isa~62~7~images/places/Israel/israel_template.html~11';
LOI[15] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Isa~62~6~images/places/Israel/israel_template.html~12';
LOI[16] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Isa~62~7~images/places/Israel/israel_template.html~12';
LOI[17] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Isa~62~6~images/places/Israel/israel_template.html~13';
LOI[18] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Isa~62~7~images/places/Israel/israel_template.html~13';
LOI[19] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Isa~62~6~images/places/Israel/israel_template.html~14';
LOI[20] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Isa~62~7~images/places/Israel/israel_template.html~14';
LOI[21] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Isa~62~6~images/places/Israel/israel_template.html~17';
LOI[22] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Isa~62~7~images/places/Israel/israel_template.html~17';
