var LOI = [];
LOI[0] = 'hymn~15~SAVIOR, SPRINKLE MANY NATIONS~htm_s_p_sprinkle.html';
LOI[1] = 'hymn~16~I WILL MAKE THE DARKNESS LIGHT~htm_i_w_iwillmak.html';
LOI[2] = 'hymn~18~JESUS PAID IT ALL~htm_j_p_jpaidall.html';
LOI[3] = 'hymn~18~THOUGH YOUR SINS BE AS SCARLET~htm_t_h_thoyours.html';
LOI[4] = 'hymn~25~AT THE FOOT OF THE CROSS~htm_a_t_athefoot.html';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~1~3~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~1~4~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~1~24~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Isa~1~1~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~1~3~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~1~4~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~1~24~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Isa~1~1~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Isa~1~1~images/maps/Otest/otest_template.html~3a';
LOI[14] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Isa~1~8~images/maps/Otest/otest_template.html~3a';
LOI[15] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Isa~1~27~images/maps/Otest/otest_template.html~3a';
LOI[16] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Isa~1~1~images/maps/Otest/otest_template.html~3b';
LOI[17] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Isa~1~8~images/maps/Otest/otest_template.html~3b';
LOI[18] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Isa~1~27~images/maps/Otest/otest_template.html~3b';
LOI[19] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~1~3~images/maps/Otest/otest_template.html~3c';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~1~4~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~1~24~images/maps/Otest/otest_template.html~3c';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~1~3~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~1~4~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~1~24~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Isa~1~1~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~1~3~images/maps/Christ/christ_template.html~1';
LOI[27] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~1~4~images/maps/Christ/christ_template.html~1';
LOI[28] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~1~24~images/maps/Christ/christ_template.html~1';
LOI[29] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Isa~1~1~images/places/Israel/israel_template.html~11';
LOI[30] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Isa~1~1~images/places/Israel/israel_template.html~12';
LOI[31] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Isa~1~1~images/places/Israel/israel_template.html~13';
LOI[32] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Isa~1~1~images/places/Israel/israel_template.html~14';
LOI[33] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Isa~1~1~images/places/Israel/israel_template.html~17';
