var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Kedar~~~~Isa~21~16~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Kedar~~~~Isa~21~17~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Dumah~~~~Isa~21~11~images/maps/Otest/otest_template.html~1a';
LOI[3] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Elam~~~~Isa~21~2~images/maps/Otest/otest_template.html~1a';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~21~10~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~21~17~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~21~10~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~21~17~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~21~10~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~21~17~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~21~10~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~21~17~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~21~10~images/maps/Christ/christ_template.html~1';
LOI[13] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~21~17~images/maps/Christ/christ_template.html~1';
LOI[14] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Isa~21~9~images/bible_images/Kings/kings_template.html~7';
