var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Isa~65~9~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Isa~65~9~images/maps/Otest/otest_template.html~1c';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Isa~65~18~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Isa~65~19~images/maps/Otest/otest_template.html~3a';
LOI[4] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Isa~65~18~images/maps/Otest/otest_template.html~3b';
LOI[5] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Isa~65~19~images/maps/Otest/otest_template.html~3b';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Sharon~~~~Isa~65~10~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Isa~65~18~images/maps/Otest/otest_template.html~4';
LOI[8] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Isa~65~19~images/maps/Otest/otest_template.html~4';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Sharon~~~~Isa~65~10~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Isa~65~18~images/places/Israel/israel_template.html~11';
LOI[11] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Isa~65~19~images/places/Israel/israel_template.html~11';
LOI[12] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Isa~65~18~images/places/Israel/israel_template.html~12';
LOI[13] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Isa~65~19~images/places/Israel/israel_template.html~12';
LOI[14] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Isa~65~18~images/places/Israel/israel_template.html~13';
LOI[15] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Isa~65~19~images/places/Israel/israel_template.html~13';
LOI[16] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Isa~65~18~images/places/Israel/israel_template.html~14';
LOI[17] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Isa~65~19~images/places/Israel/israel_template.html~14';
LOI[18] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Isa~65~18~images/places/Israel/israel_template.html~17';
LOI[19] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Isa~65~19~images/places/Israel/israel_template.html~17';
