var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~46~3~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~46~13~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~46~3~images/maps/Otest/otest_template.html~1c';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~46~13~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Isa~46~13~images/maps/Otest/otest_template.html~3a';
LOI[5] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Isa~46~13~images/maps/Otest/otest_template.html~3b';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~46~3~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~46~13~images/maps/Otest/otest_template.html~3c';
LOI[8] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~46~3~images/maps/Otest/otest_template.html~4';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~46~13~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Nebo~~~~Isa~46~1~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~46~3~images/maps/Christ/christ_template.html~1';
LOI[12] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~46~13~images/maps/Christ/christ_template.html~1';
LOI[13] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Nebo~~~~Isa~46~1~images/bible_images/Moses/moses_template.html~10';
LOI[14] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Nebo~~~~Isa~46~1~images/bible_images/Moses/moses_template.html~11';
