var LOI = [];
LOI[0] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Ephraim~~~~Isa~17~3~images/maps/Otest/otest_template.html~1b';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~17~6~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~17~7~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~17~9~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Ephraim~~~~Isa~17~3~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~17~6~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~17~7~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~17~9~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~17~3~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~17~6~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~17~7~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~17~9~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~17~3~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~17~6~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~17~7~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~17~9~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~17~3~images/maps/Christ/christ_template.html~1';
LOI[17] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~17~6~images/maps/Christ/christ_template.html~1';
LOI[18] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~17~7~images/maps/Christ/christ_template.html~1';
LOI[19] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~17~9~images/maps/Christ/christ_template.html~1';
LOI[20] = 'image~Bible~Maps~Paul\'s Second Missionary Journey (140K map) key=Syria~~~~Isa~17~3~images/maps/Journeys/journeys_template.html~2';
LOI[21] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Lot~~~~Isa~17~14~images/bible_images/Moses/moses_template.html~3i';
