var LOI = [];
LOI[0] = 'hymn~8~WHO IS THIS SO WEAK AND HELPLESS~htm_w_h_o_whoisthi.html';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ophir~~~~Isa~13~12~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Isa~13~1~images/bible_images/Kings/kings_template.html~7';
LOI[3] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Isa~13~2~images/bible_images/Kings/kings_template.html~7';
LOI[4] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Isa~13~3~images/bible_images/Kings/kings_template.html~7';
LOI[5] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Isa~13~4~images/bible_images/Kings/kings_template.html~7';
LOI[6] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Isa~13~5~images/bible_images/Kings/kings_template.html~7';
LOI[7] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving)~~~~Isa~13~6~images/bible_images/Kings/kings_template.html~7';
LOI[8] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Isa~13~19~images/bible_images/Kings/kings_template.html~7';
LOI[9] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Isa~13~1~images/bible_images/Kings/kings_template.html~8';
LOI[10] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Isa~13~2~images/bible_images/Kings/kings_template.html~8';
LOI[11] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Isa~13~3~images/bible_images/Kings/kings_template.html~8';
LOI[12] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Isa~13~4~images/bible_images/Kings/kings_template.html~8';
LOI[13] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Isa~13~5~images/bible_images/Kings/kings_template.html~8';
LOI[14] = 'image~Bible~Images~Captive Israelites (engraving)~~~~Isa~13~6~images/bible_images/Kings/kings_template.html~8';
