var LOI = [];
LOI[0] = 'hymn~19~HOW FAR FROM HOME?~htm_h_o_howfarfh.html';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~30~11~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~30~12~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~30~15~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~30~29~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~30~11~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~30~12~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~30~15~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~30~29~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Zion~~~~Isa~30~19~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Zion~~~~Isa~30~19~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~30~11~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~30~12~images/maps/Otest/otest_template.html~3c';
LOI[13] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~30~15~images/maps/Otest/otest_template.html~3c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~30~29~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~30~11~images/maps/Otest/otest_template.html~4';
LOI[16] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~30~12~images/maps/Otest/otest_template.html~4';
LOI[17] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~30~15~images/maps/Otest/otest_template.html~4';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~30~29~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Isa~30~19~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Isa~30~2~images/maps/Otest/otest_template.html~5';
LOI[21] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Isa~30~3~images/maps/Otest/otest_template.html~5';
LOI[22] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~30~11~images/maps/Christ/christ_template.html~1';
LOI[23] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~30~12~images/maps/Christ/christ_template.html~1';
LOI[24] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~30~15~images/maps/Christ/christ_template.html~1';
LOI[25] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~30~29~images/maps/Christ/christ_template.html~1';
LOI[26] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Isa~30~19~images/places/Israel/israel_template.html~11';
LOI[27] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Isa~30~19~images/places/Israel/israel_template.html~12';
LOI[28] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Isa~30~19~images/places/Israel/israel_template.html~13';
LOI[29] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Isa~30~19~images/places/Israel/israel_template.html~14';
LOI[30] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Isa~30~19~images/places/Israel/israel_template.html~17';
LOI[31] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Isa~30~2~images/bible_images/Moses/moses_template.html~5';
LOI[32] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Pharaoh~~~~Isa~30~3~images/bible_images/Moses/moses_template.html~5';
