var LOI = [];
LOI[0] = 'hymn~8~RORATE~htm_r_o_rorate.html';
LOI[1] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ethiopia~~~~Isa~45~14~images/maps/Otest/otest_template.html~1a';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~45~3~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~45~4~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~45~11~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~45~15~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~45~17~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~45~25~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~45~3~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~45~4~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~45~11~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~45~15~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~45~17~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~45~25~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~45~3~images/maps/Otest/otest_template.html~3c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~45~4~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~45~11~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~45~15~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~45~17~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~45~25~images/maps/Otest/otest_template.html~3c';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~45~3~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~45~4~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~45~11~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~45~15~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~45~17~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~45~25~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Isa~45~14~images/maps/Otest/otest_template.html~5';
LOI[27] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~45~3~images/maps/Christ/christ_template.html~1';
LOI[28] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~45~4~images/maps/Christ/christ_template.html~1';
LOI[29] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~45~11~images/maps/Christ/christ_template.html~1';
LOI[30] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~45~15~images/maps/Christ/christ_template.html~1';
LOI[31] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~45~17~images/maps/Christ/christ_template.html~1';
LOI[32] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~45~25~images/maps/Christ/christ_template.html~1';
LOI[33] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving)~~~~Isa~45~20~images/bible_images/Moses/moses_template.html~9';
LOI[34] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving)~~~~Isa~45~21~images/bible_images/Moses/moses_template.html~9';
LOI[35] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving)~~~~Isa~45~22~images/bible_images/Moses/moses_template.html~9';
LOI[36] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving)~~~~Isa~45~23~images/bible_images/Moses/moses_template.html~9';
