var LOI = [];
LOI[0] = 'hymn~1~LET EVERY MORTAL EAR ATTEND~htm_l_e_lemortal.html';
LOI[1] = 'hymn~6~MY SON, KNOW THOU THE LORD~htm_m_s_msonkttl.html';
LOI[2] = 'hymn~7~YES, THERE IS PARDON FOR YOU~htm_y_e_yesthere.html';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~55~5~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~55~5~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~55~5~images/maps/Otest/otest_template.html~3c';
LOI[6] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~55~5~images/maps/Otest/otest_template.html~4';
LOI[7] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~55~5~images/maps/Christ/christ_template.html~1';
LOI[8] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Isa~55~3~images/bible_images/Kings/kings_template.html~1';
LOI[9] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Isa~55~3~images/bible_images/Kings/kings_template.html~2';
