var LOI = [];
LOI[0] = 'hymn~8~GREAT MASTER, TOUCH US~htm_g_r_greatmast.html';
LOI[1] = 'hymn~8~HAVE THINE OWN WAY, LORD~htm_h_t_hthineow.html';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Zion~~~~Isa~64~10~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Zion~~~~Isa~64~10~images/maps/Otest/otest_template.html~3b';
LOI[4] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Isa~64~10~images/maps/Otest/otest_template.html~4';
LOI[5] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Isa~64~10~images/places/Israel/israel_template.html~11';
LOI[6] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Isa~64~10~images/places/Israel/israel_template.html~12';
LOI[7] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Isa~64~10~images/places/Israel/israel_template.html~13';
LOI[8] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Isa~64~10~images/places/Israel/israel_template.html~14';
LOI[9] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Isa~64~10~images/places/Israel/israel_template.html~17';
