var LOI = [];
LOI[0] = 'hymn~1~IN A MANGER LAID SO LOWLY~htm_i_n_inamangr.html';
LOI[1] = 'hymn~8~I WALK THE KING&#8217;S HIGHWAY~htm_i_w_iwalktkh.html';
LOI[2] = 'hymn~8~THE KING&#8217;S HIGHWAY~htm_k_i_kinghway.html';
LOI[3] = 'hymn~10~BURY THY SORROW~htm_b_u_burythys.html';
LOI[4] = 'hymn~10~JOIN, ALL YE RANSOMED SONS OF GRACE~htm_j_o_joinayrs.html';
LOI[5] = 'hymn~10~JOY AND TRIUMPH EVERLASTING~htm_j_o_joytrium.html';
LOI[6] = 'hymn~10~O! SAY, BUT I&#8217;M GLAD~htm_o_s_osaybuti.html';
LOI[7] = 'hymn~10~WAKE THE SONG~htm_w_a_wakesong.html';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Isa~35~10~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Isa~35~10~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Sharon,Carmel~~~~Isa~35~2~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Sharon~~~~Isa~35~2~images/maps/Otest/otest_template.html~4';
