var LOI = [];
LOI[0] = 'hymn~3~OUT OF BONDAGE~htm_o_u_outobond.html';
LOI[1] = 'hymn~26~LORD GOD OF HOSTS, WHOSE MIGHTY HAND~htm_l_g_lghoswmh.html';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~14~1~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~14~2~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~14~1~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~14~2~images/maps/Otest/otest_template.html~1c';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Isa~14~32~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Isa~14~32~images/maps/Otest/otest_template.html~3b';
LOI[8] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~14~1~images/maps/Otest/otest_template.html~3c';
LOI[9] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~14~2~images/maps/Otest/otest_template.html~3c';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~14~1~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~14~2~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~14~1~images/maps/Christ/christ_template.html~1';
LOI[13] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~14~2~images/maps/Christ/christ_template.html~1';
LOI[14] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Isa~14~4~images/bible_images/Kings/kings_template.html~7';
LOI[15] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Isa~14~22~images/bible_images/Kings/kings_template.html~7';
