var LOI = [];
LOI[0] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Elam~~~~Isa~22~6~images/maps/Otest/otest_template.html~1a';
LOI[1] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Isa~22~8~images/maps/Otest/otest_template.html~1b';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Judah~~~~Isa~22~21~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Isa~22~8~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Judah~~~~Isa~22~21~images/maps/Otest/otest_template.html~1c';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Isa~22~10~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Isa~22~21~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Isa~22~10~images/maps/Otest/otest_template.html~3b';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Isa~22~21~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Isa~22~10~images/maps/Otest/otest_template.html~4';
LOI[10] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Isa~22~21~images/maps/Otest/otest_template.html~4';
LOI[11] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Isa~22~10~images/places/Israel/israel_template.html~11';
LOI[12] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Isa~22~21~images/places/Israel/israel_template.html~11';
LOI[13] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Isa~22~10~images/places/Israel/israel_template.html~12';
LOI[14] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Isa~22~21~images/places/Israel/israel_template.html~12';
LOI[15] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Isa~22~10~images/places/Israel/israel_template.html~13';
LOI[16] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Isa~22~21~images/places/Israel/israel_template.html~13';
LOI[17] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Isa~22~10~images/places/Israel/israel_template.html~14';
LOI[18] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Isa~22~21~images/places/Israel/israel_template.html~14';
LOI[19] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Isa~22~10~images/places/Israel/israel_template.html~17';
LOI[20] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Isa~22~21~images/places/Israel/israel_template.html~17';
LOI[21] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Isa~22~9~images/bible_images/Kings/kings_template.html~1';
LOI[22] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Isa~22~22~images/bible_images/Kings/kings_template.html~1';
LOI[23] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Isa~22~9~images/bible_images/Kings/kings_template.html~2';
LOI[24] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Isa~22~22~images/bible_images/Kings/kings_template.html~2';
