var LOI = [];
LOI[0] = 'hymn~1~COME, PURE HEARTS~htm_c_o_compureh.html';
LOI[1] = 'hymn~1~HO, EVERY ONE THAT IS THIRSTY!~htm_h_o_hoeveryo.html';
LOI[2] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~4~2~images/maps/Otest/otest_template.html~1b';
LOI[3] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~4~2~images/maps/Otest/otest_template.html~1c';
LOI[4] = 'image~Bible~Maps~Cities of Refuge (map) key=refuge~~~~Isa~4~6~images/maps/Otest/otest_template.html~2';
LOI[5] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Zion~~~~Isa~4~3~images/maps/Otest/otest_template.html~3a';
LOI[6] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem,Zion~~~~Isa~4~4~images/maps/Otest/otest_template.html~3a';
LOI[7] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Isa~4~5~images/maps/Otest/otest_template.html~3a';
LOI[8] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Zion~~~~Isa~4~3~images/maps/Otest/otest_template.html~3b';
LOI[9] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem,Zion~~~~Isa~4~4~images/maps/Otest/otest_template.html~3b';
LOI[10] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Isa~4~5~images/maps/Otest/otest_template.html~3b';
LOI[11] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~4~2~images/maps/Otest/otest_template.html~3c';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~4~2~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Isa~4~3~images/maps/Otest/otest_template.html~4';
LOI[14] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Isa~4~4~images/maps/Otest/otest_template.html~4';
LOI[15] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~4~2~images/maps/Christ/christ_template.html~1';
LOI[16] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Isa~4~3~images/places/Israel/israel_template.html~11';
LOI[17] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Isa~4~4~images/places/Israel/israel_template.html~11';
LOI[18] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Isa~4~3~images/places/Israel/israel_template.html~12';
LOI[19] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Isa~4~4~images/places/Israel/israel_template.html~12';
LOI[20] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Isa~4~3~images/places/Israel/israel_template.html~13';
LOI[21] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Isa~4~4~images/places/Israel/israel_template.html~13';
LOI[22] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Isa~4~3~images/places/Israel/israel_template.html~14';
LOI[23] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Isa~4~4~images/places/Israel/israel_template.html~14';
LOI[24] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Isa~4~3~images/places/Israel/israel_template.html~17';
LOI[25] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Isa~4~4~images/places/Israel/israel_template.html~17';
LOI[26] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Isa~4~6~images/bible_images/Temple/temple_template.html~2';
LOI[27] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Isa~4~6~images/bible_images/Temple/temple_template.html~3';
