var LOI = [];
LOI[0] = 'hymn~1~ALLELUIA! SING TO JESUS!~htm_a_s_asingtoj.html';
LOI[1] = 'hymn~12~I&#8217;VE GOT PEACE LIKE A RIVER~htm_i_g_igopeace.html';
LOI[2] = 'hymn~12~LIKE A RIVER GLORIOUS~htm_l_i_likriver.html';
LOI[3] = 'hymn~13~LIKE AS A MOTHER COMFORTETH~htm_l_i_likemoth.html';
LOI[4] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Javan~~~~Isa~66~19~images/maps/Otest/otest_template.html~1a';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~66~20~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~66~20~images/maps/Otest/otest_template.html~1c';
LOI[7] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Isa~66~10~images/maps/Otest/otest_template.html~3a';
LOI[8] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Isa~66~13~images/maps/Otest/otest_template.html~3a';
LOI[9] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Isa~66~20~images/maps/Otest/otest_template.html~3a';
LOI[10] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Isa~66~6~images/maps/Otest/otest_template.html~3a';
LOI[11] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Zion~~~~Isa~66~8~images/maps/Otest/otest_template.html~3a';
LOI[12] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Isa~66~10~images/maps/Otest/otest_template.html~3b';
LOI[13] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Isa~66~13~images/maps/Otest/otest_template.html~3b';
LOI[14] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Isa~66~20~images/maps/Otest/otest_template.html~3b';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Isa~66~6~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Maps~Modern Jerusalem (map) key=Zion~~~~Isa~66~8~images/maps/Otest/otest_template.html~3b';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~66~20~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Southern Palestine (map) key=Israel,Jerusalem~~~~Isa~66~20~images/maps/Otest/otest_template.html~4';
LOI[19] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Isa~66~10~images/maps/Otest/otest_template.html~4';
LOI[20] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Isa~66~13~images/maps/Otest/otest_template.html~4';
LOI[21] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~66~20~images/maps/Christ/christ_template.html~1';
LOI[22] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Isa~66~10~images/places/Israel/israel_template.html~11';
LOI[23] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Isa~66~13~images/places/Israel/israel_template.html~11';
LOI[24] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Isa~66~20~images/places/Israel/israel_template.html~11';
LOI[25] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Isa~66~10~images/places/Israel/israel_template.html~12';
LOI[26] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Isa~66~13~images/places/Israel/israel_template.html~12';
LOI[27] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Isa~66~20~images/places/Israel/israel_template.html~12';
LOI[28] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Isa~66~10~images/places/Israel/israel_template.html~13';
LOI[29] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Isa~66~13~images/places/Israel/israel_template.html~13';
LOI[30] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Isa~66~20~images/places/Israel/israel_template.html~13';
LOI[31] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Isa~66~10~images/places/Israel/israel_template.html~14';
LOI[32] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Isa~66~13~images/places/Israel/israel_template.html~14';
LOI[33] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Isa~66~20~images/places/Israel/israel_template.html~14';
LOI[34] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Isa~66~10~images/places/Israel/israel_template.html~17';
LOI[35] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Isa~66~13~images/places/Israel/israel_template.html~17';
LOI[36] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Isa~66~20~images/places/Israel/israel_template.html~17';
LOI[37] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Isa~66~6~images/bible_images/Temple/temple_template.html~1';
LOI[38] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Isa~66~6~images/bible_images/Temple/temple_template.html~2';
