var LOI = [];
LOI[0] = 'hymn~10~GOD&#8217;S TRUMPET WAKES THE SLUMBERING WORLD~htm_g_t_gtrumpet.html';
LOI[1] = 'hymn~15~MY MAKER AND MY KING~htm_m_y_mymakera.html';
LOI[2] = 'image~Bible~Maps~The World as Known to the Hebrews (map) key=Ethiopia,Seba~~~~Isa~43~3~images/maps/Otest/otest_template.html~1a';
LOI[3] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~43~1~images/maps/Otest/otest_template.html~1b';
LOI[4] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~43~3~images/maps/Otest/otest_template.html~1b';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~43~14~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~43~15~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~43~22~images/maps/Otest/otest_template.html~1b';
LOI[8] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel~~~~Isa~43~28~images/maps/Otest/otest_template.html~1b';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~43~1~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~43~3~images/maps/Otest/otest_template.html~1c';
LOI[11] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~43~14~images/maps/Otest/otest_template.html~1c';
LOI[12] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~43~15~images/maps/Otest/otest_template.html~1c';
LOI[13] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~43~22~images/maps/Otest/otest_template.html~1c';
LOI[14] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel~~~~Isa~43~28~images/maps/Otest/otest_template.html~1c';
LOI[15] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~43~1~images/maps/Otest/otest_template.html~3c';
LOI[16] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~43~3~images/maps/Otest/otest_template.html~3c';
LOI[17] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~43~14~images/maps/Otest/otest_template.html~3c';
LOI[18] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~43~15~images/maps/Otest/otest_template.html~3c';
LOI[19] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~43~22~images/maps/Otest/otest_template.html~3c';
LOI[20] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Isa~43~28~images/maps/Otest/otest_template.html~3c';
LOI[21] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~43~1~images/maps/Otest/otest_template.html~4';
LOI[22] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~43~3~images/maps/Otest/otest_template.html~4';
LOI[23] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~43~14~images/maps/Otest/otest_template.html~4';
LOI[24] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~43~15~images/maps/Otest/otest_template.html~4';
LOI[25] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~43~22~images/maps/Otest/otest_template.html~4';
LOI[26] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Isa~43~28~images/maps/Otest/otest_template.html~4';
LOI[27] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Isa~43~3~images/maps/Otest/otest_template.html~5';
LOI[28] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~43~1~images/maps/Christ/christ_template.html~1';
LOI[29] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~43~3~images/maps/Christ/christ_template.html~1';
LOI[30] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~43~14~images/maps/Christ/christ_template.html~1';
LOI[31] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~43~15~images/maps/Christ/christ_template.html~1';
LOI[32] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~43~22~images/maps/Christ/christ_template.html~1';
LOI[33] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Isa~43~28~images/maps/Christ/christ_template.html~1';
LOI[34] = 'image~Bible~Images~Jerusalem Taken Captive Into Babylon (engraving) key=Babylon~~~~Isa~43~14~images/bible_images/Kings/kings_template.html~7';
