var LOI = [];
LOI[0] = 'hymn~8~THE LORD WILL COME! THE EARTH SHALL QUAKE~htm_l_w_lwictesq.html';
LOI[1] = 'hymn~26~HE IS COMING, HE IS COMING~htm_h_i_hischisc.html';
LOI[2] = 'hymn~26~I KNOW THAT SOME DAY~htm_i_k_iksomeda.html';
LOI[3] = 'hymn~26~JESUS CAME, THE HEAVENS ADORING~htm_j_c_jcamehva.html';
LOI[4] = 'hymn~26~JUST AS I AM, THINE OWN TO BE~htm_j_u_juaithin.html';
LOI[5] = 'hymn~26~LO, HE COMES WITH CLOUDS DESCENDING~htm_l_h_lhecomes.html';
LOI[6] = 'hymn~26~WE SHALL SEE THE KING~htm_w_s_wsstking.html';
LOI[7] = 'hymn~26~WHEN EACH OTHERS FACE WE SEE~htm_w_h_wheneach.html';
LOI[8] = 'hymn~32~HE IS NEAR~htm_h_e_heisnear.html';
LOI[9] = 'hymn~33~O&#8217;ER THE DISTANT MOUNTAINS BREAKING~htm_o_e_oerdistm.html';
LOI[10] = 'hymn~34~OH, WHAT ARE YOU GOING TO DO?~htm_o_w_owhatare.html';
LOI[11] = 'hymn~35~O WHY NOT TONIGHT?~htm_o_w_owhynott.html';
LOI[12] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Mar~13~1~images/maps/Otest/otest_template.html~3a';
LOI[13] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Temple~~~~Mar~13~3~images/maps/Otest/otest_template.html~3a';
LOI[14] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Mar~13~1~images/maps/Otest/otest_template.html~3b';
LOI[15] = 'image~Bible~Maps~Modern Jerusalem (map) key=Temple~~~~Mar~13~3~images/maps/Otest/otest_template.html~3b';
LOI[16] = 'image~Bible~Charts~The Revelation of Jesus (Ironside\'s chart) key=tribulation~~~~Mar~13~24~images/charts/Bible/bible_template.html~1';
LOI[17] = 'image~Bible~Images~The Creation (engraving) key=creation~~~~Mar~13~19~images/bible_images/Moses/moses_template.html~1a';
LOI[18] = 'image~Bible~Images~Daniel and Nebuchadnezzar\'s Dream key=Daniel~~~~Mar~13~14~images/bible_images/Daniel/daniel_template.html~1';
LOI[19] = 'image~Bible~Images~The Fiery Furnace (engraving) key=Daniel~~~~Mar~13~14~images/bible_images/Daniel/daniel_template.html~2';
LOI[20] = 'image~Bible~Images~Daniel Calls Nebuchadnezzar to Repentance key=Daniel~~~~Mar~13~14~images/bible_images/Daniel/daniel_template.html~3';
LOI[21] = 'image~Bible~Images~MENE MENE TEKEL UPHARSIN  key=Daniel~~~~Mar~13~14~images/bible_images/Daniel/daniel_template.html~4';
LOI[22] = 'image~Bible~Images~Daniel in the Lions Den (engraving) key=Daniel,Daniel~~~~Mar~13~14~images/bible_images/Daniel/daniel_template.html~5';
LOI[23] = 'image~Bible~Images~Daniel\'s Vision (engraving) key=Daniel~~~~Mar~13~14~images/bible_images/Daniel/daniel_template.html~6';
LOI[24] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Mar~13~1~images/bible_images/Temple/temple_template.html~1';
LOI[25] = 'image~Bible~Images~The Jews Wailing Place (engraving) key=temple~~~~Mar~13~3~images/bible_images/Temple/temple_template.html~1';
LOI[26] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Mar~13~1~images/bible_images/Temple/temple_template.html~2';
LOI[27] = 'image~Bible~Images~The Tabernacle (engraving) key=temple~~~~Mar~13~3~images/bible_images/Temple/temple_template.html~2';
