var LOI = [];
LOI[0] = 'hymn~35~WE BEAR THE STRAIN OF EARTHLY CARE~htm_w_e_webearth.html';
LOI[1] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Mar~3~8~images/maps/Otest/otest_template.html~3a';
LOI[2] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Mar~3~22~images/maps/Otest/otest_template.html~3a';
LOI[3] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Mar~3~8~images/maps/Otest/otest_template.html~3b';
LOI[4] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Mar~3~22~images/maps/Otest/otest_template.html~3b';
LOI[5] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Mar~3~7~images/maps/Otest/otest_template.html~3c';
LOI[6] = 'image~Bible~Maps~Middle Palestine (map) key=Tyre,Jordan~~~~Mar~3~8~images/maps/Otest/otest_template.html~3c';
LOI[7] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Mar~3~8~images/maps/Otest/otest_template.html~4';
LOI[8] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Mar~3~22~images/maps/Otest/otest_template.html~4';
LOI[9] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Mar~3~7~images/maps/Christ/christ_template.html~1';
LOI[10] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Tyre~~~~Mar~3~8~images/maps/Journeys/journeys_template.html~3';
LOI[11] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Mar~3~8~images/places/Israel/israel_template.html~11';
LOI[12] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Mar~3~22~images/places/Israel/israel_template.html~11';
LOI[13] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Mar~3~8~images/places/Israel/israel_template.html~12';
LOI[14] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Mar~3~22~images/places/Israel/israel_template.html~12';
LOI[15] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Mar~3~8~images/places/Israel/israel_template.html~13';
LOI[16] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Mar~3~22~images/places/Israel/israel_template.html~13';
LOI[17] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Mar~3~8~images/places/Israel/israel_template.html~14';
LOI[18] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Mar~3~22~images/places/Israel/israel_template.html~14';
LOI[19] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Mar~3~8~images/places/Israel/israel_template.html~17';
LOI[20] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Mar~3~22~images/places/Israel/israel_template.html~17';
