var LOI = [];
LOI[0] = 'hymn~5~LORD JESUS, ON THE HOLY MOUNT~htm_l_j_ljeonthm.html';
LOI[1] = 'hymn~7~I LOVE THE VOICE DIVINE~htm_i_l_ilovoice.html';
LOI[2] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee~~~~Mar~9~30~images/maps/Otest/otest_template.html~3c';
LOI[3] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Mar~9~30~images/maps/Christ/christ_template.html~1';
LOI[4] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Mar~9~4~images/bible_images/Moses/moses_template.html~6';
LOI[5] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Mar~9~5~images/bible_images/Moses/moses_template.html~6';
LOI[6] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Mar~9~4~images/bible_images/Moses/moses_template.html~7';
LOI[7] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Mar~9~5~images/bible_images/Moses/moses_template.html~7';
LOI[8] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Mar~9~4~images/bible_images/Moses/moses_template.html~9';
LOI[9] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Mar~9~5~images/bible_images/Moses/moses_template.html~9';
LOI[10] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Mar~9~4~images/bible_images/Moses/moses_template.html~10';
LOI[11] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Mar~9~5~images/bible_images/Moses/moses_template.html~10';
LOI[12] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Mar~9~4~images/bible_images/Moses/moses_template.html~11';
LOI[13] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Mar~9~5~images/bible_images/Moses/moses_template.html~11';
