var LOI = [];
LOI[0] = 'image~Bible~Maps~Ancient Jerusalem (map) key=Jerusalem~~~~Mar~7~1~images/maps/Otest/otest_template.html~3a';
LOI[1] = 'image~Bible~Maps~Modern Jerusalem (map) key=Jerusalem~~~~Mar~7~1~images/maps/Otest/otest_template.html~3b';
LOI[2] = 'image~Bible~Maps~Middle Palestine (map) key=Galilee,Tyre~~~~Mar~7~31~images/maps/Otest/otest_template.html~3c';
LOI[3] = 'image~Bible~Maps~Middle Palestine (map) key=Tyre~~~~Mar~7~24~images/maps/Otest/otest_template.html~3c';
LOI[4] = 'image~Bible~Maps~Southern Palestine (map) key=Jerusalem~~~~Mar~7~1~images/maps/Otest/otest_template.html~4';
LOI[5] = 'image~Bible~Maps~Divisions of Palestine (map) key=Galilee~~~~Mar~7~31~images/maps/Christ/christ_template.html~1';
LOI[6] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Tyre~~~~Mar~7~24~images/maps/Journeys/journeys_template.html~3';
LOI[7] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Tyre~~~~Mar~7~31~images/maps/Journeys/journeys_template.html~3';
LOI[8] = 'image~Bible~Places~Tower of David (engraving) key=Jerusalem~~~~Mar~7~1~images/places/Israel/israel_template.html~11';
LOI[9] = 'image~Bible~Places~Damascus Gate (engraving) key=Jerusalem~~~~Mar~7~1~images/places/Israel/israel_template.html~12';
LOI[10] = 'image~Bible~Places~Golden Gate-interior (engraving) key=Jerusalem~~~~Mar~7~1~images/places/Israel/israel_template.html~13';
LOI[11] = 'image~Bible~Places~Golden Gate-exterior (engraving) key=Jerusalem~~~~Mar~7~1~images/places/Israel/israel_template.html~14';
LOI[12] = 'image~Bible~Places~Mt. of Olives and Jerusalem (engraving) key=Jerusalem~~~~Mar~7~1~images/places/Israel/israel_template.html~17';
LOI[13] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Mar~7~10~images/bible_images/Moses/moses_template.html~6';
LOI[14] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Mar~7~10~images/bible_images/Moses/moses_template.html~7';
LOI[15] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Mar~7~10~images/bible_images/Moses/moses_template.html~9';
LOI[16] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Mar~7~10~images/bible_images/Moses/moses_template.html~10';
LOI[17] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Mar~7~10~images/bible_images/Moses/moses_template.html~11';
LOI[18] = 'image~Bible~Images~Healing Demoniac Daughter (engraving)~~~~Mar~7~24~images/bible_images/Miracles/miracles_template.html~7';
LOI[19] = 'image~Bible~Images~Healing Demoniac Daughter (engraving)~~~~Mar~7~25~images/bible_images/Miracles/miracles_template.html~7';
LOI[20] = 'image~Bible~Images~Healing Demoniac Daughter (engraving)~~~~Mar~7~26~images/bible_images/Miracles/miracles_template.html~7';
LOI[21] = 'image~Bible~Images~Healing Demoniac Daughter (engraving)~~~~Mar~7~27~images/bible_images/Miracles/miracles_template.html~7';
LOI[22] = 'image~Bible~Images~Healing Demoniac Daughter (engraving)~~~~Mar~7~28~images/bible_images/Miracles/miracles_template.html~7';
LOI[23] = 'image~Bible~Images~Healing Demoniac Daughter (engraving)~~~~Mar~7~29~images/bible_images/Miracles/miracles_template.html~7';
LOI[24] = 'image~Bible~Images~Healing Demoniac Daughter (engraving)~~~~Mar~7~30~images/bible_images/Miracles/miracles_template.html~7';
LOI[25] = 'image~Bible~Images~Deaf Man Hears (engraving)~~~~Mar~7~31~images/bible_images/Miracles/miracles_template.html~8';
LOI[26] = 'image~Bible~Images~Deaf Man Hears (engraving)~~~~Mar~7~32~images/bible_images/Miracles/miracles_template.html~8';
LOI[27] = 'image~Bible~Images~Deaf Man Hears (engraving)~~~~Mar~7~33~images/bible_images/Miracles/miracles_template.html~8';
LOI[28] = 'image~Bible~Images~Deaf Man Hears (engraving)~~~~Mar~7~34~images/bible_images/Miracles/miracles_template.html~8';
LOI[29] = 'image~Bible~Images~Deaf Man Hears (engraving)~~~~Mar~7~35~images/bible_images/Miracles/miracles_template.html~8';
LOI[30] = 'image~Bible~Images~Deaf Man Hears (engraving)~~~~Mar~7~36~images/bible_images/Miracles/miracles_template.html~8';
LOI[31] = 'image~Bible~Images~Deaf Man Hears (engraving)~~~~Mar~7~37~images/bible_images/Miracles/miracles_template.html~8';
