var LOI = [];
LOI[0] = 'hymn~3~MY FAITH HAS FOUND A RESTING PLACE~htm_m_y_myfaithh.html';
LOI[1] = 'hymn~7~JESUS IS TENDERLY CALLING YOU HOME~htm_j_i_jitcyhom.html';
LOI[2] = 'hymn~9~AND NOW THE WANTS ARE TOLD~htm_a_n_andnowtw.html';
LOI[3] = 'hymn~9~BEAUTIFUL VALE OF REST~htm_b_v_bvaleres.html';
LOI[4] = 'hymn~9~BLESSED HOMELAND~htm_b_l_blessedh.html';
LOI[5] = 'hymn~9~COME, LET US JOIN WITH ONE ACCORD~htm_c_o_c1accord.html';
LOI[6] = 'hymn~9~I&#8217;M BUT A STRANGER HERE~htm_i_m_imbutash.html';
LOI[7] = 'hymn~9~JESUS, I AM RESTING, RESTING~htm_j_i_jiamrest.html';
LOI[8] = 'hymn~9~REST AT HOME~htm_r_e_resthome.html';
LOI[9] = 'hymn~9~SOFTLY FADES THE TWILIGHT RAY~htm_s_o_softlyft.html';
LOI[10] = 'hymn~9~TO REALMS OF GLORY~htm_t_o_torealms.html';
LOI[11] = 'hymn~9~WHEN WINDS ARE RAGING~htm_w_w_wwaragin.html';
LOI[12] = 'hymn~16~BEHOLD THE THRONE OF GRACE~htm_b_e_bethrone.html';
LOI[13] = 'hymn~16~COME BOLDLY TO THE THRONE OF GRACE~htm_c_o_comebold.html';
LOI[14] = 'hymn~16~I NEED THEE EVERY HOUR~htm_i_n_ineedteh.html';
LOI[15] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Hbr~4~7~images/bible_images/Kings/kings_template.html~1';
LOI[16] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Hbr~4~7~images/bible_images/Kings/kings_template.html~2';
