var LOI = [];
LOI[0] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Hbr~3~16~images/maps/Otest/otest_template.html~5';
LOI[1] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Hbr~3~2~images/bible_images/Moses/moses_template.html~6';
LOI[2] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Hbr~3~3~images/bible_images/Moses/moses_template.html~6';
LOI[3] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Hbr~3~5~images/bible_images/Moses/moses_template.html~6';
LOI[4] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Hbr~3~16~images/bible_images/Moses/moses_template.html~6';
LOI[5] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Hbr~3~2~images/bible_images/Moses/moses_template.html~7';
LOI[6] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Hbr~3~3~images/bible_images/Moses/moses_template.html~7';
LOI[7] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Hbr~3~5~images/bible_images/Moses/moses_template.html~7';
LOI[8] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Hbr~3~16~images/bible_images/Moses/moses_template.html~7';
LOI[9] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Hbr~3~2~images/bible_images/Moses/moses_template.html~9';
LOI[10] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Hbr~3~3~images/bible_images/Moses/moses_template.html~9';
LOI[11] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Hbr~3~5~images/bible_images/Moses/moses_template.html~9';
LOI[12] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Hbr~3~16~images/bible_images/Moses/moses_template.html~9';
LOI[13] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Hbr~3~2~images/bible_images/Moses/moses_template.html~10';
LOI[14] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Hbr~3~3~images/bible_images/Moses/moses_template.html~10';
LOI[15] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Hbr~3~5~images/bible_images/Moses/moses_template.html~10';
LOI[16] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Hbr~3~16~images/bible_images/Moses/moses_template.html~10';
LOI[17] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Hbr~3~2~images/bible_images/Moses/moses_template.html~11';
LOI[18] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Hbr~3~3~images/bible_images/Moses/moses_template.html~11';
LOI[19] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Hbr~3~5~images/bible_images/Moses/moses_template.html~11';
LOI[20] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Hbr~3~16~images/bible_images/Moses/moses_template.html~11';
