var LOI = [];
LOI[0] = 'hymn~19~AS A TREE BESIDE THE WATER~htm_a_s_asatreeb.html';
LOI[1] = 'hymn~19~I&#8217;VE ANCHORED IN JESUS~htm_i_v_ivanchor.html';
LOI[2] = 'hymn~19~MY ANCHOR HOLDS~htm_m_y_myanchor.html';
LOI[3] = 'hymn~19~NOW I HAVE FOUND THE GROUND WHEREIN~htm_n_i_nihavftg.html';
LOI[4] = 'hymn~19~WE HAVE AN ANCHOR~htm_w_e_h_wehavean.html';
LOI[5] = 'hymn~19~WHISPERING HOPE~htm_w_h_i_whisperh.html';
LOI[6] = 'image~Bible~Maps~Cities of Refuge (map) key=refuge~~~~Hbr~6~18~images/maps/Otest/otest_template.html~2';
LOI[7] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Hbr~6~13~images/places/Israel/israel_template.html~8';
LOI[8] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~1~images/bible_images/Moses/moses_template.html~3';
LOI[9] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~2~images/bible_images/Moses/moses_template.html~3';
LOI[10] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~3~images/bible_images/Moses/moses_template.html~3';
LOI[11] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~4~images/bible_images/Moses/moses_template.html~3';
LOI[12] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~5~images/bible_images/Moses/moses_template.html~3';
LOI[13] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~6~images/bible_images/Moses/moses_template.html~3';
LOI[14] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~7~images/bible_images/Moses/moses_template.html~3';
LOI[15] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~8~images/bible_images/Moses/moses_template.html~3';
LOI[16] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~9~images/bible_images/Moses/moses_template.html~3';
LOI[17] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~10~images/bible_images/Moses/moses_template.html~3';
LOI[18] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~11~images/bible_images/Moses/moses_template.html~3';
LOI[19] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~12~images/bible_images/Moses/moses_template.html~3';
LOI[20] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~13~images/bible_images/Moses/moses_template.html~3';
LOI[21] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~14~images/bible_images/Moses/moses_template.html~3';
LOI[22] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~15~images/bible_images/Moses/moses_template.html~3';
LOI[23] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~16~images/bible_images/Moses/moses_template.html~3';
LOI[24] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~17~images/bible_images/Moses/moses_template.html~3';
LOI[25] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~18~images/bible_images/Moses/moses_template.html~3';
LOI[26] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~19~images/bible_images/Moses/moses_template.html~3';
LOI[27] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving)~~~~Hbr~6~20~images/bible_images/Moses/moses_template.html~3';
LOI[28] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Hbr~6~13~images/bible_images/Moses/moses_template.html~3i';
LOI[29] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Hbr~6~13~images/bible_images/Moses/moses_template.html~3a';
