var LOI = [];
LOI[0] = 'hymn~5~HOW FIRM A FOUNDATION~htm_h_f_hfirmafo.html';
LOI[1] = 'hymn~5~NO, NOT ONE!~htm_n_o_nonotone.html';
LOI[2] = 'hymn~8~YESTERDAY, TODAY, FOREVER~htm_y_e_yestofor.html';
LOI[3] = 'hymn~14~BRIEF LIFE IS HERE OUR PORTION~htm_b_r_brieflif.html';
LOI[4] = 'hymn~20~NOW MAY HE WHO FROM THE DEAD~htm_n_m_nmayhewf.html';
LOI[5] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Timothy~~~~Hbr~13~23~images/maps/Journeys/journeys_template.html~3';
LOI[6] = 'image~Bible~Maps~Paul\'s Third Missionary Journey (156K map) key=Timothy~~~~Hbr~13~25~images/maps/Journeys/journeys_template.html~3';
LOI[7] = 'image~Bible~Images~The Tabernacle (engraving) key=tabernacle~~~~Hbr~13~10~images/bible_images/Temple/temple_template.html~2';
LOI[8] = 'image~Bible~Images~Tabernacle in the Midst of the Encampment (illustration) key=Tabernacle~~~~Hbr~13~10~images/bible_images/Temple/temple_template.html~3';
