var LOI = [];
LOI[0] = 'hymn~1~FAITH OF OUR FATHERS~htm_f_a_faithoof.html';
LOI[1] = 'hymn~1~OLD-TIME RELIGION~htm_o_l_oldtimer.html';
LOI[2] = 'hymn~2~MARCHING WITH THE HEROES~htm_m_a_marchinh.html';
LOI[3] = 'hymn~10~BUILT BY JEHOVAH&#8217;S HAND~htm_b_u_builtbyj.html';
LOI[4] = 'hymn~10~THE PEARLY WHITE CITY~htm_p_w_pwhitcit.html';
LOI[5] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Israel,Joseph~~~~Hbr~11~22~images/maps/Otest/otest_template.html~1b';
LOI[6] = 'image~Bible~Maps~Boundaries of the Tribes of Israel (map) key=Joseph~~~~Hbr~11~21~images/maps/Otest/otest_template.html~1b';
LOI[7] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Israel,Joseph~~~~Hbr~11~22~images/maps/Otest/otest_template.html~1c';
LOI[8] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Joseph~~~~Hbr~11~21~images/maps/Otest/otest_template.html~1c';
LOI[9] = 'image~Bible~Maps~Battlefields of O.T. and Dist\'n of 12 Tribes (map) key=Samuel~~~~Hbr~11~32~images/maps/Otest/otest_template.html~1c';
LOI[10] = 'image~Bible~Maps~Middle Palestine (map) key=Israel~~~~Hbr~11~22~images/maps/Otest/otest_template.html~3c';
LOI[11] = 'image~Bible~Maps~Southern Palestine (map) key=Israel~~~~Hbr~11~22~images/maps/Otest/otest_template.html~4';
LOI[12] = 'image~Bible~Maps~Southern Palestine (map) key=Jericho~~~~Hbr~11~30~images/maps/Otest/otest_template.html~4';
LOI[13] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Hbr~11~26~images/maps/Otest/otest_template.html~5';
LOI[14] = 'image~Bible~Maps~The Sinai Peninsula (map) key=Egypt~~~~Hbr~11~27~images/maps/Otest/otest_template.html~5';
LOI[15] = 'image~Bible~Maps~Divisions of Palestine (map) key=Israel~~~~Hbr~11~22~images/maps/Christ/christ_template.html~1';
LOI[16] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Hbr~11~8~images/places/Israel/israel_template.html~8';
LOI[17] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Hbr~11~17~images/places/Israel/israel_template.html~8';
LOI[18] = 'image~Bible~Places~House in Jericho (engraving) key=Jericho~~~~Hbr~11~30~images/places/Israel/israel_template.html~9';
LOI[19] = 'image~Bible~Images~The Deluge (engraving) key=Noah~~~~Hbr~11~7~images/bible_images/Moses/moses_template.html~1';
LOI[20] = 'image~Bible~Images~Noah\'s Sacrifice (engraving) key=Noah~~~~Hbr~11~7~images/bible_images/Moses/moses_template.html~2';
LOI[21] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Hbr~11~8~images/bible_images/Moses/moses_template.html~3';
LOI[22] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Hbr~11~17~images/bible_images/Moses/moses_template.html~3';
LOI[23] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Hbr~11~8~images/bible_images/Moses/moses_template.html~3i';
LOI[24] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Hbr~11~17~images/bible_images/Moses/moses_template.html~3i';
LOI[25] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving)~~~~Hbr~11~17~images/bible_images/Moses/moses_template.html~3a';
LOI[26] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving)~~~~Hbr~11~18~images/bible_images/Moses/moses_template.html~3a';
LOI[27] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving)~~~~Hbr~11~19~images/bible_images/Moses/moses_template.html~3a';
LOI[28] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac~~~~Hbr~11~9~images/bible_images/Moses/moses_template.html~3a';
LOI[29] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Isaac~~~~Hbr~11~20~images/bible_images/Moses/moses_template.html~3a';
LOI[30] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Hbr~11~8~images/bible_images/Moses/moses_template.html~3a';
LOI[31] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Hbr~11~9~images/bible_images/Moses/moses_template.html~4';
LOI[32] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Hbr~11~17~images/bible_images/Moses/moses_template.html~4';
LOI[33] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Hbr~11~18~images/bible_images/Moses/moses_template.html~4';
LOI[34] = 'image~Bible~Images~The Departure of Rebekah (engraving) key=Isaac~~~~Hbr~11~20~images/bible_images/Moses/moses_template.html~4';
LOI[35] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Hbr~11~21~images/bible_images/Moses/moses_template.html~5';
LOI[36] = 'image~Bible~Images~Joseph Interprets Pharaoh\'s Dream (engraving) key=Joseph~~~~Hbr~11~22~images/bible_images/Moses/moses_template.html~5';
LOI[37] = 'image~Bible~Images~The Exposure of Moses (engraving)~~~~Hbr~11~23~images/bible_images/Moses/moses_template.html~6';
LOI[38] = 'image~Bible~Images~The Exposure of Moses (engraving) key=Moses~~~~Hbr~11~24~images/bible_images/Moses/moses_template.html~6';
LOI[39] = 'image~Bible~Images~The Finding of Moses (engraving)~~~~Hbr~11~23~images/bible_images/Moses/moses_template.html~7';
LOI[40] = 'image~Bible~Images~The Finding of Moses (engraving) key=Moses~~~~Hbr~11~24~images/bible_images/Moses/moses_template.html~7';
LOI[41] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Hbr~11~23~images/bible_images/Moses/moses_template.html~9';
LOI[42] = 'image~Bible~Images~Moses and the Brazen Serpent (engraving) key=Moses~~~~Hbr~11~24~images/bible_images/Moses/moses_template.html~9';
LOI[43] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Hbr~11~23~images/bible_images/Moses/moses_template.html~10';
LOI[44] = 'image~Bible~Images~Moses on Mount Pisgah (engraving) key=Moses~~~~Hbr~11~24~images/bible_images/Moses/moses_template.html~10';
LOI[45] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Hbr~11~23~images/bible_images/Moses/moses_template.html~11';
LOI[46] = 'image~Bible~Images~Death of Moses on Mount Nebo (engraving) key=Moses~~~~Hbr~11~24~images/bible_images/Moses/moses_template.html~11';
LOI[47] = 'image~Bible~Images~Manoah\'s Sacrifice (engraving) key=Samson~~~~Hbr~11~32~images/bible_images/Samson/samson_template.html~1a';
LOI[48] = 'image~Bible~Images~Samson Killing the Lion (engraving) key=Samson~~~~Hbr~11~32~images/bible_images/Samson/samson_template.html~1b';
LOI[49] = 'image~Bible~Images~Samson Finding Honey (engraving) key=Samson~~~~Hbr~11~32~images/bible_images/Samson/samson_template.html~2';
LOI[50] = 'image~Bible~Images~Samson and the 300 Foxes (engraving) key=Samson~~~~Hbr~11~32~images/bible_images/Samson/samson_template.html~3';
LOI[51] = 'image~Bible~Images~Samson Carrying Away the Gates of Gaza key=Samson~~~~Hbr~11~32~images/bible_images/Samson/samson_template.html~4';
LOI[52] = 'image~Bible~Images~Samson in Delilah\'s Lap (engraving) key=Samson~~~~Hbr~11~32~images/bible_images/Samson/samson_template.html~5';
LOI[53] = 'image~Bible~Images~Samson Taken by the Philstines (engraving) key=Samson~~~~Hbr~11~32~images/bible_images/Samson/samson_template.html~6';
LOI[54] = 'image~Bible~Images~Samson Grinding at the Mill (engraving) key=Samson~~~~Hbr~11~32~images/bible_images/Samson/samson_template.html~7';
LOI[55] = 'image~Bible~Images~Samson and the Dagon Fish god (engraving) key=Samson~~~~Hbr~11~32~images/bible_images/Samson/samson_template.html~8';
LOI[56] = 'image~Bible~Images~Saul and David (engraving) key=David~~~~Hbr~11~32~images/bible_images/Kings/kings_template.html~1';
LOI[57] = 'image~Bible~Images~David Mourning for Absalom (engraving) key=David~~~~Hbr~11~32~images/bible_images/Kings/kings_template.html~2';
LOI[58] = 'image~Bible~Images~The Ark and Mercy Seat (engraving) key=Ark~~~~Hbr~11~7~images/bible_images/Temple/temple_template.html~4';
