var LOI = [];
LOI[0] = 'hymn~7~O JESUS, CROWNED WITH ALL RENOWN~htm_o_j_ojcrownd.html';
LOI[1] = 'hymn~9~THE HEAD THAT ONCE WAS CROWNED~htm_h_t_hthatwoc.html';
LOI[2] = 'hymn~10~O SON OF GOD, OUR CAPTAIN OF SALVATION~htm_o_s_osgcapsal.html';
LOI[3] = 'image~Bible~Places~Abraham\'s House (engraving) key=Abraham~~~~Hbr~2~16~images/places/Israel/israel_template.html~8';
LOI[4] = 'image~Bible~Images~Melchizedek Blessing Abraham (engraving) key=Abraham~~~~Hbr~2~16~images/bible_images/Moses/moses_template.html~3';
LOI[5] = 'image~Bible~Images~Parting of Lot and Abraham (engraving) key=Abraham~~~~Hbr~2~16~images/bible_images/Moses/moses_template.html~3i';
LOI[6] = 'image~Bible~Images~Abraham\'s Sacrifice: Jehovah Jirah (engraving) key=Abraham~~~~Hbr~2~16~images/bible_images/Moses/moses_template.html~3a';
LOI[7] = 'image~Bible~Images~The Leper Healed (engraving) key=miracles~~~~Hbr~2~4~images/bible_images/Miracles/miracles_template.html~1';
LOI[8] = 'image~Bible~Images~Man With Palsy Healed (engraving) key=miracles~~~~Hbr~2~4~images/bible_images/Miracles/miracles_template.html~2';
LOI[9] = 'image~Bible~Images~The Raising of Jairus\' Daughter (engraving) key=miracles~~~~Hbr~2~4~images/bible_images/Miracles/miracles_template.html~3';
LOI[10] = 'image~Bible~Images~The Paralytic Healed (engraving) key=miracles~~~~Hbr~2~4~images/bible_images/Miracles/miracles_template.html~4';
LOI[11] = 'image~Bible~Images~The Miracle of the Loaves and Fishes (engraving) key=miracles~~~~Hbr~2~4~images/bible_images/Miracles/miracles_template.html~5';
LOI[12] = 'image~Bible~Images~Jesus Walking on the Sea (engraving) key=miracles~~~~Hbr~2~4~images/bible_images/Miracles/miracles_template.html~6';
LOI[13] = 'image~Bible~Images~Healing Demoniac Daughter (engraving) key=miracles~~~~Hbr~2~4~images/bible_images/Miracles/miracles_template.html~7';
LOI[14] = 'image~Bible~Images~Deaf Man Hears (engraving) key=miracles~~~~Hbr~2~4~images/bible_images/Miracles/miracles_template.html~8';
LOI[15] = 'image~Bible~Images~Man Born Blind Healed (engraving) key=miracles~~~~Hbr~2~4~images/bible_images/Miracles/miracles_template.html~9';
LOI[16] = 'image~Bible~Images~Jesus Healing Ten Lepers (engraving) key=miracles~~~~Hbr~2~4~images/bible_images/Miracles/miracles_template.html~10';
LOI[17] = 'image~Bible~Images~Jesus Heals Bartimaeus (engraving) key=miracles~~~~Hbr~2~4~images/bible_images/Miracles/miracles_template.html~11';
